<?php
			$optionsArray = array( 'welcome' => array( 'welcomePageSkip' => true,
'welcomeItems' => array( 'intelagro_logito' => array( 'menutItem' => false ),
'intelagro_logo' => array( 'menutItem' => false ),
'galex_logo' => array( 'menutItem' => false ),
'logo' => array( 'menutItem' => false ),
'menu' => array( 'menutItem' => false ),
'loginform_login' => array( 'menutItem' => false ),
'username_button' => array( 'menutItem' => false ),
'btn_update_usuarios' => array( 'menutItem' => false ),
'menu_licencias' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'cat_usuarios_licencias',
'page' => 'list' ),
'menu_usuarios' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'cat_usuarios',
'page' => 'list' ),
'menu_usuarios_modulos_detalle' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'cat_usuarios_02_modulos',
'page' => 'list' ),
'menu_usuarios_modulos' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'cat_usuarios_modulos',
'page' => 'list' ),
'welcome_item' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'tr_menu_noticias',
'page' => 'list' ),
'welcome_item1' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'tr_menu_sugerencias',
'page' => 'list' ),
'galex_nave' => array( 'menutItem' => false ),
'enviar_asistencia' => array( 'menutItem' => false ),
'enviar_cosecha' => array( 'menutItem' => false ),
'welcome_item2' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'cat_ventas_productos_precios',
'page' => 'list' ) ) ),
'fields' => array( 'gridFields' => array(  ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array(  ) ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'intelagro_logito',
'intelagro_logo',
'galex_logo' ),
'supertop' => array( 'logo',
'menu',
'loginform_login',
'username_button' ),
'grid' => array( 'welcome_item',
'welcome_item1',
'menu_licencias',
'menu_usuarios',
'menu_usuarios_modulos_detalle',
'menu_usuarios_modulos',
'btn_update_usuarios',
'galex_nave',
'enviar_asistencia',
'enviar_cosecha',
'welcome_item2' ) ),
'formXtTags' => array(  ),
'itemForms' => array( 'intelagro_logito' => 'above-grid',
'intelagro_logo' => 'above-grid',
'galex_logo' => 'above-grid',
'logo' => 'supertop',
'menu' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'welcome_item' => 'grid',
'welcome_item1' => 'grid',
'menu_licencias' => 'grid',
'menu_usuarios' => 'grid',
'menu_usuarios_modulos_detalle' => 'grid',
'menu_usuarios_modulos' => 'grid',
'btn_update_usuarios' => 'grid',
'galex_nave' => 'grid',
'enviar_asistencia' => 'grid',
'enviar_cosecha' => 'grid',
'welcome_item2' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array( 'menu' => 3,
'username_button' => 3,
'loginform_login' => 3,
'intelagro_logito' => 2,
'intelagro_logo' => 5 ) ),
'itemsByType' => array( 'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'userinfo_link' => array( 'userinfo_link' ),
'logout_link' => array( 'logout_link' ),
'adminarea_link' => array( 'adminarea_link' ),
'welcome_item' => array( 'welcome_item1',
'welcome_item',
'menu_licencias',
'menu_usuarios',
'menu_usuarios_modulos',
'menu_usuarios_modulos_detalle',
'welcome_item2' ),
'custom_button' => array( 'btn_update_usuarios',
'enviar_asistencia',
'enviar_cosecha' ),
'image' => array( 'intelagro_logito',
'intelagro_logo',
'galex_logo',
'galex_nave' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => true,
'customButtons' => array( 'update_usuarios_todo_el_clouster',
'New_Button1',
'New_Button2' ),
'hasNotifications' => false,
'menus' => array( array( 'id' => 'main',
'horizontal' => true ) ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array( 'update_usuarios_todo_el_clouster',
'New_Button1',
'New_Button2' ) ) );
			$pageArray = array( 'id' => 'menu',
'type' => 'menu',
'layoutId' => 'topbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'empty-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'intelagro_logito',
'intelagro_logo',
'galex_logo' ),
'align' => 'center' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'menu-topbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c2',
'colspan' => 1 ),
array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c2' => array( 'model' => 'c1',
'items' => array( 'logo',
'menu' ) ),
'c' => array( 'model' => 'c2',
'items' => array( 'loginform_login',
'username_button' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'welcome',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c3' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4' ) ) ) ),
'cells' => array( 'c2' => array( 'model' => 'c1',
'items' => array( 'welcome_item',
'welcome_item1' ),
'align' => 'center' ),
'c3' => array( 'model' => 'c1',
'items' => array( 'menu_licencias',
'menu_usuarios',
'menu_usuarios_modulos_detalle',
'menu_usuarios_modulos' ),
'align' => 'center' ),
'c' => array( 'model' => 'c1',
'items' => array( 'btn_update_usuarios' ) ),
'c4' => array( 'model' => 'c1',
'items' => array( 'galex_nave',
'enviar_asistencia',
'enviar_cosecha',
'welcome_item2' ),
'align' => 'center' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu',
'menuId' => 'main' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'adminarea_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => false ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'logout_link' => array( 'type' => 'logout_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'welcome_item1' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'tr_menu_sugerencias',
'linkPage' => 'list',
'linkText' => array( 'table' => 'tr_menu_sugerencias',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'pencil' ),
'linkComments' => array( 'type' => 0,
'text' => '' ),
'background' => '#6da5c8',
'linkType' => 0 ),
'welcome_item' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'tr_menu_noticias',
'linkPage' => 'list',
'linkText' => array( 'type' => 0,
'text' => 'Noticias' ),
'linkIcon' => array( 'glyph' => 'envelope' ),
'linkComments' => array( 'type' => 0,
'text' => '' ),
'background' => '#6DA5C8',
'linkType' => 0 ),
'btn_update_usuarios' => array( 'eventId' => 'update_usuarios_todo_el_clouster',
'label' => array( 'text' => 'Update Usuarios Todo El Clouster',
'type' => 0 ),
'type' => 'custom_button',
'buttonSize' => 'large',
'buttonStyle' => 'warning' ),
'menu_licencias' => array( 'type' => 'welcome_item',
'linkTable' => 'cat_usuarios_licencias',
'linkPage' => 'list',
'linkText' => array( 'type' => 0,
'text' => 'Licencias' ),
'linkType' => 0 ),
'menu_usuarios' => array( 'type' => 'welcome_item',
'linkTable' => 'cat_usuarios',
'linkPage' => 'list',
'linkText' => array( 'type' => 0,
'text' => 'Usuarios' ),
'linkType' => 0 ),
'menu_usuarios_modulos' => array( 'type' => 'welcome_item',
'linkTable' => 'cat_usuarios_modulos',
'linkPage' => 'list',
'linkText' => array( 'type' => 0,
'text' => 'Usuarios Modulos' ),
'linkType' => 0 ),
'menu_usuarios_modulos_detalle' => array( 'type' => 'welcome_item',
'linkTable' => 'cat_usuarios_02_modulos',
'linkPage' => 'list',
'linkText' => array( 'type' => 0,
'text' => 'Moduos detalle' ),
'linkType' => 0 ),
'intelagro_logito' => array( 'type' => 'image',
'image' => array( 'image' => 'intelagro_logito.png',
'source' => 2 ),
'mobileDisplay' => 'mobile',
'mobileControl' => 'always' ),
'intelagro_logo' => array( 'type' => 'image',
'image' => array( 'image' => 'intelagro_logo.png',
'source' => 2 ),
'mobileDisplay' => 'desktop' ),
'galex_logo' => array( 'type' => 'image',
'image' => array( 'image' => 'galex_logo.png',
'source' => 2 ) ),
'galex_nave' => array( 'type' => 'image',
'image' => array( 'image' => 'galex_nave.jpg',
'source' => 2 ),
'mobileDisplay' => '' ),
'enviar_asistencia' => array( 'eventId' => 'New_Button1',
'label' => array( 'text' => 'Enviar Asistencia',
'type' => 0 ),
'type' => 'custom_button',
'buttonSize' => 'large',
'buttonStyle' => 'info',
'padding' => array( 'padding' => '5px' ) ),
'enviar_cosecha' => array( 'eventId' => 'New_Button2',
'label' => array( 'text' => 'Enviar Cosecha',
'type' => 0 ),
'type' => 'custom_button',
'buttonSize' => 'large',
'buttonStyle' => 'info',
'padding' => array( 'padding' => '5px' ) ),
'welcome_item2' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'cat_ventas_productos_precios',
'linkPage' => 'list',
'linkText' => array( 'table' => 'cat_ventas_productos_precios',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'camera' ),
'background' => '#DC143C',
'linkType' => 0 ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image',
'image' => null,
'fullSize' => true ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>