<?php
			$optionsArray = array( 'list' => array( 'inlineAdd' => false,
'detailsAdd' => false,
'inlineEdit' => false,
'spreadsheetMode' => false,
'reorderRows' => false,
'addToBottom' => false,
'delete' => false,
'updateSelected' => false,
'addInPopup' => null,
'editInPopup' => null,
'viewInPopup' => null,
'clickSort' => true,
'sortDropdown' => false,
'showHideFields' => false,
'reorderFields' => false,
'fieldFilter' => false,
'hideNumberOfRecords' => false ),
'listSearch' => array( 'alwaysOnPanelFields' => array(  ),
'searchPanel' => true,
'fixedSearchPanel' => false,
'simpleSearchOptions' => true,
'searchSaving' => false ),
'totals' => array( 'vigente' => array( 'totalsType' => '' ),
'descripcion_nomina' => array( 'totalsType' => '' ),
'dia_de_inicio' => array( 'totalsType' => '' ),
'fecha_de_inicio' => array( 'totalsType' => '' ),
'fecha_de_termino' => array( 'totalsType' => '' ),
'cat_nominas_01_generales_id' => array( 'totalsType' => '' ),
'capturista' => array( 'totalsType' => '' ),
'time_stamp' => array( 'totalsType' => '' ),
'cat_nominas_01_generales_uuid' => array( 'totalsType' => '' ),
'cat_nominas_periodicidad_mu_id' => array( 'totalsType' => '' ),
'horas_semana_laboral' => array( 'totalsType' => '' ),
'cat_nominas_uuid_semana' => array( 'totalsType' => '' ),
'cat_usuarios_licencias_id1' => array( 'totalsType' => '' ),
'llave_ano_semana_nominas_uuid' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'descripcion_nomina',
'cat_nominas_01_generales_uuid',
'fecha_de_inicio',
'fecha_de_termino' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array( 'vigente',
'llave_ano_semana_nominas_uuid',
'cat_usuarios_licencias_id1',
'cat_nominas_uuid_semana',
'horas_semana_laboral',
'cat_nominas_periodicidad_mu_id',
'cat_nominas_01_generales_uuid',
'time_stamp',
'capturista',
'cat_nominas_01_generales_id',
'fecha_de_termino',
'fecha_de_inicio',
'dia_de_inicio',
'descripcion_nomina' ),
'filterFields' => array(  ),
'inlineAddFields' => array(  ),
'inlineEditFields' => array(  ),
'fieldItems' => array( 'descripcion_nomina' => array( 'grid_field2',
'grid_field_label2' ),
'fecha_de_inicio' => array( 'grid_field',
'grid_field_label' ),
'cat_nominas_01_generales_uuid' => array( 'grid_field9',
'grid_field_label9' ),
'fecha_de_termino' => array( 'grid_field1',
'grid_field_label1' ) ),
'hideEmptyFields' => array(  ),
'fieldFilterFields' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'details_found',
'page_size',
'print_details',
'text1' ),
'below-grid' => array( 'pagination' ),
'left' => array( 'logo',
'expand_button',
'menu',
'search_panel' ),
'supertop' => array( 'expand_menu_button',
'collapse_button',
'breadcrumb',
'simple_search_field',
'simple_search_option',
'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'grid' => array( 'grid_field_label2',
'grid_field2',
'text2',
'details_preview',
'grid_field_label9',
'grid_field9',
'custom_button8',
'grid_checkbox_head',
'grid_checkbox',
'grid_alldetails_link',
'grid_details_link',
'grid_field_label',
'grid_field',
'grid_field_label1',
'grid_field1' ),
'top' => array(  ) ),
'formXtTags' => array( 'below-grid' => array( 'pagination' ),
'top' => array(  ) ),
'itemForms' => array( 'details_found' => 'above-grid',
'page_size' => 'above-grid',
'print_details' => 'above-grid',
'text1' => 'above-grid',
'pagination' => 'below-grid',
'logo' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'search_panel' => 'left',
'expand_menu_button' => 'supertop',
'collapse_button' => 'supertop',
'breadcrumb' => 'supertop',
'simple_search_field' => 'supertop',
'simple_search_option' => 'supertop',
'simple_search' => 'supertop',
'list_options' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'grid_field_label2' => 'grid',
'grid_field2' => 'grid',
'text2' => 'grid',
'details_preview' => 'grid',
'grid_field_label9' => 'grid',
'grid_field9' => 'grid',
'custom_button8' => 'grid',
'grid_checkbox_head' => 'grid',
'grid_checkbox' => 'grid',
'grid_alldetails_link' => 'grid',
'grid_details_link' => 'grid',
'grid_field_label' => 'grid',
'grid_field' => 'grid',
'grid_field_label1' => 'grid',
'grid_field1' => 'grid' ),
'itemLocations' => array( 'grid_field_label2' => array( 'location' => 'grid',
'cellId' => 'headcell_field1' ),
'grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'text2' => array( 'location' => 'grid',
'cellId' => 'headcell_icons5' ),
'details_preview' => array( 'location' => 'grid',
'cellId' => 'headcell_icons7' ),
'grid_field_label9' => array( 'location' => 'grid',
'cellId' => 'headcell_field9' ),
'grid_field9' => array( 'location' => 'grid',
'cellId' => 'cell_field17' ),
'custom_button8' => array( 'location' => 'grid',
'cellId' => 'cell_field21' ),
'grid_checkbox_head' => array( 'location' => 'grid',
'cellId' => 'headcell_checkbox' ),
'grid_checkbox' => array( 'location' => 'grid',
'cellId' => 'cell_checkbox' ),
'grid_alldetails_link' => array( 'location' => 'grid',
'cellId' => 'cell_details' ),
'grid_details_link' => array( 'location' => 'grid',
'cellId' => 'cell_details' ),
'grid_field_label' => array( 'location' => 'grid',
'cellId' => 'headcell_field' ),
'grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field3' ),
'grid_field_label1' => array( 'location' => 'grid',
'cellId' => 'headcell_field2' ),
'grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field5' ) ),
'itemVisiblity' => array( 'breadcrumb' => 5,
'expand_menu_button' => 2,
'expand_button' => 5 ) ),
'itemsByType' => array( 'page_size' => array( 'page_size' ),
'details_found' => array( 'details_found' ),
'breadcrumb' => array( 'breadcrumb' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'simple_search' => array( 'simple_search' ),
'pagination' => array( 'pagination' ),
'list_options' => array( 'list_options' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'userinfo_link' => array( 'userinfo_link' ),
'logout_link' => array( 'logout_link' ),
'adminarea_link' => array( 'adminarea_link' ),
'changepassword_link' => array( 'changepassword_link' ),
'expand_menu_button' => array( 'expand_menu_button' ),
'collapse_button' => array( 'collapse_button' ),
'-' => array( '-',
'-1',
'-2',
'-3',
'-4' ),
'advsearch_link' => array( 'advsearch_link' ),
'print_details' => array( 'print_details' ),
'custom_button' => array( 'custom_button8' ),
'grid_field' => array( 'grid_field2',
'grid_field',
'grid_field9',
'grid_field1' ),
'grid_field_label' => array( 'grid_field_label2',
'grid_field_label',
'grid_field_label9',
'grid_field_label1' ),
'text' => array( 'text1',
'text2' ),
'grid_checkbox_head' => array( 'grid_checkbox_head' ),
'grid_checkbox' => array( 'grid_checkbox' ),
'details_preview' => array( 'details_preview' ),
'grid_alldetails_link' => array( 'grid_alldetails_link' ),
'grid_details_link' => array( 'grid_details_link' ),
'search_panel' => array( 'search_panel' ),
'show_search_panel' => array( 'show_search_panel' ),
'hide_search_panel' => array( 'hide_search_panel' ),
'search_panel_field' => array( 'search_panel_field',
'search_panel_field1',
'search_panel_field2',
'search_panel_field3',
'search_panel_field4',
'search_panel_field5',
'search_panel_field6',
'search_panel_field7',
'search_panel_field8',
'search_panel_field9',
'search_panel_field10',
'search_panel_field11',
'search_panel_field12',
'search_panel_field13' ),
'simple_search_field' => array( 'simple_search_field' ),
'simple_search_option' => array( 'simple_search_option' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'headcell_icons5' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'text2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'headcell_checkbox' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array( 'checkbox_column' ),
'items' => array( 'grid_checkbox_head' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_details' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field1' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array( 'descripcion_nomina_fieldheadercolumn' ),
'items' => array( 'grid_field_label2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field9' => array( 'cols' => array( 4 ),
'rows' => array( 0 ),
'tags' => array( 'cat_nominas_01_generales_uuid_fieldheadercolumn' ),
'items' => array( 'grid_field_label9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 5 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field' => array( 'cols' => array( 6 ),
'rows' => array( 0 ),
'tags' => array( 'fecha_de_inicio_fieldheadercolumn' ),
'items' => array( 'grid_field_label' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field2' => array( 'cols' => array( 7 ),
'rows' => array( 0 ),
'tags' => array( 'fecha_de_termino_fieldheadercolumn' ),
'items' => array( 'grid_field_label1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_icons6' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_checkbox' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array( 'checkbox_column' ),
'items' => array( 'grid_checkbox' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_details' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'grid_alldetails_link',
'grid_details_link' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array( 'descripcion_nomina_fieldcolumn' ),
'items' => array( 'grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field17' => array( 'cols' => array( 4 ),
'rows' => array( 1 ),
'tags' => array( 'cat_nominas_01_generales_uuid_fieldcolumn' ),
'items' => array( 'grid_field9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field21' => array( 'cols' => array( 5 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'cell_field3' => array( 'cols' => array( 6 ),
'rows' => array( 1 ),
'tags' => array( 'fecha_de_inicio_fieldcolumn' ),
'items' => array( 'grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field5' => array( 'cols' => array( 7 ),
'rows' => array( 1 ),
'tags' => array( 'fecha_de_termino_fieldcolumn' ),
'items' => array( 'grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_icons7' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'details_preview' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'cell_checkbox1' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_details1' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field18' => array( 'cols' => array( 4 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field22' => array( 'cols' => array( 5 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field4' => array( 'cols' => array( 6 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field6' => array( 'cols' => array( 7 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_icons8' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_checkbox' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_details' => array( 'cols' => array( 2 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field1' => array( 'cols' => array( 3 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field9' => array( 'cols' => array( 4 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field23' => array( 'cols' => array( 5 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field' => array( 'cols' => array( 6 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field2' => array( 'cols' => array( 7 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 8,
'height' => 4 ) ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array( 'details_found' => array( 'tag' => 'DISPLAYING',
'type' => 2 ) ) ),
'gridType' => 0,
'recsPerRow' => 1,
'hasCustomButtons' => true,
'customButtons' => array( 'tr_nominas_pre_nomina_01' ),
'hasNotifications' => false,
'menus' => array( array( 'id' => 'main',
'horizontal' => false ) ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'list',
'breadcrumb' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array( 'tr_nominas_pre_nomina_01' ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'list',
'type' => 'list',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'list-above-grid',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ),
array( 'cell' => 'c5' ) ) ),
array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c3' ),
array( 'cell' => 'c4' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'details_found',
'page_size',
'print_details' ) ),
'c3' => array( 'model' => 'c3',
'items' => array(  ) ),
'c4' => array( 'model' => 'c4',
'items' => array(  ) ),
'c' => array( 'model' => 'c1',
'items' => array( 'text1' ) ),
'c5' => array( 'model' => 'c2',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'list-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'pagination' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo',
'expand_button' ) ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu',
'search_panel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'expand_menu_button',
'collapse_button',
'breadcrumb' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'simple_search_field',
'simple_search_option',
'simple_search',
'list_options',
'loginform_login',
'username_button' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'horizontal-grid',
'grid' => array( array( 'section' => 'head',
'cells' => array( array( 'cell' => 'headcell_icons5' ),
array( 'cell' => 'headcell_checkbox' ),
array( 'cell' => 'headcell_details' ),
array( 'cell' => 'headcell_field1' ),
array( 'cell' => 'headcell_field9' ),
array( 'cell' => 'cell_field' ),
array( 'cell' => 'headcell_field' ),
array( 'cell' => 'headcell_field2' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'headcell_icons6' ),
array( 'cell' => 'cell_checkbox' ),
array( 'cell' => 'cell_details' ),
array( 'cell' => 'cell_field1' ),
array( 'cell' => 'cell_field17' ),
array( 'cell' => 'cell_field21' ),
array( 'cell' => 'cell_field3' ),
array( 'cell' => 'cell_field5' ) ) ),
array( 'cells' => array( array( 'cell' => 'headcell_icons7' ),
array( 'cell' => 'cell_checkbox1' ),
array( 'cell' => 'cell_details1' ),
array( 'cell' => 'cell_field2' ),
array( 'cell' => 'cell_field18' ),
array( 'cell' => 'cell_field22' ),
array( 'cell' => 'cell_field4' ),
array( 'cell' => 'cell_field6' ) ),
'section' => 'body' ),
array( 'section' => 'foot',
'cells' => array( array( 'cell' => 'headcell_icons8' ),
array( 'cell' => 'footcell_checkbox' ),
array( 'cell' => 'footcell_details' ),
array( 'cell' => 'footcell_field1' ),
array( 'cell' => 'footcell_field9' ),
array( 'cell' => 'cell_field23' ),
array( 'cell' => 'footcell_field' ),
array( 'cell' => 'footcell_field2' ) ) ) ),
'cells' => array( 'headcell_field1' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label2' ),
'field' => 'descripcion_nomina',
'columnName' => 'field' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'grid_field2' ),
'field' => 'descripcion_nomina',
'columnName' => 'field' ),
'footcell_field1' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'headcell_icons5' => array( 'model' => 'headcell_icons',
'items' => array( 'text2' ) ),
'headcell_icons6' => array( 'model' => 'cell_icons',
'items' => array(  ) ),
'headcell_icons7' => array( 'model' => 'cell_dpreview',
'items' => array( 'details_preview' ) ),
'headcell_icons8' => array( 'model' => 'footcell_icons',
'items' => array(  ) ),
'headcell_field9' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label9' ),
'field' => 'cat_nominas_01_generales_uuid',
'columnName' => 'field' ),
'cell_field17' => array( 'model' => 'cell_field',
'items' => array( 'grid_field9' ),
'field' => 'cat_nominas_01_generales_uuid',
'columnName' => 'field' ),
'cell_field18' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'footcell_field9' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'cell_field' => array( 'model' => 'headcell_field',
'items' => array(  ) ),
'cell_field21' => array( 'model' => 'cell_field',
'items' => array( 'custom_button8' ) ),
'cell_field22' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'cell_field23' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_checkbox' => array( 'model' => 'headcell_checkbox',
'items' => array( 'grid_checkbox_head' ) ),
'cell_checkbox' => array( 'model' => 'cell_checkbox',
'items' => array( 'grid_checkbox' ) ),
'cell_checkbox1' => array( 'model' => 'cell_checkbox',
'items' => array(  ) ),
'footcell_checkbox' => array( 'model' => 'footcell_checkbox',
'items' => array(  ) ),
'headcell_details' => array( 'model' => 'headcell_details',
'items' => array(  ) ),
'cell_details' => array( 'model' => 'cell_details',
'items' => array( 'grid_alldetails_link',
'grid_details_link' ) ),
'cell_details1' => array( 'model' => 'cell_details',
'items' => array(  ) ),
'footcell_details' => array( 'model' => 'footcell_details',
'items' => array(  ) ),
'headcell_field' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label' ),
'field' => 'fecha_de_inicio',
'columnName' => 'field' ),
'cell_field3' => array( 'model' => 'cell_field',
'items' => array( 'grid_field' ),
'field' => 'fecha_de_inicio',
'columnName' => 'field' ),
'cell_field4' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'footcell_field' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field2' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label1' ),
'field' => 'fecha_de_termino',
'columnName' => 'field' ),
'cell_field5' => array( 'model' => 'cell_field',
'items' => array( 'grid_field1' ),
'field' => 'fecha_de_termino',
'columnName' => 'field' ),
'cell_field6' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'footcell_field2' => array( 'model' => 'footcell_field',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'list-sidebar-top',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'page_size' => array( 'type' => 'page_size' ),
'details_found' => array( 'type' => 'details_found' ),
'breadcrumb' => array( 'type' => 'breadcrumb' ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'simple_search' => array( 'type' => 'simple_search' ),
'pagination' => array( 'type' => 'pagination' ),
'list_options' => array( 'type' => 'list_options',
'items' => array( 'advsearch_link',
'show_search_panel',
'hide_search_panel' ) ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'adminarea_link',
'changepassword_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => false ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'logout_link' => array( 'type' => 'logout_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'changepassword_link' => array( 'type' => 'changepassword_link' ),
'expand_menu_button' => array( 'type' => 'expand_menu_button' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'-' => array( 'type' => '-' ),
'-1' => array( 'type' => '-' ),
'-2' => array( 'type' => '-' ),
'advsearch_link' => array( 'type' => 'advsearch_link' ),
'-3' => array( 'type' => '-' ),
'print_details' => array( 'type' => 'print_details',
'tables' => array( 'cat_nominas_03_trabajadores_costo_bruto_conceptos_edicion_masiva' => true,
'catt_nominas_03_trabajadores_costo_bruto_conceptos_edicion_masiva' => true,
'cat_nominas_02_trabajadores' => true ) ),
'custom_button8' => array( 'type' => 'custom_button',
'eventId' => 'tr_nominas_pre_nomina_01',
'label' => array( 'text' => 'Generar',
'type' => 0 ),
'buttonSize' => 'small',
'buttonStyle' => 'warning' ),
'grid_field2' => array( 'field' => 'descripcion_nomina',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label2' => array( 'type' => 'grid_field_label',
'field' => 'descripcion_nomina',
'clickSort' => true ),
'grid_field' => array( 'field' => 'fecha_de_inicio',
'type' => 'grid_field' ),
'grid_field_label' => array( 'type' => 'grid_field_label',
'field' => 'fecha_de_inicio',
'clickSort' => true ),
'grid_field9' => array( 'field' => 'cat_nominas_01_generales_uuid',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label9' => array( 'type' => 'grid_field_label',
'field' => 'cat_nominas_01_generales_uuid',
'clickSort' => true ),
'grid_field1' => array( 'field' => 'fecha_de_termino',
'type' => 'grid_field' ),
'grid_field_label1' => array( 'type' => 'grid_field_label',
'field' => 'fecha_de_termino',
'clickSort' => true ),
'-4' => array( 'type' => '-' ),
'text1' => array( 'type' => 'text',
'label' => array( 'text' => 'CONFIGURAR NOMINA: definir nóminas y sus variables.',
'type' => 0 ),
'editedByRte' => false ),
'text2' => array( 'type' => 'text',
'label' => array( 'text' => 'Editar',
'type' => 0 ),
'editedByRte' => false ),
'grid_checkbox_head' => array( 'type' => 'grid_checkbox_head' ),
'grid_checkbox' => array( 'type' => 'grid_checkbox' ),
'details_preview' => array( 'type' => 'details_preview',
'table' => 'cat_nominas_02_trabajadores',
'items' => array(  ),
'popup' => false,
'hideEmptyPreview' => false,
'proceedLink' => true,
'pageId' => 'list' ),
'grid_alldetails_link' => array( 'type' => 'grid_alldetails_link' ),
'grid_details_link' => array( 'type' => 'grid_details_link',
'table' => 'cat_nominas_02_trabajadores',
'badge' => true,
'hideIfNone' => false,
'showCount' => false ),
'search_panel' => array( 'type' => 'search_panel',
'items' => array( 'search_panel_field',
'search_panel_field13',
'search_panel_field12',
'search_panel_field11',
'search_panel_field10',
'search_panel_field9',
'search_panel_field8',
'search_panel_field7',
'search_panel_field6',
'search_panel_field5',
'search_panel_field4',
'search_panel_field3',
'search_panel_field2',
'search_panel_field1' ) ),
'show_search_panel' => array( 'type' => 'show_search_panel' ),
'hide_search_panel' => array( 'type' => 'hide_search_panel' ),
'search_panel_field' => array( 'field' => 'vigente',
'type' => 'search_panel_field' ),
'search_panel_field1' => array( 'field' => 'descripcion_nomina',
'type' => 'search_panel_field' ),
'search_panel_field2' => array( 'field' => 'dia_de_inicio',
'type' => 'search_panel_field' ),
'search_panel_field3' => array( 'field' => 'fecha_de_inicio',
'type' => 'search_panel_field' ),
'search_panel_field4' => array( 'field' => 'fecha_de_termino',
'type' => 'search_panel_field' ),
'search_panel_field5' => array( 'field' => 'cat_nominas_01_generales_id',
'type' => 'search_panel_field' ),
'search_panel_field6' => array( 'field' => 'capturista',
'type' => 'search_panel_field' ),
'search_panel_field7' => array( 'field' => 'time_stamp',
'type' => 'search_panel_field' ),
'search_panel_field8' => array( 'field' => 'cat_nominas_01_generales_uuid',
'type' => 'search_panel_field' ),
'search_panel_field9' => array( 'field' => 'cat_nominas_periodicidad_mu_id',
'type' => 'search_panel_field' ),
'search_panel_field10' => array( 'field' => 'horas_semana_laboral',
'type' => 'search_panel_field' ),
'search_panel_field11' => array( 'field' => 'cat_nominas_uuid_semana',
'type' => 'search_panel_field' ),
'search_panel_field12' => array( 'field' => 'cat_usuarios_licencias_id1',
'type' => 'search_panel_field' ),
'search_panel_field13' => array( 'field' => 'llave_ano_semana_nominas_uuid',
'type' => 'search_panel_field' ),
'simple_search_field' => array( 'type' => 'simple_search_field' ),
'simple_search_option' => array( 'type' => 'simple_search_option' ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'spreadsheetGrid' => false,
'version' => 14,
'reorderRows' => false,
'reorderRowsField' => '',
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>