<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'cat_trabajadores_altas_id',
'cat_trabajadores_altas_id_empresa',
'vigente',
'fecha_de_ingreso',
'apellido_paterno',
'apellido_materno',
'primer_nombre',
'segundo_nombre',
'link_foto',
'fecha_de_nacimiento',
'contacto_emergencia',
'celular_mensajes',
'rfc',
'curp',
'num_seguridad_social',
'nacionalidad',
'calle',
'numero_domicilio',
'colonia',
'municipio',
'estado',
'codigo_postal',
'cat_trabajadores_sexo_mu_id',
'banco',
'cuenta_bancaria',
'cat_trabajadores_sangre_mu_id',
'cat_trabajadores_local_foraneo_mu_id',
'cat_trabajadores_tipo_de_pago_id',
'telefono_emergencia',
'municipio_nacimiento',
'estado_nacimiento',
'cat_trabajadores_estado_civil_mu_id',
'cat_holding_02_empresas',
'observaciones',
'capturista',
'nombre_completook',
'tr_tags_numero_asignado',
'fecha_de_registro',
'time_stamp',
'cat_trabajadores_puestos_id' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'cat_trabajadores_altas_id' => array( 'simple_grid_field',
'simple_grid_field40' ),
'cat_trabajadores_altas_id_empresa' => array( 'simple_grid_field1',
'simple_grid_field41' ),
'vigente' => array( 'simple_grid_field2',
'simple_grid_field42' ),
'fecha_de_ingreso' => array( 'simple_grid_field3',
'simple_grid_field43' ),
'apellido_paterno' => array( 'simple_grid_field4',
'simple_grid_field44' ),
'apellido_materno' => array( 'simple_grid_field5',
'simple_grid_field45' ),
'primer_nombre' => array( 'simple_grid_field6',
'simple_grid_field46' ),
'segundo_nombre' => array( 'simple_grid_field7',
'simple_grid_field47' ),
'link_foto' => array( 'simple_grid_field8',
'simple_grid_field48' ),
'fecha_de_nacimiento' => array( 'simple_grid_field9',
'simple_grid_field49' ),
'contacto_emergencia' => array( 'simple_grid_field11',
'simple_grid_field50' ),
'celular_mensajes' => array( 'simple_grid_field12',
'simple_grid_field51' ),
'rfc' => array( 'simple_grid_field13',
'simple_grid_field52' ),
'curp' => array( 'simple_grid_field14',
'simple_grid_field53' ),
'num_seguridad_social' => array( 'simple_grid_field15',
'simple_grid_field54' ),
'nacionalidad' => array( 'simple_grid_field16',
'simple_grid_field55' ),
'calle' => array( 'simple_grid_field17',
'simple_grid_field56' ),
'numero_domicilio' => array( 'simple_grid_field18',
'simple_grid_field57' ),
'colonia' => array( 'simple_grid_field19',
'simple_grid_field58' ),
'municipio' => array( 'simple_grid_field20',
'simple_grid_field59' ),
'estado' => array( 'simple_grid_field21',
'simple_grid_field60' ),
'codigo_postal' => array( 'simple_grid_field22',
'simple_grid_field61' ),
'cat_trabajadores_sexo_mu_id' => array( 'simple_grid_field23',
'simple_grid_field62' ),
'banco' => array( 'simple_grid_field24',
'simple_grid_field63' ),
'cuenta_bancaria' => array( 'simple_grid_field25',
'simple_grid_field64' ),
'cat_trabajadores_sangre_mu_id' => array( 'simple_grid_field26',
'simple_grid_field65' ),
'cat_trabajadores_local_foraneo_mu_id' => array( 'simple_grid_field27',
'simple_grid_field66' ),
'cat_trabajadores_tipo_de_pago_id' => array( 'simple_grid_field28',
'simple_grid_field67' ),
'telefono_emergencia' => array( 'simple_grid_field29',
'simple_grid_field68' ),
'municipio_nacimiento' => array( 'simple_grid_field30',
'simple_grid_field69' ),
'estado_nacimiento' => array( 'simple_grid_field31',
'simple_grid_field70' ),
'cat_trabajadores_estado_civil_mu_id' => array( 'simple_grid_field32',
'simple_grid_field71' ),
'cat_holding_02_empresas' => array( 'simple_grid_field33',
'simple_grid_field72' ),
'observaciones' => array( 'simple_grid_field34',
'simple_grid_field73' ),
'capturista' => array( 'simple_grid_field35',
'simple_grid_field74' ),
'nombre_completook' => array( 'simple_grid_field36',
'simple_grid_field75' ),
'tr_tags_numero_asignado' => array( 'simple_grid_field37',
'simple_grid_field76' ),
'fecha_de_registro' => array( 'simple_grid_field38',
'simple_grid_field77' ),
'time_stamp' => array( 'simple_grid_field39',
'simple_grid_field78' ),
'cat_trabajadores_puestos_id' => array( 'simple_grid_field10',
'simple_grid_field79' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array(  ),
'below-grid' => array(  ),
'top' => array( 'back_master',
'masterlist_header' ),
'grid' => array( 'simple_grid_field40',
'simple_grid_field',
'simple_grid_field41',
'simple_grid_field1',
'simple_grid_field42',
'simple_grid_field2',
'simple_grid_field43',
'simple_grid_field3',
'simple_grid_field44',
'simple_grid_field4',
'simple_grid_field45',
'simple_grid_field5',
'simple_grid_field46',
'simple_grid_field6',
'simple_grid_field47',
'simple_grid_field7',
'simple_grid_field48',
'simple_grid_field8',
'simple_grid_field49',
'simple_grid_field9',
'simple_grid_field50',
'simple_grid_field11',
'simple_grid_field51',
'simple_grid_field12',
'simple_grid_field52',
'simple_grid_field13',
'simple_grid_field53',
'simple_grid_field14',
'simple_grid_field54',
'simple_grid_field15',
'simple_grid_field55',
'simple_grid_field16',
'simple_grid_field56',
'simple_grid_field17',
'simple_grid_field57',
'simple_grid_field18',
'simple_grid_field58',
'simple_grid_field19',
'simple_grid_field59',
'simple_grid_field20',
'simple_grid_field60',
'simple_grid_field21',
'simple_grid_field61',
'simple_grid_field22',
'simple_grid_field62',
'simple_grid_field23',
'simple_grid_field63',
'simple_grid_field24',
'simple_grid_field64',
'simple_grid_field25',
'simple_grid_field65',
'simple_grid_field26',
'simple_grid_field66',
'simple_grid_field27',
'simple_grid_field67',
'simple_grid_field28',
'simple_grid_field68',
'simple_grid_field29',
'simple_grid_field69',
'simple_grid_field30',
'simple_grid_field70',
'simple_grid_field31',
'simple_grid_field71',
'simple_grid_field32',
'simple_grid_field72',
'simple_grid_field33',
'simple_grid_field73',
'simple_grid_field34',
'simple_grid_field74',
'simple_grid_field35',
'simple_grid_field75',
'simple_grid_field36',
'simple_grid_field76',
'simple_grid_field37',
'simple_grid_field77',
'simple_grid_field38',
'simple_grid_field78',
'simple_grid_field39',
'simple_grid_field79',
'simple_grid_field10' ) ),
'formXtTags' => array( 'above-grid' => array(  ),
'below-grid' => array(  ) ),
'itemForms' => array( 'back_master' => 'top',
'masterlist_header' => 'top',
'simple_grid_field40' => 'grid',
'simple_grid_field' => 'grid',
'simple_grid_field41' => 'grid',
'simple_grid_field1' => 'grid',
'simple_grid_field42' => 'grid',
'simple_grid_field2' => 'grid',
'simple_grid_field43' => 'grid',
'simple_grid_field3' => 'grid',
'simple_grid_field44' => 'grid',
'simple_grid_field4' => 'grid',
'simple_grid_field45' => 'grid',
'simple_grid_field5' => 'grid',
'simple_grid_field46' => 'grid',
'simple_grid_field6' => 'grid',
'simple_grid_field47' => 'grid',
'simple_grid_field7' => 'grid',
'simple_grid_field48' => 'grid',
'simple_grid_field8' => 'grid',
'simple_grid_field49' => 'grid',
'simple_grid_field9' => 'grid',
'simple_grid_field50' => 'grid',
'simple_grid_field11' => 'grid',
'simple_grid_field51' => 'grid',
'simple_grid_field12' => 'grid',
'simple_grid_field52' => 'grid',
'simple_grid_field13' => 'grid',
'simple_grid_field53' => 'grid',
'simple_grid_field14' => 'grid',
'simple_grid_field54' => 'grid',
'simple_grid_field15' => 'grid',
'simple_grid_field55' => 'grid',
'simple_grid_field16' => 'grid',
'simple_grid_field56' => 'grid',
'simple_grid_field17' => 'grid',
'simple_grid_field57' => 'grid',
'simple_grid_field18' => 'grid',
'simple_grid_field58' => 'grid',
'simple_grid_field19' => 'grid',
'simple_grid_field59' => 'grid',
'simple_grid_field20' => 'grid',
'simple_grid_field60' => 'grid',
'simple_grid_field21' => 'grid',
'simple_grid_field61' => 'grid',
'simple_grid_field22' => 'grid',
'simple_grid_field62' => 'grid',
'simple_grid_field23' => 'grid',
'simple_grid_field63' => 'grid',
'simple_grid_field24' => 'grid',
'simple_grid_field64' => 'grid',
'simple_grid_field25' => 'grid',
'simple_grid_field65' => 'grid',
'simple_grid_field26' => 'grid',
'simple_grid_field66' => 'grid',
'simple_grid_field27' => 'grid',
'simple_grid_field67' => 'grid',
'simple_grid_field28' => 'grid',
'simple_grid_field68' => 'grid',
'simple_grid_field29' => 'grid',
'simple_grid_field69' => 'grid',
'simple_grid_field30' => 'grid',
'simple_grid_field70' => 'grid',
'simple_grid_field31' => 'grid',
'simple_grid_field71' => 'grid',
'simple_grid_field32' => 'grid',
'simple_grid_field72' => 'grid',
'simple_grid_field33' => 'grid',
'simple_grid_field73' => 'grid',
'simple_grid_field34' => 'grid',
'simple_grid_field74' => 'grid',
'simple_grid_field35' => 'grid',
'simple_grid_field75' => 'grid',
'simple_grid_field36' => 'grid',
'simple_grid_field76' => 'grid',
'simple_grid_field37' => 'grid',
'simple_grid_field77' => 'grid',
'simple_grid_field38' => 'grid',
'simple_grid_field78' => 'grid',
'simple_grid_field39' => 'grid',
'simple_grid_field79' => 'grid',
'simple_grid_field10' => 'grid' ),
'itemLocations' => array( 'simple_grid_field40' => array( 'location' => 'grid',
'cellId' => 'headcell_field' ),
'simple_grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'simple_grid_field41' => array( 'location' => 'grid',
'cellId' => 'headcell_field1' ),
'simple_grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'simple_grid_field42' => array( 'location' => 'grid',
'cellId' => 'headcell_field2' ),
'simple_grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field2' ),
'simple_grid_field43' => array( 'location' => 'grid',
'cellId' => 'headcell_field3' ),
'simple_grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_field3' ),
'simple_grid_field44' => array( 'location' => 'grid',
'cellId' => 'headcell_field4' ),
'simple_grid_field4' => array( 'location' => 'grid',
'cellId' => 'cell_field4' ),
'simple_grid_field45' => array( 'location' => 'grid',
'cellId' => 'headcell_field5' ),
'simple_grid_field5' => array( 'location' => 'grid',
'cellId' => 'cell_field5' ),
'simple_grid_field46' => array( 'location' => 'grid',
'cellId' => 'headcell_field6' ),
'simple_grid_field6' => array( 'location' => 'grid',
'cellId' => 'cell_field6' ),
'simple_grid_field47' => array( 'location' => 'grid',
'cellId' => 'headcell_field7' ),
'simple_grid_field7' => array( 'location' => 'grid',
'cellId' => 'cell_field7' ),
'simple_grid_field48' => array( 'location' => 'grid',
'cellId' => 'headcell_field8' ),
'simple_grid_field8' => array( 'location' => 'grid',
'cellId' => 'cell_field8' ),
'simple_grid_field49' => array( 'location' => 'grid',
'cellId' => 'headcell_field9' ),
'simple_grid_field9' => array( 'location' => 'grid',
'cellId' => 'cell_field9' ),
'simple_grid_field50' => array( 'location' => 'grid',
'cellId' => 'headcell_field10' ),
'simple_grid_field11' => array( 'location' => 'grid',
'cellId' => 'cell_field10' ),
'simple_grid_field51' => array( 'location' => 'grid',
'cellId' => 'headcell_field11' ),
'simple_grid_field12' => array( 'location' => 'grid',
'cellId' => 'cell_field11' ),
'simple_grid_field52' => array( 'location' => 'grid',
'cellId' => 'headcell_field12' ),
'simple_grid_field13' => array( 'location' => 'grid',
'cellId' => 'cell_field12' ),
'simple_grid_field53' => array( 'location' => 'grid',
'cellId' => 'headcell_field13' ),
'simple_grid_field14' => array( 'location' => 'grid',
'cellId' => 'cell_field13' ),
'simple_grid_field54' => array( 'location' => 'grid',
'cellId' => 'headcell_field14' ),
'simple_grid_field15' => array( 'location' => 'grid',
'cellId' => 'cell_field14' ),
'simple_grid_field55' => array( 'location' => 'grid',
'cellId' => 'headcell_field15' ),
'simple_grid_field16' => array( 'location' => 'grid',
'cellId' => 'cell_field15' ),
'simple_grid_field56' => array( 'location' => 'grid',
'cellId' => 'headcell_field16' ),
'simple_grid_field17' => array( 'location' => 'grid',
'cellId' => 'cell_field16' ),
'simple_grid_field57' => array( 'location' => 'grid',
'cellId' => 'headcell_field17' ),
'simple_grid_field18' => array( 'location' => 'grid',
'cellId' => 'cell_field17' ),
'simple_grid_field58' => array( 'location' => 'grid',
'cellId' => 'headcell_field18' ),
'simple_grid_field19' => array( 'location' => 'grid',
'cellId' => 'cell_field18' ),
'simple_grid_field59' => array( 'location' => 'grid',
'cellId' => 'headcell_field19' ),
'simple_grid_field20' => array( 'location' => 'grid',
'cellId' => 'cell_field19' ),
'simple_grid_field60' => array( 'location' => 'grid',
'cellId' => 'headcell_field20' ),
'simple_grid_field21' => array( 'location' => 'grid',
'cellId' => 'cell_field20' ),
'simple_grid_field61' => array( 'location' => 'grid',
'cellId' => 'headcell_field21' ),
'simple_grid_field22' => array( 'location' => 'grid',
'cellId' => 'cell_field21' ),
'simple_grid_field62' => array( 'location' => 'grid',
'cellId' => 'headcell_field22' ),
'simple_grid_field23' => array( 'location' => 'grid',
'cellId' => 'cell_field22' ),
'simple_grid_field63' => array( 'location' => 'grid',
'cellId' => 'headcell_field23' ),
'simple_grid_field24' => array( 'location' => 'grid',
'cellId' => 'cell_field23' ),
'simple_grid_field64' => array( 'location' => 'grid',
'cellId' => 'headcell_field24' ),
'simple_grid_field25' => array( 'location' => 'grid',
'cellId' => 'cell_field24' ),
'simple_grid_field65' => array( 'location' => 'grid',
'cellId' => 'headcell_field25' ),
'simple_grid_field26' => array( 'location' => 'grid',
'cellId' => 'cell_field25' ),
'simple_grid_field66' => array( 'location' => 'grid',
'cellId' => 'headcell_field26' ),
'simple_grid_field27' => array( 'location' => 'grid',
'cellId' => 'cell_field26' ),
'simple_grid_field67' => array( 'location' => 'grid',
'cellId' => 'headcell_field27' ),
'simple_grid_field28' => array( 'location' => 'grid',
'cellId' => 'cell_field27' ),
'simple_grid_field68' => array( 'location' => 'grid',
'cellId' => 'headcell_field28' ),
'simple_grid_field29' => array( 'location' => 'grid',
'cellId' => 'cell_field28' ),
'simple_grid_field69' => array( 'location' => 'grid',
'cellId' => 'headcell_field29' ),
'simple_grid_field30' => array( 'location' => 'grid',
'cellId' => 'cell_field29' ),
'simple_grid_field70' => array( 'location' => 'grid',
'cellId' => 'headcell_field30' ),
'simple_grid_field31' => array( 'location' => 'grid',
'cellId' => 'cell_field30' ),
'simple_grid_field71' => array( 'location' => 'grid',
'cellId' => 'headcell_field31' ),
'simple_grid_field32' => array( 'location' => 'grid',
'cellId' => 'cell_field31' ),
'simple_grid_field72' => array( 'location' => 'grid',
'cellId' => 'headcell_field32' ),
'simple_grid_field33' => array( 'location' => 'grid',
'cellId' => 'cell_field32' ),
'simple_grid_field73' => array( 'location' => 'grid',
'cellId' => 'headcell_field33' ),
'simple_grid_field34' => array( 'location' => 'grid',
'cellId' => 'cell_field33' ),
'simple_grid_field74' => array( 'location' => 'grid',
'cellId' => 'headcell_field34' ),
'simple_grid_field35' => array( 'location' => 'grid',
'cellId' => 'cell_field34' ),
'simple_grid_field75' => array( 'location' => 'grid',
'cellId' => 'headcell_field35' ),
'simple_grid_field36' => array( 'location' => 'grid',
'cellId' => 'cell_field35' ),
'simple_grid_field76' => array( 'location' => 'grid',
'cellId' => 'headcell_field36' ),
'simple_grid_field37' => array( 'location' => 'grid',
'cellId' => 'cell_field36' ),
'simple_grid_field77' => array( 'location' => 'grid',
'cellId' => 'headcell_field37' ),
'simple_grid_field38' => array( 'location' => 'grid',
'cellId' => 'cell_field37' ),
'simple_grid_field78' => array( 'location' => 'grid',
'cellId' => 'headcell_field38' ),
'simple_grid_field39' => array( 'location' => 'grid',
'cellId' => 'cell_field38' ),
'simple_grid_field79' => array( 'location' => 'grid',
'cellId' => 'headcell_field39' ),
'simple_grid_field10' => array( 'location' => 'grid',
'cellId' => 'cell_field39' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'masterlist_header' => array( 'masterlist_header' ),
'back_master' => array( 'back_master' ),
'grid_field' => array( 'simple_grid_field',
'simple_grid_field1',
'simple_grid_field2',
'simple_grid_field3',
'simple_grid_field4',
'simple_grid_field5',
'simple_grid_field6',
'simple_grid_field7',
'simple_grid_field8',
'simple_grid_field9',
'simple_grid_field11',
'simple_grid_field12',
'simple_grid_field13',
'simple_grid_field14',
'simple_grid_field15',
'simple_grid_field16',
'simple_grid_field17',
'simple_grid_field18',
'simple_grid_field19',
'simple_grid_field20',
'simple_grid_field21',
'simple_grid_field22',
'simple_grid_field23',
'simple_grid_field24',
'simple_grid_field25',
'simple_grid_field26',
'simple_grid_field27',
'simple_grid_field28',
'simple_grid_field29',
'simple_grid_field30',
'simple_grid_field31',
'simple_grid_field32',
'simple_grid_field33',
'simple_grid_field34',
'simple_grid_field35',
'simple_grid_field36',
'simple_grid_field37',
'simple_grid_field38',
'simple_grid_field39',
'simple_grid_field10' ),
'grid_field_label' => array( 'simple_grid_field40',
'simple_grid_field41',
'simple_grid_field42',
'simple_grid_field43',
'simple_grid_field44',
'simple_grid_field45',
'simple_grid_field46',
'simple_grid_field47',
'simple_grid_field48',
'simple_grid_field49',
'simple_grid_field50',
'simple_grid_field51',
'simple_grid_field52',
'simple_grid_field53',
'simple_grid_field54',
'simple_grid_field55',
'simple_grid_field56',
'simple_grid_field57',
'simple_grid_field58',
'simple_grid_field59',
'simple_grid_field60',
'simple_grid_field61',
'simple_grid_field62',
'simple_grid_field63',
'simple_grid_field64',
'simple_grid_field65',
'simple_grid_field66',
'simple_grid_field67',
'simple_grid_field68',
'simple_grid_field69',
'simple_grid_field70',
'simple_grid_field71',
'simple_grid_field72',
'simple_grid_field73',
'simple_grid_field74',
'simple_grid_field75',
'simple_grid_field76',
'simple_grid_field77',
'simple_grid_field78',
'simple_grid_field79' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'headcell_field' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array( 'cat_trabajadores_altas_id_fieldheadercolumn' ),
'items' => array( 'simple_grid_field40' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field1' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array( 'cat_trabajadores_altas_id_empresa_fieldheadercolumn' ),
'items' => array( 'simple_grid_field41' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field2' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array( 'vigente_fieldheadercolumn' ),
'items' => array( 'simple_grid_field42' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field3' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array( 'fecha_de_ingreso_fieldheadercolumn' ),
'items' => array( 'simple_grid_field43' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field4' => array( 'cols' => array( 4 ),
'rows' => array( 0 ),
'tags' => array( 'apellido_paterno_fieldheadercolumn' ),
'items' => array( 'simple_grid_field44' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field5' => array( 'cols' => array( 5 ),
'rows' => array( 0 ),
'tags' => array( 'apellido_materno_fieldheadercolumn' ),
'items' => array( 'simple_grid_field45' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field6' => array( 'cols' => array( 6 ),
'rows' => array( 0 ),
'tags' => array( 'primer_nombre_fieldheadercolumn' ),
'items' => array( 'simple_grid_field46' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field7' => array( 'cols' => array( 7 ),
'rows' => array( 0 ),
'tags' => array( 'segundo_nombre_fieldheadercolumn' ),
'items' => array( 'simple_grid_field47' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field8' => array( 'cols' => array( 8 ),
'rows' => array( 0 ),
'tags' => array( 'link_foto_fieldheadercolumn' ),
'items' => array( 'simple_grid_field48' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field9' => array( 'cols' => array( 9 ),
'rows' => array( 0 ),
'tags' => array( 'fecha_de_nacimiento_fieldheadercolumn' ),
'items' => array( 'simple_grid_field49' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field10' => array( 'cols' => array( 10 ),
'rows' => array( 0 ),
'tags' => array( 'contacto_emergencia_fieldheadercolumn' ),
'items' => array( 'simple_grid_field50' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field11' => array( 'cols' => array( 11 ),
'rows' => array( 0 ),
'tags' => array( 'celular_mensajes_fieldheadercolumn' ),
'items' => array( 'simple_grid_field51' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field12' => array( 'cols' => array( 12 ),
'rows' => array( 0 ),
'tags' => array( 'rfc_fieldheadercolumn' ),
'items' => array( 'simple_grid_field52' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field13' => array( 'cols' => array( 13 ),
'rows' => array( 0 ),
'tags' => array( 'curp_fieldheadercolumn' ),
'items' => array( 'simple_grid_field53' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field14' => array( 'cols' => array( 14 ),
'rows' => array( 0 ),
'tags' => array( 'num_seguridad_social_fieldheadercolumn' ),
'items' => array( 'simple_grid_field54' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field15' => array( 'cols' => array( 15 ),
'rows' => array( 0 ),
'tags' => array( 'nacionalidad_fieldheadercolumn' ),
'items' => array( 'simple_grid_field55' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field16' => array( 'cols' => array( 16 ),
'rows' => array( 0 ),
'tags' => array( 'calle_fieldheadercolumn' ),
'items' => array( 'simple_grid_field56' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field17' => array( 'cols' => array( 17 ),
'rows' => array( 0 ),
'tags' => array( 'numero_domicilio_fieldheadercolumn' ),
'items' => array( 'simple_grid_field57' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field18' => array( 'cols' => array( 18 ),
'rows' => array( 0 ),
'tags' => array( 'colonia_fieldheadercolumn' ),
'items' => array( 'simple_grid_field58' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field19' => array( 'cols' => array( 19 ),
'rows' => array( 0 ),
'tags' => array( 'municipio_fieldheadercolumn' ),
'items' => array( 'simple_grid_field59' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field20' => array( 'cols' => array( 20 ),
'rows' => array( 0 ),
'tags' => array( 'estado_fieldheadercolumn' ),
'items' => array( 'simple_grid_field60' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field21' => array( 'cols' => array( 21 ),
'rows' => array( 0 ),
'tags' => array( 'codigo_postal_fieldheadercolumn' ),
'items' => array( 'simple_grid_field61' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field22' => array( 'cols' => array( 22 ),
'rows' => array( 0 ),
'tags' => array( 'cat_trabajadores_sexo_mu_id_fieldheadercolumn' ),
'items' => array( 'simple_grid_field62' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field23' => array( 'cols' => array( 23 ),
'rows' => array( 0 ),
'tags' => array( 'banco_fieldheadercolumn' ),
'items' => array( 'simple_grid_field63' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field24' => array( 'cols' => array( 24 ),
'rows' => array( 0 ),
'tags' => array( 'cuenta_bancaria_fieldheadercolumn' ),
'items' => array( 'simple_grid_field64' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field25' => array( 'cols' => array( 25 ),
'rows' => array( 0 ),
'tags' => array( 'cat_trabajadores_sangre_mu_id_fieldheadercolumn' ),
'items' => array( 'simple_grid_field65' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field26' => array( 'cols' => array( 26 ),
'rows' => array( 0 ),
'tags' => array( 'cat_trabajadores_local_foraneo_mu_id_fieldheadercolumn' ),
'items' => array( 'simple_grid_field66' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field27' => array( 'cols' => array( 27 ),
'rows' => array( 0 ),
'tags' => array( 'cat_trabajadores_tipo_de_pago_id_fieldheadercolumn' ),
'items' => array( 'simple_grid_field67' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field28' => array( 'cols' => array( 28 ),
'rows' => array( 0 ),
'tags' => array( 'telefono_emergencia_fieldheadercolumn' ),
'items' => array( 'simple_grid_field68' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field29' => array( 'cols' => array( 29 ),
'rows' => array( 0 ),
'tags' => array( 'municipio_nacimiento_fieldheadercolumn' ),
'items' => array( 'simple_grid_field69' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field30' => array( 'cols' => array( 30 ),
'rows' => array( 0 ),
'tags' => array( 'estado_nacimiento_fieldheadercolumn' ),
'items' => array( 'simple_grid_field70' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field31' => array( 'cols' => array( 31 ),
'rows' => array( 0 ),
'tags' => array( 'cat_trabajadores_estado_civil_mu_id_fieldheadercolumn' ),
'items' => array( 'simple_grid_field71' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field32' => array( 'cols' => array( 32 ),
'rows' => array( 0 ),
'tags' => array( 'cat_holding_02_empresas_fieldheadercolumn' ),
'items' => array( 'simple_grid_field72' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field33' => array( 'cols' => array( 33 ),
'rows' => array( 0 ),
'tags' => array( 'observaciones_fieldheadercolumn' ),
'items' => array( 'simple_grid_field73' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field34' => array( 'cols' => array( 34 ),
'rows' => array( 0 ),
'tags' => array( 'capturista_fieldheadercolumn' ),
'items' => array( 'simple_grid_field74' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field35' => array( 'cols' => array( 35 ),
'rows' => array( 0 ),
'tags' => array( 'nombre_completook_fieldheadercolumn' ),
'items' => array( 'simple_grid_field75' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field36' => array( 'cols' => array( 36 ),
'rows' => array( 0 ),
'tags' => array( 'tr_tags_numero_asignado_fieldheadercolumn' ),
'items' => array( 'simple_grid_field76' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field37' => array( 'cols' => array( 37 ),
'rows' => array( 0 ),
'tags' => array( 'fecha_de_registro_fieldheadercolumn' ),
'items' => array( 'simple_grid_field77' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field38' => array( 'cols' => array( 38 ),
'rows' => array( 0 ),
'tags' => array( 'time_stamp_fieldheadercolumn' ),
'items' => array( 'simple_grid_field78' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field39' => array( 'cols' => array( 39 ),
'rows' => array( 0 ),
'tags' => array( 'cat_trabajadores_puestos_id_fieldheadercolumn' ),
'items' => array( 'simple_grid_field79' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'cat_trabajadores_altas_id_fieldcolumn' ),
'items' => array( 'simple_grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array( 'cat_trabajadores_altas_id_empresa_fieldcolumn' ),
'items' => array( 'simple_grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array( 'vigente_fieldcolumn' ),
'items' => array( 'simple_grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field3' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array( 'fecha_de_ingreso_fieldcolumn' ),
'items' => array( 'simple_grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field4' => array( 'cols' => array( 4 ),
'rows' => array( 1 ),
'tags' => array( 'apellido_paterno_fieldcolumn' ),
'items' => array( 'simple_grid_field4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field5' => array( 'cols' => array( 5 ),
'rows' => array( 1 ),
'tags' => array( 'apellido_materno_fieldcolumn' ),
'items' => array( 'simple_grid_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field6' => array( 'cols' => array( 6 ),
'rows' => array( 1 ),
'tags' => array( 'primer_nombre_fieldcolumn' ),
'items' => array( 'simple_grid_field6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field7' => array( 'cols' => array( 7 ),
'rows' => array( 1 ),
'tags' => array( 'segundo_nombre_fieldcolumn' ),
'items' => array( 'simple_grid_field7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field8' => array( 'cols' => array( 8 ),
'rows' => array( 1 ),
'tags' => array( 'link_foto_fieldcolumn' ),
'items' => array( 'simple_grid_field8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field9' => array( 'cols' => array( 9 ),
'rows' => array( 1 ),
'tags' => array( 'fecha_de_nacimiento_fieldcolumn' ),
'items' => array( 'simple_grid_field9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field10' => array( 'cols' => array( 10 ),
'rows' => array( 1 ),
'tags' => array( 'contacto_emergencia_fieldcolumn' ),
'items' => array( 'simple_grid_field11' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field11' => array( 'cols' => array( 11 ),
'rows' => array( 1 ),
'tags' => array( 'celular_mensajes_fieldcolumn' ),
'items' => array( 'simple_grid_field12' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field12' => array( 'cols' => array( 12 ),
'rows' => array( 1 ),
'tags' => array( 'rfc_fieldcolumn' ),
'items' => array( 'simple_grid_field13' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field13' => array( 'cols' => array( 13 ),
'rows' => array( 1 ),
'tags' => array( 'curp_fieldcolumn' ),
'items' => array( 'simple_grid_field14' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field14' => array( 'cols' => array( 14 ),
'rows' => array( 1 ),
'tags' => array( 'num_seguridad_social_fieldcolumn' ),
'items' => array( 'simple_grid_field15' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field15' => array( 'cols' => array( 15 ),
'rows' => array( 1 ),
'tags' => array( 'nacionalidad_fieldcolumn' ),
'items' => array( 'simple_grid_field16' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field16' => array( 'cols' => array( 16 ),
'rows' => array( 1 ),
'tags' => array( 'calle_fieldcolumn' ),
'items' => array( 'simple_grid_field17' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field17' => array( 'cols' => array( 17 ),
'rows' => array( 1 ),
'tags' => array( 'numero_domicilio_fieldcolumn' ),
'items' => array( 'simple_grid_field18' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field18' => array( 'cols' => array( 18 ),
'rows' => array( 1 ),
'tags' => array( 'colonia_fieldcolumn' ),
'items' => array( 'simple_grid_field19' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field19' => array( 'cols' => array( 19 ),
'rows' => array( 1 ),
'tags' => array( 'municipio_fieldcolumn' ),
'items' => array( 'simple_grid_field20' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field20' => array( 'cols' => array( 20 ),
'rows' => array( 1 ),
'tags' => array( 'estado_fieldcolumn' ),
'items' => array( 'simple_grid_field21' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field21' => array( 'cols' => array( 21 ),
'rows' => array( 1 ),
'tags' => array( 'codigo_postal_fieldcolumn' ),
'items' => array( 'simple_grid_field22' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field22' => array( 'cols' => array( 22 ),
'rows' => array( 1 ),
'tags' => array( 'cat_trabajadores_sexo_mu_id_fieldcolumn' ),
'items' => array( 'simple_grid_field23' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field23' => array( 'cols' => array( 23 ),
'rows' => array( 1 ),
'tags' => array( 'banco_fieldcolumn' ),
'items' => array( 'simple_grid_field24' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field24' => array( 'cols' => array( 24 ),
'rows' => array( 1 ),
'tags' => array( 'cuenta_bancaria_fieldcolumn' ),
'items' => array( 'simple_grid_field25' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field25' => array( 'cols' => array( 25 ),
'rows' => array( 1 ),
'tags' => array( 'cat_trabajadores_sangre_mu_id_fieldcolumn' ),
'items' => array( 'simple_grid_field26' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field26' => array( 'cols' => array( 26 ),
'rows' => array( 1 ),
'tags' => array( 'cat_trabajadores_local_foraneo_mu_id_fieldcolumn' ),
'items' => array( 'simple_grid_field27' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field27' => array( 'cols' => array( 27 ),
'rows' => array( 1 ),
'tags' => array( 'cat_trabajadores_tipo_de_pago_id_fieldcolumn' ),
'items' => array( 'simple_grid_field28' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field28' => array( 'cols' => array( 28 ),
'rows' => array( 1 ),
'tags' => array( 'telefono_emergencia_fieldcolumn' ),
'items' => array( 'simple_grid_field29' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field29' => array( 'cols' => array( 29 ),
'rows' => array( 1 ),
'tags' => array( 'municipio_nacimiento_fieldcolumn' ),
'items' => array( 'simple_grid_field30' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field30' => array( 'cols' => array( 30 ),
'rows' => array( 1 ),
'tags' => array( 'estado_nacimiento_fieldcolumn' ),
'items' => array( 'simple_grid_field31' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field31' => array( 'cols' => array( 31 ),
'rows' => array( 1 ),
'tags' => array( 'cat_trabajadores_estado_civil_mu_id_fieldcolumn' ),
'items' => array( 'simple_grid_field32' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field32' => array( 'cols' => array( 32 ),
'rows' => array( 1 ),
'tags' => array( 'cat_holding_02_empresas_fieldcolumn' ),
'items' => array( 'simple_grid_field33' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field33' => array( 'cols' => array( 33 ),
'rows' => array( 1 ),
'tags' => array( 'observaciones_fieldcolumn' ),
'items' => array( 'simple_grid_field34' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field34' => array( 'cols' => array( 34 ),
'rows' => array( 1 ),
'tags' => array( 'capturista_fieldcolumn' ),
'items' => array( 'simple_grid_field35' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field35' => array( 'cols' => array( 35 ),
'rows' => array( 1 ),
'tags' => array( 'nombre_completook_fieldcolumn' ),
'items' => array( 'simple_grid_field36' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field36' => array( 'cols' => array( 36 ),
'rows' => array( 1 ),
'tags' => array( 'tr_tags_numero_asignado_fieldcolumn' ),
'items' => array( 'simple_grid_field37' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field37' => array( 'cols' => array( 37 ),
'rows' => array( 1 ),
'tags' => array( 'fecha_de_registro_fieldcolumn' ),
'items' => array( 'simple_grid_field38' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field38' => array( 'cols' => array( 38 ),
'rows' => array( 1 ),
'tags' => array( 'time_stamp_fieldcolumn' ),
'items' => array( 'simple_grid_field39' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field39' => array( 'cols' => array( 39 ),
'rows' => array( 1 ),
'tags' => array( 'cat_trabajadores_puestos_id_fieldcolumn' ),
'items' => array( 'simple_grid_field10' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field1' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field2' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field3' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field4' => array( 'cols' => array( 4 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field5' => array( 'cols' => array( 5 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field6' => array( 'cols' => array( 6 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field7' => array( 'cols' => array( 7 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field8' => array( 'cols' => array( 8 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field9' => array( 'cols' => array( 9 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field10' => array( 'cols' => array( 10 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field11' => array( 'cols' => array( 11 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field12' => array( 'cols' => array( 12 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field13' => array( 'cols' => array( 13 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field14' => array( 'cols' => array( 14 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field15' => array( 'cols' => array( 15 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field16' => array( 'cols' => array( 16 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field17' => array( 'cols' => array( 17 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field18' => array( 'cols' => array( 18 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field19' => array( 'cols' => array( 19 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field20' => array( 'cols' => array( 20 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field21' => array( 'cols' => array( 21 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field22' => array( 'cols' => array( 22 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field23' => array( 'cols' => array( 23 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field24' => array( 'cols' => array( 24 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field25' => array( 'cols' => array( 25 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field26' => array( 'cols' => array( 26 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field27' => array( 'cols' => array( 27 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field28' => array( 'cols' => array( 28 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field29' => array( 'cols' => array( 29 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field30' => array( 'cols' => array( 30 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field31' => array( 'cols' => array( 31 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field32' => array( 'cols' => array( 32 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field33' => array( 'cols' => array( 33 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field34' => array( 'cols' => array( 34 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field35' => array( 'cols' => array( 35 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field36' => array( 'cols' => array( 36 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field37' => array( 'cols' => array( 37 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field38' => array( 'cols' => array( 38 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field39' => array( 'cols' => array( 39 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 40,
'height' => 3 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'gridType' => 0,
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'masterlist',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'masterlist',
'type' => 'masterlist',
'layoutId' => 'masterlist',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'empty-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'empty-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'masterlist-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'back_master',
'masterlist_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'horizontal-grid',
'grid' => array( array( 'section' => 'head',
'cells' => array( array( 'cell' => 'headcell_field' ),
array( 'cell' => 'headcell_field1' ),
array( 'cell' => 'headcell_field2' ),
array( 'cell' => 'headcell_field3' ),
array( 'cell' => 'headcell_field4' ),
array( 'cell' => 'headcell_field5' ),
array( 'cell' => 'headcell_field6' ),
array( 'cell' => 'headcell_field7' ),
array( 'cell' => 'headcell_field8' ),
array( 'cell' => 'headcell_field9' ),
array( 'cell' => 'headcell_field10' ),
array( 'cell' => 'headcell_field11' ),
array( 'cell' => 'headcell_field12' ),
array( 'cell' => 'headcell_field13' ),
array( 'cell' => 'headcell_field14' ),
array( 'cell' => 'headcell_field15' ),
array( 'cell' => 'headcell_field16' ),
array( 'cell' => 'headcell_field17' ),
array( 'cell' => 'headcell_field18' ),
array( 'cell' => 'headcell_field19' ),
array( 'cell' => 'headcell_field20' ),
array( 'cell' => 'headcell_field21' ),
array( 'cell' => 'headcell_field22' ),
array( 'cell' => 'headcell_field23' ),
array( 'cell' => 'headcell_field24' ),
array( 'cell' => 'headcell_field25' ),
array( 'cell' => 'headcell_field26' ),
array( 'cell' => 'headcell_field27' ),
array( 'cell' => 'headcell_field28' ),
array( 'cell' => 'headcell_field29' ),
array( 'cell' => 'headcell_field30' ),
array( 'cell' => 'headcell_field31' ),
array( 'cell' => 'headcell_field32' ),
array( 'cell' => 'headcell_field33' ),
array( 'cell' => 'headcell_field34' ),
array( 'cell' => 'headcell_field35' ),
array( 'cell' => 'headcell_field36' ),
array( 'cell' => 'headcell_field37' ),
array( 'cell' => 'headcell_field38' ),
array( 'cell' => 'headcell_field39' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_field' ),
array( 'cell' => 'cell_field1' ),
array( 'cell' => 'cell_field2' ),
array( 'cell' => 'cell_field3' ),
array( 'cell' => 'cell_field4' ),
array( 'cell' => 'cell_field5' ),
array( 'cell' => 'cell_field6' ),
array( 'cell' => 'cell_field7' ),
array( 'cell' => 'cell_field8' ),
array( 'cell' => 'cell_field9' ),
array( 'cell' => 'cell_field10' ),
array( 'cell' => 'cell_field11' ),
array( 'cell' => 'cell_field12' ),
array( 'cell' => 'cell_field13' ),
array( 'cell' => 'cell_field14' ),
array( 'cell' => 'cell_field15' ),
array( 'cell' => 'cell_field16' ),
array( 'cell' => 'cell_field17' ),
array( 'cell' => 'cell_field18' ),
array( 'cell' => 'cell_field19' ),
array( 'cell' => 'cell_field20' ),
array( 'cell' => 'cell_field21' ),
array( 'cell' => 'cell_field22' ),
array( 'cell' => 'cell_field23' ),
array( 'cell' => 'cell_field24' ),
array( 'cell' => 'cell_field25' ),
array( 'cell' => 'cell_field26' ),
array( 'cell' => 'cell_field27' ),
array( 'cell' => 'cell_field28' ),
array( 'cell' => 'cell_field29' ),
array( 'cell' => 'cell_field30' ),
array( 'cell' => 'cell_field31' ),
array( 'cell' => 'cell_field32' ),
array( 'cell' => 'cell_field33' ),
array( 'cell' => 'cell_field34' ),
array( 'cell' => 'cell_field35' ),
array( 'cell' => 'cell_field36' ),
array( 'cell' => 'cell_field37' ),
array( 'cell' => 'cell_field38' ),
array( 'cell' => 'cell_field39' ) ) ),
array( 'section' => 'foot',
'cells' => array( array( 'cell' => 'footcell_field' ),
array( 'cell' => 'footcell_field1' ),
array( 'cell' => 'footcell_field2' ),
array( 'cell' => 'footcell_field3' ),
array( 'cell' => 'footcell_field4' ),
array( 'cell' => 'footcell_field5' ),
array( 'cell' => 'footcell_field6' ),
array( 'cell' => 'footcell_field7' ),
array( 'cell' => 'footcell_field8' ),
array( 'cell' => 'footcell_field9' ),
array( 'cell' => 'footcell_field10' ),
array( 'cell' => 'footcell_field11' ),
array( 'cell' => 'footcell_field12' ),
array( 'cell' => 'footcell_field13' ),
array( 'cell' => 'footcell_field14' ),
array( 'cell' => 'footcell_field15' ),
array( 'cell' => 'footcell_field16' ),
array( 'cell' => 'footcell_field17' ),
array( 'cell' => 'footcell_field18' ),
array( 'cell' => 'footcell_field19' ),
array( 'cell' => 'footcell_field20' ),
array( 'cell' => 'footcell_field21' ),
array( 'cell' => 'footcell_field22' ),
array( 'cell' => 'footcell_field23' ),
array( 'cell' => 'footcell_field24' ),
array( 'cell' => 'footcell_field25' ),
array( 'cell' => 'footcell_field26' ),
array( 'cell' => 'footcell_field27' ),
array( 'cell' => 'footcell_field28' ),
array( 'cell' => 'footcell_field29' ),
array( 'cell' => 'footcell_field30' ),
array( 'cell' => 'footcell_field31' ),
array( 'cell' => 'footcell_field32' ),
array( 'cell' => 'footcell_field33' ),
array( 'cell' => 'footcell_field34' ),
array( 'cell' => 'footcell_field35' ),
array( 'cell' => 'footcell_field36' ),
array( 'cell' => 'footcell_field37' ),
array( 'cell' => 'footcell_field38' ),
array( 'cell' => 'footcell_field39' ) ) ) ),
'cells' => array( 'headcell_field' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field40' ),
'field' => 'cat_trabajadores_altas_id',
'columnName' => 'field' ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field' ),
'field' => 'cat_trabajadores_altas_id',
'columnName' => 'field' ),
'footcell_field' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field1' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field41' ),
'field' => 'cat_trabajadores_altas_id_empresa',
'columnName' => 'field' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field1' ),
'field' => 'cat_trabajadores_altas_id_empresa',
'columnName' => 'field' ),
'footcell_field1' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field2' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field42' ),
'field' => 'vigente',
'columnName' => 'field' ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field2' ),
'field' => 'vigente',
'columnName' => 'field' ),
'footcell_field2' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field3' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field43' ),
'field' => 'fecha_de_ingreso',
'columnName' => 'field' ),
'cell_field3' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field3' ),
'field' => 'fecha_de_ingreso',
'columnName' => 'field' ),
'footcell_field3' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field4' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field44' ),
'field' => 'apellido_paterno',
'columnName' => 'field' ),
'cell_field4' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field4' ),
'field' => 'apellido_paterno',
'columnName' => 'field' ),
'footcell_field4' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field5' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field45' ),
'field' => 'apellido_materno',
'columnName' => 'field' ),
'cell_field5' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field5' ),
'field' => 'apellido_materno',
'columnName' => 'field' ),
'footcell_field5' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field6' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field46' ),
'field' => 'primer_nombre',
'columnName' => 'field' ),
'cell_field6' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field6' ),
'field' => 'primer_nombre',
'columnName' => 'field' ),
'footcell_field6' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field7' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field47' ),
'field' => 'segundo_nombre',
'columnName' => 'field' ),
'cell_field7' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field7' ),
'field' => 'segundo_nombre',
'columnName' => 'field' ),
'footcell_field7' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field8' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field48' ),
'field' => 'link_foto',
'columnName' => 'field' ),
'cell_field8' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field8' ),
'field' => 'link_foto',
'columnName' => 'field' ),
'footcell_field8' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field9' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field49' ),
'field' => 'fecha_de_nacimiento',
'columnName' => 'field' ),
'cell_field9' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field9' ),
'field' => 'fecha_de_nacimiento',
'columnName' => 'field' ),
'footcell_field9' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field10' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field50' ),
'field' => 'contacto_emergencia',
'columnName' => 'field' ),
'cell_field10' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field11' ),
'field' => 'contacto_emergencia',
'columnName' => 'field' ),
'footcell_field10' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field11' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field51' ),
'field' => 'celular_mensajes',
'columnName' => 'field' ),
'cell_field11' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field12' ),
'field' => 'celular_mensajes',
'columnName' => 'field' ),
'footcell_field11' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field12' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field52' ),
'field' => 'rfc',
'columnName' => 'field' ),
'cell_field12' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field13' ),
'field' => 'rfc',
'columnName' => 'field' ),
'footcell_field12' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field13' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field53' ),
'field' => 'curp',
'columnName' => 'field' ),
'cell_field13' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field14' ),
'field' => 'curp',
'columnName' => 'field' ),
'footcell_field13' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field14' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field54' ),
'field' => 'num_seguridad_social',
'columnName' => 'field' ),
'cell_field14' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field15' ),
'field' => 'num_seguridad_social',
'columnName' => 'field' ),
'footcell_field14' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field15' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field55' ),
'field' => 'nacionalidad',
'columnName' => 'field' ),
'cell_field15' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field16' ),
'field' => 'nacionalidad',
'columnName' => 'field' ),
'footcell_field15' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field16' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field56' ),
'field' => 'calle',
'columnName' => 'field' ),
'cell_field16' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field17' ),
'field' => 'calle',
'columnName' => 'field' ),
'footcell_field16' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field17' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field57' ),
'field' => 'numero_domicilio',
'columnName' => 'field' ),
'cell_field17' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field18' ),
'field' => 'numero_domicilio',
'columnName' => 'field' ),
'footcell_field17' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field18' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field58' ),
'field' => 'colonia',
'columnName' => 'field' ),
'cell_field18' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field19' ),
'field' => 'colonia',
'columnName' => 'field' ),
'footcell_field18' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field19' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field59' ),
'field' => 'municipio',
'columnName' => 'field' ),
'cell_field19' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field20' ),
'field' => 'municipio',
'columnName' => 'field' ),
'footcell_field19' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field20' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field60' ),
'field' => 'estado',
'columnName' => 'field' ),
'cell_field20' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field21' ),
'field' => 'estado',
'columnName' => 'field' ),
'footcell_field20' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field21' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field61' ),
'field' => 'codigo_postal',
'columnName' => 'field' ),
'cell_field21' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field22' ),
'field' => 'codigo_postal',
'columnName' => 'field' ),
'footcell_field21' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field22' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field62' ),
'field' => 'cat_trabajadores_sexo_mu_id',
'columnName' => 'field' ),
'cell_field22' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field23' ),
'field' => 'cat_trabajadores_sexo_mu_id',
'columnName' => 'field' ),
'footcell_field22' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field23' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field63' ),
'field' => 'banco',
'columnName' => 'field' ),
'cell_field23' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field24' ),
'field' => 'banco',
'columnName' => 'field' ),
'footcell_field23' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field24' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field64' ),
'field' => 'cuenta_bancaria',
'columnName' => 'field' ),
'cell_field24' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field25' ),
'field' => 'cuenta_bancaria',
'columnName' => 'field' ),
'footcell_field24' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field25' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field65' ),
'field' => 'cat_trabajadores_sangre_mu_id',
'columnName' => 'field' ),
'cell_field25' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field26' ),
'field' => 'cat_trabajadores_sangre_mu_id',
'columnName' => 'field' ),
'footcell_field25' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field26' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field66' ),
'field' => 'cat_trabajadores_local_foraneo_mu_id',
'columnName' => 'field' ),
'cell_field26' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field27' ),
'field' => 'cat_trabajadores_local_foraneo_mu_id',
'columnName' => 'field' ),
'footcell_field26' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field27' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field67' ),
'field' => 'cat_trabajadores_tipo_de_pago_id',
'columnName' => 'field' ),
'cell_field27' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field28' ),
'field' => 'cat_trabajadores_tipo_de_pago_id',
'columnName' => 'field' ),
'footcell_field27' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field28' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field68' ),
'field' => 'telefono_emergencia',
'columnName' => 'field' ),
'cell_field28' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field29' ),
'field' => 'telefono_emergencia',
'columnName' => 'field' ),
'footcell_field28' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field29' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field69' ),
'field' => 'municipio_nacimiento',
'columnName' => 'field' ),
'cell_field29' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field30' ),
'field' => 'municipio_nacimiento',
'columnName' => 'field' ),
'footcell_field29' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field30' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field70' ),
'field' => 'estado_nacimiento',
'columnName' => 'field' ),
'cell_field30' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field31' ),
'field' => 'estado_nacimiento',
'columnName' => 'field' ),
'footcell_field30' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field31' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field71' ),
'field' => 'cat_trabajadores_estado_civil_mu_id',
'columnName' => 'field' ),
'cell_field31' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field32' ),
'field' => 'cat_trabajadores_estado_civil_mu_id',
'columnName' => 'field' ),
'footcell_field31' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field32' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field72' ),
'field' => 'cat_holding_02_empresas',
'columnName' => 'field' ),
'cell_field32' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field33' ),
'field' => 'cat_holding_02_empresas',
'columnName' => 'field' ),
'footcell_field32' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field33' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field73' ),
'field' => 'observaciones',
'columnName' => 'field' ),
'cell_field33' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field34' ),
'field' => 'observaciones',
'columnName' => 'field' ),
'footcell_field33' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field34' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field74' ),
'field' => 'capturista',
'columnName' => 'field' ),
'cell_field34' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field35' ),
'field' => 'capturista',
'columnName' => 'field' ),
'footcell_field34' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field35' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field75' ),
'field' => 'nombre_completook',
'columnName' => 'field' ),
'cell_field35' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field36' ),
'field' => 'nombre_completook',
'columnName' => 'field' ),
'footcell_field35' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field36' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field76' ),
'field' => 'tr_tags_numero_asignado',
'columnName' => 'field' ),
'cell_field36' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field37' ),
'field' => 'tr_tags_numero_asignado',
'columnName' => 'field' ),
'footcell_field36' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field37' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field77' ),
'field' => 'fecha_de_registro',
'columnName' => 'field' ),
'cell_field37' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field38' ),
'field' => 'fecha_de_registro',
'columnName' => 'field' ),
'footcell_field37' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field38' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field78' ),
'field' => 'time_stamp',
'columnName' => 'field' ),
'cell_field38' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field39' ),
'field' => 'time_stamp',
'columnName' => 'field' ),
'footcell_field38' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field39' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field79' ),
'field' => 'cat_trabajadores_puestos_id',
'columnName' => 'field' ),
'cell_field39' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field10' ),
'field' => 'cat_trabajadores_puestos_id',
'columnName' => 'field' ),
'footcell_field39' => array( 'model' => 'footcell_field',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'masterlist_header' => array( 'type' => 'masterlist_header' ),
'back_master' => array( 'type' => 'back_master' ),
'simple_grid_field' => array( 'field' => 'cat_trabajadores_altas_id',
'type' => 'grid_field' ),
'simple_grid_field40' => array( 'type' => 'grid_field_label',
'field' => 'cat_trabajadores_altas_id' ),
'simple_grid_field1' => array( 'field' => 'cat_trabajadores_altas_id_empresa',
'type' => 'grid_field' ),
'simple_grid_field41' => array( 'type' => 'grid_field_label',
'field' => 'cat_trabajadores_altas_id_empresa' ),
'simple_grid_field2' => array( 'field' => 'vigente',
'type' => 'grid_field' ),
'simple_grid_field42' => array( 'type' => 'grid_field_label',
'field' => 'vigente' ),
'simple_grid_field3' => array( 'field' => 'fecha_de_ingreso',
'type' => 'grid_field' ),
'simple_grid_field43' => array( 'type' => 'grid_field_label',
'field' => 'fecha_de_ingreso' ),
'simple_grid_field4' => array( 'field' => 'apellido_paterno',
'type' => 'grid_field' ),
'simple_grid_field44' => array( 'type' => 'grid_field_label',
'field' => 'apellido_paterno' ),
'simple_grid_field5' => array( 'field' => 'apellido_materno',
'type' => 'grid_field' ),
'simple_grid_field45' => array( 'type' => 'grid_field_label',
'field' => 'apellido_materno' ),
'simple_grid_field6' => array( 'field' => 'primer_nombre',
'type' => 'grid_field' ),
'simple_grid_field46' => array( 'type' => 'grid_field_label',
'field' => 'primer_nombre' ),
'simple_grid_field7' => array( 'field' => 'segundo_nombre',
'type' => 'grid_field' ),
'simple_grid_field47' => array( 'type' => 'grid_field_label',
'field' => 'segundo_nombre' ),
'simple_grid_field8' => array( 'field' => 'link_foto',
'type' => 'grid_field' ),
'simple_grid_field48' => array( 'type' => 'grid_field_label',
'field' => 'link_foto' ),
'simple_grid_field9' => array( 'field' => 'fecha_de_nacimiento',
'type' => 'grid_field' ),
'simple_grid_field49' => array( 'type' => 'grid_field_label',
'field' => 'fecha_de_nacimiento' ),
'simple_grid_field11' => array( 'field' => 'contacto_emergencia',
'type' => 'grid_field' ),
'simple_grid_field50' => array( 'type' => 'grid_field_label',
'field' => 'contacto_emergencia' ),
'simple_grid_field12' => array( 'field' => 'celular_mensajes',
'type' => 'grid_field' ),
'simple_grid_field51' => array( 'type' => 'grid_field_label',
'field' => 'celular_mensajes' ),
'simple_grid_field13' => array( 'field' => 'rfc',
'type' => 'grid_field' ),
'simple_grid_field52' => array( 'type' => 'grid_field_label',
'field' => 'rfc' ),
'simple_grid_field14' => array( 'field' => 'curp',
'type' => 'grid_field' ),
'simple_grid_field53' => array( 'type' => 'grid_field_label',
'field' => 'curp' ),
'simple_grid_field15' => array( 'field' => 'num_seguridad_social',
'type' => 'grid_field' ),
'simple_grid_field54' => array( 'type' => 'grid_field_label',
'field' => 'num_seguridad_social' ),
'simple_grid_field16' => array( 'field' => 'nacionalidad',
'type' => 'grid_field' ),
'simple_grid_field55' => array( 'type' => 'grid_field_label',
'field' => 'nacionalidad' ),
'simple_grid_field17' => array( 'field' => 'calle',
'type' => 'grid_field' ),
'simple_grid_field56' => array( 'type' => 'grid_field_label',
'field' => 'calle' ),
'simple_grid_field18' => array( 'field' => 'numero_domicilio',
'type' => 'grid_field' ),
'simple_grid_field57' => array( 'type' => 'grid_field_label',
'field' => 'numero_domicilio' ),
'simple_grid_field19' => array( 'field' => 'colonia',
'type' => 'grid_field' ),
'simple_grid_field58' => array( 'type' => 'grid_field_label',
'field' => 'colonia' ),
'simple_grid_field20' => array( 'field' => 'municipio',
'type' => 'grid_field' ),
'simple_grid_field59' => array( 'type' => 'grid_field_label',
'field' => 'municipio' ),
'simple_grid_field21' => array( 'field' => 'estado',
'type' => 'grid_field' ),
'simple_grid_field60' => array( 'type' => 'grid_field_label',
'field' => 'estado' ),
'simple_grid_field22' => array( 'field' => 'codigo_postal',
'type' => 'grid_field' ),
'simple_grid_field61' => array( 'type' => 'grid_field_label',
'field' => 'codigo_postal' ),
'simple_grid_field23' => array( 'field' => 'cat_trabajadores_sexo_mu_id',
'type' => 'grid_field' ),
'simple_grid_field62' => array( 'type' => 'grid_field_label',
'field' => 'cat_trabajadores_sexo_mu_id' ),
'simple_grid_field24' => array( 'field' => 'banco',
'type' => 'grid_field' ),
'simple_grid_field63' => array( 'type' => 'grid_field_label',
'field' => 'banco' ),
'simple_grid_field25' => array( 'field' => 'cuenta_bancaria',
'type' => 'grid_field' ),
'simple_grid_field64' => array( 'type' => 'grid_field_label',
'field' => 'cuenta_bancaria' ),
'simple_grid_field26' => array( 'field' => 'cat_trabajadores_sangre_mu_id',
'type' => 'grid_field' ),
'simple_grid_field65' => array( 'type' => 'grid_field_label',
'field' => 'cat_trabajadores_sangre_mu_id' ),
'simple_grid_field27' => array( 'field' => 'cat_trabajadores_local_foraneo_mu_id',
'type' => 'grid_field' ),
'simple_grid_field66' => array( 'type' => 'grid_field_label',
'field' => 'cat_trabajadores_local_foraneo_mu_id' ),
'simple_grid_field28' => array( 'field' => 'cat_trabajadores_tipo_de_pago_id',
'type' => 'grid_field' ),
'simple_grid_field67' => array( 'type' => 'grid_field_label',
'field' => 'cat_trabajadores_tipo_de_pago_id' ),
'simple_grid_field29' => array( 'field' => 'telefono_emergencia',
'type' => 'grid_field' ),
'simple_grid_field68' => array( 'type' => 'grid_field_label',
'field' => 'telefono_emergencia' ),
'simple_grid_field30' => array( 'field' => 'municipio_nacimiento',
'type' => 'grid_field' ),
'simple_grid_field69' => array( 'type' => 'grid_field_label',
'field' => 'municipio_nacimiento' ),
'simple_grid_field31' => array( 'field' => 'estado_nacimiento',
'type' => 'grid_field' ),
'simple_grid_field70' => array( 'type' => 'grid_field_label',
'field' => 'estado_nacimiento' ),
'simple_grid_field32' => array( 'field' => 'cat_trabajadores_estado_civil_mu_id',
'type' => 'grid_field' ),
'simple_grid_field71' => array( 'type' => 'grid_field_label',
'field' => 'cat_trabajadores_estado_civil_mu_id' ),
'simple_grid_field33' => array( 'field' => 'cat_holding_02_empresas',
'type' => 'grid_field' ),
'simple_grid_field72' => array( 'type' => 'grid_field_label',
'field' => 'cat_holding_02_empresas' ),
'simple_grid_field34' => array( 'field' => 'observaciones',
'type' => 'grid_field' ),
'simple_grid_field73' => array( 'type' => 'grid_field_label',
'field' => 'observaciones' ),
'simple_grid_field35' => array( 'field' => 'capturista',
'type' => 'grid_field' ),
'simple_grid_field74' => array( 'type' => 'grid_field_label',
'field' => 'capturista' ),
'simple_grid_field36' => array( 'field' => 'nombre_completook',
'type' => 'grid_field' ),
'simple_grid_field75' => array( 'type' => 'grid_field_label',
'field' => 'nombre_completook' ),
'simple_grid_field37' => array( 'field' => 'tr_tags_numero_asignado',
'type' => 'grid_field' ),
'simple_grid_field76' => array( 'type' => 'grid_field_label',
'field' => 'tr_tags_numero_asignado' ),
'simple_grid_field38' => array( 'field' => 'fecha_de_registro',
'type' => 'grid_field' ),
'simple_grid_field77' => array( 'type' => 'grid_field_label',
'field' => 'fecha_de_registro' ),
'simple_grid_field39' => array( 'field' => 'time_stamp',
'type' => 'grid_field' ),
'simple_grid_field78' => array( 'type' => 'grid_field_label',
'field' => 'time_stamp' ),
'simple_grid_field10' => array( 'field' => 'cat_trabajadores_puestos_id',
'type' => 'grid_field' ),
'simple_grid_field79' => array( 'type' => 'grid_field_label',
'field' => 'cat_trabajadores_puestos_id' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>