<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'dia_semana',
'dia_de_inicio',
'llave_dias_de_inicio',
'cat_usuarios_licencias_id',
'llave_fecha_licencia',
'cat_nominas_01_generales_uuid',
'cat_nominas_01_generales_id',
'llave_dias_de_inicio_nominas_uuid',
'llave_fecha_nominas_uuid',
'semana',
'fecha_de_inicio',
'fecha_de_termino',
'ano',
'mes',
'ano_semana',
'periodo',
'descripcion_nomina',
'horas_semana_laboral',
'dia',
'llave_ano_semana_nominas_uuid' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'fecha_de_inicio' => array( 'import_field' ),
'dia_semana' => array( 'import_field1' ),
'dia_de_inicio' => array( 'import_field2' ),
'periodo' => array( 'import_field3' ),
'llave_dias_de_inicio' => array( 'import_field4' ),
'llave_dias_de_inicio_nominas_uuid' => array( 'import_field5' ),
'cat_usuarios_licencias_id' => array( 'import_field6' ),
'llave_fecha_licencia' => array( 'import_field7' ),
'cat_nominas_01_generales_uuid' => array( 'import_field8' ),
'cat_nominas_01_generales_id' => array( 'import_field9' ),
'descripcion_nomina' => array( 'import_field10' ),
'llave_fecha_nominas_uuid' => array( 'import_field11' ),
'semana' => array( 'import_field12' ),
'fecha_de_termino' => array( 'import_field13' ),
'ano' => array( 'import_field14' ),
'mes' => array( 'import_field15' ),
'ano_semana' => array( 'import_field16' ),
'horas_semana_laboral' => array( 'import_field17' ),
'dia' => array( 'import_field18' ),
'llave_ano_semana_nominas_uuid' => array( 'import_field19' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field1',
'import_field2',
'import_field4',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field5',
'import_field11',
'import_field12',
'import_field',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field3',
'import_field10',
'import_field17',
'import_field18',
'import_field19' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field4' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field5' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field' => 'grid',
'import_field13' => 'grid',
'import_field14' => 'grid',
'import_field15' => 'grid',
'import_field16' => 'grid',
'import_field3' => 'grid',
'import_field10' => 'grid',
'import_field17' => 'grid',
'import_field18' => 'grid',
'import_field19' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field1',
'import_field2',
'import_field4',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field5',
'import_field11',
'import_field12',
'import_field',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field3',
'import_field10',
'import_field17',
'import_field18',
'import_field19' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'fecha_de_inicio',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'dia_semana',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'dia_de_inicio',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'periodo',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'llave_dias_de_inicio',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'llave_dias_de_inicio_nominas_uuid',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'cat_usuarios_licencias_id',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'llave_fecha_licencia',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'cat_nominas_01_generales_uuid',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'cat_nominas_01_generales_id',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'descripcion_nomina',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'llave_fecha_nominas_uuid',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'semana',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'fecha_de_termino',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'ano',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'mes',
'type' => 'import_field' ),
'import_field16' => array( 'field' => 'ano_semana',
'type' => 'import_field' ),
'import_field17' => array( 'field' => 'horas_semana_laboral',
'type' => 'import_field' ),
'import_field18' => array( 'field' => 'dia',
'type' => 'import_field' ),
'import_field19' => array( 'field' => 'llave_ano_semana_nominas_uuid',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>