<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'vigente',
'fecha_de_registro',
'apellido_paterno',
'apellido_materno',
'primer_nombre',
'segundo_nombre',
'rfc',
'curp',
'num_seguridad_social',
'municipio_nacimiento',
'estado_nacimiento',
'nacionalidad',
'telefono_emergencia',
'contacto_emergencia',
'capturista',
'fecha_de_nacimiento',
'celular_mensajes',
'cat_trabajadores_altas_id_empresa',
'cat_trabajadores_altas_id',
'tr_tags_numero_asignado',
'cat_trabajadores_sexo_mu_id',
'cat_trabajadores_estado_civil_mu_id',
'calle',
'colonia',
'municipio',
'estado',
'codigo_postal',
'banco',
'cuenta_bancaria',
'cat_trabajadores_sangre_mu_id',
'cat_trabajadores_local_foraneo_mu_id',
'cat_trabajadores_tipo_de_pago_id',
'cat_holding_02_empresas',
'fecha_de_ingreso',
'numero_domicilio',
'observaciones',
'link_foto',
'time_stamp',
'cat_nominas_01_generales_uuid',
'cat_trabajadores_puestos_id',
'permiso_msm',
'estatus',
'fecha_de_captura',
'face_id',
'descripcion_puesto',
'descripcion_sexo',
'descripcion_estado_civil',
'descripcion_sangre',
'descripcion_local_foraneo',
'descripcion_tipo_de_pago',
'descripcion_empresas' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'capturista' => array( 'import_field2' ),
'vigente' => array( 'import_field3' ),
'fecha_de_registro' => array( 'import_field4' ),
'apellido_paterno' => array( 'import_field6' ),
'apellido_materno' => array( 'import_field7' ),
'primer_nombre' => array( 'import_field8' ),
'segundo_nombre' => array( 'import_field9' ),
'rfc' => array( 'import_field10' ),
'curp' => array( 'import_field11' ),
'num_seguridad_social' => array( 'import_field12' ),
'municipio_nacimiento' => array( 'import_field13' ),
'estado_nacimiento' => array( 'import_field14' ),
'nacionalidad' => array( 'import_field15' ),
'telefono_emergencia' => array( 'import_field16' ),
'contacto_emergencia' => array( 'import_field17' ),
'fecha_de_nacimiento' => array( 'import_field' ),
'celular_mensajes' => array( 'import_field19' ),
'cat_trabajadores_altas_id_empresa' => array( 'import_field5' ),
'cat_trabajadores_altas_id' => array( 'import_field20' ),
'tr_tags_numero_asignado' => array( 'import_field21' ),
'cat_trabajadores_sexo_mu_id' => array( 'import_field22' ),
'cat_trabajadores_estado_civil_mu_id' => array( 'import_field23' ),
'calle' => array( 'import_field24' ),
'colonia' => array( 'import_field25' ),
'municipio' => array( 'import_field26' ),
'estado' => array( 'import_field27' ),
'codigo_postal' => array( 'import_field28' ),
'banco' => array( 'import_field29' ),
'cuenta_bancaria' => array( 'import_field30' ),
'cat_trabajadores_sangre_mu_id' => array( 'import_field31' ),
'cat_trabajadores_local_foraneo_mu_id' => array( 'import_field32' ),
'cat_trabajadores_tipo_de_pago_id' => array( 'import_field33' ),
'cat_holding_02_empresas' => array( 'import_field34' ),
'fecha_de_ingreso' => array( 'import_field35' ),
'numero_domicilio' => array( 'import_field36' ),
'observaciones' => array( 'import_field37' ),
'link_foto' => array( 'import_field38' ),
'time_stamp' => array( 'import_field39' ),
'cat_nominas_01_generales_uuid' => array( 'import_field41' ),
'cat_trabajadores_puestos_id' => array( 'import_field1' ),
'permiso_msm' => array( 'import_field18' ),
'estatus' => array( 'import_field40' ),
'fecha_de_captura' => array( 'import_field42' ),
'face_id' => array( 'import_field43' ),
'descripcion_puesto' => array( 'import_field44' ),
'descripcion_sexo' => array( 'import_field45' ),
'descripcion_estado_civil' => array( 'import_field46' ),
'descripcion_sangre' => array( 'import_field47' ),
'descripcion_local_foraneo' => array( 'import_field48' ),
'descripcion_tipo_de_pago' => array( 'import_field49' ),
'descripcion_empresas' => array( 'import_field50' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field3',
'import_field4',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field2',
'import_field',
'import_field19',
'import_field5',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32',
'import_field33',
'import_field34',
'import_field35',
'import_field36',
'import_field37',
'import_field38',
'import_field39',
'import_field41',
'import_field1',
'import_field18',
'import_field40',
'import_field42',
'import_field43',
'import_field44',
'import_field45',
'import_field46',
'import_field47',
'import_field48',
'import_field49',
'import_field50' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field13' => 'grid',
'import_field14' => 'grid',
'import_field15' => 'grid',
'import_field16' => 'grid',
'import_field17' => 'grid',
'import_field2' => 'grid',
'import_field' => 'grid',
'import_field19' => 'grid',
'import_field5' => 'grid',
'import_field20' => 'grid',
'import_field21' => 'grid',
'import_field22' => 'grid',
'import_field23' => 'grid',
'import_field24' => 'grid',
'import_field25' => 'grid',
'import_field26' => 'grid',
'import_field27' => 'grid',
'import_field28' => 'grid',
'import_field29' => 'grid',
'import_field30' => 'grid',
'import_field31' => 'grid',
'import_field32' => 'grid',
'import_field33' => 'grid',
'import_field34' => 'grid',
'import_field35' => 'grid',
'import_field36' => 'grid',
'import_field37' => 'grid',
'import_field38' => 'grid',
'import_field39' => 'grid',
'import_field41' => 'grid',
'import_field1' => 'grid',
'import_field18' => 'grid',
'import_field40' => 'grid',
'import_field42' => 'grid',
'import_field43' => 'grid',
'import_field44' => 'grid',
'import_field45' => 'grid',
'import_field46' => 'grid',
'import_field47' => 'grid',
'import_field48' => 'grid',
'import_field49' => 'grid',
'import_field50' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field2',
'import_field3',
'import_field4',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field',
'import_field19',
'import_field5',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32',
'import_field33',
'import_field34',
'import_field35',
'import_field36',
'import_field37',
'import_field38',
'import_field39',
'import_field41',
'import_field1',
'import_field18',
'import_field40',
'import_field42',
'import_field43',
'import_field44',
'import_field45',
'import_field46',
'import_field47',
'import_field48',
'import_field49',
'import_field50' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field3',
'import_field4',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field2',
'import_field',
'import_field19',
'import_field5',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32',
'import_field33',
'import_field34',
'import_field35',
'import_field36',
'import_field37',
'import_field38',
'import_field39',
'import_field41',
'import_field1',
'import_field18',
'import_field40',
'import_field42',
'import_field43',
'import_field44',
'import_field45',
'import_field46',
'import_field47',
'import_field48',
'import_field49',
'import_field50' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field2' => array( 'field' => 'capturista',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'vigente',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'fecha_de_registro',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'apellido_paterno',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'apellido_materno',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'primer_nombre',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'segundo_nombre',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'rfc',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'curp',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'num_seguridad_social',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'municipio_nacimiento',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'estado_nacimiento',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'nacionalidad',
'type' => 'import_field' ),
'import_field16' => array( 'field' => 'telefono_emergencia',
'type' => 'import_field' ),
'import_field17' => array( 'field' => 'contacto_emergencia',
'type' => 'import_field' ),
'import_field' => array( 'field' => 'fecha_de_nacimiento',
'type' => 'import_field' ),
'import_field19' => array( 'field' => 'celular_mensajes',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'cat_trabajadores_altas_id_empresa',
'type' => 'import_field' ),
'import_field20' => array( 'field' => 'cat_trabajadores_altas_id',
'type' => 'import_field' ),
'import_field21' => array( 'field' => 'tr_tags_numero_asignado',
'type' => 'import_field' ),
'import_field22' => array( 'field' => 'cat_trabajadores_sexo_mu_id',
'type' => 'import_field' ),
'import_field23' => array( 'field' => 'cat_trabajadores_estado_civil_mu_id',
'type' => 'import_field' ),
'import_field24' => array( 'field' => 'calle',
'type' => 'import_field' ),
'import_field25' => array( 'field' => 'colonia',
'type' => 'import_field' ),
'import_field26' => array( 'field' => 'municipio',
'type' => 'import_field' ),
'import_field27' => array( 'field' => 'estado',
'type' => 'import_field' ),
'import_field28' => array( 'field' => 'codigo_postal',
'type' => 'import_field' ),
'import_field29' => array( 'field' => 'banco',
'type' => 'import_field' ),
'import_field30' => array( 'field' => 'cuenta_bancaria',
'type' => 'import_field' ),
'import_field31' => array( 'field' => 'cat_trabajadores_sangre_mu_id',
'type' => 'import_field' ),
'import_field32' => array( 'field' => 'cat_trabajadores_local_foraneo_mu_id',
'type' => 'import_field' ),
'import_field33' => array( 'field' => 'cat_trabajadores_tipo_de_pago_id',
'type' => 'import_field' ),
'import_field34' => array( 'field' => 'cat_holding_02_empresas',
'type' => 'import_field' ),
'import_field35' => array( 'field' => 'fecha_de_ingreso',
'type' => 'import_field' ),
'import_field36' => array( 'field' => 'numero_domicilio',
'type' => 'import_field' ),
'import_field37' => array( 'field' => 'observaciones',
'type' => 'import_field' ),
'import_field38' => array( 'field' => 'link_foto',
'type' => 'import_field' ),
'import_field39' => array( 'field' => 'time_stamp',
'type' => 'import_field' ),
'import_field41' => array( 'field' => 'cat_nominas_01_generales_uuid',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'cat_trabajadores_puestos_id',
'type' => 'import_field' ),
'import_field18' => array( 'field' => 'permiso_msm',
'type' => 'import_field' ),
'import_field40' => array( 'field' => 'estatus',
'type' => 'import_field' ),
'import_field42' => array( 'field' => 'fecha_de_captura',
'type' => 'import_field' ),
'import_field43' => array( 'field' => 'face_id',
'type' => 'import_field' ),
'import_field44' => array( 'field' => 'descripcion_puesto',
'type' => 'import_field' ),
'import_field45' => array( 'field' => 'descripcion_sexo',
'type' => 'import_field' ),
'import_field46' => array( 'field' => 'descripcion_estado_civil',
'type' => 'import_field' ),
'import_field47' => array( 'field' => 'descripcion_sangre',
'type' => 'import_field' ),
'import_field48' => array( 'field' => 'descripcion_local_foraneo',
'type' => 'import_field' ),
'import_field49' => array( 'field' => 'descripcion_tipo_de_pago',
'type' => 'import_field' ),
'import_field50' => array( 'field' => 'descripcion_empresas',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>