<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'cat_trabajadores_altas_id',
'nombre',
'cat_nominas_periodicidad_mu_id',
'descripcion_periodicidad',
'cat_nominas_dias_semana_mu_id_inicio',
'descripcion_dias',
'cat_nomina_conceptos_factor_de_calculo_mu_id',
'descripcion_factor_de_calculo',
'factor_nomina_conceptos',
'costo_bruto_nominas_conceptos',
'fecha_de_inicio_conceptos',
'fecha_de_termino_conceptos',
'cat_holding_03_empresas_unidades_productivas_id',
'descripcion_unidades_productivas',
'cat_actividades_id',
'descripcion_actividad',
'cat_actividades_unidades_de_costo_id',
'descripcion_unidades_de_costo',
'factor_de_calculo',
'cat_actividades_alcance_mu_id',
'descripcion_alcance',
'cat_nominas_intervalos_mu_id',
'descripcion_intervalos',
'cat_actividades_metodo_de_costeo_variables_id',
'descripcion_variable',
'descripcion_metodo_de_costeo',
'fecha_de_inicio_actividad',
'fecha_de_termino_actividad',
'limite_inferior',
'limite_superior',
'costo_bruto_actividad',
'cat_holding_04_unidades_productivas_lotes_id',
'descripcion_lote',
'cat_usuarios_licencias_id',
'cat_nominas_conceptos_clasificacion_mu_id',
'descripcion_nominas_conceptos_clasificacion',
'cat_nominas_conceptos_id',
'descripcion_nominas_conceptos1',
'cat_nomina_conceptos_id',
'descripcion_nominas_conceptos' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'cat_nominas_conceptos_id' => array( 'import_field' ),
'cat_trabajadores_altas_id' => array( 'import_field1' ),
'nombre' => array( 'import_field2' ),
'cat_nominas_periodicidad_mu_id' => array( 'import_field3' ),
'descripcion_periodicidad' => array( 'import_field4' ),
'cat_nominas_dias_semana_mu_id_inicio' => array( 'import_field5' ),
'descripcion_dias' => array( 'import_field6' ),
'descripcion_nominas_conceptos1' => array( 'import_field7' ),
'cat_nomina_conceptos_id' => array( 'import_field8' ),
'cat_nomina_conceptos_factor_de_calculo_mu_id' => array( 'import_field9' ),
'descripcion_factor_de_calculo' => array( 'import_field10' ),
'factor_nomina_conceptos' => array( 'import_field11' ),
'costo_bruto_nominas_conceptos' => array( 'import_field12' ),
'fecha_de_inicio_conceptos' => array( 'import_field13' ),
'fecha_de_termino_conceptos' => array( 'import_field14' ),
'cat_holding_03_empresas_unidades_productivas_id' => array( 'import_field15' ),
'descripcion_unidades_productivas' => array( 'import_field16' ),
'cat_actividades_id' => array( 'import_field17' ),
'descripcion_actividad' => array( 'import_field18' ),
'cat_actividades_unidades_de_costo_id' => array( 'import_field19' ),
'descripcion_unidades_de_costo' => array( 'import_field20' ),
'factor_de_calculo' => array( 'import_field21' ),
'descripcion_nominas_conceptos' => array( 'import_field22' ),
'cat_actividades_alcance_mu_id' => array( 'import_field24' ),
'descripcion_alcance' => array( 'import_field25' ),
'cat_nominas_intervalos_mu_id' => array( 'import_field26' ),
'descripcion_intervalos' => array( 'import_field27' ),
'cat_actividades_metodo_de_costeo_variables_id' => array( 'import_field28' ),
'descripcion_variable' => array( 'import_field29' ),
'descripcion_metodo_de_costeo' => array( 'import_field30' ),
'fecha_de_inicio_actividad' => array( 'import_field31' ),
'fecha_de_termino_actividad' => array( 'import_field32' ),
'limite_inferior' => array( 'import_field33' ),
'limite_superior' => array( 'import_field34' ),
'costo_bruto_actividad' => array( 'import_field35' ),
'cat_holding_04_unidades_productivas_lotes_id' => array( 'import_field36' ),
'descripcion_lote' => array( 'import_field37' ),
'cat_usuarios_licencias_id' => array( 'import_field38' ),
'cat_nominas_conceptos_clasificacion_mu_id' => array( 'import_field39' ),
'descripcion_nominas_conceptos_clasificacion' => array( 'import_field40' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32',
'import_field33',
'import_field34',
'import_field35',
'import_field36',
'import_field37',
'import_field38',
'import_field39',
'import_field40',
'import_field',
'import_field7',
'import_field8',
'import_field22' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field13' => 'grid',
'import_field14' => 'grid',
'import_field15' => 'grid',
'import_field16' => 'grid',
'import_field17' => 'grid',
'import_field18' => 'grid',
'import_field19' => 'grid',
'import_field20' => 'grid',
'import_field21' => 'grid',
'import_field24' => 'grid',
'import_field25' => 'grid',
'import_field26' => 'grid',
'import_field27' => 'grid',
'import_field28' => 'grid',
'import_field29' => 'grid',
'import_field30' => 'grid',
'import_field31' => 'grid',
'import_field32' => 'grid',
'import_field33' => 'grid',
'import_field34' => 'grid',
'import_field35' => 'grid',
'import_field36' => 'grid',
'import_field37' => 'grid',
'import_field38' => 'grid',
'import_field39' => 'grid',
'import_field40' => 'grid',
'import_field' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field22' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32',
'import_field33',
'import_field34',
'import_field35',
'import_field36',
'import_field37',
'import_field38',
'import_field39',
'import_field40' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32',
'import_field33',
'import_field34',
'import_field35',
'import_field36',
'import_field37',
'import_field38',
'import_field39',
'import_field40',
'import_field',
'import_field7',
'import_field8',
'import_field22' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'cat_nominas_conceptos_id',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'cat_trabajadores_altas_id',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'nombre',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'cat_nominas_periodicidad_mu_id',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'descripcion_periodicidad',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'cat_nominas_dias_semana_mu_id_inicio',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'descripcion_dias',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'descripcion_nominas_conceptos1',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'cat_nomina_conceptos_id',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'cat_nomina_conceptos_factor_de_calculo_mu_id',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'descripcion_factor_de_calculo',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'factor_nomina_conceptos',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'costo_bruto_nominas_conceptos',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'fecha_de_inicio_conceptos',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'fecha_de_termino_conceptos',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'cat_holding_03_empresas_unidades_productivas_id',
'type' => 'import_field' ),
'import_field16' => array( 'field' => 'descripcion_unidades_productivas',
'type' => 'import_field' ),
'import_field17' => array( 'field' => 'cat_actividades_id',
'type' => 'import_field' ),
'import_field18' => array( 'field' => 'descripcion_actividad',
'type' => 'import_field' ),
'import_field19' => array( 'field' => 'cat_actividades_unidades_de_costo_id',
'type' => 'import_field' ),
'import_field20' => array( 'field' => 'descripcion_unidades_de_costo',
'type' => 'import_field' ),
'import_field21' => array( 'field' => 'factor_de_calculo',
'type' => 'import_field' ),
'import_field22' => array( 'field' => 'descripcion_nominas_conceptos',
'type' => 'import_field' ),
'import_field24' => array( 'field' => 'cat_actividades_alcance_mu_id',
'type' => 'import_field' ),
'import_field25' => array( 'field' => 'descripcion_alcance',
'type' => 'import_field' ),
'import_field26' => array( 'field' => 'cat_nominas_intervalos_mu_id',
'type' => 'import_field' ),
'import_field27' => array( 'field' => 'descripcion_intervalos',
'type' => 'import_field' ),
'import_field28' => array( 'field' => 'cat_actividades_metodo_de_costeo_variables_id',
'type' => 'import_field' ),
'import_field29' => array( 'field' => 'descripcion_variable',
'type' => 'import_field' ),
'import_field30' => array( 'field' => 'descripcion_metodo_de_costeo',
'type' => 'import_field' ),
'import_field31' => array( 'field' => 'fecha_de_inicio_actividad',
'type' => 'import_field' ),
'import_field32' => array( 'field' => 'fecha_de_termino_actividad',
'type' => 'import_field' ),
'import_field33' => array( 'field' => 'limite_inferior',
'type' => 'import_field' ),
'import_field34' => array( 'field' => 'limite_superior',
'type' => 'import_field' ),
'import_field35' => array( 'field' => 'costo_bruto_actividad',
'type' => 'import_field' ),
'import_field36' => array( 'field' => 'cat_holding_04_unidades_productivas_lotes_id',
'type' => 'import_field' ),
'import_field37' => array( 'field' => 'descripcion_lote',
'type' => 'import_field' ),
'import_field38' => array( 'field' => 'cat_usuarios_licencias_id',
'type' => 'import_field' ),
'import_field39' => array( 'field' => 'cat_nominas_conceptos_clasificacion_mu_id',
'type' => 'import_field' ),
'import_field40' => array( 'field' => 'descripcion_nominas_conceptos_clasificacion',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>