<?php
			$optionsArray = array( 'totals' => array( 'cat_ventas_clientes_id' => array( 'totalsType' => '' ),
'vigente' => array( 'totalsType' => '' ),
'time_stamp' => array( 'totalsType' => '' ),
'capturista' => array( 'totalsType' => '' ),
'fecha_de_captura' => array( 'totalsType' => '' ),
'nombre_cliente_old' => array( 'totalsType' => '' ),
'rfc_cliente' => array( 'totalsType' => '' ),
'descripcion_cliente' => array( 'totalsType' => '' ),
'cp' => array( 'totalsType' => '' ),
'calle' => array( 'totalsType' => '' ),
'num_ex' => array( 'totalsType' => '' ),
'num_int' => array( 'totalsType' => '' ),
'colonia' => array( 'totalsType' => '' ),
'localidad' => array( 'totalsType' => '' ),
'municipio' => array( 'totalsType' => '' ),
'estado' => array( 'totalsType' => '' ),
'pais' => array( 'totalsType' => '' ),
'telefono' => array( 'totalsType' => '' ),
'celular' => array( 'totalsType' => '' ),
'email' => array( 'totalsType' => '' ),
'pagina_web' => array( 'totalsType' => '' ),
'contacto' => array( 'totalsType' => '' ),
'puesto' => array( 'totalsType' => '' ),
'correo_contacto' => array( 'totalsType' => '' ),
'celular_contacto' => array( 'totalsType' => '' ),
'clabe_interbancaria' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'vigente',
'rfc_cliente',
'descripcion_cliente',
'cp',
'calle',
'num_ex',
'num_int',
'colonia',
'localidad',
'municipio',
'estado',
'pais',
'telefono',
'celular',
'email',
'pagina_web',
'contacto',
'puesto',
'correo_contacto',
'celular_contacto',
'capturista',
'fecha_de_captura' ),
'exportFields' => array( 'vigente',
'rfc_cliente',
'descripcion_cliente',
'cp',
'calle',
'num_ex',
'num_int',
'colonia',
'localidad',
'municipio',
'estado',
'pais',
'telefono',
'celular',
'email',
'pagina_web',
'contacto',
'puesto',
'correo_contacto',
'celular_contacto',
'capturista',
'fecha_de_captura' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'vigente' => array( 'export_field' ),
'rfc_cliente' => array( 'export_field1' ),
'descripcion_cliente' => array( 'export_field2' ),
'cp' => array( 'export_field3' ),
'calle' => array( 'export_field4' ),
'num_ex' => array( 'export_field5' ),
'num_int' => array( 'export_field6' ),
'colonia' => array( 'export_field7' ),
'localidad' => array( 'export_field8' ),
'municipio' => array( 'export_field9' ),
'estado' => array( 'export_field10' ),
'pais' => array( 'export_field11' ),
'telefono' => array( 'export_field12' ),
'celular' => array( 'export_field13' ),
'email' => array( 'export_field14' ),
'pagina_web' => array( 'export_field15' ),
'contacto' => array( 'export_field16' ),
'puesto' => array( 'export_field17' ),
'correo_contacto' => array( 'export_field18' ),
'celular_contacto' => array( 'export_field19' ),
'capturista' => array( 'export_field20' ),
'fecha_de_captura' => array( 'export_field21' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field15' => 'grid',
'export_field16' => 'grid',
'export_field17' => 'grid',
'export_field18' => 'grid',
'export_field19' => 'grid',
'export_field20' => 'grid',
'export_field21' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'vigente',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'rfc_cliente',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'descripcion_cliente',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'cp',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'calle',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'num_ex',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'num_int',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'colonia',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'localidad',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'municipio',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'estado',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'pais',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'telefono',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'celular',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'email',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'pagina_web',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'contacto',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'puesto',
'type' => 'export_field' ),
'export_field18' => array( 'field' => 'correo_contacto',
'type' => 'export_field' ),
'export_field19' => array( 'field' => 'celular_contacto',
'type' => 'export_field' ),
'export_field20' => array( 'field' => 'capturista',
'type' => 'export_field' ),
'export_field21' => array( 'field' => 'fecha_de_captura',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>