<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'cat_holding_04a_unidades_productivas_lotes_historico_id',
'cat_produccion_cultivos_01_productos_id',
'cat_produccion_cultivos_01_variedades_id',
'hectareas',
'acres',
'time_stamp',
'vigente',
'capturista',
'descripcion_lote',
'Lat',
'Lng',
'cat_holding_04_unidades_productivas_lotes_id',
'llave',
'surcos' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'cat_holding_04a_unidades_productivas_lotes_historico_id' => array( 'import_field' ),
'cat_produccion_cultivos_01_productos_id' => array( 'import_field1' ),
'cat_produccion_cultivos_01_variedades_id' => array( 'import_field2' ),
'hectareas' => array( 'import_field3' ),
'acres' => array( 'import_field4' ),
'time_stamp' => array( 'import_field5' ),
'vigente' => array( 'import_field6' ),
'capturista' => array( 'import_field7' ),
'descripcion_lote' => array( 'import_field8' ),
'Lat' => array( 'import_field9' ),
'Lng' => array( 'import_field10' ),
'cat_holding_04_unidades_productivas_lotes_id' => array( 'import_field11' ),
'llave' => array( 'import_field12' ),
'surcos' => array( 'import_field13' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field13' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'cat_holding_04a_unidades_productivas_lotes_historico_id',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'cat_produccion_cultivos_01_productos_id',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'cat_produccion_cultivos_01_variedades_id',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'hectareas',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'acres',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'time_stamp',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'vigente',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'capturista',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'descripcion_lote',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'Lat',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'Lng',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'cat_holding_04_unidades_productivas_lotes_id',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'llave',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'surcos',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>