<?php
			$optionsArray = array( 'totals' => array( 'periodo' => array( 'totalsType' => '' ),
'cat_nominas_01_generales_uuid' => array( 'totalsType' => '' ),
'fecha_de_inicio' => array( 'totalsType' => '' ),
'fecha_de_termino' => array( 'totalsType' => '' ),
'ano' => array( 'totalsType' => '' ),
'mes' => array( 'totalsType' => '' ),
'semana' => array( 'totalsType' => '' ),
'ano_semana' => array( 'totalsType' => '' ),
'descripcion_nomina' => array( 'totalsType' => '' ),
'horas_semana_laboral' => array( 'totalsType' => '' ),
'dia' => array( 'totalsType' => '' ),
'dia_de_inicio' => array( 'totalsType' => '' ),
'dia_semana' => array( 'totalsType' => '' ),
'llave_dias_de_inicio' => array( 'totalsType' => '' ),
'llave_dias_de_inicio_nominas_uuid' => array( 'totalsType' => '' ),
'llave_fecha_nominas_uuid' => array( 'totalsType' => '' ),
'llave_ano_semana_nominas_uuid' => array( 'totalsType' => '' ),
'llave_fecha_licencia' => array( 'totalsType' => '' ),
'cat_usuarios_licencias_id' => array( 'totalsType' => '' ),
'cat_nominas_01_generales_id' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'fecha_de_inicio',
'dia_semana',
'dia_de_inicio',
'periodo',
'llave_dias_de_inicio',
'llave_dias_de_inicio_nominas_uuid',
'cat_usuarios_licencias_id',
'llave_fecha_licencia',
'cat_nominas_01_generales_uuid',
'cat_nominas_01_generales_id',
'descripcion_nomina',
'llave_fecha_nominas_uuid',
'semana',
'fecha_de_termino',
'ano',
'mes',
'ano_semana',
'horas_semana_laboral',
'dia',
'llave_ano_semana_nominas_uuid' ),
'exportFields' => array( 'dia_semana',
'dia_de_inicio',
'llave_dias_de_inicio',
'cat_usuarios_licencias_id',
'llave_fecha_licencia',
'cat_nominas_01_generales_uuid',
'cat_nominas_01_generales_id',
'llave_dias_de_inicio_nominas_uuid',
'llave_fecha_nominas_uuid',
'semana',
'fecha_de_inicio',
'fecha_de_termino',
'ano',
'mes',
'ano_semana',
'periodo',
'descripcion_nomina',
'horas_semana_laboral',
'dia',
'llave_ano_semana_nominas_uuid' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'fecha_de_inicio' => array( 'export_field' ),
'dia_semana' => array( 'export_field1' ),
'dia_de_inicio' => array( 'export_field2' ),
'periodo' => array( 'export_field3' ),
'llave_dias_de_inicio' => array( 'export_field4' ),
'llave_dias_de_inicio_nominas_uuid' => array( 'export_field5' ),
'cat_usuarios_licencias_id' => array( 'export_field6' ),
'llave_fecha_licencia' => array( 'export_field7' ),
'cat_nominas_01_generales_uuid' => array( 'export_field8' ),
'cat_nominas_01_generales_id' => array( 'export_field9' ),
'descripcion_nomina' => array( 'export_field10' ),
'llave_fecha_nominas_uuid' => array( 'export_field11' ),
'semana' => array( 'export_field12' ),
'fecha_de_termino' => array( 'export_field13' ),
'ano' => array( 'export_field14' ),
'mes' => array( 'export_field15' ),
'ano_semana' => array( 'export_field16' ),
'horas_semana_laboral' => array( 'export_field17' ),
'dia' => array( 'export_field18' ),
'llave_ano_semana_nominas_uuid' => array( 'export_field19' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field1',
'export_field2',
'export_field4',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field5',
'export_field11',
'export_field12',
'export_field',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field3',
'export_field10',
'export_field17',
'export_field18',
'export_field19' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field4' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field5' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field15' => 'grid',
'export_field16' => 'grid',
'export_field3' => 'grid',
'export_field10' => 'grid',
'export_field17' => 'grid',
'export_field18' => 'grid',
'export_field19' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field1',
'export_field2',
'export_field4',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field5',
'export_field11',
'export_field12',
'export_field',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field3',
'export_field10',
'export_field17',
'export_field18',
'export_field19' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'fecha_de_inicio',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'dia_semana',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'dia_de_inicio',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'periodo',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'llave_dias_de_inicio',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'llave_dias_de_inicio_nominas_uuid',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'cat_usuarios_licencias_id',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'llave_fecha_licencia',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'cat_nominas_01_generales_uuid',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'cat_nominas_01_generales_id',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'descripcion_nomina',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'llave_fecha_nominas_uuid',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'semana',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'fecha_de_termino',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'ano',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'mes',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'ano_semana',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'horas_semana_laboral',
'type' => 'export_field' ),
'export_field18' => array( 'field' => 'dia',
'type' => 'export_field' ),
'export_field19' => array( 'field' => 'llave_ano_semana_nominas_uuid',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>