<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'tr_actividades_asistencias_app_uuid',
'cat_holding_03_empresas_unidades_productivas_id',
'cat_actividades_turnos_id',
'cat_trabajadores_altas_id',
'vigente',
'capturista',
'cat_actividades_ingreso_egreso_mu',
'fecha',
'mes',
'fecha_de_captura',
'cat_usuarios_licencias_id1',
'dia_de_inicio',
'dia_nombre',
'dia_numero',
'calculo' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'tr_actividades_asistencias_app_uuid' => array( 'import_field1' ),
'cat_holding_03_empresas_unidades_productivas_id' => array( 'import_field2' ),
'cat_actividades_turnos_id' => array( 'import_field3' ),
'cat_trabajadores_altas_id' => array( 'import_field4' ),
'dia_nombre' => array( 'import_field5' ),
'vigente' => array( 'import_field6' ),
'capturista' => array( 'import_field7' ),
'cat_actividades_ingreso_egreso_mu' => array( 'import_field' ),
'fecha' => array( 'import_field8' ),
'dia_numero' => array( 'import_field9' ),
'calculo' => array( 'import_field10' ),
'mes' => array( 'import_field12' ),
'fecha_de_captura' => array( 'import_field13' ),
'cat_usuarios_licencias_id1' => array( 'import_field14' ),
'dia_de_inicio' => array( 'import_field15' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field6',
'import_field7',
'import_field',
'import_field8',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field5',
'import_field9',
'import_field10' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field' => 'grid',
'import_field8' => 'grid',
'import_field12' => 'grid',
'import_field13' => 'grid',
'import_field14' => 'grid',
'import_field15' => 'grid',
'import_field5' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field',
'import_field8',
'import_field9',
'import_field10',
'import_field12',
'import_field13',
'import_field14',
'import_field15' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field6',
'import_field7',
'import_field',
'import_field8',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field5',
'import_field9',
'import_field10' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field1' => array( 'field' => 'tr_actividades_asistencias_app_uuid',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'cat_holding_03_empresas_unidades_productivas_id',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'cat_actividades_turnos_id',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'cat_trabajadores_altas_id',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'dia_nombre',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'vigente',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'capturista',
'type' => 'import_field' ),
'import_field' => array( 'field' => 'cat_actividades_ingreso_egreso_mu',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'fecha',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'dia_numero',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'calculo',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'mes',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'fecha_de_captura',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'cat_usuarios_licencias_id1',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'dia_de_inicio',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>