<?php
			$optionsArray = array( 'captcha' => array( 'captcha' => false ),
'fields' => array( 'gridFields' => array( 'fecha_de_captura',
'cat_holding_03_empresas_unidades_productivas_id',
'cat_holding_04_unidades_productivas_lotes_id',
'consecutivo_id',
'identificador_dispositivo',
'cat_actividades_especificas_id',
'vigente',
'capturista',
'cat_trabajador_altas_id',
'cantidad',
'peso',
'descuento',
'calidad',
'cat_produccion_cultivos_01_productos_id',
'numero_de_bote' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'updateOnEditFields' => array( 'cat_holding_03_empresas_unidades_productivas_id',
'cat_holding_04_unidades_productivas_lotes_id',
'cat_actividades_especificas_id',
'vigente',
'cat_trabajador_altas_id',
'cantidad',
'descuento',
'calidad',
'cat_produccion_cultivos_01_productos_id',
'numero_de_bote' ),
'fieldItems' => array( 'fecha_de_captura' => array( 'integrated_edit_field4' ),
'cat_holding_03_empresas_unidades_productivas_id' => array( 'integrated_edit_field6' ),
'cat_holding_04_unidades_productivas_lotes_id' => array( 'integrated_edit_field9' ),
'consecutivo_id' => array( 'integrated_edit_field12' ),
'identificador_dispositivo' => array( 'integrated_edit_field16' ),
'cat_actividades_especificas_id' => array( 'integrated_edit_field33' ),
'vigente' => array( 'integrated_edit_field' ),
'capturista' => array( 'integrated_edit_field5' ),
'cat_trabajador_altas_id' => array( 'integrated_edit_field8' ),
'cantidad' => array( 'integrated_edit_field10' ),
'peso' => array( 'integrated_edit_field11' ),
'descuento' => array( 'integrated_edit_field15' ),
'calidad' => array( 'integrated_edit_field19' ),
'cat_produccion_cultivos_01_productos_id' => array( 'integrated_edit_field20' ),
'numero_de_bote' => array( 'integrated_edit_field1' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'edit_message' ),
'below-grid' => array( 'edit_save',
'update_records',
'edit_back_list',
'edit_close',
'hamburger' ),
'top' => array( 'edit_header' ),
'grid' => array( 'integrated_edit_field4',
'integrated_edit_field6',
'integrated_edit_field9',
'integrated_edit_field12',
'integrated_edit_field16',
'integrated_edit_field33',
'integrated_edit_field5',
'integrated_edit_field8',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field15',
'integrated_edit_field19',
'integrated_edit_field20',
'integrated_edit_field',
'integrated_edit_field1' ) ),
'formXtTags' => array( 'above-grid' => array( 'message_block' ) ),
'itemForms' => array( 'edit_message' => 'above-grid',
'edit_save' => 'below-grid',
'update_records' => 'below-grid',
'edit_back_list' => 'below-grid',
'edit_close' => 'below-grid',
'hamburger' => 'below-grid',
'edit_header' => 'top',
'integrated_edit_field4' => 'grid',
'integrated_edit_field6' => 'grid',
'integrated_edit_field9' => 'grid',
'integrated_edit_field12' => 'grid',
'integrated_edit_field16' => 'grid',
'integrated_edit_field33' => 'grid',
'integrated_edit_field5' => 'grid',
'integrated_edit_field8' => 'grid',
'integrated_edit_field10' => 'grid',
'integrated_edit_field11' => 'grid',
'integrated_edit_field15' => 'grid',
'integrated_edit_field19' => 'grid',
'integrated_edit_field20' => 'grid',
'integrated_edit_field' => 'grid',
'integrated_edit_field1' => 'grid' ),
'itemLocations' => array( 'integrated_edit_field4' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field6' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field9' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field12' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field16' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field33' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field5' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field8' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field10' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field11' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field15' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field19' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field20' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field1' => array( 'location' => 'grid',
'cellId' => 'c3' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'edit_header' => array( 'edit_header' ),
'hamburger' => array( 'hamburger' ),
'edit_reset' => array( 'edit_reset' ),
'edit_message' => array( 'edit_message' ),
'edit_save' => array( 'edit_save' ),
'edit_back_list' => array( 'edit_back_list' ),
'edit_close' => array( 'edit_close' ),
'integrated_edit_field' => array( 'integrated_edit_field4',
'integrated_edit_field6',
'integrated_edit_field9',
'integrated_edit_field12',
'integrated_edit_field16',
'integrated_edit_field33',
'integrated_edit_field',
'integrated_edit_field5',
'integrated_edit_field8',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field15',
'integrated_edit_field19',
'integrated_edit_field20',
'integrated_edit_field1' ),
'update_records' => array( 'update_records' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field4',
'integrated_edit_field6',
'integrated_edit_field9',
'integrated_edit_field12',
'integrated_edit_field16',
'integrated_edit_field33',
'integrated_edit_field5',
'integrated_edit_field8',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field15',
'integrated_edit_field19',
'integrated_edit_field20',
'integrated_edit_field',
'integrated_edit_field1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array( 'update_records' => array( 'tag' => 'UPDATE_N_RECORDS',
'type' => 2 ) ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'edit',
'breadcrumb' => false,
'nextPrev' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'edit' => array( 'updateSelected' => true ) );
			$pageArray = array( 'id' => 'edit',
'type' => 'edit',
'layoutId' => 'nomenu',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'edit-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_message' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'edit-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_save',
'update_records',
'edit_back_list',
'edit_close' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'hamburger' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'edit-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3' ) ),
'section' => '' ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field4',
'integrated_edit_field6',
'integrated_edit_field9',
'integrated_edit_field12',
'integrated_edit_field16',
'integrated_edit_field33',
'integrated_edit_field5',
'integrated_edit_field8',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field15',
'integrated_edit_field19',
'integrated_edit_field20',
'integrated_edit_field',
'integrated_edit_field1' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'edit_header' => array( 'type' => 'edit_header' ),
'hamburger' => array( 'type' => 'hamburger',
'items' => array( 'edit_reset' ) ),
'edit_reset' => array( 'type' => 'edit_reset' ),
'edit_message' => array( 'type' => 'edit_message' ),
'edit_save' => array( 'type' => 'edit_save' ),
'edit_back_list' => array( 'type' => 'edit_back_list' ),
'edit_close' => array( 'type' => 'edit_close' ),
'integrated_edit_field4' => array( 'field' => 'fecha_de_captura',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field6' => array( 'field' => 'cat_holding_03_empresas_unidades_productivas_id',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field9' => array( 'field' => 'cat_holding_04_unidades_productivas_lotes_id',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field12' => array( 'field' => 'consecutivo_id',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field16' => array( 'field' => 'identificador_dispositivo',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field33' => array( 'field' => 'cat_actividades_especificas_id',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'update_records' => array( 'type' => 'update_records' ),
'integrated_edit_field' => array( 'field' => 'vigente',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field5' => array( 'field' => 'capturista',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field8' => array( 'field' => 'cat_trabajador_altas_id',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field10' => array( 'field' => 'cantidad',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field11' => array( 'field' => 'peso',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field15' => array( 'field' => 'descuento',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field19' => array( 'field' => 'calidad',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field20' => array( 'field' => 'cat_produccion_cultivos_01_productos_id',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field1' => array( 'field' => 'numero_de_bote',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>