<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'fecha_de_captura',
'cat_holding_04_unidades_productivas_lotes_id',
'cat_produccion_variedades_id',
'cantidad',
'vigente',
'consecutivo',
'tr_actividades_cosecha_salidas_02_id',
'tr_actividades_cosecha_salidas_01_uuid',
'lpn',
'cat_holding_03_empresas_up_group_predios_id',
'cat_holding_03_empresas_unidades_productivas_id',
'cat_ventas_productos_sku_id',
'cantidad_rechazos',
'tratamiento',
'status_recibo',
'cat_ventas_productos_status_recibo_id',
'cantidad_cajas_status',
'cat_produccion_cultivos_01_productos_id' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'tr_actividades_cosecha_salidas_02_id' => array( 'import_field' ),
'tr_actividades_cosecha_salidas_01_uuid' => array( 'import_field1' ),
'fecha_de_captura' => array( 'import_field2' ),
'cat_holding_04_unidades_productivas_lotes_id' => array( 'import_field6' ),
'cat_produccion_variedades_id' => array( 'import_field9' ),
'cantidad' => array( 'import_field10' ),
'vigente' => array( 'import_field15' ),
'consecutivo' => array( 'import_field16' ),
'lpn' => array( 'import_field3' ),
'cat_holding_03_empresas_up_group_predios_id' => array( 'import_field4' ),
'cat_holding_03_empresas_unidades_productivas_id' => array( 'import_field5' ),
'cat_ventas_productos_sku_id' => array( 'import_field7' ),
'cantidad_rechazos' => array( 'import_field8' ),
'tratamiento' => array( 'import_field11' ),
'status_recibo' => array( 'import_field12' ),
'cat_produccion_cultivos_01_productos_id' => array( 'import_field13' ),
'cat_ventas_productos_status_recibo_id' => array( 'import_field14' ),
'cantidad_cajas_status' => array( 'import_field18' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field2',
'import_field6',
'import_field9',
'import_field10',
'import_field15',
'import_field16',
'import_field',
'import_field1',
'import_field3',
'import_field4',
'import_field5',
'import_field7',
'import_field8',
'import_field11',
'import_field12',
'import_field14',
'import_field18',
'import_field13' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field2' => 'grid',
'import_field6' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field15' => 'grid',
'import_field16' => 'grid',
'import_field' => 'grid',
'import_field1' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field14' => 'grid',
'import_field18' => 'grid',
'import_field13' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field6',
'import_field9',
'import_field10',
'import_field15',
'import_field16',
'import_field3',
'import_field4',
'import_field5',
'import_field7',
'import_field8',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field18' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field2',
'import_field6',
'import_field9',
'import_field10',
'import_field15',
'import_field16',
'import_field',
'import_field1',
'import_field3',
'import_field4',
'import_field5',
'import_field7',
'import_field8',
'import_field11',
'import_field12',
'import_field14',
'import_field18',
'import_field13' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'tr_actividades_cosecha_salidas_02_id',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'tr_actividades_cosecha_salidas_01_uuid',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'fecha_de_captura',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'cat_holding_04_unidades_productivas_lotes_id',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'cat_produccion_variedades_id',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'cantidad',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'vigente',
'type' => 'import_field' ),
'import_field16' => array( 'field' => 'consecutivo',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'lpn',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'cat_holding_03_empresas_up_group_predios_id',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'cat_holding_03_empresas_unidades_productivas_id',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'cat_ventas_productos_sku_id',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'cantidad_rechazos',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'tratamiento',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'status_recibo',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'cat_produccion_cultivos_01_productos_id',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'cat_ventas_productos_status_recibo_id',
'type' => 'import_field' ),
'import_field18' => array( 'field' => 'cantidad_cajas_status',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>