<?php
			$optionsArray = array( 'totals' => array( 'tr_actividades_cosecha_id' => array( 'totalsType' => '' ),
'tr_actividades_cosecha_uuid' => array( 'totalsType' => '' ),
'time_stamp' => array( 'totalsType' => '' ),
'vigente' => array( 'totalsType' => '' ),
'capturista' => array( 'totalsType' => '' ),
'fecha_de_captura' => array( 'totalsType' => '' ),
'hora' => array( 'totalsType' => '' ),
'cat_trabajador_altas_id' => array( 'totalsType' => '' ),
'cat_holding_03_empresas_unidades_productivas_id' => array( 'totalsType' => '' ),
'cantidad' => array( 'totalsType' => '' ),
'peso' => array( 'totalsType' => '' ),
'cat_holding_04_unidades_productivas_lotes_id' => array( 'totalsType' => '' ),
'surco' => array( 'totalsType' => '' ),
'tunel' => array( 'totalsType' => '' ),
'consecutivo_id' => array( 'totalsType' => '' ),
'descuento' => array( 'totalsType' => '' ),
'Lat' => array( 'totalsType' => '' ),
'Lng' => array( 'totalsType' => '' ),
'identificador_dispositivo' => array( 'totalsType' => '' ),
'calidad' => array( 'totalsType' => '' ),
'cat_produccion_cultivos_01_productos_id' => array( 'totalsType' => '' ),
'cat_produccion_empaques_id' => array( 'totalsType' => '' ),
'cat_nominas_01_generales_uuid' => array( 'totalsType' => '' ),
'cat_nominas_tabulador_actividades_sueldos_variables_id' => array( 'totalsType' => '' ),
'cat_usuarios_licencias_id' => array( 'totalsType' => '' ),
'fecha' => array( 'totalsType' => '' ),
'numero_de_bote' => array( 'totalsType' => '' ),
'llave_fecha_nominas_uuid' => array( 'totalsType' => '' ),
'llave_fecha_trabajador_actividad' => array( 'totalsType' => '' ),
'llave_fecha_trabajador_catnominas02actividades' => array( 'totalsType' => '' ),
'llave_fecha_up_consecutivo' => array( 'totalsType' => '' ),
'llave_up_lote_actesp_prod' => array( 'totalsType' => '' ),
'llave_up_lote_actesp_prod_uuid' => array( 'totalsType' => '' ),
'llave_fecha_up_consecutivo_trab' => array( 'totalsType' => '' ),
'llave_fecha_trabajador' => array( 'totalsType' => '' ),
'cat_nominas_02_actividades_id' => array( 'totalsType' => '' ),
'cat_actividades_especificas_id' => array( 'totalsType' => '' ),
'llave_fcup' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'fecha_de_captura',
'cat_holding_03_empresas_unidades_productivas_id',
'cat_holding_04_unidades_productivas_lotes_id',
'identificador_dispositivo',
'cat_actividades_especificas_id',
'tr_actividades_cosecha_uuid',
'vigente',
'capturista',
'cat_trabajador_altas_id',
'cantidad',
'descuento',
'calidad',
'cat_produccion_cultivos_01_productos_id',
'numero_de_bote' ),
'exportFields' => array( 'fecha_de_captura',
'cat_holding_03_empresas_unidades_productivas_id',
'cat_holding_04_unidades_productivas_lotes_id',
'identificador_dispositivo',
'cat_actividades_especificas_id',
'tr_actividades_cosecha_uuid',
'vigente',
'capturista',
'cat_trabajador_altas_id',
'cantidad',
'descuento',
'calidad',
'cat_produccion_cultivos_01_productos_id',
'numero_de_bote' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'fecha_de_captura' => array( 'export_field5' ),
'cat_holding_03_empresas_unidades_productivas_id' => array( 'export_field7' ),
'cat_holding_04_unidades_productivas_lotes_id' => array( 'export_field10' ),
'identificador_dispositivo' => array( 'export_field17' ),
'cat_actividades_especificas_id' => array( 'export_field34' ),
'tr_actividades_cosecha_uuid' => array( 'export_field1' ),
'vigente' => array( 'export_field3' ),
'capturista' => array( 'export_field4' ),
'cat_trabajador_altas_id' => array( 'export_field8' ),
'cantidad' => array( 'export_field9' ),
'descuento' => array( 'export_field15' ),
'calidad' => array( 'export_field19' ),
'cat_produccion_cultivos_01_productos_id' => array( 'export_field20' ),
'numero_de_bote' => array( 'export_field' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field5',
'export_field7',
'export_field10',
'export_field17',
'export_field34',
'export_field1',
'export_field3',
'export_field4',
'export_field8',
'export_field9',
'export_field15',
'export_field19',
'export_field20',
'export_field' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field5' => 'grid',
'export_field7' => 'grid',
'export_field10' => 'grid',
'export_field17' => 'grid',
'export_field34' => 'grid',
'export_field1' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field15' => 'grid',
'export_field19' => 'grid',
'export_field20' => 'grid',
'export_field' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field5',
'export_field7',
'export_field10',
'export_field17',
'export_field34',
'export_field1',
'export_field3',
'export_field4',
'export_field8',
'export_field9',
'export_field15',
'export_field19',
'export_field20',
'export_field' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field5',
'export_field7',
'export_field10',
'export_field17',
'export_field34',
'export_field1',
'export_field3',
'export_field4',
'export_field8',
'export_field9',
'export_field15',
'export_field19',
'export_field20',
'export_field' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field5' => array( 'field' => 'fecha_de_captura',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'cat_holding_03_empresas_unidades_productivas_id',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'cat_holding_04_unidades_productivas_lotes_id',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'identificador_dispositivo',
'type' => 'export_field' ),
'export_field34' => array( 'field' => 'cat_actividades_especificas_id',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'tr_actividades_cosecha_uuid',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'vigente',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'capturista',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'cat_trabajador_altas_id',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'cantidad',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'descuento',
'type' => 'export_field' ),
'export_field19' => array( 'field' => 'calidad',
'type' => 'export_field' ),
'export_field20' => array( 'field' => 'cat_produccion_cultivos_01_productos_id',
'type' => 'export_field' ),
'export_field' => array( 'field' => 'numero_de_bote',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>