<?php
			$optionsArray = array( 'totals' => array( 'tr_actividades_destajos_id' => array( 'totalsType' => '' ),
'cat_holding_03_empresas_unidades_productivas_id' => array( 'totalsType' => '' ),
'cat_holding_04_unidades_productivas_lotes_id' => array( 'totalsType' => '' ),
'supervisor_id' => array( 'totalsType' => '' ),
'fecha_de_captura' => array( 'totalsType' => '' ),
'observacion' => array( 'totalsType' => '' ),
'cat_trabajadores_altas_id' => array( 'totalsType' => '' ),
'cat_actividades_unidades_de_costo_id' => array( 'totalsType' => '' ),
'cantidad' => array( 'totalsType' => '' ),
'costo' => array( 'totalsType' => '' ),
'tunel' => array( 'totalsType' => '' ),
'vigente' => array( 'totalsType' => '' ),
'capturista' => array( 'totalsType' => '' ),
'cat_actividades_especificas_id' => array( 'totalsType' => '' ),
'time_stamp' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'cat_holding_04_unidades_productivas_lotes_id',
'cantidad',
'supervisor_id',
'fecha_de_captura',
'cat_trabajadores_altas_id',
'cat_holding_03_empresas_unidades_productivas_id',
'observacion',
'cat_actividades_unidades_de_costo_id',
'costo',
'tunel',
'vigente',
'capturista',
'cat_actividades_especificas_id',
'time_stamp' ),
'exportFields' => array( 'cat_trabajadores_altas_id',
'cantidad',
'cat_holding_03_empresas_unidades_productivas_id',
'cat_holding_04_unidades_productivas_lotes_id',
'supervisor_id',
'fecha_de_captura',
'observacion',
'cat_actividades_unidades_de_costo_id',
'costo',
'tunel',
'vigente',
'capturista',
'cat_actividades_especificas_id',
'time_stamp' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'cat_holding_04_unidades_productivas_lotes_id' => array( 'export_field1' ),
'cantidad' => array( 'export_field2' ),
'supervisor_id' => array( 'export_field3' ),
'fecha_de_captura' => array( 'export_field4' ),
'cat_trabajadores_altas_id' => array( 'export_field6' ),
'cat_holding_03_empresas_unidades_productivas_id' => array( 'export_field5' ),
'observacion' => array( 'export_field7' ),
'cat_actividades_unidades_de_costo_id' => array( 'export_field8' ),
'costo' => array( 'export_field9' ),
'tunel' => array( 'export_field10' ),
'vigente' => array( 'export_field11' ),
'capturista' => array( 'export_field12' ),
'cat_actividades_especificas_id' => array( 'export_field13' ),
'time_stamp' => array( 'export_field14' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field6',
'export_field2',
'export_field5',
'export_field1',
'export_field3',
'export_field4',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field6' => 'grid',
'export_field2' => 'grid',
'export_field5' => 'grid',
'export_field1' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field6',
'export_field5',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field6',
'export_field2',
'export_field5',
'export_field1',
'export_field3',
'export_field4',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field1' => array( 'field' => 'cat_holding_04_unidades_productivas_lotes_id',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'cantidad',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'supervisor_id',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'fecha_de_captura',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'cat_trabajadores_altas_id',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'cat_holding_03_empresas_unidades_productivas_id',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'observacion',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'cat_actividades_unidades_de_costo_id',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'costo',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'tunel',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'vigente',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'capturista',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'cat_actividades_especificas_id',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'time_stamp',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>