<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'fecha_de_captura',
'cat_holding_03_empresas_unidades_productivas_id',
'cat_holding_04_unidades_productivas_lotes_id',
'cat_actividades_especificas_id',
'tr_actividades_cosecha_uuid',
'vigente',
'capturista',
'cat_trabajador_altas_id',
'cantidad',
'descuento',
'calidad',
'cat_produccion_cultivos_01_productos_id',
'identificador_dispositivo',
'numero_de_bote' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'fecha_de_captura' => array( 'import_field5' ),
'cat_holding_03_empresas_unidades_productivas_id' => array( 'import_field7' ),
'cat_holding_04_unidades_productivas_lotes_id' => array( 'import_field10' ),
'cat_actividades_especificas_id' => array( 'import_field34' ),
'identificador_dispositivo' => array( 'import_field' ),
'tr_actividades_cosecha_uuid' => array( 'import_field1' ),
'vigente' => array( 'import_field3' ),
'capturista' => array( 'import_field4' ),
'cat_trabajador_altas_id' => array( 'import_field8' ),
'cantidad' => array( 'import_field9' ),
'descuento' => array( 'import_field15' ),
'calidad' => array( 'import_field19' ),
'cat_produccion_cultivos_01_productos_id' => array( 'import_field20' ),
'numero_de_bote' => array( 'import_field2' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field5',
'import_field7',
'import_field10',
'import_field34',
'import_field1',
'import_field3',
'import_field4',
'import_field8',
'import_field9',
'import_field15',
'import_field19',
'import_field20',
'import_field',
'import_field2' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field5' => 'grid',
'import_field7' => 'grid',
'import_field10' => 'grid',
'import_field34' => 'grid',
'import_field1' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field15' => 'grid',
'import_field19' => 'grid',
'import_field20' => 'grid',
'import_field' => 'grid',
'import_field2' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field5',
'import_field7',
'import_field10',
'import_field34',
'import_field',
'import_field1',
'import_field3',
'import_field4',
'import_field8',
'import_field9',
'import_field15',
'import_field19',
'import_field20',
'import_field2' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field5',
'import_field7',
'import_field10',
'import_field34',
'import_field1',
'import_field3',
'import_field4',
'import_field8',
'import_field9',
'import_field15',
'import_field19',
'import_field20',
'import_field',
'import_field2' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field5' => array( 'field' => 'fecha_de_captura',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'cat_holding_03_empresas_unidades_productivas_id',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'cat_holding_04_unidades_productivas_lotes_id',
'type' => 'import_field' ),
'import_field34' => array( 'field' => 'cat_actividades_especificas_id',
'type' => 'import_field' ),
'import_field' => array( 'field' => 'identificador_dispositivo',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'tr_actividades_cosecha_uuid',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'vigente',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'capturista',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'cat_trabajador_altas_id',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'cantidad',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'descuento',
'type' => 'import_field' ),
'import_field19' => array( 'field' => 'calidad',
'type' => 'import_field' ),
'import_field20' => array( 'field' => 'cat_produccion_cultivos_01_productos_id',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'numero_de_bote',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>