<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'tr_compras_requisiciones_02_productos_id',
'observaciones',
'llave_idbalance03_idcatalogos_cargo',
'vigente',
'llave_idbalance03_idcatalogos_abono',
'cat_compras_productos_id',
'precio_neto',
'cantidad',
'nombre_producto_generico',
'cat_compras_proveedores_id',
'cat_holding_03_empresas_unidades_productivas_id',
'cat_trabajadores_altas_id',
'utilizacion',
'ubicacion',
'llave_tr_compras_requisiciones_01',
'cat_compras_productos_presentacion_mu_id',
'contenido_presentacion',
'cat_compras_productos_unidad_de_medida_mu_id',
'llave_unica_fecha_folio_imei_usuario',
'llave_unica_requisiciones_02_productos',
'autorizado_check',
'fecha_de_autorizacion_requisicion',
'capturista_que_autoriza',
'UUID_sat',
'registro_requisicion',
'llave_oc_folio_proveedor',
'observacion' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'tr_compras_requisiciones_02_productos_id' => array( 'integrated_search_field' ),
'observaciones' => array( 'integrated_search_field1' ),
'llave_idbalance03_idcatalogos_cargo' => array( 'integrated_search_field2' ),
'vigente' => array( 'integrated_search_field3' ),
'llave_idbalance03_idcatalogos_abono' => array( 'integrated_search_field4' ),
'cat_compras_productos_id' => array( 'integrated_search_field5' ),
'precio_neto' => array( 'integrated_search_field6' ),
'cantidad' => array( 'integrated_search_field7' ),
'nombre_producto_generico' => array( 'integrated_search_field8' ),
'cat_compras_proveedores_id' => array( 'integrated_search_field9' ),
'cat_holding_03_empresas_unidades_productivas_id' => array( 'integrated_search_field10' ),
'cat_trabajadores_altas_id' => array( 'integrated_search_field11' ),
'utilizacion' => array( 'integrated_search_field12' ),
'ubicacion' => array( 'integrated_search_field13' ),
'llave_tr_compras_requisiciones_01' => array( 'integrated_search_field14' ),
'cat_compras_productos_presentacion_mu_id' => array( 'integrated_search_field15' ),
'contenido_presentacion' => array( 'integrated_search_field16' ),
'cat_compras_productos_unidad_de_medida_mu_id' => array( 'integrated_search_field17' ),
'llave_unica_fecha_folio_imei_usuario' => array( 'integrated_search_field18' ),
'llave_unica_requisiciones_02_productos' => array( 'integrated_search_field19' ),
'autorizado_check' => array( 'integrated_search_field20' ),
'fecha_de_autorizacion_requisicion' => array( 'integrated_search_field21' ),
'capturista_que_autoriza' => array( 'integrated_search_field22' ),
'UUID_sat' => array( 'integrated_search_field24' ),
'registro_requisicion' => array( 'integrated_search_field23' ),
'llave_oc_folio_proveedor' => array( 'integrated_search_field37' ),
'observacion' => array( 'integrated_search_field38' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array(  ),
'below-grid' => array( 'search_search',
'search_reset',
'search_back_list',
'search_cancel' ),
'top' => array( 'search_header' ),
'grid' => array( 'integrated_search_field',
'integrated_search_field3',
'integrated_search_field5',
'integrated_search_field6',
'integrated_search_field7',
'integrated_search_field9',
'integrated_search_field11',
'integrated_search_field12',
'integrated_search_field13',
'integrated_search_field14',
'integrated_search_field8',
'integrated_search_field16',
'integrated_search_field18',
'integrated_search_field19',
'integrated_search_field15',
'integrated_search_field17',
'integrated_search_field20',
'integrated_search_field21',
'integrated_search_field22',
'integrated_search_field10',
'integrated_search_field23',
'integrated_search_field24',
'integrated_search_field37',
'integrated_search_field38',
'integrated_search_field1',
'integrated_search_field2',
'integrated_search_field4' ) ),
'formXtTags' => array( 'above-grid' => array(  ) ),
'itemForms' => array( 'search_search' => 'below-grid',
'search_reset' => 'below-grid',
'search_back_list' => 'below-grid',
'search_cancel' => 'below-grid',
'search_header' => 'top',
'integrated_search_field' => 'grid',
'integrated_search_field3' => 'grid',
'integrated_search_field5' => 'grid',
'integrated_search_field6' => 'grid',
'integrated_search_field7' => 'grid',
'integrated_search_field9' => 'grid',
'integrated_search_field11' => 'grid',
'integrated_search_field12' => 'grid',
'integrated_search_field13' => 'grid',
'integrated_search_field14' => 'grid',
'integrated_search_field8' => 'grid',
'integrated_search_field16' => 'grid',
'integrated_search_field18' => 'grid',
'integrated_search_field19' => 'grid',
'integrated_search_field15' => 'grid',
'integrated_search_field17' => 'grid',
'integrated_search_field20' => 'grid',
'integrated_search_field21' => 'grid',
'integrated_search_field22' => 'grid',
'integrated_search_field10' => 'grid',
'integrated_search_field23' => 'grid',
'integrated_search_field24' => 'grid',
'integrated_search_field37' => 'grid',
'integrated_search_field38' => 'grid',
'integrated_search_field1' => 'grid',
'integrated_search_field2' => 'grid',
'integrated_search_field4' => 'grid' ),
'itemLocations' => array( 'integrated_search_field' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field3' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field5' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field6' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field7' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field9' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field11' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field12' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field13' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field14' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field8' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field16' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field18' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field19' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field15' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field17' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field20' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field21' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field22' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field10' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field23' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field24' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field37' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field38' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field1' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field2' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field4' => array( 'location' => 'grid',
'cellId' => 'c3' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'search_header' => array( 'search_header' ),
'search_reset' => array( 'search_reset' ),
'search_back_list' => array( 'search_back_list' ),
'search_search' => array( 'search_search' ),
'search_cancel' => array( 'search_cancel' ),
'integrated_search_field' => array( 'integrated_search_field',
'integrated_search_field1',
'integrated_search_field2',
'integrated_search_field3',
'integrated_search_field4',
'integrated_search_field5',
'integrated_search_field6',
'integrated_search_field7',
'integrated_search_field8',
'integrated_search_field9',
'integrated_search_field10',
'integrated_search_field11',
'integrated_search_field12',
'integrated_search_field13',
'integrated_search_field14',
'integrated_search_field15',
'integrated_search_field16',
'integrated_search_field17',
'integrated_search_field18',
'integrated_search_field19',
'integrated_search_field20',
'integrated_search_field21',
'integrated_search_field22',
'integrated_search_field24',
'integrated_search_field23',
'integrated_search_field37',
'integrated_search_field38' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field',
'integrated_search_field3',
'integrated_search_field5',
'integrated_search_field6',
'integrated_search_field7',
'integrated_search_field9',
'integrated_search_field11',
'integrated_search_field12',
'integrated_search_field13',
'integrated_search_field14',
'integrated_search_field8',
'integrated_search_field16',
'integrated_search_field18',
'integrated_search_field19',
'integrated_search_field15',
'integrated_search_field17',
'integrated_search_field20',
'integrated_search_field21',
'integrated_search_field22',
'integrated_search_field10',
'integrated_search_field23',
'integrated_search_field24',
'integrated_search_field37',
'integrated_search_field38',
'integrated_search_field1',
'integrated_search_field2',
'integrated_search_field4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'search',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'search',
'type' => 'search',
'layoutId' => 'nomenu',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'search-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1',
'colspan' => 2 ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'search-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'search_search',
'search_reset',
'search_back_list',
'search_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'search-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'search_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-search',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3' ) ),
'section' => '' ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'integrated_search_field',
'integrated_search_field3',
'integrated_search_field5',
'integrated_search_field6',
'integrated_search_field7',
'integrated_search_field9',
'integrated_search_field11',
'integrated_search_field12',
'integrated_search_field13',
'integrated_search_field14',
'integrated_search_field8',
'integrated_search_field16',
'integrated_search_field18',
'integrated_search_field19',
'integrated_search_field15',
'integrated_search_field17',
'integrated_search_field20',
'integrated_search_field21',
'integrated_search_field22',
'integrated_search_field10',
'integrated_search_field23',
'integrated_search_field24',
'integrated_search_field37',
'integrated_search_field38',
'integrated_search_field1',
'integrated_search_field2',
'integrated_search_field4' ) ) ),
'deferredItems' => array(  ),
'separateLabels' => false ) ),
'items' => array( 'search_header' => array( 'type' => 'search_header' ),
'search_reset' => array( 'type' => 'search_reset' ),
'search_back_list' => array( 'type' => 'search_back_list' ),
'search_search' => array( 'type' => 'search_search' ),
'search_cancel' => array( 'type' => 'search_cancel' ),
'integrated_search_field' => array( 'field' => 'tr_compras_requisiciones_02_productos_id',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field1' => array( 'field' => 'observaciones',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field2' => array( 'field' => 'llave_idbalance03_idcatalogos_cargo',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field3' => array( 'field' => 'vigente',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field4' => array( 'field' => 'llave_idbalance03_idcatalogos_abono',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field5' => array( 'field' => 'cat_compras_productos_id',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field6' => array( 'field' => 'precio_neto',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field7' => array( 'field' => 'cantidad',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field8' => array( 'field' => 'nombre_producto_generico',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field9' => array( 'field' => 'cat_compras_proveedores_id',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field10' => array( 'field' => 'cat_holding_03_empresas_unidades_productivas_id',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field11' => array( 'field' => 'cat_trabajadores_altas_id',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field12' => array( 'field' => 'utilizacion',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field13' => array( 'field' => 'ubicacion',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field14' => array( 'field' => 'llave_tr_compras_requisiciones_01',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field15' => array( 'field' => 'cat_compras_productos_presentacion_mu_id',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field16' => array( 'field' => 'contenido_presentacion',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field17' => array( 'field' => 'cat_compras_productos_unidad_de_medida_mu_id',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field18' => array( 'field' => 'llave_unica_fecha_folio_imei_usuario',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field19' => array( 'field' => 'llave_unica_requisiciones_02_productos',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field20' => array( 'field' => 'autorizado_check',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field21' => array( 'field' => 'fecha_de_autorizacion_requisicion',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field22' => array( 'field' => 'capturista_que_autoriza',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field24' => array( 'field' => 'UUID_sat',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field23' => array( 'field' => 'registro_requisicion',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field37' => array( 'field' => 'llave_oc_folio_proveedor',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field38' => array( 'field' => 'observacion',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>