<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'referencia_bancaria',
'cat_finanzas_cuentas_de_balance_04_llave',
'fecha_de_compra',
'ano_mes',
'id_prov',
'uuid_cargo_abono_pago',
'cat_usuarios_licencias_id',
'cat_finanzas_cajas_chicas_id',
'cat_finanzas_bancos_cuentas_id',
'consecutivo_id',
'time_stamp',
'imei',
'fecha_de_pago',
'importe_cargo_pago',
'alias_cuenta_de_balance',
'alias_cuenta_de_cargo_pago',
'tr_compras_proveedores_01_cargos_abonos_id',
'uuid_cargo_abono_compra',
'tr_compras_requisiciones_01_uuid',
'capturista',
'saldo',
'total_pagos_cargos',
'total_compras_abonos',
'vigente',
'fecha_de_vencimiento',
'referencia',
'cat_compras_documentos_mu_id',
'uuid_sat',
'orden_de_compra_proveedor',
'importe_abono_compra',
'concepto',
'alias_proveedor',
'cat_compras_proveedores_id',
'observacion_abono_compra',
'cat_compras_estatus_mu_id',
'fecha_de_recibo',
'tr_compras_almacenes_01_recibo_lpn_uuid',
'fecha_de_solicitud',
'fecha_de_requisicion',
'saldo1',
'cargo_abono',
'cat_compras_cargo_abono_mu_id',
'llave_unica_cargo_abono_tr_compras_requisiciones_01_uuid_pago' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'referencia_bancaria' => array( 'simple_grid_field34',
'simple_grid_field71' ),
'cat_finanzas_cuentas_de_balance_04_llave' => array( 'simple_grid_field33',
'simple_grid_field70' ),
'fecha_de_compra' => array( 'simple_grid_field1',
'simple_grid_field38' ),
'ano_mes' => array( 'simple_grid_field2',
'simple_grid_field39' ),
'id_prov' => array( 'simple_grid_field3',
'simple_grid_field40' ),
'uuid_cargo_abono_pago' => array( 'simple_grid_field32',
'simple_grid_field69' ),
'cat_usuarios_licencias_id' => array( 'simple_grid_field31',
'simple_grid_field68' ),
'cat_finanzas_cajas_chicas_id' => array( 'simple_grid_field30',
'simple_grid_field67' ),
'cat_finanzas_bancos_cuentas_id' => array( 'simple_grid_field29',
'simple_grid_field66' ),
'consecutivo_id' => array( 'simple_grid_field28',
'simple_grid_field65' ),
'time_stamp' => array( 'simple_grid_field27',
'simple_grid_field64' ),
'imei' => array( 'simple_grid_field26',
'simple_grid_field63' ),
'fecha_de_pago' => array( 'simple_grid_field25',
'simple_grid_field62' ),
'importe_cargo_pago' => array( 'simple_grid_field24',
'simple_grid_field61' ),
'alias_cuenta_de_balance' => array( 'simple_grid_field23',
'simple_grid_field60' ),
'alias_cuenta_de_cargo_pago' => array( 'simple_grid_field22',
'simple_grid_field59' ),
'tr_compras_proveedores_01_cargos_abonos_id' => array( 'simple_grid_field20',
'simple_grid_field57' ),
'uuid_cargo_abono_compra' => array( 'simple_grid_field19',
'simple_grid_field56' ),
'tr_compras_requisiciones_01_uuid' => array( 'simple_grid_field18',
'simple_grid_field55' ),
'capturista' => array( 'simple_grid_field17',
'simple_grid_field54' ),
'saldo' => array( 'simple_grid_field16',
'simple_grid_field53' ),
'total_pagos_cargos' => array( 'simple_grid_field15',
'simple_grid_field52' ),
'total_compras_abonos' => array( 'simple_grid_field14',
'simple_grid_field51' ),
'vigente' => array( 'simple_grid_field13',
'simple_grid_field50' ),
'fecha_de_vencimiento' => array( 'simple_grid_field12',
'simple_grid_field49' ),
'referencia' => array( 'simple_grid_field11',
'simple_grid_field48' ),
'cat_compras_documentos_mu_id' => array( 'simple_grid_field10',
'simple_grid_field47' ),
'uuid_sat' => array( 'simple_grid_field9',
'simple_grid_field46' ),
'orden_de_compra_proveedor' => array( 'simple_grid_field8',
'simple_grid_field45' ),
'importe_abono_compra' => array( 'simple_grid_field7',
'simple_grid_field44' ),
'concepto' => array( 'simple_grid_field6',
'simple_grid_field43' ),
'alias_proveedor' => array( 'simple_grid_field5',
'simple_grid_field42' ),
'cat_compras_proveedores_id' => array( 'simple_grid_field4',
'simple_grid_field41' ),
'observacion_abono_compra' => array( 'simple_grid_field35',
'simple_grid_field72' ),
'cat_compras_estatus_mu_id' => array( 'simple_grid_field36',
'simple_grid_field73' ),
'fecha_de_recibo' => array( 'simple_grid_field',
'simple_grid_field74' ),
'tr_compras_almacenes_01_recibo_lpn_uuid' => array( 'simple_grid_field37',
'simple_grid_field75' ),
'fecha_de_solicitud' => array( 'grid_field',
'grid_field_label' ),
'fecha_de_requisicion' => array( 'grid_field1',
'grid_field_label1' ),
'saldo1' => array( 'grid_field2',
'grid_field_label2' ),
'cargo_abono' => array( 'grid_field3',
'grid_field_label3' ),
'cat_compras_cargo_abono_mu_id' => array( 'grid_field4',
'grid_field_label4' ),
'llave_unica_cargo_abono_tr_compras_requisiciones_01_uuid_pago' => array( 'grid_field5',
'grid_field_label5' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array(  ),
'below-grid' => array(  ),
'top' => array( 'masterprint_header' ),
'grid' => array( 'simple_grid_field38',
'simple_grid_field1',
'simple_grid_field39',
'simple_grid_field2',
'simple_grid_field40',
'simple_grid_field3',
'simple_grid_field41',
'simple_grid_field4',
'simple_grid_field42',
'simple_grid_field5',
'simple_grid_field43',
'simple_grid_field6',
'simple_grid_field44',
'simple_grid_field7',
'simple_grid_field45',
'simple_grid_field8',
'simple_grid_field46',
'simple_grid_field9',
'simple_grid_field47',
'simple_grid_field10',
'simple_grid_field48',
'simple_grid_field11',
'simple_grid_field49',
'simple_grid_field12',
'simple_grid_field50',
'simple_grid_field13',
'simple_grid_field51',
'simple_grid_field14',
'simple_grid_field52',
'simple_grid_field15',
'simple_grid_field53',
'simple_grid_field16',
'simple_grid_field54',
'simple_grid_field17',
'simple_grid_field55',
'simple_grid_field18',
'simple_grid_field56',
'simple_grid_field19',
'simple_grid_field57',
'simple_grid_field20',
'grid_field_label3',
'grid_field3',
'simple_grid_field59',
'simple_grid_field22',
'simple_grid_field60',
'simple_grid_field23',
'simple_grid_field61',
'simple_grid_field24',
'simple_grid_field62',
'simple_grid_field25',
'simple_grid_field63',
'simple_grid_field26',
'simple_grid_field64',
'simple_grid_field27',
'simple_grid_field65',
'simple_grid_field28',
'simple_grid_field66',
'simple_grid_field29',
'simple_grid_field67',
'simple_grid_field30',
'simple_grid_field68',
'simple_grid_field31',
'simple_grid_field69',
'simple_grid_field32',
'simple_grid_field70',
'simple_grid_field33',
'simple_grid_field71',
'simple_grid_field34',
'simple_grid_field72',
'simple_grid_field35',
'simple_grid_field73',
'simple_grid_field36',
'simple_grid_field74',
'simple_grid_field',
'simple_grid_field75',
'simple_grid_field37',
'grid_field_label',
'grid_field',
'grid_field_label1',
'grid_field1',
'grid_field_label2',
'grid_field2',
'grid_field_label4',
'grid_field4',
'grid_field_label5',
'grid_field5' ) ),
'formXtTags' => array( 'above-grid' => array(  ),
'below-grid' => array(  ) ),
'itemForms' => array( 'masterprint_header' => 'top',
'simple_grid_field38' => 'grid',
'simple_grid_field1' => 'grid',
'simple_grid_field39' => 'grid',
'simple_grid_field2' => 'grid',
'simple_grid_field40' => 'grid',
'simple_grid_field3' => 'grid',
'simple_grid_field41' => 'grid',
'simple_grid_field4' => 'grid',
'simple_grid_field42' => 'grid',
'simple_grid_field5' => 'grid',
'simple_grid_field43' => 'grid',
'simple_grid_field6' => 'grid',
'simple_grid_field44' => 'grid',
'simple_grid_field7' => 'grid',
'simple_grid_field45' => 'grid',
'simple_grid_field8' => 'grid',
'simple_grid_field46' => 'grid',
'simple_grid_field9' => 'grid',
'simple_grid_field47' => 'grid',
'simple_grid_field10' => 'grid',
'simple_grid_field48' => 'grid',
'simple_grid_field11' => 'grid',
'simple_grid_field49' => 'grid',
'simple_grid_field12' => 'grid',
'simple_grid_field50' => 'grid',
'simple_grid_field13' => 'grid',
'simple_grid_field51' => 'grid',
'simple_grid_field14' => 'grid',
'simple_grid_field52' => 'grid',
'simple_grid_field15' => 'grid',
'simple_grid_field53' => 'grid',
'simple_grid_field16' => 'grid',
'simple_grid_field54' => 'grid',
'simple_grid_field17' => 'grid',
'simple_grid_field55' => 'grid',
'simple_grid_field18' => 'grid',
'simple_grid_field56' => 'grid',
'simple_grid_field19' => 'grid',
'simple_grid_field57' => 'grid',
'simple_grid_field20' => 'grid',
'grid_field_label3' => 'grid',
'grid_field3' => 'grid',
'simple_grid_field59' => 'grid',
'simple_grid_field22' => 'grid',
'simple_grid_field60' => 'grid',
'simple_grid_field23' => 'grid',
'simple_grid_field61' => 'grid',
'simple_grid_field24' => 'grid',
'simple_grid_field62' => 'grid',
'simple_grid_field25' => 'grid',
'simple_grid_field63' => 'grid',
'simple_grid_field26' => 'grid',
'simple_grid_field64' => 'grid',
'simple_grid_field27' => 'grid',
'simple_grid_field65' => 'grid',
'simple_grid_field28' => 'grid',
'simple_grid_field66' => 'grid',
'simple_grid_field29' => 'grid',
'simple_grid_field67' => 'grid',
'simple_grid_field30' => 'grid',
'simple_grid_field68' => 'grid',
'simple_grid_field31' => 'grid',
'simple_grid_field69' => 'grid',
'simple_grid_field32' => 'grid',
'simple_grid_field70' => 'grid',
'simple_grid_field33' => 'grid',
'simple_grid_field71' => 'grid',
'simple_grid_field34' => 'grid',
'simple_grid_field72' => 'grid',
'simple_grid_field35' => 'grid',
'simple_grid_field73' => 'grid',
'simple_grid_field36' => 'grid',
'simple_grid_field74' => 'grid',
'simple_grid_field' => 'grid',
'simple_grid_field75' => 'grid',
'simple_grid_field37' => 'grid',
'grid_field_label' => 'grid',
'grid_field' => 'grid',
'grid_field_label1' => 'grid',
'grid_field1' => 'grid',
'grid_field_label2' => 'grid',
'grid_field2' => 'grid',
'grid_field_label4' => 'grid',
'grid_field4' => 'grid',
'grid_field_label5' => 'grid',
'grid_field5' => 'grid' ),
'itemLocations' => array( 'simple_grid_field38' => array( 'location' => 'grid',
'cellId' => 'headcell_field' ),
'simple_grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'simple_grid_field39' => array( 'location' => 'grid',
'cellId' => 'headcell_field1' ),
'simple_grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'simple_grid_field40' => array( 'location' => 'grid',
'cellId' => 'headcell_field2' ),
'simple_grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_field2' ),
'simple_grid_field41' => array( 'location' => 'grid',
'cellId' => 'headcell_field3' ),
'simple_grid_field4' => array( 'location' => 'grid',
'cellId' => 'cell_field3' ),
'simple_grid_field42' => array( 'location' => 'grid',
'cellId' => 'headcell_field4' ),
'simple_grid_field5' => array( 'location' => 'grid',
'cellId' => 'cell_field4' ),
'simple_grid_field43' => array( 'location' => 'grid',
'cellId' => 'headcell_field5' ),
'simple_grid_field6' => array( 'location' => 'grid',
'cellId' => 'cell_field5' ),
'simple_grid_field44' => array( 'location' => 'grid',
'cellId' => 'headcell_field6' ),
'simple_grid_field7' => array( 'location' => 'grid',
'cellId' => 'cell_field6' ),
'simple_grid_field45' => array( 'location' => 'grid',
'cellId' => 'headcell_field7' ),
'simple_grid_field8' => array( 'location' => 'grid',
'cellId' => 'cell_field7' ),
'simple_grid_field46' => array( 'location' => 'grid',
'cellId' => 'headcell_field8' ),
'simple_grid_field9' => array( 'location' => 'grid',
'cellId' => 'cell_field8' ),
'simple_grid_field47' => array( 'location' => 'grid',
'cellId' => 'headcell_field9' ),
'simple_grid_field10' => array( 'location' => 'grid',
'cellId' => 'cell_field9' ),
'simple_grid_field48' => array( 'location' => 'grid',
'cellId' => 'headcell_field10' ),
'simple_grid_field11' => array( 'location' => 'grid',
'cellId' => 'cell_field10' ),
'simple_grid_field49' => array( 'location' => 'grid',
'cellId' => 'headcell_field11' ),
'simple_grid_field12' => array( 'location' => 'grid',
'cellId' => 'cell_field11' ),
'simple_grid_field50' => array( 'location' => 'grid',
'cellId' => 'headcell_field12' ),
'simple_grid_field13' => array( 'location' => 'grid',
'cellId' => 'cell_field12' ),
'simple_grid_field51' => array( 'location' => 'grid',
'cellId' => 'headcell_field13' ),
'simple_grid_field14' => array( 'location' => 'grid',
'cellId' => 'cell_field13' ),
'simple_grid_field52' => array( 'location' => 'grid',
'cellId' => 'headcell_field14' ),
'simple_grid_field15' => array( 'location' => 'grid',
'cellId' => 'cell_field14' ),
'simple_grid_field53' => array( 'location' => 'grid',
'cellId' => 'headcell_field15' ),
'simple_grid_field16' => array( 'location' => 'grid',
'cellId' => 'cell_field15' ),
'simple_grid_field54' => array( 'location' => 'grid',
'cellId' => 'headcell_field16' ),
'simple_grid_field17' => array( 'location' => 'grid',
'cellId' => 'cell_field16' ),
'simple_grid_field55' => array( 'location' => 'grid',
'cellId' => 'headcell_field17' ),
'simple_grid_field18' => array( 'location' => 'grid',
'cellId' => 'cell_field17' ),
'simple_grid_field56' => array( 'location' => 'grid',
'cellId' => 'headcell_field18' ),
'simple_grid_field19' => array( 'location' => 'grid',
'cellId' => 'cell_field18' ),
'simple_grid_field57' => array( 'location' => 'grid',
'cellId' => 'headcell_field19' ),
'simple_grid_field20' => array( 'location' => 'grid',
'cellId' => 'cell_field19' ),
'grid_field_label3' => array( 'location' => 'grid',
'cellId' => 'headcell_field20' ),
'grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_field20' ),
'simple_grid_field59' => array( 'location' => 'grid',
'cellId' => 'headcell_field21' ),
'simple_grid_field22' => array( 'location' => 'grid',
'cellId' => 'cell_field21' ),
'simple_grid_field60' => array( 'location' => 'grid',
'cellId' => 'headcell_field22' ),
'simple_grid_field23' => array( 'location' => 'grid',
'cellId' => 'cell_field22' ),
'simple_grid_field61' => array( 'location' => 'grid',
'cellId' => 'headcell_field23' ),
'simple_grid_field24' => array( 'location' => 'grid',
'cellId' => 'cell_field23' ),
'simple_grid_field62' => array( 'location' => 'grid',
'cellId' => 'headcell_field24' ),
'simple_grid_field25' => array( 'location' => 'grid',
'cellId' => 'cell_field24' ),
'simple_grid_field63' => array( 'location' => 'grid',
'cellId' => 'headcell_field25' ),
'simple_grid_field26' => array( 'location' => 'grid',
'cellId' => 'cell_field25' ),
'simple_grid_field64' => array( 'location' => 'grid',
'cellId' => 'headcell_field26' ),
'simple_grid_field27' => array( 'location' => 'grid',
'cellId' => 'cell_field26' ),
'simple_grid_field65' => array( 'location' => 'grid',
'cellId' => 'headcell_field27' ),
'simple_grid_field28' => array( 'location' => 'grid',
'cellId' => 'cell_field27' ),
'simple_grid_field66' => array( 'location' => 'grid',
'cellId' => 'headcell_field28' ),
'simple_grid_field29' => array( 'location' => 'grid',
'cellId' => 'cell_field28' ),
'simple_grid_field67' => array( 'location' => 'grid',
'cellId' => 'headcell_field29' ),
'simple_grid_field30' => array( 'location' => 'grid',
'cellId' => 'cell_field29' ),
'simple_grid_field68' => array( 'location' => 'grid',
'cellId' => 'headcell_field30' ),
'simple_grid_field31' => array( 'location' => 'grid',
'cellId' => 'cell_field30' ),
'simple_grid_field69' => array( 'location' => 'grid',
'cellId' => 'headcell_field31' ),
'simple_grid_field32' => array( 'location' => 'grid',
'cellId' => 'cell_field31' ),
'simple_grid_field70' => array( 'location' => 'grid',
'cellId' => 'headcell_field32' ),
'simple_grid_field33' => array( 'location' => 'grid',
'cellId' => 'cell_field32' ),
'simple_grid_field71' => array( 'location' => 'grid',
'cellId' => 'headcell_field33' ),
'simple_grid_field34' => array( 'location' => 'grid',
'cellId' => 'cell_field33' ),
'simple_grid_field72' => array( 'location' => 'grid',
'cellId' => 'headcell_field34' ),
'simple_grid_field35' => array( 'location' => 'grid',
'cellId' => 'cell_field34' ),
'simple_grid_field73' => array( 'location' => 'grid',
'cellId' => 'headcell_field35' ),
'simple_grid_field36' => array( 'location' => 'grid',
'cellId' => 'cell_field35' ),
'simple_grid_field74' => array( 'location' => 'grid',
'cellId' => 'headcell_field36' ),
'simple_grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field36' ),
'simple_grid_field75' => array( 'location' => 'grid',
'cellId' => 'headcell_field37' ),
'simple_grid_field37' => array( 'location' => 'grid',
'cellId' => 'cell_field37' ),
'grid_field_label' => array( 'location' => 'grid',
'cellId' => 'headcell_field38' ),
'grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field38' ),
'grid_field_label1' => array( 'location' => 'grid',
'cellId' => 'headcell_field39' ),
'grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field39' ),
'grid_field_label2' => array( 'location' => 'grid',
'cellId' => 'headcell_field40' ),
'grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field40' ),
'grid_field_label4' => array( 'location' => 'grid',
'cellId' => 'headcell_field41' ),
'grid_field4' => array( 'location' => 'grid',
'cellId' => 'cell_field41' ),
'grid_field_label5' => array( 'location' => 'grid',
'cellId' => 'headcell_field42' ),
'grid_field5' => array( 'location' => 'grid',
'cellId' => 'cell_field42' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'masterprint_header' => array( 'masterprint_header' ),
'grid_field' => array( 'simple_grid_field34',
'simple_grid_field33',
'simple_grid_field1',
'simple_grid_field2',
'simple_grid_field3',
'simple_grid_field32',
'simple_grid_field31',
'simple_grid_field30',
'simple_grid_field29',
'simple_grid_field28',
'simple_grid_field27',
'simple_grid_field26',
'simple_grid_field25',
'simple_grid_field24',
'simple_grid_field23',
'simple_grid_field22',
'simple_grid_field20',
'simple_grid_field19',
'simple_grid_field18',
'simple_grid_field17',
'simple_grid_field16',
'simple_grid_field15',
'simple_grid_field14',
'simple_grid_field13',
'simple_grid_field12',
'simple_grid_field11',
'simple_grid_field10',
'simple_grid_field9',
'simple_grid_field8',
'simple_grid_field7',
'simple_grid_field6',
'simple_grid_field5',
'simple_grid_field4',
'simple_grid_field35',
'simple_grid_field36',
'simple_grid_field',
'simple_grid_field37',
'grid_field',
'grid_field1',
'grid_field2',
'grid_field3',
'grid_field4',
'grid_field5' ),
'grid_field_label' => array( 'simple_grid_field38',
'simple_grid_field39',
'simple_grid_field40',
'simple_grid_field41',
'simple_grid_field42',
'simple_grid_field43',
'simple_grid_field44',
'simple_grid_field45',
'simple_grid_field46',
'simple_grid_field47',
'simple_grid_field48',
'simple_grid_field49',
'simple_grid_field50',
'simple_grid_field51',
'simple_grid_field52',
'simple_grid_field53',
'simple_grid_field54',
'simple_grid_field55',
'simple_grid_field56',
'simple_grid_field57',
'simple_grid_field59',
'simple_grid_field60',
'simple_grid_field61',
'simple_grid_field62',
'simple_grid_field63',
'simple_grid_field64',
'simple_grid_field65',
'simple_grid_field66',
'simple_grid_field67',
'simple_grid_field68',
'simple_grid_field69',
'simple_grid_field70',
'simple_grid_field71',
'simple_grid_field72',
'simple_grid_field73',
'simple_grid_field74',
'simple_grid_field75',
'grid_field_label',
'grid_field_label1',
'grid_field_label2',
'grid_field_label3',
'grid_field_label4',
'grid_field_label5' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'headcell_field' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array( 'fecha_de_compra_fieldheadercolumn' ),
'items' => array( 'simple_grid_field38' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field1' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array( 'ano_mes_fieldheadercolumn' ),
'items' => array( 'simple_grid_field39' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field2' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array( 'id_prov_fieldheadercolumn' ),
'items' => array( 'simple_grid_field40' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field3' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array( 'cat_compras_proveedores_id_fieldheadercolumn' ),
'items' => array( 'simple_grid_field41' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field4' => array( 'cols' => array( 4 ),
'rows' => array( 0 ),
'tags' => array( 'alias_proveedor_fieldheadercolumn' ),
'items' => array( 'simple_grid_field42' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field5' => array( 'cols' => array( 5 ),
'rows' => array( 0 ),
'tags' => array( 'concepto_fieldheadercolumn' ),
'items' => array( 'simple_grid_field43' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field6' => array( 'cols' => array( 6 ),
'rows' => array( 0 ),
'tags' => array( 'importe_abono_compra_fieldheadercolumn' ),
'items' => array( 'simple_grid_field44' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field7' => array( 'cols' => array( 7 ),
'rows' => array( 0 ),
'tags' => array( 'orden_de_compra_proveedor_fieldheadercolumn' ),
'items' => array( 'simple_grid_field45' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field8' => array( 'cols' => array( 8 ),
'rows' => array( 0 ),
'tags' => array( 'uuid_sat_fieldheadercolumn' ),
'items' => array( 'simple_grid_field46' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field9' => array( 'cols' => array( 9 ),
'rows' => array( 0 ),
'tags' => array( 'cat_compras_documentos_mu_id_fieldheadercolumn' ),
'items' => array( 'simple_grid_field47' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field10' => array( 'cols' => array( 10 ),
'rows' => array( 0 ),
'tags' => array( 'referencia_fieldheadercolumn' ),
'items' => array( 'simple_grid_field48' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field11' => array( 'cols' => array( 11 ),
'rows' => array( 0 ),
'tags' => array( 'fecha_de_vencimiento_fieldheadercolumn' ),
'items' => array( 'simple_grid_field49' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field12' => array( 'cols' => array( 12 ),
'rows' => array( 0 ),
'tags' => array( 'vigente_fieldheadercolumn' ),
'items' => array( 'simple_grid_field50' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field13' => array( 'cols' => array( 13 ),
'rows' => array( 0 ),
'tags' => array( 'total_compras_abonos_fieldheadercolumn' ),
'items' => array( 'simple_grid_field51' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field14' => array( 'cols' => array( 14 ),
'rows' => array( 0 ),
'tags' => array( 'total_pagos_cargos_fieldheadercolumn' ),
'items' => array( 'simple_grid_field52' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field15' => array( 'cols' => array( 15 ),
'rows' => array( 0 ),
'tags' => array( 'saldo_fieldheadercolumn' ),
'items' => array( 'simple_grid_field53' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field16' => array( 'cols' => array( 16 ),
'rows' => array( 0 ),
'tags' => array( 'capturista_fieldheadercolumn' ),
'items' => array( 'simple_grid_field54' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field17' => array( 'cols' => array( 17 ),
'rows' => array( 0 ),
'tags' => array( 'tr_compras_requisiciones_01_uuid_fieldheadercolumn' ),
'items' => array( 'simple_grid_field55' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field18' => array( 'cols' => array( 18 ),
'rows' => array( 0 ),
'tags' => array( 'uuid_cargo_abono_compra_fieldheadercolumn' ),
'items' => array( 'simple_grid_field56' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field19' => array( 'cols' => array( 19 ),
'rows' => array( 0 ),
'tags' => array( 'tr_compras_proveedores_01_cargos_abonos_id_fieldheadercolumn' ),
'items' => array( 'simple_grid_field57' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field21' => array( 'cols' => array( 20 ),
'rows' => array( 0 ),
'tags' => array( 'alias_cuenta_de_cargo_pago_fieldheadercolumn' ),
'items' => array( 'simple_grid_field59' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field22' => array( 'cols' => array( 21 ),
'rows' => array( 0 ),
'tags' => array( 'alias_cuenta_de_balance_fieldheadercolumn' ),
'items' => array( 'simple_grid_field60' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field23' => array( 'cols' => array( 22 ),
'rows' => array( 0 ),
'tags' => array( 'importe_cargo_pago_fieldheadercolumn' ),
'items' => array( 'simple_grid_field61' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field24' => array( 'cols' => array( 23 ),
'rows' => array( 0 ),
'tags' => array( 'fecha_de_pago_fieldheadercolumn' ),
'items' => array( 'simple_grid_field62' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field25' => array( 'cols' => array( 24 ),
'rows' => array( 0 ),
'tags' => array( 'imei_fieldheadercolumn' ),
'items' => array( 'simple_grid_field63' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field26' => array( 'cols' => array( 25 ),
'rows' => array( 0 ),
'tags' => array( 'time_stamp_fieldheadercolumn' ),
'items' => array( 'simple_grid_field64' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field27' => array( 'cols' => array( 26 ),
'rows' => array( 0 ),
'tags' => array( 'consecutivo_id_fieldheadercolumn' ),
'items' => array( 'simple_grid_field65' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field28' => array( 'cols' => array( 27 ),
'rows' => array( 0 ),
'tags' => array( 'cat_finanzas_bancos_cuentas_id_fieldheadercolumn' ),
'items' => array( 'simple_grid_field66' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field29' => array( 'cols' => array( 28 ),
'rows' => array( 0 ),
'tags' => array( 'cat_finanzas_cajas_chicas_id_fieldheadercolumn' ),
'items' => array( 'simple_grid_field67' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field30' => array( 'cols' => array( 29 ),
'rows' => array( 0 ),
'tags' => array( 'cat_usuarios_licencias_id_fieldheadercolumn' ),
'items' => array( 'simple_grid_field68' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field31' => array( 'cols' => array( 30 ),
'rows' => array( 0 ),
'tags' => array( 'uuid_cargo_abono_pago_fieldheadercolumn' ),
'items' => array( 'simple_grid_field69' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field32' => array( 'cols' => array( 31 ),
'rows' => array( 0 ),
'tags' => array( 'cat_finanzas_cuentas_de_balance_04_llave_fieldheadercolumn' ),
'items' => array( 'simple_grid_field70' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field33' => array( 'cols' => array( 32 ),
'rows' => array( 0 ),
'tags' => array( 'referencia_bancaria_fieldheadercolumn' ),
'items' => array( 'simple_grid_field71' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field34' => array( 'cols' => array( 33 ),
'rows' => array( 0 ),
'tags' => array( 'observacion_abono_compra_fieldheadercolumn' ),
'items' => array( 'simple_grid_field72' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field35' => array( 'cols' => array( 34 ),
'rows' => array( 0 ),
'tags' => array( 'cat_compras_estatus_mu_id_fieldheadercolumn' ),
'items' => array( 'simple_grid_field73' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field36' => array( 'cols' => array( 35 ),
'rows' => array( 0 ),
'tags' => array( 'fecha_de_recibo_fieldheadercolumn' ),
'items' => array( 'simple_grid_field74' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field37' => array( 'cols' => array( 36 ),
'rows' => array( 0 ),
'tags' => array( 'tr_compras_almacenes_01_recibo_lpn_uuid_fieldheadercolumn' ),
'items' => array( 'simple_grid_field75' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field38' => array( 'cols' => array( 37 ),
'rows' => array( 0 ),
'tags' => array( 'fecha_de_solicitud_fieldheadercolumn' ),
'items' => array( 'grid_field_label' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field39' => array( 'cols' => array( 38 ),
'rows' => array( 0 ),
'tags' => array( 'fecha_de_requisicion_fieldheadercolumn' ),
'items' => array( 'grid_field_label1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field40' => array( 'cols' => array( 39 ),
'rows' => array( 0 ),
'tags' => array( 'saldo1_fieldheadercolumn' ),
'items' => array( 'grid_field_label2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field20' => array( 'cols' => array( 40 ),
'rows' => array( 0 ),
'tags' => array( 'cargo_abono_fieldheadercolumn' ),
'items' => array( 'grid_field_label3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field41' => array( 'cols' => array( 41 ),
'rows' => array( 0 ),
'tags' => array( 'cat_compras_cargo_abono_mu_id_fieldheadercolumn' ),
'items' => array( 'grid_field_label4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field42' => array( 'cols' => array( 42 ),
'rows' => array( 0 ),
'tags' => array( 'llave_unica_cargo_abono_tr_compras_requisiciones_01_uuid_pago_fieldheadercolumn' ),
'items' => array( 'grid_field_label5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'fecha_de_compra_fieldcolumn' ),
'items' => array( 'simple_grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array( 'ano_mes_fieldcolumn' ),
'items' => array( 'simple_grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array( 'id_prov_fieldcolumn' ),
'items' => array( 'simple_grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field3' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array( 'cat_compras_proveedores_id_fieldcolumn' ),
'items' => array( 'simple_grid_field4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field4' => array( 'cols' => array( 4 ),
'rows' => array( 1 ),
'tags' => array( 'alias_proveedor_fieldcolumn' ),
'items' => array( 'simple_grid_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field5' => array( 'cols' => array( 5 ),
'rows' => array( 1 ),
'tags' => array( 'concepto_fieldcolumn' ),
'items' => array( 'simple_grid_field6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field6' => array( 'cols' => array( 6 ),
'rows' => array( 1 ),
'tags' => array( 'importe_abono_compra_fieldcolumn' ),
'items' => array( 'simple_grid_field7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field7' => array( 'cols' => array( 7 ),
'rows' => array( 1 ),
'tags' => array( 'orden_de_compra_proveedor_fieldcolumn' ),
'items' => array( 'simple_grid_field8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field8' => array( 'cols' => array( 8 ),
'rows' => array( 1 ),
'tags' => array( 'uuid_sat_fieldcolumn' ),
'items' => array( 'simple_grid_field9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field9' => array( 'cols' => array( 9 ),
'rows' => array( 1 ),
'tags' => array( 'cat_compras_documentos_mu_id_fieldcolumn' ),
'items' => array( 'simple_grid_field10' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field10' => array( 'cols' => array( 10 ),
'rows' => array( 1 ),
'tags' => array( 'referencia_fieldcolumn' ),
'items' => array( 'simple_grid_field11' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field11' => array( 'cols' => array( 11 ),
'rows' => array( 1 ),
'tags' => array( 'fecha_de_vencimiento_fieldcolumn' ),
'items' => array( 'simple_grid_field12' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field12' => array( 'cols' => array( 12 ),
'rows' => array( 1 ),
'tags' => array( 'vigente_fieldcolumn' ),
'items' => array( 'simple_grid_field13' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field13' => array( 'cols' => array( 13 ),
'rows' => array( 1 ),
'tags' => array( 'total_compras_abonos_fieldcolumn' ),
'items' => array( 'simple_grid_field14' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field14' => array( 'cols' => array( 14 ),
'rows' => array( 1 ),
'tags' => array( 'total_pagos_cargos_fieldcolumn' ),
'items' => array( 'simple_grid_field15' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field15' => array( 'cols' => array( 15 ),
'rows' => array( 1 ),
'tags' => array( 'saldo_fieldcolumn' ),
'items' => array( 'simple_grid_field16' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field16' => array( 'cols' => array( 16 ),
'rows' => array( 1 ),
'tags' => array( 'capturista_fieldcolumn' ),
'items' => array( 'simple_grid_field17' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field17' => array( 'cols' => array( 17 ),
'rows' => array( 1 ),
'tags' => array( 'tr_compras_requisiciones_01_uuid_fieldcolumn' ),
'items' => array( 'simple_grid_field18' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field18' => array( 'cols' => array( 18 ),
'rows' => array( 1 ),
'tags' => array( 'uuid_cargo_abono_compra_fieldcolumn' ),
'items' => array( 'simple_grid_field19' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field19' => array( 'cols' => array( 19 ),
'rows' => array( 1 ),
'tags' => array( 'tr_compras_proveedores_01_cargos_abonos_id_fieldcolumn' ),
'items' => array( 'simple_grid_field20' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field21' => array( 'cols' => array( 20 ),
'rows' => array( 1 ),
'tags' => array( 'alias_cuenta_de_cargo_pago_fieldcolumn' ),
'items' => array( 'simple_grid_field22' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field22' => array( 'cols' => array( 21 ),
'rows' => array( 1 ),
'tags' => array( 'alias_cuenta_de_balance_fieldcolumn' ),
'items' => array( 'simple_grid_field23' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field23' => array( 'cols' => array( 22 ),
'rows' => array( 1 ),
'tags' => array( 'importe_cargo_pago_fieldcolumn' ),
'items' => array( 'simple_grid_field24' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field24' => array( 'cols' => array( 23 ),
'rows' => array( 1 ),
'tags' => array( 'fecha_de_pago_fieldcolumn' ),
'items' => array( 'simple_grid_field25' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field25' => array( 'cols' => array( 24 ),
'rows' => array( 1 ),
'tags' => array( 'imei_fieldcolumn' ),
'items' => array( 'simple_grid_field26' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field26' => array( 'cols' => array( 25 ),
'rows' => array( 1 ),
'tags' => array( 'time_stamp_fieldcolumn' ),
'items' => array( 'simple_grid_field27' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field27' => array( 'cols' => array( 26 ),
'rows' => array( 1 ),
'tags' => array( 'consecutivo_id_fieldcolumn' ),
'items' => array( 'simple_grid_field28' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field28' => array( 'cols' => array( 27 ),
'rows' => array( 1 ),
'tags' => array( 'cat_finanzas_bancos_cuentas_id_fieldcolumn' ),
'items' => array( 'simple_grid_field29' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field29' => array( 'cols' => array( 28 ),
'rows' => array( 1 ),
'tags' => array( 'cat_finanzas_cajas_chicas_id_fieldcolumn' ),
'items' => array( 'simple_grid_field30' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field30' => array( 'cols' => array( 29 ),
'rows' => array( 1 ),
'tags' => array( 'cat_usuarios_licencias_id_fieldcolumn' ),
'items' => array( 'simple_grid_field31' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field31' => array( 'cols' => array( 30 ),
'rows' => array( 1 ),
'tags' => array( 'uuid_cargo_abono_pago_fieldcolumn' ),
'items' => array( 'simple_grid_field32' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field32' => array( 'cols' => array( 31 ),
'rows' => array( 1 ),
'tags' => array( 'cat_finanzas_cuentas_de_balance_04_llave_fieldcolumn' ),
'items' => array( 'simple_grid_field33' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field33' => array( 'cols' => array( 32 ),
'rows' => array( 1 ),
'tags' => array( 'referencia_bancaria_fieldcolumn' ),
'items' => array( 'simple_grid_field34' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field34' => array( 'cols' => array( 33 ),
'rows' => array( 1 ),
'tags' => array( 'observacion_abono_compra_fieldcolumn' ),
'items' => array( 'simple_grid_field35' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field35' => array( 'cols' => array( 34 ),
'rows' => array( 1 ),
'tags' => array( 'cat_compras_estatus_mu_id_fieldcolumn' ),
'items' => array( 'simple_grid_field36' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field36' => array( 'cols' => array( 35 ),
'rows' => array( 1 ),
'tags' => array( 'fecha_de_recibo_fieldcolumn' ),
'items' => array( 'simple_grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field37' => array( 'cols' => array( 36 ),
'rows' => array( 1 ),
'tags' => array( 'tr_compras_almacenes_01_recibo_lpn_uuid_fieldcolumn' ),
'items' => array( 'simple_grid_field37' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field38' => array( 'cols' => array( 37 ),
'rows' => array( 1 ),
'tags' => array( 'fecha_de_solicitud_fieldcolumn' ),
'items' => array( 'grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field39' => array( 'cols' => array( 38 ),
'rows' => array( 1 ),
'tags' => array( 'fecha_de_requisicion_fieldcolumn' ),
'items' => array( 'grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field40' => array( 'cols' => array( 39 ),
'rows' => array( 1 ),
'tags' => array( 'saldo1_fieldcolumn' ),
'items' => array( 'grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field20' => array( 'cols' => array( 40 ),
'rows' => array( 1 ),
'tags' => array( 'cargo_abono_fieldcolumn' ),
'items' => array( 'grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field41' => array( 'cols' => array( 41 ),
'rows' => array( 1 ),
'tags' => array( 'cat_compras_cargo_abono_mu_id_fieldcolumn' ),
'items' => array( 'grid_field4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field42' => array( 'cols' => array( 42 ),
'rows' => array( 1 ),
'tags' => array( 'llave_unica_cargo_abono_tr_compras_requisiciones_01_uuid_pago_fieldcolumn' ),
'items' => array( 'grid_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field1' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field2' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field3' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field4' => array( 'cols' => array( 4 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field5' => array( 'cols' => array( 5 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field6' => array( 'cols' => array( 6 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field7' => array( 'cols' => array( 7 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field8' => array( 'cols' => array( 8 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field9' => array( 'cols' => array( 9 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field10' => array( 'cols' => array( 10 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field11' => array( 'cols' => array( 11 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field12' => array( 'cols' => array( 12 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field13' => array( 'cols' => array( 13 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field14' => array( 'cols' => array( 14 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field15' => array( 'cols' => array( 15 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field16' => array( 'cols' => array( 16 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field17' => array( 'cols' => array( 17 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field18' => array( 'cols' => array( 18 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field19' => array( 'cols' => array( 19 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field21' => array( 'cols' => array( 20 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field22' => array( 'cols' => array( 21 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field23' => array( 'cols' => array( 22 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field24' => array( 'cols' => array( 23 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field25' => array( 'cols' => array( 24 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field26' => array( 'cols' => array( 25 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field27' => array( 'cols' => array( 26 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field28' => array( 'cols' => array( 27 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field29' => array( 'cols' => array( 28 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field30' => array( 'cols' => array( 29 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field31' => array( 'cols' => array( 30 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field32' => array( 'cols' => array( 31 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field33' => array( 'cols' => array( 32 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field34' => array( 'cols' => array( 33 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field35' => array( 'cols' => array( 34 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field36' => array( 'cols' => array( 35 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field37' => array( 'cols' => array( 36 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field38' => array( 'cols' => array( 37 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field39' => array( 'cols' => array( 38 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field40' => array( 'cols' => array( 39 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field20' => array( 'cols' => array( 40 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field41' => array( 'cols' => array( 41 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field42' => array( 'cols' => array( 42 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 43,
'height' => 3 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'gridType' => 0,
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'masterprint',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'masterprint',
'type' => 'masterprint',
'layoutId' => 'masterprint',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'empty-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'empty-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'masterlist-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'masterprint_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'horizontal-grid',
'grid' => array( array( 'section' => 'head',
'cells' => array( array( 'cell' => 'headcell_field' ),
array( 'cell' => 'headcell_field1' ),
array( 'cell' => 'headcell_field2' ),
array( 'cell' => 'headcell_field3' ),
array( 'cell' => 'headcell_field4' ),
array( 'cell' => 'headcell_field5' ),
array( 'cell' => 'headcell_field6' ),
array( 'cell' => 'headcell_field7' ),
array( 'cell' => 'headcell_field8' ),
array( 'cell' => 'headcell_field9' ),
array( 'cell' => 'headcell_field10' ),
array( 'cell' => 'headcell_field11' ),
array( 'cell' => 'headcell_field12' ),
array( 'cell' => 'headcell_field13' ),
array( 'cell' => 'headcell_field14' ),
array( 'cell' => 'headcell_field15' ),
array( 'cell' => 'headcell_field16' ),
array( 'cell' => 'headcell_field17' ),
array( 'cell' => 'headcell_field18' ),
array( 'cell' => 'headcell_field19' ),
array( 'cell' => 'headcell_field21' ),
array( 'cell' => 'headcell_field22' ),
array( 'cell' => 'headcell_field23' ),
array( 'cell' => 'headcell_field24' ),
array( 'cell' => 'headcell_field25' ),
array( 'cell' => 'headcell_field26' ),
array( 'cell' => 'headcell_field27' ),
array( 'cell' => 'headcell_field28' ),
array( 'cell' => 'headcell_field29' ),
array( 'cell' => 'headcell_field30' ),
array( 'cell' => 'headcell_field31' ),
array( 'cell' => 'headcell_field32' ),
array( 'cell' => 'headcell_field33' ),
array( 'cell' => 'headcell_field34' ),
array( 'cell' => 'headcell_field35' ),
array( 'cell' => 'headcell_field36' ),
array( 'cell' => 'headcell_field37' ),
array( 'cell' => 'headcell_field38' ),
array( 'cell' => 'headcell_field39' ),
array( 'cell' => 'headcell_field40' ),
array( 'cell' => 'headcell_field20' ),
array( 'cell' => 'headcell_field41' ),
array( 'cell' => 'headcell_field42' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_field' ),
array( 'cell' => 'cell_field1' ),
array( 'cell' => 'cell_field2' ),
array( 'cell' => 'cell_field3' ),
array( 'cell' => 'cell_field4' ),
array( 'cell' => 'cell_field5' ),
array( 'cell' => 'cell_field6' ),
array( 'cell' => 'cell_field7' ),
array( 'cell' => 'cell_field8' ),
array( 'cell' => 'cell_field9' ),
array( 'cell' => 'cell_field10' ),
array( 'cell' => 'cell_field11' ),
array( 'cell' => 'cell_field12' ),
array( 'cell' => 'cell_field13' ),
array( 'cell' => 'cell_field14' ),
array( 'cell' => 'cell_field15' ),
array( 'cell' => 'cell_field16' ),
array( 'cell' => 'cell_field17' ),
array( 'cell' => 'cell_field18' ),
array( 'cell' => 'cell_field19' ),
array( 'cell' => 'cell_field21' ),
array( 'cell' => 'cell_field22' ),
array( 'cell' => 'cell_field23' ),
array( 'cell' => 'cell_field24' ),
array( 'cell' => 'cell_field25' ),
array( 'cell' => 'cell_field26' ),
array( 'cell' => 'cell_field27' ),
array( 'cell' => 'cell_field28' ),
array( 'cell' => 'cell_field29' ),
array( 'cell' => 'cell_field30' ),
array( 'cell' => 'cell_field31' ),
array( 'cell' => 'cell_field32' ),
array( 'cell' => 'cell_field33' ),
array( 'cell' => 'cell_field34' ),
array( 'cell' => 'cell_field35' ),
array( 'cell' => 'cell_field36' ),
array( 'cell' => 'cell_field37' ),
array( 'cell' => 'cell_field38' ),
array( 'cell' => 'cell_field39' ),
array( 'cell' => 'cell_field40' ),
array( 'cell' => 'cell_field20' ),
array( 'cell' => 'cell_field41' ),
array( 'cell' => 'cell_field42' ) ) ),
array( 'section' => 'foot',
'cells' => array( array( 'cell' => 'footcell_field' ),
array( 'cell' => 'footcell_field1' ),
array( 'cell' => 'footcell_field2' ),
array( 'cell' => 'footcell_field3' ),
array( 'cell' => 'footcell_field4' ),
array( 'cell' => 'footcell_field5' ),
array( 'cell' => 'footcell_field6' ),
array( 'cell' => 'footcell_field7' ),
array( 'cell' => 'footcell_field8' ),
array( 'cell' => 'footcell_field9' ),
array( 'cell' => 'footcell_field10' ),
array( 'cell' => 'footcell_field11' ),
array( 'cell' => 'footcell_field12' ),
array( 'cell' => 'footcell_field13' ),
array( 'cell' => 'footcell_field14' ),
array( 'cell' => 'footcell_field15' ),
array( 'cell' => 'footcell_field16' ),
array( 'cell' => 'footcell_field17' ),
array( 'cell' => 'footcell_field18' ),
array( 'cell' => 'footcell_field19' ),
array( 'cell' => 'footcell_field21' ),
array( 'cell' => 'footcell_field22' ),
array( 'cell' => 'footcell_field23' ),
array( 'cell' => 'footcell_field24' ),
array( 'cell' => 'footcell_field25' ),
array( 'cell' => 'footcell_field26' ),
array( 'cell' => 'footcell_field27' ),
array( 'cell' => 'footcell_field28' ),
array( 'cell' => 'footcell_field29' ),
array( 'cell' => 'footcell_field30' ),
array( 'cell' => 'footcell_field31' ),
array( 'cell' => 'footcell_field32' ),
array( 'cell' => 'footcell_field33' ),
array( 'cell' => 'footcell_field34' ),
array( 'cell' => 'footcell_field35' ),
array( 'cell' => 'footcell_field36' ),
array( 'cell' => 'footcell_field37' ),
array( 'cell' => 'footcell_field38' ),
array( 'cell' => 'footcell_field39' ),
array( 'cell' => 'footcell_field40' ),
array( 'cell' => 'footcell_field20' ),
array( 'cell' => 'footcell_field41' ),
array( 'cell' => 'footcell_field42' ) ) ) ),
'cells' => array( 'headcell_field' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field38' ),
'field' => 'fecha_de_compra',
'columnName' => 'field' ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field1' ),
'field' => 'fecha_de_compra',
'columnName' => 'field' ),
'footcell_field' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field1' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field39' ),
'field' => 'ano_mes',
'columnName' => 'field' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field2' ),
'field' => 'ano_mes',
'columnName' => 'field' ),
'footcell_field1' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field2' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field40' ),
'field' => 'id_prov',
'columnName' => 'field' ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field3' ),
'field' => 'id_prov',
'columnName' => 'field' ),
'footcell_field2' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field3' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field41' ),
'field' => 'cat_compras_proveedores_id',
'columnName' => 'field' ),
'cell_field3' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field4' ),
'field' => 'cat_compras_proveedores_id',
'columnName' => 'field' ),
'footcell_field3' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field4' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field42' ),
'field' => 'alias_proveedor',
'columnName' => 'field' ),
'cell_field4' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field5' ),
'field' => 'alias_proveedor',
'columnName' => 'field' ),
'footcell_field4' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field5' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field43' ),
'field' => 'concepto',
'columnName' => 'field' ),
'cell_field5' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field6' ),
'field' => 'concepto',
'columnName' => 'field' ),
'footcell_field5' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field6' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field44' ),
'field' => 'importe_abono_compra',
'columnName' => 'field' ),
'cell_field6' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field7' ),
'field' => 'importe_abono_compra',
'columnName' => 'field' ),
'footcell_field6' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field7' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field45' ),
'field' => 'orden_de_compra_proveedor',
'columnName' => 'field' ),
'cell_field7' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field8' ),
'field' => 'orden_de_compra_proveedor',
'columnName' => 'field' ),
'footcell_field7' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field8' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field46' ),
'field' => 'uuid_sat',
'columnName' => 'field' ),
'cell_field8' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field9' ),
'field' => 'uuid_sat',
'columnName' => 'field' ),
'footcell_field8' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field9' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field47' ),
'field' => 'cat_compras_documentos_mu_id',
'columnName' => 'field' ),
'cell_field9' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field10' ),
'field' => 'cat_compras_documentos_mu_id',
'columnName' => 'field' ),
'footcell_field9' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field10' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field48' ),
'field' => 'referencia',
'columnName' => 'field' ),
'cell_field10' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field11' ),
'field' => 'referencia',
'columnName' => 'field' ),
'footcell_field10' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field11' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field49' ),
'field' => 'fecha_de_vencimiento',
'columnName' => 'field' ),
'cell_field11' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field12' ),
'field' => 'fecha_de_vencimiento',
'columnName' => 'field' ),
'footcell_field11' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field12' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field50' ),
'field' => 'vigente',
'columnName' => 'field' ),
'cell_field12' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field13' ),
'field' => 'vigente',
'columnName' => 'field' ),
'footcell_field12' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field13' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field51' ),
'field' => 'total_compras_abonos',
'columnName' => 'field' ),
'cell_field13' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field14' ),
'field' => 'total_compras_abonos',
'columnName' => 'field' ),
'footcell_field13' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field14' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field52' ),
'field' => 'total_pagos_cargos',
'columnName' => 'field' ),
'cell_field14' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field15' ),
'field' => 'total_pagos_cargos',
'columnName' => 'field' ),
'footcell_field14' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field15' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field53' ),
'field' => 'saldo',
'columnName' => 'field' ),
'cell_field15' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field16' ),
'field' => 'saldo',
'columnName' => 'field' ),
'footcell_field15' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field16' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field54' ),
'field' => 'capturista',
'columnName' => 'field' ),
'cell_field16' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field17' ),
'field' => 'capturista',
'columnName' => 'field' ),
'footcell_field16' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field17' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field55' ),
'field' => 'tr_compras_requisiciones_01_uuid',
'columnName' => 'field' ),
'cell_field17' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field18' ),
'field' => 'tr_compras_requisiciones_01_uuid',
'columnName' => 'field' ),
'footcell_field17' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field18' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field56' ),
'field' => 'uuid_cargo_abono_compra',
'columnName' => 'field' ),
'cell_field18' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field19' ),
'field' => 'uuid_cargo_abono_compra',
'columnName' => 'field' ),
'footcell_field18' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field19' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field57' ),
'field' => 'tr_compras_proveedores_01_cargos_abonos_id',
'columnName' => 'field' ),
'cell_field19' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field20' ),
'field' => 'tr_compras_proveedores_01_cargos_abonos_id',
'columnName' => 'field' ),
'footcell_field19' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field20' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label3' ),
'field' => 'cargo_abono',
'columnName' => 'field' ),
'cell_field20' => array( 'model' => 'cell_field',
'items' => array( 'grid_field3' ),
'field' => 'cargo_abono',
'columnName' => 'field' ),
'footcell_field20' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field21' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field59' ),
'field' => 'alias_cuenta_de_cargo_pago',
'columnName' => 'field' ),
'cell_field21' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field22' ),
'field' => 'alias_cuenta_de_cargo_pago',
'columnName' => 'field' ),
'footcell_field21' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field22' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field60' ),
'field' => 'alias_cuenta_de_balance',
'columnName' => 'field' ),
'cell_field22' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field23' ),
'field' => 'alias_cuenta_de_balance',
'columnName' => 'field' ),
'footcell_field22' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field23' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field61' ),
'field' => 'importe_cargo_pago',
'columnName' => 'field' ),
'cell_field23' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field24' ),
'field' => 'importe_cargo_pago',
'columnName' => 'field' ),
'footcell_field23' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field24' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field62' ),
'field' => 'fecha_de_pago',
'columnName' => 'field' ),
'cell_field24' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field25' ),
'field' => 'fecha_de_pago',
'columnName' => 'field' ),
'footcell_field24' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field25' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field63' ),
'field' => 'imei',
'columnName' => 'field' ),
'cell_field25' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field26' ),
'field' => 'imei',
'columnName' => 'field' ),
'footcell_field25' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field26' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field64' ),
'field' => 'time_stamp',
'columnName' => 'field' ),
'cell_field26' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field27' ),
'field' => 'time_stamp',
'columnName' => 'field' ),
'footcell_field26' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field27' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field65' ),
'field' => 'consecutivo_id',
'columnName' => 'field' ),
'cell_field27' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field28' ),
'field' => 'consecutivo_id',
'columnName' => 'field' ),
'footcell_field27' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field28' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field66' ),
'field' => 'cat_finanzas_bancos_cuentas_id',
'columnName' => 'field' ),
'cell_field28' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field29' ),
'field' => 'cat_finanzas_bancos_cuentas_id',
'columnName' => 'field' ),
'footcell_field28' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field29' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field67' ),
'field' => 'cat_finanzas_cajas_chicas_id',
'columnName' => 'field' ),
'cell_field29' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field30' ),
'field' => 'cat_finanzas_cajas_chicas_id',
'columnName' => 'field' ),
'footcell_field29' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field30' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field68' ),
'field' => 'cat_usuarios_licencias_id',
'columnName' => 'field' ),
'cell_field30' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field31' ),
'field' => 'cat_usuarios_licencias_id',
'columnName' => 'field' ),
'footcell_field30' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field31' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field69' ),
'field' => 'uuid_cargo_abono_pago',
'columnName' => 'field' ),
'cell_field31' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field32' ),
'field' => 'uuid_cargo_abono_pago',
'columnName' => 'field' ),
'footcell_field31' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field32' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field70' ),
'field' => 'cat_finanzas_cuentas_de_balance_04_llave',
'columnName' => 'field' ),
'cell_field32' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field33' ),
'field' => 'cat_finanzas_cuentas_de_balance_04_llave',
'columnName' => 'field' ),
'footcell_field32' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field33' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field71' ),
'field' => 'referencia_bancaria',
'columnName' => 'field' ),
'cell_field33' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field34' ),
'field' => 'referencia_bancaria',
'columnName' => 'field' ),
'footcell_field33' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field34' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field72' ),
'field' => 'observacion_abono_compra',
'columnName' => 'field' ),
'cell_field34' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field35' ),
'field' => 'observacion_abono_compra',
'columnName' => 'field' ),
'footcell_field34' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field35' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field73' ),
'field' => 'cat_compras_estatus_mu_id',
'columnName' => 'field' ),
'cell_field35' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field36' ),
'field' => 'cat_compras_estatus_mu_id',
'columnName' => 'field' ),
'footcell_field35' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field36' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field74' ),
'field' => 'fecha_de_recibo',
'columnName' => 'field' ),
'cell_field36' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field' ),
'field' => 'fecha_de_recibo',
'columnName' => 'field' ),
'footcell_field36' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field37' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field75' ),
'field' => 'tr_compras_almacenes_01_recibo_lpn_uuid',
'columnName' => 'field' ),
'cell_field37' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field37' ),
'field' => 'tr_compras_almacenes_01_recibo_lpn_uuid',
'columnName' => 'field' ),
'footcell_field37' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field38' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label' ),
'field' => 'fecha_de_solicitud',
'columnName' => 'field' ),
'cell_field38' => array( 'model' => 'cell_field',
'items' => array( 'grid_field' ),
'field' => 'fecha_de_solicitud',
'columnName' => 'field' ),
'footcell_field38' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field39' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label1' ),
'field' => 'fecha_de_requisicion',
'columnName' => 'field' ),
'cell_field39' => array( 'model' => 'cell_field',
'items' => array( 'grid_field1' ),
'field' => 'fecha_de_requisicion',
'columnName' => 'field' ),
'footcell_field39' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field40' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label2' ),
'field' => 'saldo1',
'columnName' => 'field' ),
'cell_field40' => array( 'model' => 'cell_field',
'items' => array( 'grid_field2' ),
'field' => 'saldo1',
'columnName' => 'field' ),
'footcell_field40' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field41' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label4' ),
'field' => 'cat_compras_cargo_abono_mu_id',
'columnName' => 'field' ),
'cell_field41' => array( 'model' => 'cell_field',
'items' => array( 'grid_field4' ),
'field' => 'cat_compras_cargo_abono_mu_id',
'columnName' => 'field' ),
'footcell_field41' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field42' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label5' ),
'field' => 'llave_unica_cargo_abono_tr_compras_requisiciones_01_uuid_pago',
'columnName' => 'field' ),
'cell_field42' => array( 'model' => 'cell_field',
'items' => array( 'grid_field5' ),
'field' => 'llave_unica_cargo_abono_tr_compras_requisiciones_01_uuid_pago',
'columnName' => 'field' ),
'footcell_field42' => array( 'model' => 'footcell_field',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'masterprint_header' => array( 'type' => 'masterprint_header' ),
'simple_grid_field34' => array( 'field' => 'referencia_bancaria',
'type' => 'grid_field' ),
'simple_grid_field33' => array( 'field' => 'cat_finanzas_cuentas_de_balance_04_llave',
'type' => 'grid_field' ),
'simple_grid_field1' => array( 'field' => 'fecha_de_compra',
'type' => 'grid_field' ),
'simple_grid_field2' => array( 'field' => 'ano_mes',
'type' => 'grid_field' ),
'simple_grid_field3' => array( 'field' => 'id_prov',
'type' => 'grid_field' ),
'simple_grid_field32' => array( 'field' => 'uuid_cargo_abono_pago',
'type' => 'grid_field' ),
'simple_grid_field31' => array( 'field' => 'cat_usuarios_licencias_id',
'type' => 'grid_field' ),
'simple_grid_field30' => array( 'field' => 'cat_finanzas_cajas_chicas_id',
'type' => 'grid_field' ),
'simple_grid_field29' => array( 'field' => 'cat_finanzas_bancos_cuentas_id',
'type' => 'grid_field' ),
'simple_grid_field28' => array( 'field' => 'consecutivo_id',
'type' => 'grid_field' ),
'simple_grid_field27' => array( 'field' => 'time_stamp',
'type' => 'grid_field' ),
'simple_grid_field26' => array( 'field' => 'imei',
'type' => 'grid_field' ),
'simple_grid_field25' => array( 'field' => 'fecha_de_pago',
'type' => 'grid_field' ),
'simple_grid_field24' => array( 'field' => 'importe_cargo_pago',
'type' => 'grid_field' ),
'simple_grid_field23' => array( 'field' => 'alias_cuenta_de_balance',
'type' => 'grid_field' ),
'simple_grid_field22' => array( 'field' => 'alias_cuenta_de_cargo_pago',
'type' => 'grid_field' ),
'simple_grid_field20' => array( 'field' => 'tr_compras_proveedores_01_cargos_abonos_id',
'type' => 'grid_field' ),
'simple_grid_field19' => array( 'field' => 'uuid_cargo_abono_compra',
'type' => 'grid_field' ),
'simple_grid_field18' => array( 'field' => 'tr_compras_requisiciones_01_uuid',
'type' => 'grid_field' ),
'simple_grid_field17' => array( 'field' => 'capturista',
'type' => 'grid_field' ),
'simple_grid_field16' => array( 'field' => 'saldo',
'type' => 'grid_field' ),
'simple_grid_field15' => array( 'field' => 'total_pagos_cargos',
'type' => 'grid_field' ),
'simple_grid_field14' => array( 'field' => 'total_compras_abonos',
'type' => 'grid_field' ),
'simple_grid_field13' => array( 'field' => 'vigente',
'type' => 'grid_field' ),
'simple_grid_field12' => array( 'field' => 'fecha_de_vencimiento',
'type' => 'grid_field' ),
'simple_grid_field11' => array( 'field' => 'referencia',
'type' => 'grid_field' ),
'simple_grid_field10' => array( 'field' => 'cat_compras_documentos_mu_id',
'type' => 'grid_field' ),
'simple_grid_field9' => array( 'field' => 'uuid_sat',
'type' => 'grid_field' ),
'simple_grid_field8' => array( 'field' => 'orden_de_compra_proveedor',
'type' => 'grid_field' ),
'simple_grid_field7' => array( 'field' => 'importe_abono_compra',
'type' => 'grid_field' ),
'simple_grid_field6' => array( 'field' => 'concepto',
'type' => 'grid_field' ),
'simple_grid_field5' => array( 'field' => 'alias_proveedor',
'type' => 'grid_field' ),
'simple_grid_field4' => array( 'field' => 'cat_compras_proveedores_id',
'type' => 'grid_field' ),
'simple_grid_field35' => array( 'field' => 'observacion_abono_compra',
'type' => 'grid_field' ),
'simple_grid_field36' => array( 'field' => 'cat_compras_estatus_mu_id',
'type' => 'grid_field' ),
'simple_grid_field' => array( 'field' => 'fecha_de_recibo',
'type' => 'grid_field' ),
'simple_grid_field37' => array( 'field' => 'tr_compras_almacenes_01_recibo_lpn_uuid',
'type' => 'grid_field' ),
'simple_grid_field38' => array( 'type' => 'grid_field_label',
'field' => 'fecha_de_compra' ),
'simple_grid_field39' => array( 'type' => 'grid_field_label',
'field' => 'ano_mes' ),
'simple_grid_field40' => array( 'type' => 'grid_field_label',
'field' => 'id_prov' ),
'simple_grid_field41' => array( 'type' => 'grid_field_label',
'field' => 'cat_compras_proveedores_id' ),
'simple_grid_field42' => array( 'type' => 'grid_field_label',
'field' => 'alias_proveedor' ),
'simple_grid_field43' => array( 'type' => 'grid_field_label',
'field' => 'concepto' ),
'simple_grid_field44' => array( 'type' => 'grid_field_label',
'field' => 'importe_abono_compra' ),
'simple_grid_field45' => array( 'type' => 'grid_field_label',
'field' => 'orden_de_compra_proveedor' ),
'simple_grid_field46' => array( 'type' => 'grid_field_label',
'field' => 'uuid_sat' ),
'simple_grid_field47' => array( 'type' => 'grid_field_label',
'field' => 'cat_compras_documentos_mu_id' ),
'simple_grid_field48' => array( 'type' => 'grid_field_label',
'field' => 'referencia' ),
'simple_grid_field49' => array( 'type' => 'grid_field_label',
'field' => 'fecha_de_vencimiento' ),
'simple_grid_field50' => array( 'type' => 'grid_field_label',
'field' => 'vigente' ),
'simple_grid_field51' => array( 'type' => 'grid_field_label',
'field' => 'total_compras_abonos' ),
'simple_grid_field52' => array( 'type' => 'grid_field_label',
'field' => 'total_pagos_cargos' ),
'simple_grid_field53' => array( 'type' => 'grid_field_label',
'field' => 'saldo' ),
'simple_grid_field54' => array( 'type' => 'grid_field_label',
'field' => 'capturista' ),
'simple_grid_field55' => array( 'type' => 'grid_field_label',
'field' => 'tr_compras_requisiciones_01_uuid' ),
'simple_grid_field56' => array( 'type' => 'grid_field_label',
'field' => 'uuid_cargo_abono_compra' ),
'simple_grid_field57' => array( 'type' => 'grid_field_label',
'field' => 'tr_compras_proveedores_01_cargos_abonos_id' ),
'simple_grid_field59' => array( 'type' => 'grid_field_label',
'field' => 'alias_cuenta_de_cargo_pago' ),
'simple_grid_field60' => array( 'type' => 'grid_field_label',
'field' => 'alias_cuenta_de_balance' ),
'simple_grid_field61' => array( 'type' => 'grid_field_label',
'field' => 'importe_cargo_pago' ),
'simple_grid_field62' => array( 'type' => 'grid_field_label',
'field' => 'fecha_de_pago' ),
'simple_grid_field63' => array( 'type' => 'grid_field_label',
'field' => 'imei' ),
'simple_grid_field64' => array( 'type' => 'grid_field_label',
'field' => 'time_stamp' ),
'simple_grid_field65' => array( 'type' => 'grid_field_label',
'field' => 'consecutivo_id' ),
'simple_grid_field66' => array( 'type' => 'grid_field_label',
'field' => 'cat_finanzas_bancos_cuentas_id' ),
'simple_grid_field67' => array( 'type' => 'grid_field_label',
'field' => 'cat_finanzas_cajas_chicas_id' ),
'simple_grid_field68' => array( 'type' => 'grid_field_label',
'field' => 'cat_usuarios_licencias_id' ),
'simple_grid_field69' => array( 'type' => 'grid_field_label',
'field' => 'uuid_cargo_abono_pago' ),
'simple_grid_field70' => array( 'type' => 'grid_field_label',
'field' => 'cat_finanzas_cuentas_de_balance_04_llave' ),
'simple_grid_field71' => array( 'type' => 'grid_field_label',
'field' => 'referencia_bancaria' ),
'simple_grid_field72' => array( 'type' => 'grid_field_label',
'field' => 'observacion_abono_compra' ),
'simple_grid_field73' => array( 'type' => 'grid_field_label',
'field' => 'cat_compras_estatus_mu_id' ),
'simple_grid_field74' => array( 'type' => 'grid_field_label',
'field' => 'fecha_de_recibo' ),
'simple_grid_field75' => array( 'type' => 'grid_field_label',
'field' => 'tr_compras_almacenes_01_recibo_lpn_uuid' ),
'grid_field' => array( 'field' => 'fecha_de_solicitud',
'type' => 'grid_field' ),
'grid_field_label' => array( 'type' => 'grid_field_label',
'field' => 'fecha_de_solicitud' ),
'grid_field1' => array( 'field' => 'fecha_de_requisicion',
'type' => 'grid_field' ),
'grid_field_label1' => array( 'type' => 'grid_field_label',
'field' => 'fecha_de_requisicion' ),
'grid_field2' => array( 'field' => 'saldo1',
'type' => 'grid_field' ),
'grid_field_label2' => array( 'type' => 'grid_field_label',
'field' => 'saldo1' ),
'grid_field3' => array( 'field' => 'cargo_abono',
'type' => 'grid_field' ),
'grid_field_label3' => array( 'type' => 'grid_field_label',
'field' => 'cargo_abono' ),
'grid_field4' => array( 'field' => 'cat_compras_cargo_abono_mu_id',
'type' => 'grid_field' ),
'grid_field_label4' => array( 'type' => 'grid_field_label',
'field' => 'cat_compras_cargo_abono_mu_id' ),
'grid_field5' => array( 'field' => 'llave_unica_cargo_abono_tr_compras_requisiciones_01_uuid_pago',
'type' => 'grid_field' ),
'grid_field_label5' => array( 'type' => 'grid_field_label',
'field' => 'llave_unica_cargo_abono_tr_compras_requisiciones_01_uuid_pago' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>