<?php
			$optionsArray = array( 'details' => array( 'tr_compras_requisiciones_02_productos' => array( 'displayPreview' => 2,
'previewPageId' => '' ) ),
'captcha' => array( 'captcha' => false ),
'fields' => array( 'gridFields' => array( 'fecha_de_captura',
'check_compra_directa',
'cat_holding_03_empresas_unidades_productivas_id',
'cat_trabajadores_altas_id_solicitante',
'capturista_que_autoriza',
'cat_compras_proveedores_id',
'fecha_de_compra',
'importe_abono_compra',
'observaciones',
'cat_finanzas_bancos_cuentas_id',
'cat_compras_estatus_mu_id',
'cat_finanzas_cajas_chicas_id',
'cat_finanzas_cuentas_de_balance_04_llave',
'total_productos',
'uuid_sat',
'vigente',
'fecha_de_pago',
'tr_compras_requisiciones_01_uuid',
'capturista',
'orden_de_compra_proveedor',
'referencia_bancaria',
'observacion_cargo_pago',
'observacion_abono_compra',
'referencia',
'cat_compras_documentos_mu_id' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'updateOnEditFields' => array( 'cat_trabajadores_altas_id_solicitante' ),
'fieldItems' => array( 'fecha_de_captura' => array( 'integrated_edit_field2' ),
'check_compra_directa' => array( 'integrated_edit_field1' ),
'cat_holding_03_empresas_unidades_productivas_id' => array( 'integrated_edit_field4' ),
'cat_trabajadores_altas_id_solicitante' => array( 'integrated_edit_field6' ),
'capturista_que_autoriza' => array( 'integrated_edit_field' ),
'cat_compras_proveedores_id' => array( 'integrated_edit_field3' ),
'fecha_de_compra' => array( 'integrated_edit_field5' ),
'importe_abono_compra' => array( 'integrated_edit_field7' ),
'observaciones' => array( 'integrated_edit_field8' ),
'cat_finanzas_bancos_cuentas_id' => array( 'integrated_edit_field9' ),
'cat_compras_estatus_mu_id' => array( 'integrated_edit_field10' ),
'cat_finanzas_cajas_chicas_id' => array( 'integrated_edit_field11' ),
'cat_finanzas_cuentas_de_balance_04_llave' => array( 'integrated_edit_field13' ),
'total_productos' => array( 'integrated_edit_field14' ),
'uuid_sat' => array( 'integrated_edit_field15' ),
'vigente' => array( 'integrated_edit_field16' ),
'fecha_de_pago' => array( 'integrated_edit_field17' ),
'tr_compras_requisiciones_01_uuid' => array( 'integrated_edit_field18' ),
'capturista' => array( 'integrated_edit_field19' ),
'orden_de_compra_proveedor' => array( 'integrated_edit_field20' ),
'referencia_bancaria' => array( 'integrated_edit_field21' ),
'observacion_cargo_pago' => array( 'integrated_edit_field22' ),
'observacion_abono_compra' => array( 'integrated_edit_field23' ),
'referencia' => array( 'integrated_edit_field12' ),
'cat_compras_documentos_mu_id' => array( 'integrated_edit_field24' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'edit_message' ),
'below-grid' => array( 'edit_save',
'edit_back_list',
'edit_close',
'hamburger' ),
'top' => array( 'edit_header' ),
'grid' => array( 'integrated_edit_field',
'integrated_edit_field2',
'integrated_edit_field4',
'integrated_edit_field6',
'integrated_edit_field8',
'integrated_edit_field10',
'integrated_edit_field14',
'integrated_edit_field16',
'integrated_edit_field18',
'integrated_edit_field19',
'integrated_edit_field1',
'integrated_edit_field5',
'integrated_edit_field17',
'integrated_edit_field3',
'integrated_edit_field24',
'integrated_edit_field12',
'integrated_edit_field7',
'integrated_edit_field20',
'integrated_edit_field21',
'integrated_edit_field23',
'integrated_edit_field22',
'integrated_edit_field15',
'integrated_edit_field9',
'integrated_edit_field11',
'integrated_edit_field13',
'boton_afectar_compra' ) ),
'formXtTags' => array( 'above-grid' => array( 'message_block' ) ),
'itemForms' => array( 'edit_message' => 'above-grid',
'edit_save' => 'below-grid',
'edit_back_list' => 'below-grid',
'edit_close' => 'below-grid',
'hamburger' => 'below-grid',
'edit_header' => 'top',
'integrated_edit_field' => 'grid',
'integrated_edit_field2' => 'grid',
'integrated_edit_field4' => 'grid',
'integrated_edit_field6' => 'grid',
'integrated_edit_field8' => 'grid',
'integrated_edit_field10' => 'grid',
'integrated_edit_field14' => 'grid',
'integrated_edit_field16' => 'grid',
'integrated_edit_field18' => 'grid',
'integrated_edit_field19' => 'grid',
'integrated_edit_field1' => 'grid',
'integrated_edit_field5' => 'grid',
'integrated_edit_field17' => 'grid',
'integrated_edit_field3' => 'grid',
'integrated_edit_field24' => 'grid',
'integrated_edit_field12' => 'grid',
'integrated_edit_field7' => 'grid',
'integrated_edit_field20' => 'grid',
'integrated_edit_field21' => 'grid',
'integrated_edit_field23' => 'grid',
'integrated_edit_field22' => 'grid',
'integrated_edit_field15' => 'grid',
'integrated_edit_field9' => 'grid',
'integrated_edit_field11' => 'grid',
'integrated_edit_field13' => 'grid',
'boton_afectar_compra' => 'grid' ),
'itemLocations' => array( 'integrated_edit_field' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field2' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field4' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field6' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field8' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field10' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field14' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field16' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field18' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field19' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field1' => array( 'location' => 'grid',
'cellId' => 'c' ),
'integrated_edit_field5' => array( 'location' => 'grid',
'cellId' => 'c' ),
'integrated_edit_field17' => array( 'location' => 'grid',
'cellId' => 'c' ),
'integrated_edit_field3' => array( 'location' => 'grid',
'cellId' => 'c' ),
'integrated_edit_field24' => array( 'location' => 'grid',
'cellId' => 'c' ),
'integrated_edit_field12' => array( 'location' => 'grid',
'cellId' => 'c' ),
'integrated_edit_field7' => array( 'location' => 'grid',
'cellId' => 'c' ),
'integrated_edit_field20' => array( 'location' => 'grid',
'cellId' => 'c' ),
'integrated_edit_field21' => array( 'location' => 'grid',
'cellId' => 'c' ),
'integrated_edit_field23' => array( 'location' => 'grid',
'cellId' => 'c' ),
'integrated_edit_field22' => array( 'location' => 'grid',
'cellId' => 'c' ),
'integrated_edit_field15' => array( 'location' => 'grid',
'cellId' => 'c' ),
'integrated_edit_field9' => array( 'location' => 'grid',
'cellId' => 'c' ),
'integrated_edit_field11' => array( 'location' => 'grid',
'cellId' => 'c' ),
'integrated_edit_field13' => array( 'location' => 'grid',
'cellId' => 'c' ),
'boton_afectar_compra' => array( 'location' => 'grid',
'cellId' => 'c' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'edit_header' => array( 'edit_header' ),
'hamburger' => array( 'hamburger' ),
'edit_reset' => array( 'edit_reset' ),
'edit_message' => array( 'edit_message' ),
'edit_save' => array( 'edit_save' ),
'edit_back_list' => array( 'edit_back_list' ),
'edit_close' => array( 'edit_close' ),
'integrated_edit_field' => array( 'integrated_edit_field2',
'integrated_edit_field1',
'integrated_edit_field4',
'integrated_edit_field6',
'integrated_edit_field',
'integrated_edit_field3',
'integrated_edit_field5',
'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field13',
'integrated_edit_field14',
'integrated_edit_field15',
'integrated_edit_field16',
'integrated_edit_field17',
'integrated_edit_field18',
'integrated_edit_field19',
'integrated_edit_field20',
'integrated_edit_field21',
'integrated_edit_field22',
'integrated_edit_field23',
'integrated_edit_field12',
'integrated_edit_field24' ),
'custom_button' => array( 'boton_afectar_compra' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field',
'integrated_edit_field2',
'integrated_edit_field4',
'integrated_edit_field6',
'integrated_edit_field8',
'integrated_edit_field10',
'integrated_edit_field14',
'integrated_edit_field16',
'integrated_edit_field18',
'integrated_edit_field19' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ) ),
'width' => 2,
'height' => 1 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => true,
'customButtons' => array( 'insert_COMPRA_DIRECTA_tr_compras_proveedores_01_cargos_abonos' ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'edit',
'breadcrumb' => false,
'nextPrev' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array( 'insert_COMPRA_DIRECTA_tr_compras_proveedores_01_cargos_abonos' ) ),
'edit' => array( 'updateSelected' => false ) );
			$pageArray = array( 'id' => 'edit',
'type' => 'edit',
'layoutId' => 'nomenu',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'edit-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_message' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'edit-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1',
'colspan' => 1 ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_save',
'edit_back_list',
'edit_close',
'hamburger' ),
'align' => 'center' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'edit-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3' ),
array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field',
'integrated_edit_field2',
'integrated_edit_field4',
'integrated_edit_field6',
'integrated_edit_field8',
'integrated_edit_field10',
'integrated_edit_field14',
'integrated_edit_field16',
'integrated_edit_field18',
'integrated_edit_field19' ) ),
'c' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field1',
'integrated_edit_field5',
'integrated_edit_field17',
'integrated_edit_field3',
'integrated_edit_field24',
'integrated_edit_field12',
'integrated_edit_field7',
'integrated_edit_field20',
'integrated_edit_field21',
'integrated_edit_field23',
'integrated_edit_field22',
'integrated_edit_field15',
'integrated_edit_field9',
'integrated_edit_field11',
'integrated_edit_field13',
'boton_afectar_compra' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 2,
'inlineLabels' => true,
'separateLabels' => false ) ),
'items' => array( 'edit_header' => array( 'type' => 'edit_header' ),
'hamburger' => array( 'type' => 'hamburger',
'items' => array( 'edit_reset' ) ),
'edit_reset' => array( 'type' => 'edit_reset' ),
'edit_message' => array( 'type' => 'edit_message' ),
'edit_save' => array( 'type' => 'edit_save' ),
'edit_back_list' => array( 'type' => 'edit_back_list' ),
'edit_close' => array( 'type' => 'edit_close' ),
'integrated_edit_field2' => array( 'field' => 'fecha_de_captura',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field1' => array( 'field' => 'check_compra_directa',
'type' => 'integrated_edit_field',
'orientation' => 1,
'updateOnEdit' => false ),
'integrated_edit_field4' => array( 'field' => 'cat_holding_03_empresas_unidades_productivas_id',
'type' => 'integrated_edit_field',
'orientation' => 1,
'updateOnEdit' => false ),
'integrated_edit_field6' => array( 'field' => 'cat_trabajadores_altas_id_solicitante',
'type' => 'integrated_edit_field',
'orientation' => 1,
'updateOnEdit' => true ),
'integrated_edit_field' => array( 'field' => 'capturista_que_autoriza',
'type' => 'integrated_edit_field',
'orientation' => 1,
'updateOnEdit' => false ),
'integrated_edit_field3' => array( 'field' => 'cat_compras_proveedores_id',
'type' => 'integrated_edit_field',
'orientation' => 1,
'updateOnEdit' => false ),
'integrated_edit_field5' => array( 'field' => 'fecha_de_compra',
'type' => 'integrated_edit_field',
'orientation' => 1,
'updateOnEdit' => false ),
'integrated_edit_field7' => array( 'field' => 'importe_abono_compra',
'type' => 'integrated_edit_field',
'orientation' => 1,
'updateOnEdit' => false ),
'integrated_edit_field8' => array( 'field' => 'observaciones',
'type' => 'integrated_edit_field',
'orientation' => 1,
'updateOnEdit' => false ),
'integrated_edit_field9' => array( 'field' => 'cat_finanzas_bancos_cuentas_id',
'type' => 'integrated_edit_field',
'orientation' => 1,
'updateOnEdit' => false ),
'integrated_edit_field10' => array( 'field' => 'cat_compras_estatus_mu_id',
'type' => 'integrated_edit_field',
'orientation' => 1,
'updateOnEdit' => false ),
'integrated_edit_field11' => array( 'field' => 'cat_finanzas_cajas_chicas_id',
'type' => 'integrated_edit_field',
'orientation' => 1,
'updateOnEdit' => false ),
'integrated_edit_field13' => array( 'field' => 'cat_finanzas_cuentas_de_balance_04_llave',
'type' => 'integrated_edit_field',
'orientation' => 1,
'updateOnEdit' => false ),
'integrated_edit_field14' => array( 'field' => 'total_productos',
'type' => 'integrated_edit_field',
'orientation' => 1,
'updateOnEdit' => false,
'label' => array( 'field' => 'total_productos',
'table' => 'tr_compras_requisiciones_01',
'type' => 3 ) ),
'integrated_edit_field15' => array( 'field' => 'uuid_sat',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field16' => array( 'field' => 'vigente',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field17' => array( 'field' => 'fecha_de_pago',
'type' => 'integrated_edit_field',
'orientation' => 1,
'updateOnEdit' => false ),
'integrated_edit_field18' => array( 'field' => 'tr_compras_requisiciones_01_uuid',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field19' => array( 'field' => 'capturista',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field20' => array( 'field' => 'orden_de_compra_proveedor',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field21' => array( 'field' => 'referencia_bancaria',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field22' => array( 'field' => 'observacion_cargo_pago',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field23' => array( 'field' => 'observacion_abono_compra',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field12' => array( 'field' => 'referencia',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field24' => array( 'field' => 'cat_compras_documentos_mu_id',
'type' => 'integrated_edit_field',
'orientation' => 1,
'updateOnEdit' => false ),
'boton_afectar_compra' => array( 'eventId' => 'insert_COMPRA_DIRECTA_tr_compras_proveedores_01_cargos_abonos',
'label' => array( 'type' => 0,
'text' => 'Afecta compra directa' ),
'type' => 'custom_button',
'buttonStyle' => 'warning' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>