<?php
			$optionsArray = array( 'list' => array( 'inlineAdd' => true,
'detailsAdd' => true,
'inlineEdit' => true,
'spreadsheetMode' => false,
'reorderRows' => false,
'addToBottom' => false,
'delete' => false,
'updateSelected' => false,
'addInPopup' => null,
'editInPopup' => null,
'viewInPopup' => null,
'clickSort' => true,
'sortDropdown' => false,
'showHideFields' => false,
'reorderFields' => false,
'fieldFilter' => false,
'hideNumberOfRecords' => false ),
'allDetails' => array( 'linkType' => 0 ),
'details' => array( 'tr_compras_proveedores_01_cargos_abonos_pagos' => array( 'displayPreview' => 1,
'previewPageId' => 'list',
'showCount' => true,
'hideEmptyChild' => false,
'hideEmptyPreview' => false,
'showProceedLink' => true,
'printDetails' => true ),
'tr_compras_proveedores_02_cargos_abonos_centros_de_costos' => array( 'displayPreview' => 1,
'previewPageId' => 'list',
'showCount' => false,
'hideEmptyChild' => false,
'hideEmptyPreview' => false,
'showProceedLink' => true,
'printDetails' => true ),
'tr_compras_proveedores_02_cargos_abonos_movimientos' => array( 'displayPreview' => 1,
'previewPageId' => 'list',
'showCount' => false,
'badgeColor' => '',
'hideEmptyChild' => false,
'hideEmptyPreview' => false,
'showProceedLink' => true,
'printDetails' => true ),
'tr_compras_requisiciones_02_productos' => array( 'displayPreview' => 2,
'previewPageId' => '',
'showCount' => false,
'hideEmptyChild' => false,
'hideEmptyPreview' => null,
'showProceedLink' => null,
'printDetails' => true ),
'tr_compras_requisiciones_02_productos_compras' => array( 'displayPreview' => 1,
'previewPageId' => 'list',
'showCount' => false,
'badgeColor' => '',
'hideEmptyChild' => false,
'hideEmptyPreview' => false,
'showProceedLink' => true,
'printDetails' => true ),
'tr_compras_facturas_sat_02' => array( 'displayPreview' => 1,
'previewPageId' => 'list',
'showCount' => false,
'badgeColor' => '',
'hideEmptyChild' => false,
'hideEmptyPreview' => false,
'showProceedLink' => true,
'printDetails' => true ) ),
'listSearch' => array( 'alwaysOnPanelFields' => array(  ),
'searchPanel' => true,
'fixedSearchPanel' => false,
'simpleSearchOptions' => true,
'searchSaving' => false ),
'totals' => array( 'tr_compras_proveedores_01_cargos_abonos_id' => array( 'totalsType' => '' ),
'id_prov' => array( 'totalsType' => '' ),
'cat_compras_proveedores_id' => array( 'totalsType' => '' ),
'alias_proveedor' => array( 'totalsType' => '' ),
'fecha_de_compra' => array( 'totalsType' => '' ),
'ano_mes' => array( 'totalsType' => '' ),
'referencia' => array( 'totalsType' => '' ),
'importe_abono_compra' => array( 'totalsType' => 'TOTAL' ),
'importe_cargo_pago' => array( 'totalsType' => '' ),
'fecha_de_pago' => array( 'totalsType' => '' ),
'concepto' => array( 'totalsType' => '' ),
'cat_compras_documentos_mu_id' => array( 'totalsType' => '' ),
'capturista' => array( 'totalsType' => '' ),
'vigente' => array( 'totalsType' => '' ),
'cat_finanzas_cuentas_de_balance_03_mu_id' => array( 'totalsType' => '' ),
'cat_finanzas_cuentas_de_balance_04_llave' => array( 'totalsType' => '' ),
'alias_cuenta_de_balance' => array( 'totalsType' => '' ),
'imei' => array( 'totalsType' => '' ),
'uuid_sat' => array( 'totalsType' => '' ),
'time_stamp' => array( 'totalsType' => '' ),
'consecutivo_id' => array( 'totalsType' => '' ),
'cat_finanzas_bancos_cuentas_id' => array( 'totalsType' => '' ),
'cat_finanzas_cajas_chicas_id' => array( 'totalsType' => '' ),
'uuid_cargo_abono_compra' => array( 'totalsType' => '' ),
'uuid_cargo_abono_pago' => array( 'totalsType' => '' ),
'cat_usuarios_licencias_id' => array( 'totalsType' => '' ),
'total_compras_abonos' => array( 'totalsType' => '' ),
'total_pagos_cargos' => array( 'totalsType' => '' ),
'saldo' => array( 'totalsType' => '' ),
'alias_cuenta_de_abono_compra' => array( 'totalsType' => '' ),
'alias_cuenta_de_cargo_pago' => array( 'totalsType' => '' ),
'tr_compras_requisiciones_01_uuid' => array( 'totalsType' => '' ),
'tr_compras_requisiciones_01_uuid_pago' => array( 'totalsType' => '' ),
'orden_de_compra_proveedor' => array( 'totalsType' => '' ),
'referencia_bancaria' => array( 'totalsType' => '' ),
'observacion_abono_compra' => array( 'totalsType' => '' ),
'cat_compras_estatus_mu_id' => array( 'totalsType' => '' ),
'fecha_de_recibo' => array( 'totalsType' => '' ),
'tr_compras_almacenes_01_recibo_lpn_uuid' => array( 'totalsType' => '' ),
'fecha_de_solicitud' => array( 'totalsType' => '' ),
'fecha_de_requisicion' => array( 'totalsType' => '' ),
'fecha_de_vencimiento' => array( 'totalsType' => '' ),
'saldo1' => array( 'totalsType' => '' ),
'cargo_abono' => array( 'totalsType' => '' ),
'cat_compras_cargo_abono_mu_id' => array( 'totalsType' => '' ),
'llave_unica_cargo_abono_tr_compras_requisiciones_01_uuid_pago' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'cat_compras_estatus_mu_id',
'fecha_de_compra',
'id_prov',
'cat_compras_proveedores_id',
'concepto',
'importe_abono_compra',
'saldo1',
'tr_compras_proveedores_01_cargos_abonos_id',
'cat_compras_documentos_mu_id',
'uuid_sat',
'fecha_de_solicitud',
'fecha_de_requisicion',
'fecha_de_vencimiento',
'orden_de_compra_proveedor',
'observacion_abono_compra',
'total_compras_abonos',
'total_pagos_cargos',
'cat_finanzas_cuentas_de_balance_04_llave',
'saldo',
'tr_compras_requisiciones_01_uuid',
'uuid_cargo_abono_compra',
'ano_mes',
'cargo_abono',
'capturista',
'vigente',
'cat_compras_cargo_abono_mu_id',
'llave_unica_cargo_abono_tr_compras_requisiciones_01_uuid_pago',
'alias_proveedor',
'referencia' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array( 'cat_compras_estatus_mu_id',
'orden_de_compra_proveedor',
'cat_finanzas_cuentas_de_balance_04_llave',
'uuid_cargo_abono_compra',
'importe_abono_compra',
'fecha_de_compra',
'uuid_sat',
'concepto',
'ano_mes',
'id_prov',
'cat_compras_proveedores_id' ),
'filterFields' => array(  ),
'inlineAddFields' => array( 'cat_compras_proveedores_id',
'fecha_de_compra',
'importe_abono_compra',
'fecha_de_vencimiento',
'concepto',
'cat_compras_documentos_mu_id',
'capturista',
'uuid_cargo_abono_compra',
'orden_de_compra_proveedor',
'observacion_abono_compra',
'fecha_de_solicitud',
'fecha_de_requisicion',
'vigente',
'cat_compras_cargo_abono_mu_id',
'llave_unica_cargo_abono_tr_compras_requisiciones_01_uuid_pago',
'cat_finanzas_cuentas_de_balance_04_llave' ),
'inlineEditFields' => array( 'cat_compras_proveedores_id',
'fecha_de_compra',
'importe_abono_compra',
'fecha_de_vencimiento',
'concepto',
'cat_compras_documentos_mu_id',
'capturista',
'uuid_cargo_abono_compra',
'orden_de_compra_proveedor',
'observacion_abono_compra',
'fecha_de_solicitud',
'fecha_de_requisicion',
'vigente',
'cat_finanzas_cuentas_de_balance_04_llave' ),
'fieldItems' => array( 'id_prov' => array( 'simple_grid_field17',
'simple_grid_field28' ),
'total_pagos_cargos' => array( 'simple_grid_field25',
'simple_grid_field41' ),
'cat_compras_proveedores_id' => array( 'simple_grid_field2',
'simple_grid_field29' ),
'fecha_de_compra' => array( 'simple_grid_field4',
'simple_grid_field24' ),
'importe_abono_compra' => array( 'simple_grid_field6',
'simple_grid_field31',
'simple_grid_field32' ),
'fecha_de_vencimiento' => array( 'simple_grid_field9',
'simple_grid_field36',
'grid_field2' ),
'concepto' => array( 'simple_grid_field10',
'simple_grid_field30' ),
'cat_compras_documentos_mu_id' => array( 'simple_grid_field11',
'simple_grid_field34' ),
'capturista' => array( 'simple_grid_field12',
'simple_grid_field43' ),
'uuid_cargo_abono_compra' => array( 'simple_grid_field23',
'simple_grid_field45' ),
'saldo' => array( 'simple_grid_field26',
'simple_grid_field42' ),
'total_compras_abonos' => array( 'simple_grid_field20',
'simple_grid_field40' ),
'ano_mes' => array( 'simple_grid_field',
'simple_grid_field27' ),
'tr_compras_proveedores_01_cargos_abonos_id' => array( 'simple_grid_field7',
'simple_grid_field18' ),
'tr_compras_requisiciones_01_uuid' => array( 'simple_grid_field8',
'simple_grid_field44' ),
'orden_de_compra_proveedor' => array( 'simple_grid_field15',
'simple_grid_field33' ),
'observacion_abono_compra' => array( 'simple_grid_field1',
'simple_grid_field37' ),
'cat_compras_estatus_mu_id' => array( 'simple_grid_field3',
'simple_grid_field22' ),
'fecha_de_solicitud' => array( 'simple_grid_field16',
'simple_grid_field21' ),
'fecha_de_requisicion' => array( 'grid_field',
'grid_field_label' ),
'cargo_abono' => array( 'grid_field1',
'grid_field_label1' ),
'saldo1' => array( 'grid_field3',
'grid_field_label2' ),
'uuid_sat' => array( 'grid_field4',
'grid_field_label3' ),
'vigente' => array( 'grid_field5',
'grid_field_label4' ),
'cat_compras_cargo_abono_mu_id' => array( 'grid_field6',
'grid_field_label5' ),
'llave_unica_cargo_abono_tr_compras_requisiciones_01_uuid_pago' => array( 'grid_field7',
'grid_field_label6' ),
'cat_finanzas_cuentas_de_balance_04_llave' => array( 'grid_field8',
'grid_field_label7' ),
'alias_proveedor' => array( 'grid_field9',
'grid_field_label8' ),
'referencia' => array( 'grid_field10',
'grid_field_label9' ) ),
'hideEmptyFields' => array(  ),
'fieldFilterFields' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'inline_add',
'inline_save_all',
'inline_cancel_all',
'details_found',
'page_size',
'print_panel',
'custom_button',
'text',
'inline_save_all1' ),
'below-grid' => array( 'pagination' ),
'left' => array( 'logo',
'expand_button',
'menu',
'search_panel' ),
'supertop' => array( 'expand_menu_button',
'collapse_button',
'breadcrumb',
'simple_search_field',
'simple_search_option',
'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'grid' => array( 'simple_grid_field22',
'simple_grid_field3',
'simple_grid_field24',
'simple_grid_field4',
'simple_grid_field28',
'simple_grid_field17',
'simple_grid_field29',
'simple_grid_field2',
'simple_grid_field30',
'simple_grid_field10',
'simple_grid_field31',
'simple_grid_field6',
'simple_grid_field32',
'grid_field_label2',
'grid_field3',
'simple_grid_field18',
'simple_grid_field7',
'simple_grid_field34',
'simple_grid_field11',
'grid_field_label3',
'grid_field4',
'simple_grid_field21',
'simple_grid_field16',
'grid_field_label',
'grid_field',
'simple_grid_field36',
'grid_field2',
'simple_grid_field33',
'simple_grid_field15',
'simple_grid_field37',
'simple_grid_field1',
'simple_grid_field40',
'simple_grid_field20',
'simple_grid_field41',
'simple_grid_field25',
'grid_field_label7',
'grid_field8',
'details_preview',
'details_preview4',
'details_preview1',
'details_preview2',
'details_preview3',
'grid_checkbox_head',
'grid_checkbox',
'grid_inline_edit',
'grid_inline_save',
'grid_inline_cancel',
'grid_alldetails_link',
'grid_details_link',
'grid_details_link1',
'custom_button1',
'simple_grid_field27',
'simple_grid_field',
'simple_grid_field45',
'simple_grid_field23',
'grid_field_label1',
'grid_field1',
'simple_grid_field43',
'simple_grid_field12',
'simple_grid_field44',
'simple_grid_field8',
'grid_field_label4',
'grid_field5',
'grid_field_label5',
'grid_field6',
'grid_field_label6',
'grid_field7',
'inline_save_all2',
'grid_field_label8',
'grid_field9',
'grid_field_label9',
'grid_field10',
'simple_grid_field42',
'simple_grid_field26',
'custom_button2' ),
'top' => array(  ) ),
'formXtTags' => array( 'below-grid' => array( 'pagination' ),
'top' => array(  ) ),
'itemForms' => array( 'inline_add' => 'above-grid',
'inline_save_all' => 'above-grid',
'inline_cancel_all' => 'above-grid',
'details_found' => 'above-grid',
'page_size' => 'above-grid',
'print_panel' => 'above-grid',
'custom_button' => 'above-grid',
'text' => 'above-grid',
'inline_save_all1' => 'above-grid',
'pagination' => 'below-grid',
'logo' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'search_panel' => 'left',
'expand_menu_button' => 'supertop',
'collapse_button' => 'supertop',
'breadcrumb' => 'supertop',
'simple_search_field' => 'supertop',
'simple_search_option' => 'supertop',
'simple_search' => 'supertop',
'list_options' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'simple_grid_field22' => 'grid',
'simple_grid_field3' => 'grid',
'simple_grid_field24' => 'grid',
'simple_grid_field4' => 'grid',
'simple_grid_field28' => 'grid',
'simple_grid_field17' => 'grid',
'simple_grid_field29' => 'grid',
'simple_grid_field2' => 'grid',
'simple_grid_field30' => 'grid',
'simple_grid_field10' => 'grid',
'simple_grid_field31' => 'grid',
'simple_grid_field6' => 'grid',
'simple_grid_field32' => 'grid',
'grid_field_label2' => 'grid',
'grid_field3' => 'grid',
'simple_grid_field18' => 'grid',
'simple_grid_field7' => 'grid',
'simple_grid_field34' => 'grid',
'simple_grid_field11' => 'grid',
'grid_field_label3' => 'grid',
'grid_field4' => 'grid',
'simple_grid_field21' => 'grid',
'simple_grid_field16' => 'grid',
'grid_field_label' => 'grid',
'grid_field' => 'grid',
'simple_grid_field36' => 'grid',
'grid_field2' => 'grid',
'simple_grid_field33' => 'grid',
'simple_grid_field15' => 'grid',
'simple_grid_field37' => 'grid',
'simple_grid_field1' => 'grid',
'simple_grid_field40' => 'grid',
'simple_grid_field20' => 'grid',
'simple_grid_field41' => 'grid',
'simple_grid_field25' => 'grid',
'grid_field_label7' => 'grid',
'grid_field8' => 'grid',
'details_preview' => 'grid',
'details_preview4' => 'grid',
'details_preview1' => 'grid',
'details_preview2' => 'grid',
'details_preview3' => 'grid',
'grid_checkbox_head' => 'grid',
'grid_checkbox' => 'grid',
'grid_inline_edit' => 'grid',
'grid_inline_save' => 'grid',
'grid_inline_cancel' => 'grid',
'grid_alldetails_link' => 'grid',
'grid_details_link' => 'grid',
'grid_details_link1' => 'grid',
'custom_button1' => 'grid',
'simple_grid_field27' => 'grid',
'simple_grid_field' => 'grid',
'simple_grid_field45' => 'grid',
'simple_grid_field23' => 'grid',
'grid_field_label1' => 'grid',
'grid_field1' => 'grid',
'simple_grid_field43' => 'grid',
'simple_grid_field12' => 'grid',
'simple_grid_field44' => 'grid',
'simple_grid_field8' => 'grid',
'grid_field_label4' => 'grid',
'grid_field5' => 'grid',
'grid_field_label5' => 'grid',
'grid_field6' => 'grid',
'grid_field_label6' => 'grid',
'grid_field7' => 'grid',
'inline_save_all2' => 'grid',
'grid_field_label8' => 'grid',
'grid_field9' => 'grid',
'grid_field_label9' => 'grid',
'grid_field10' => 'grid',
'simple_grid_field42' => 'grid',
'simple_grid_field26' => 'grid',
'custom_button2' => 'grid' ),
'itemLocations' => array( 'simple_grid_field22' => array( 'location' => 'grid',
'cellId' => 'headcell_field' ),
'simple_grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'simple_grid_field24' => array( 'location' => 'grid',
'cellId' => 'headcell_field1' ),
'simple_grid_field4' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'simple_grid_field28' => array( 'location' => 'grid',
'cellId' => 'headcell_field2' ),
'simple_grid_field17' => array( 'location' => 'grid',
'cellId' => 'cell_field2' ),
'simple_grid_field29' => array( 'location' => 'grid',
'cellId' => 'headcell_field5' ),
'simple_grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field5' ),
'simple_grid_field30' => array( 'location' => 'grid',
'cellId' => 'headcell_field6' ),
'simple_grid_field10' => array( 'location' => 'grid',
'cellId' => 'cell_field6' ),
'simple_grid_field31' => array( 'location' => 'grid',
'cellId' => 'headcell_field7' ),
'simple_grid_field6' => array( 'location' => 'grid',
'cellId' => 'cell_field7' ),
'simple_grid_field32' => array( 'location' => 'grid',
'cellId' => 'footcell_field7' ),
'grid_field_label2' => array( 'location' => 'grid',
'cellId' => 'headcell_field8' ),
'grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_field8' ),
'simple_grid_field18' => array( 'location' => 'grid',
'cellId' => 'headcell_field9' ),
'simple_grid_field7' => array( 'location' => 'grid',
'cellId' => 'cell_field9' ),
'simple_grid_field34' => array( 'location' => 'grid',
'cellId' => 'headcell_field11' ),
'simple_grid_field11' => array( 'location' => 'grid',
'cellId' => 'cell_field11' ),
'grid_field_label3' => array( 'location' => 'grid',
'cellId' => 'headcell_field12' ),
'grid_field4' => array( 'location' => 'grid',
'cellId' => 'cell_field12' ),
'simple_grid_field21' => array( 'location' => 'grid',
'cellId' => 'headcell_field13' ),
'simple_grid_field16' => array( 'location' => 'grid',
'cellId' => 'cell_field13' ),
'grid_field_label' => array( 'location' => 'grid',
'cellId' => 'headcell_field14' ),
'grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field14' ),
'simple_grid_field36' => array( 'location' => 'grid',
'cellId' => 'headcell_field15' ),
'grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field15' ),
'simple_grid_field33' => array( 'location' => 'grid',
'cellId' => 'headcell_field16' ),
'simple_grid_field15' => array( 'location' => 'grid',
'cellId' => 'cell_field16' ),
'simple_grid_field37' => array( 'location' => 'grid',
'cellId' => 'headcell_field18' ),
'simple_grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field18' ),
'simple_grid_field40' => array( 'location' => 'grid',
'cellId' => 'headcell_field19' ),
'simple_grid_field20' => array( 'location' => 'grid',
'cellId' => 'cell_field19' ),
'simple_grid_field41' => array( 'location' => 'grid',
'cellId' => 'headcell_field20' ),
'simple_grid_field25' => array( 'location' => 'grid',
'cellId' => 'cell_field20' ),
'grid_field_label7' => array( 'location' => 'grid',
'cellId' => 'headcell_field22' ),
'grid_field8' => array( 'location' => 'grid',
'cellId' => 'cell_field22' ),
'details_preview' => array( 'location' => 'grid',
'cellId' => 'cell_dpreview' ),
'details_preview4' => array( 'location' => 'grid',
'cellId' => 'cell_dpreview' ),
'details_preview1' => array( 'location' => 'grid',
'cellId' => 'cell_dpreview' ),
'details_preview2' => array( 'location' => 'grid',
'cellId' => 'cell_dpreview' ),
'details_preview3' => array( 'location' => 'grid',
'cellId' => 'cell_dpreview' ),
'grid_checkbox_head' => array( 'location' => 'grid',
'cellId' => 'headcell_checkbox' ),
'grid_checkbox' => array( 'location' => 'grid',
'cellId' => 'cell_checkbox' ),
'grid_inline_edit' => array( 'location' => 'grid',
'cellId' => 'cell_icons' ),
'grid_inline_save' => array( 'location' => 'grid',
'cellId' => 'cell_icons' ),
'grid_inline_cancel' => array( 'location' => 'grid',
'cellId' => 'cell_icons' ),
'grid_alldetails_link' => array( 'location' => 'grid',
'cellId' => 'cell_details' ),
'grid_details_link' => array( 'location' => 'grid',
'cellId' => 'cell_details' ),
'grid_details_link1' => array( 'location' => 'grid',
'cellId' => 'cell_details' ),
'custom_button1' => array( 'location' => 'grid',
'cellId' => 'cell_icons2' ),
'simple_grid_field27' => array( 'location' => 'grid',
'cellId' => 'headcell_field23' ),
'simple_grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field23' ),
'simple_grid_field45' => array( 'location' => 'grid',
'cellId' => 'headcell_field24' ),
'simple_grid_field23' => array( 'location' => 'grid',
'cellId' => 'headcell_field25' ),
'grid_field_label1' => array( 'location' => 'grid',
'cellId' => 'headcell_field28' ),
'grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field26' ),
'simple_grid_field43' => array( 'location' => 'grid',
'cellId' => 'headcell_field10' ),
'simple_grid_field12' => array( 'location' => 'grid',
'cellId' => 'cell_field10' ),
'simple_grid_field44' => array( 'location' => 'grid',
'cellId' => 'headcell_field29' ),
'simple_grid_field8' => array( 'location' => 'grid',
'cellId' => 'headcell_field30' ),
'grid_field_label4' => array( 'location' => 'grid',
'cellId' => 'headcell_field3' ),
'grid_field5' => array( 'location' => 'grid',
'cellId' => 'cell_field3' ),
'grid_field_label5' => array( 'location' => 'grid',
'cellId' => 'headcell_field4' ),
'grid_field6' => array( 'location' => 'grid',
'cellId' => 'cell_field21' ),
'grid_field_label6' => array( 'location' => 'grid',
'cellId' => 'headcell_field17' ),
'grid_field7' => array( 'location' => 'grid',
'cellId' => 'cell_field28' ),
'inline_save_all2' => array( 'location' => 'grid',
'cellId' => 'cell_field67' ),
'grid_field_label8' => array( 'location' => 'grid',
'cellId' => 'headcell_field33' ),
'grid_field9' => array( 'location' => 'grid',
'cellId' => 'cell_field68' ),
'grid_field_label9' => array( 'location' => 'grid',
'cellId' => 'headcell_field35' ),
'grid_field10' => array( 'location' => 'grid',
'cellId' => 'cell_field70' ),
'simple_grid_field42' => array( 'location' => 'grid',
'cellId' => 'headcell_field38' ),
'simple_grid_field26' => array( 'location' => 'grid',
'cellId' => 'headcell_field39' ),
'custom_button2' => array( 'location' => 'grid',
'cellId' => 'headcell_field44' ) ),
'itemVisiblity' => array( 'breadcrumb' => 5,
'expand_menu_button' => 2,
'print_panel' => 5,
'expand_button' => 5 ) ),
'itemsByType' => array( 'page_size' => array( 'page_size' ),
'details_found' => array( 'details_found' ),
'breadcrumb' => array( 'breadcrumb' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'simple_search' => array( 'simple_search' ),
'pagination' => array( 'pagination' ),
'grid_checkbox' => array( 'grid_checkbox' ),
'grid_checkbox_head' => array( 'grid_checkbox_head' ),
'search_panel' => array( 'search_panel' ),
'list_options' => array( 'list_options' ),
'show_search_panel' => array( 'show_search_panel' ),
'hide_search_panel' => array( 'hide_search_panel' ),
'grid_field' => array( 'simple_grid_field17',
'simple_grid_field25',
'simple_grid_field2',
'simple_grid_field4',
'simple_grid_field6',
'simple_grid_field9',
'simple_grid_field10',
'simple_grid_field11',
'simple_grid_field12',
'simple_grid_field23',
'simple_grid_field26',
'simple_grid_field20',
'simple_grid_field',
'simple_grid_field7',
'simple_grid_field8',
'simple_grid_field15',
'simple_grid_field1',
'simple_grid_field3',
'simple_grid_field16',
'grid_field',
'grid_field1',
'grid_field2',
'grid_field3',
'grid_field4',
'grid_field5',
'grid_field6',
'grid_field7',
'grid_field8',
'grid_field9',
'grid_field10' ),
'search_panel_field' => array( 'search_panel_field',
'search_panel_field3',
'search_panel_field1',
'search_panel_field2',
'search_panel_field15',
'search_panel_field4',
'search_panel_field5',
'search_panel_field6',
'search_panel_field7',
'search_panel_field8',
'search_panel_field9' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'userinfo_link' => array( 'userinfo_link' ),
'logout_link' => array( 'logout_link' ),
'adminarea_link' => array( 'adminarea_link' ),
'changepassword_link' => array( 'changepassword_link' ),
'expand_menu_button' => array( 'expand_menu_button' ),
'collapse_button' => array( 'collapse_button' ),
'grid_details_link' => array( 'grid_details_link',
'grid_details_link1',
'grid_details_link2' ),
'grid_alldetails_link' => array( 'grid_alldetails_link' ),
'details_preview' => array( 'details_preview',
'details_preview1',
'details_preview2',
'details_preview4',
'details_preview3' ),
'-' => array( '-',
'-1',
'-2',
'-3',
'-4' ),
'import' => array( 'import' ),
'print_details' => array( 'print_details' ),
'print_panel' => array( 'print_panel' ),
'advsearch_link' => array( 'advsearch_link' ),
'inline_add' => array( 'inline_add' ),
'grid_inline_cancel' => array( 'grid_inline_cancel' ),
'grid_inline_save' => array( 'grid_inline_save' ),
'inline_save_all' => array( 'inline_save_all',
'inline_save_all1',
'inline_save_all2' ),
'inline_cancel_all' => array( 'inline_cancel_all' ),
'edit_selected' => array( 'edit_selected' ),
'grid_inline_edit' => array( 'grid_inline_edit' ),
'custom_button' => array( 'custom_button',
'custom_button1',
'custom_button2' ),
'text' => array( 'text' ),
'grid_field_label' => array( 'simple_grid_field18',
'simple_grid_field21',
'simple_grid_field22',
'simple_grid_field24',
'simple_grid_field27',
'simple_grid_field28',
'simple_grid_field29',
'simple_grid_field30',
'simple_grid_field31',
'simple_grid_field33',
'simple_grid_field34',
'simple_grid_field36',
'simple_grid_field37',
'simple_grid_field40',
'simple_grid_field41',
'simple_grid_field42',
'simple_grid_field43',
'simple_grid_field44',
'simple_grid_field45',
'grid_field_label',
'grid_field_label1',
'grid_field_label2',
'grid_field_label3',
'grid_field_label4',
'grid_field_label5',
'grid_field_label6',
'grid_field_label7',
'grid_field_label8',
'grid_field_label9' ),
'grid_field_totals' => array( 'simple_grid_field32' ),
'expand_button' => array( 'expand_button' ),
'simple_search_field' => array( 'simple_search_field' ),
'simple_search_option' => array( 'simple_search_option' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'cell_field36' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field37' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field38' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field39' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field40' => array( 'cols' => array( 4 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field41' => array( 'cols' => array( 5 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field42' => array( 'cols' => array( 6 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field43' => array( 'cols' => array( 7 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field44' => array( 'cols' => array( 8 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field45' => array( 'cols' => array( 9 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field46' => array( 'cols' => array( 10 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field47' => array( 'cols' => array( 11 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field48' => array( 'cols' => array( 12 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field49' => array( 'cols' => array( 13 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field50' => array( 'cols' => array( 14 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field51' => array( 'cols' => array( 15 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field52' => array( 'cols' => array( 16 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field53' => array( 'cols' => array( 17 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field54' => array( 'cols' => array( 18 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field55' => array( 'cols' => array( 19 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field56' => array( 'cols' => array( 20 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field57' => array( 'cols' => array( 21 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field42' => array( 'cols' => array( 22 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field37' => array( 'cols' => array( 23 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field58' => array( 'cols' => array( 24 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field59' => array( 'cols' => array( 25 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field60' => array( 'cols' => array( 26 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field61' => array( 'cols' => array( 27 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field62' => array( 'cols' => array( 28 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field63' => array( 'cols' => array( 29 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field64' => array( 'cols' => array( 30 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field65' => array( 'cols' => array( 31 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field66' => array( 'cols' => array( 32 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field67' => array( 'cols' => array( 33 ),
'rows' => array( 0 ),
'tags' => array( 'saveall_link' ),
'items' => array( 'inline_save_all2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field33' => array( 'cols' => array( 34 ),
'rows' => array( 0 ),
'tags' => array( 'alias_proveedor_fieldheadercolumn' ),
'items' => array( 'grid_field_label8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field35' => array( 'cols' => array( 35 ),
'rows' => array( 0 ),
'tags' => array( 'referencia_fieldheadercolumn' ),
'items' => array( 'grid_field_label9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_icons1' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_icons' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_checkbox' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array( 'checkbox_column' ),
'items' => array( 'grid_checkbox_head' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_details' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field' => array( 'cols' => array( 4 ),
'rows' => array( 1 ),
'tags' => array( 'cat_compras_estatus_mu_id_fieldheadercolumn' ),
'items' => array( 'simple_grid_field22' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field1' => array( 'cols' => array( 5 ),
'rows' => array( 1 ),
'tags' => array( 'fecha_de_compra_fieldheadercolumn' ),
'items' => array( 'simple_grid_field24' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field2' => array( 'cols' => array( 6 ),
'rows' => array( 1 ),
'tags' => array( 'id_prov_fieldheadercolumn' ),
'items' => array( 'simple_grid_field28' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field5' => array( 'cols' => array( 7 ),
'rows' => array( 1 ),
'tags' => array( 'cat_compras_proveedores_id_fieldheadercolumn' ),
'items' => array( 'simple_grid_field29' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field6' => array( 'cols' => array( 8 ),
'rows' => array( 1 ),
'tags' => array( 'concepto_fieldheadercolumn' ),
'items' => array( 'simple_grid_field30' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field7' => array( 'cols' => array( 9 ),
'rows' => array( 1 ),
'tags' => array( 'importe_abono_compra_fieldheadercolumn' ),
'items' => array( 'simple_grid_field31' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field8' => array( 'cols' => array( 10 ),
'rows' => array( 1 ),
'tags' => array( 'saldo1_fieldheadercolumn' ),
'items' => array( 'grid_field_label2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field9' => array( 'cols' => array( 11 ),
'rows' => array( 1 ),
'tags' => array( 'tr_compras_proveedores_01_cargos_abonos_id_fieldheadercolumn' ),
'items' => array( 'simple_grid_field18' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field11' => array( 'cols' => array( 12 ),
'rows' => array( 1 ),
'tags' => array( 'cat_compras_documentos_mu_id_fieldheadercolumn' ),
'items' => array( 'simple_grid_field34' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field12' => array( 'cols' => array( 13 ),
'rows' => array( 1 ),
'tags' => array( 'uuid_sat_fieldheadercolumn' ),
'items' => array( 'grid_field_label3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field13' => array( 'cols' => array( 14 ),
'rows' => array( 1 ),
'tags' => array( 'fecha_de_solicitud_fieldheadercolumn' ),
'items' => array( 'simple_grid_field21' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field14' => array( 'cols' => array( 15 ),
'rows' => array( 1 ),
'tags' => array( 'fecha_de_requisicion_fieldheadercolumn' ),
'items' => array( 'grid_field_label' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field15' => array( 'cols' => array( 16 ),
'rows' => array( 1 ),
'tags' => array( 'fecha_de_vencimiento_fieldheadercolumn' ),
'items' => array( 'simple_grid_field36' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field16' => array( 'cols' => array( 17 ),
'rows' => array( 1 ),
'tags' => array( 'orden_de_compra_proveedor_fieldheadercolumn' ),
'items' => array( 'simple_grid_field33' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field18' => array( 'cols' => array( 18 ),
'rows' => array( 1 ),
'tags' => array( 'observacion_abono_compra_fieldheadercolumn' ),
'items' => array( 'simple_grid_field37' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field19' => array( 'cols' => array( 19 ),
'rows' => array( 1 ),
'tags' => array( 'total_compras_abonos_fieldheadercolumn' ),
'items' => array( 'simple_grid_field40' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field20' => array( 'cols' => array( 20 ),
'rows' => array( 1 ),
'tags' => array( 'total_pagos_cargos_fieldheadercolumn' ),
'items' => array( 'simple_grid_field41' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field22' => array( 'cols' => array( 21 ),
'rows' => array( 1 ),
'tags' => array( 'cat_finanzas_cuentas_de_balance_04_llave_fieldheadercolumn' ),
'items' => array( 'grid_field_label7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field43' => array( 'cols' => array( 22 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field38' => array( 'cols' => array( 23 ),
'rows' => array( 1 ),
'tags' => array( 'saldo_fieldheadercolumn' ),
'items' => array( 'simple_grid_field42' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field29' => array( 'cols' => array( 24 ),
'rows' => array( 1 ),
'tags' => array( 'tr_compras_requisiciones_01_uuid_fieldheadercolumn' ),
'items' => array( 'simple_grid_field44' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field24' => array( 'cols' => array( 25 ),
'rows' => array( 1 ),
'tags' => array( 'uuid_cargo_abono_compra_fieldheadercolumn' ),
'items' => array( 'simple_grid_field45' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field23' => array( 'cols' => array( 26 ),
'rows' => array( 1 ),
'tags' => array( 'ano_mes_fieldheadercolumn' ),
'items' => array( 'simple_grid_field27' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field28' => array( 'cols' => array( 27 ),
'rows' => array( 1 ),
'tags' => array( 'cargo_abono_fieldheadercolumn' ),
'items' => array( 'grid_field_label1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field10' => array( 'cols' => array( 28 ),
'rows' => array( 1 ),
'tags' => array( 'capturista_fieldheadercolumn' ),
'items' => array( 'simple_grid_field43' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field3' => array( 'cols' => array( 29 ),
'rows' => array( 1 ),
'tags' => array( 'vigente_fieldheadercolumn' ),
'items' => array( 'grid_field_label4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field4' => array( 'cols' => array( 30 ),
'rows' => array( 1 ),
'tags' => array( 'cat_compras_cargo_abono_mu_id_fieldheadercolumn' ),
'items' => array( 'grid_field_label5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field17' => array( 'cols' => array( 31 ),
'rows' => array( 1 ),
'tags' => array( 'llave_unica_cargo_abono_tr_compras_requisiciones_01_uuid_pago_fieldheadercolumn' ),
'items' => array( 'grid_field_label6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field21' => array( 'cols' => array( 32 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field32' => array( 'cols' => array( 33 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field34' => array( 'cols' => array( 34 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field36' => array( 'cols' => array( 35 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_icons2' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'cell_icons' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array( 'inlineedit_column',
'inline_save',
'inline_cancel' ),
'items' => array( 'grid_inline_edit',
'grid_inline_save',
'grid_inline_cancel' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_checkbox' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array( 'checkbox_column' ),
'items' => array( 'grid_checkbox' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_details' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'grid_alldetails_link',
'grid_details_link',
'grid_details_link1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 4 ),
'rows' => array( 2 ),
'tags' => array( 'cat_compras_estatus_mu_id_fieldcolumn' ),
'items' => array( 'simple_grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 5 ),
'rows' => array( 2 ),
'tags' => array( 'fecha_de_compra_fieldcolumn' ),
'items' => array( 'simple_grid_field4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 6 ),
'rows' => array( 2 ),
'tags' => array( 'id_prov_fieldcolumn' ),
'items' => array( 'simple_grid_field17' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field5' => array( 'cols' => array( 7 ),
'rows' => array( 2 ),
'tags' => array( 'cat_compras_proveedores_id_fieldcolumn' ),
'items' => array( 'simple_grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field6' => array( 'cols' => array( 8 ),
'rows' => array( 2 ),
'tags' => array( 'concepto_fieldcolumn' ),
'items' => array( 'simple_grid_field10' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field7' => array( 'cols' => array( 9 ),
'rows' => array( 2 ),
'tags' => array( 'importe_abono_compra_fieldcolumn' ),
'items' => array( 'simple_grid_field6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field8' => array( 'cols' => array( 10 ),
'rows' => array( 2 ),
'tags' => array( 'saldo1_fieldcolumn' ),
'items' => array( 'grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field9' => array( 'cols' => array( 11 ),
'rows' => array( 2 ),
'tags' => array( 'tr_compras_proveedores_01_cargos_abonos_id_fieldcolumn' ),
'items' => array( 'simple_grid_field7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field11' => array( 'cols' => array( 12 ),
'rows' => array( 2 ),
'tags' => array( 'cat_compras_documentos_mu_id_fieldcolumn' ),
'items' => array( 'simple_grid_field11' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field12' => array( 'cols' => array( 13 ),
'rows' => array( 2 ),
'tags' => array( 'uuid_sat_fieldcolumn' ),
'items' => array( 'grid_field4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field13' => array( 'cols' => array( 14 ),
'rows' => array( 2 ),
'tags' => array( 'fecha_de_solicitud_fieldcolumn' ),
'items' => array( 'simple_grid_field16' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field14' => array( 'cols' => array( 15 ),
'rows' => array( 2 ),
'tags' => array( 'fecha_de_requisicion_fieldcolumn' ),
'items' => array( 'grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field15' => array( 'cols' => array( 16 ),
'rows' => array( 2 ),
'tags' => array( 'fecha_de_vencimiento_fieldcolumn' ),
'items' => array( 'grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field16' => array( 'cols' => array( 17 ),
'rows' => array( 2 ),
'tags' => array( 'orden_de_compra_proveedor_fieldcolumn' ),
'items' => array( 'simple_grid_field15' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field18' => array( 'cols' => array( 18 ),
'rows' => array( 2 ),
'tags' => array( 'observacion_abono_compra_fieldcolumn' ),
'items' => array( 'simple_grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field19' => array( 'cols' => array( 19 ),
'rows' => array( 2 ),
'tags' => array( 'total_compras_abonos_fieldcolumn' ),
'items' => array( 'simple_grid_field20' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field20' => array( 'cols' => array( 20 ),
'rows' => array( 2 ),
'tags' => array( 'total_pagos_cargos_fieldcolumn' ),
'items' => array( 'simple_grid_field25' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field22' => array( 'cols' => array( 21 ),
'rows' => array( 2 ),
'tags' => array( 'cat_finanzas_cuentas_de_balance_04_llave_fieldcolumn' ),
'items' => array( 'grid_field8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field44' => array( 'cols' => array( 22 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'headcell_field39' => array( 'cols' => array( 23 ),
'rows' => array( 2 ),
'tags' => array( 'saldo_fieldcolumn' ),
'items' => array( 'simple_grid_field26' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field30' => array( 'cols' => array( 24 ),
'rows' => array( 2 ),
'tags' => array( 'tr_compras_requisiciones_01_uuid_fieldcolumn' ),
'items' => array( 'simple_grid_field8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field25' => array( 'cols' => array( 25 ),
'rows' => array( 2 ),
'tags' => array( 'uuid_cargo_abono_compra_fieldcolumn' ),
'items' => array( 'simple_grid_field23' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field23' => array( 'cols' => array( 26 ),
'rows' => array( 2 ),
'tags' => array( 'ano_mes_fieldcolumn' ),
'items' => array( 'simple_grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field26' => array( 'cols' => array( 27 ),
'rows' => array( 2 ),
'tags' => array( 'cargo_abono_fieldcolumn' ),
'items' => array( 'grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field10' => array( 'cols' => array( 28 ),
'rows' => array( 2 ),
'tags' => array( 'capturista_fieldcolumn' ),
'items' => array( 'simple_grid_field12' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field3' => array( 'cols' => array( 29 ),
'rows' => array( 2 ),
'tags' => array( 'vigente_fieldcolumn' ),
'items' => array( 'grid_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field21' => array( 'cols' => array( 30 ),
'rows' => array( 2 ),
'tags' => array( 'cat_compras_cargo_abono_mu_id_fieldcolumn' ),
'items' => array( 'grid_field6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field28' => array( 'cols' => array( 31 ),
'rows' => array( 2 ),
'tags' => array( 'llave_unica_cargo_abono_tr_compras_requisiciones_01_uuid_pago_fieldcolumn' ),
'items' => array( 'grid_field7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field30' => array( 'cols' => array( 32 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field33' => array( 'cols' => array( 33 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field68' => array( 'cols' => array( 34 ),
'rows' => array( 2 ),
'tags' => array( 'alias_proveedor_fieldcolumn' ),
'items' => array( 'grid_field9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field70' => array( 'cols' => array( 35 ),
'rows' => array( 2 ),
'tags' => array( 'referencia_fieldcolumn' ),
'items' => array( 'grid_field10' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_icons3' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_dpreview' => array( 'cols' => array( 1,
2,
3,
4,
5,
6,
7,
8,
9,
10,
11,
12,
13,
14,
15,
16,
17,
18,
19,
20,
21 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'details_preview',
'details_preview4',
'details_preview1',
'details_preview2',
'details_preview3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'headcell_field45' => array( 'cols' => array( 22 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field40' => array( 'cols' => array( 23 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field31' => array( 'cols' => array( 24 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field26' => array( 'cols' => array( 25 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field24' => array( 'cols' => array( 26 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field27' => array( 'cols' => array( 27 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field17' => array( 'cols' => array( 28 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field4' => array( 'cols' => array( 29 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field25' => array( 'cols' => array( 30 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field29' => array( 'cols' => array( 31 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field31' => array( 'cols' => array( 32 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field34' => array( 'cols' => array( 33 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field69' => array( 'cols' => array( 34 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field71' => array( 'cols' => array( 35 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_icons4' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_icons' => array( 'cols' => array( 1 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_checkbox' => array( 'cols' => array( 2 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_details' => array( 'cols' => array( 3 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field' => array( 'cols' => array( 4 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field1' => array( 'cols' => array( 5 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field2' => array( 'cols' => array( 6 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field5' => array( 'cols' => array( 7 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field6' => array( 'cols' => array( 8 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field7' => array( 'cols' => array( 9 ),
'rows' => array( 4 ),
'tags' => array( 'importe_abono_compra_fieldfootercolumn' ),
'items' => array( 'simple_grid_field32' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field8' => array( 'cols' => array( 10 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field9' => array( 'cols' => array( 11 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field11' => array( 'cols' => array( 12 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field12' => array( 'cols' => array( 13 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field13' => array( 'cols' => array( 14 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field14' => array( 'cols' => array( 15 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field15' => array( 'cols' => array( 16 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field16' => array( 'cols' => array( 17 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field18' => array( 'cols' => array( 18 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field19' => array( 'cols' => array( 19 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field20' => array( 'cols' => array( 20 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field22' => array( 'cols' => array( 21 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field46' => array( 'cols' => array( 22 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field41' => array( 'cols' => array( 23 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field32' => array( 'cols' => array( 24 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field27' => array( 'cols' => array( 25 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field23' => array( 'cols' => array( 26 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field24' => array( 'cols' => array( 27 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field10' => array( 'cols' => array( 28 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field3' => array( 'cols' => array( 29 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field4' => array( 'cols' => array( 30 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field17' => array( 'cols' => array( 31 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field21' => array( 'cols' => array( 32 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field35' => array( 'cols' => array( 33 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field25' => array( 'cols' => array( 34 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field26' => array( 'cols' => array( 35 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 36,
'height' => 5 ) ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array( 'details_found' => array( 'tag' => 'DISPLAYING',
'type' => 2 ) ) ),
'gridType' => 0,
'recsPerRow' => 1,
'hasCustomButtons' => true,
'customButtons' => array( 'link_requi_orden_de_compra',
'pdf_orden_de_compra',
'insert_pagos_tr_compras_proveedores_01_cargos_abonos' ),
'hasNotifications' => false,
'menus' => array( array( 'id' => 'main',
'horizontal' => false ) ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'list',
'breadcrumb' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array( 'link_requi_orden_de_compra',
'pdf_orden_de_compra',
'insert_pagos_tr_compras_proveedores_01_cargos_abonos' ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'list',
'type' => 'list',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'list-above-grid',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c3',
'colspan' => 2 ) ) ),
array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ),
array( 'cell' => 'c4' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'inline_add',
'inline_save_all',
'inline_cancel_all' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'details_found',
'page_size',
'print_panel' ) ),
'c3' => array( 'model' => 'c2',
'items' => array( 'custom_button',
'text' ),
'align' => 'left' ),
'c' => array( 'model' => 'c1',
'items' => array(  ) ),
'c4' => array( 'model' => 'c2',
'items' => array( 'inline_save_all1' ),
'align' => 'right' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'list-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'pagination' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo',
'expand_button' ) ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu',
'search_panel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'expand_menu_button',
'collapse_button',
'breadcrumb' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'simple_search_field',
'simple_search_option',
'simple_search',
'list_options',
'loginform_login',
'username_button' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'horizontal-grid',
'grid' => array( array( 'section' => 'head',
'cells' => array( array( 'cell' => 'cell_field36' ),
array( 'cell' => 'cell_field37' ),
array( 'cell' => 'cell_field38' ),
array( 'cell' => 'cell_field39' ),
array( 'cell' => 'cell_field40' ),
array( 'cell' => 'cell_field41' ),
array( 'cell' => 'cell_field42' ),
array( 'cell' => 'cell_field43' ),
array( 'cell' => 'cell_field44' ),
array( 'cell' => 'cell_field45' ),
array( 'cell' => 'cell_field46' ),
array( 'cell' => 'cell_field47' ),
array( 'cell' => 'cell_field48' ),
array( 'cell' => 'cell_field49' ),
array( 'cell' => 'cell_field50' ),
array( 'cell' => 'cell_field51' ),
array( 'cell' => 'cell_field52' ),
array( 'cell' => 'cell_field53' ),
array( 'cell' => 'cell_field54' ),
array( 'cell' => 'cell_field55' ),
array( 'cell' => 'cell_field56' ),
array( 'cell' => 'cell_field57' ),
array( 'cell' => 'headcell_field42' ),
array( 'cell' => 'headcell_field37' ),
array( 'cell' => 'cell_field58' ),
array( 'cell' => 'cell_field59' ),
array( 'cell' => 'cell_field60' ),
array( 'cell' => 'cell_field61' ),
array( 'cell' => 'cell_field62' ),
array( 'cell' => 'cell_field63' ),
array( 'cell' => 'cell_field64' ),
array( 'cell' => 'cell_field65' ),
array( 'cell' => 'cell_field66' ),
array( 'cell' => 'cell_field67' ),
array( 'cell' => 'headcell_field33' ),
array( 'cell' => 'headcell_field35' ) ) ),
array( 'section' => 'head',
'cells' => array( array( 'cell' => 'cell_icons1' ),
array( 'cell' => 'headcell_icons' ),
array( 'cell' => 'headcell_checkbox' ),
array( 'cell' => 'headcell_details' ),
array( 'cell' => 'headcell_field' ),
array( 'cell' => 'headcell_field1' ),
array( 'cell' => 'headcell_field2' ),
array( 'cell' => 'headcell_field5' ),
array( 'cell' => 'headcell_field6' ),
array( 'cell' => 'headcell_field7' ),
array( 'cell' => 'headcell_field8' ),
array( 'cell' => 'headcell_field9' ),
array( 'cell' => 'headcell_field11' ),
array( 'cell' => 'headcell_field12' ),
array( 'cell' => 'headcell_field13' ),
array( 'cell' => 'headcell_field14' ),
array( 'cell' => 'headcell_field15' ),
array( 'cell' => 'headcell_field16' ),
array( 'cell' => 'headcell_field18' ),
array( 'cell' => 'headcell_field19' ),
array( 'cell' => 'headcell_field20' ),
array( 'cell' => 'headcell_field22' ),
array( 'cell' => 'headcell_field43' ),
array( 'cell' => 'headcell_field38' ),
array( 'cell' => 'headcell_field29' ),
array( 'cell' => 'headcell_field24' ),
array( 'cell' => 'headcell_field23' ),
array( 'cell' => 'headcell_field28' ),
array( 'cell' => 'headcell_field10' ),
array( 'cell' => 'headcell_field3' ),
array( 'cell' => 'headcell_field4' ),
array( 'cell' => 'headcell_field17' ),
array( 'cell' => 'headcell_field21' ),
array( 'cell' => 'cell_field32' ),
array( 'cell' => 'headcell_field34' ),
array( 'cell' => 'headcell_field36' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_icons2' ),
array( 'cell' => 'cell_icons' ),
array( 'cell' => 'cell_checkbox' ),
array( 'cell' => 'cell_details' ),
array( 'cell' => 'cell_field' ),
array( 'cell' => 'cell_field1' ),
array( 'cell' => 'cell_field2' ),
array( 'cell' => 'cell_field5' ),
array( 'cell' => 'cell_field6' ),
array( 'cell' => 'cell_field7' ),
array( 'cell' => 'cell_field8' ),
array( 'cell' => 'cell_field9' ),
array( 'cell' => 'cell_field11' ),
array( 'cell' => 'cell_field12' ),
array( 'cell' => 'cell_field13' ),
array( 'cell' => 'cell_field14' ),
array( 'cell' => 'cell_field15' ),
array( 'cell' => 'cell_field16' ),
array( 'cell' => 'cell_field18' ),
array( 'cell' => 'cell_field19' ),
array( 'cell' => 'cell_field20' ),
array( 'cell' => 'cell_field22' ),
array( 'cell' => 'headcell_field44' ),
array( 'cell' => 'headcell_field39' ),
array( 'cell' => 'headcell_field30' ),
array( 'cell' => 'headcell_field25' ),
array( 'cell' => 'cell_field23' ),
array( 'cell' => 'cell_field26' ),
array( 'cell' => 'cell_field10' ),
array( 'cell' => 'cell_field3' ),
array( 'cell' => 'cell_field21' ),
array( 'cell' => 'cell_field28' ),
array( 'cell' => 'cell_field30' ),
array( 'cell' => 'cell_field33' ),
array( 'cell' => 'cell_field68' ),
array( 'cell' => 'cell_field70' ) ) ),
array( 'cells' => array( array( 'cell' => 'cell_icons3' ),
array( 'cell' => 'cell_dpreview',
'colspan' => 21 ),
array( 'cell' => 'headcell_field45' ),
array( 'cell' => 'headcell_field40' ),
array( 'cell' => 'headcell_field31' ),
array( 'cell' => 'headcell_field26' ),
array( 'cell' => 'cell_field24' ),
array( 'cell' => 'cell_field27' ),
array( 'cell' => 'cell_field17' ),
array( 'cell' => 'cell_field4' ),
array( 'cell' => 'cell_field25' ),
array( 'cell' => 'cell_field29' ),
array( 'cell' => 'cell_field31' ),
array( 'cell' => 'cell_field34' ),
array( 'cell' => 'cell_field69' ),
array( 'cell' => 'cell_field71' ) ),
'section' => 'body' ),
array( 'section' => 'foot',
'cells' => array( array( 'cell' => 'cell_icons4' ),
array( 'cell' => 'footcell_icons' ),
array( 'cell' => 'footcell_checkbox' ),
array( 'cell' => 'footcell_details' ),
array( 'cell' => 'footcell_field' ),
array( 'cell' => 'footcell_field1' ),
array( 'cell' => 'footcell_field2' ),
array( 'cell' => 'footcell_field5' ),
array( 'cell' => 'footcell_field6' ),
array( 'cell' => 'footcell_field7' ),
array( 'cell' => 'footcell_field8' ),
array( 'cell' => 'footcell_field9' ),
array( 'cell' => 'footcell_field11' ),
array( 'cell' => 'footcell_field12' ),
array( 'cell' => 'footcell_field13' ),
array( 'cell' => 'footcell_field14' ),
array( 'cell' => 'footcell_field15' ),
array( 'cell' => 'footcell_field16' ),
array( 'cell' => 'footcell_field18' ),
array( 'cell' => 'footcell_field19' ),
array( 'cell' => 'footcell_field20' ),
array( 'cell' => 'footcell_field22' ),
array( 'cell' => 'headcell_field46' ),
array( 'cell' => 'headcell_field41' ),
array( 'cell' => 'headcell_field32' ),
array( 'cell' => 'headcell_field27' ),
array( 'cell' => 'footcell_field23' ),
array( 'cell' => 'footcell_field24' ),
array( 'cell' => 'footcell_field10' ),
array( 'cell' => 'footcell_field3' ),
array( 'cell' => 'footcell_field4' ),
array( 'cell' => 'footcell_field17' ),
array( 'cell' => 'footcell_field21' ),
array( 'cell' => 'cell_field35' ),
array( 'cell' => 'footcell_field25' ),
array( 'cell' => 'footcell_field26' ) ) ) ),
'cells' => array( 'headcell_field' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field22' ),
'field' => 'cat_compras_estatus_mu_id',
'columnName' => 'field' ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field3' ),
'field' => 'cat_compras_estatus_mu_id',
'columnName' => 'field' ),
'footcell_field' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field1' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field24' ),
'field' => 'fecha_de_compra',
'columnName' => 'field' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field4' ),
'field' => 'fecha_de_compra',
'columnName' => 'field' ),
'footcell_field1' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field2' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field28' ),
'field' => 'id_prov',
'columnName' => 'field' ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field17' ),
'field' => 'id_prov',
'columnName' => 'field' ),
'footcell_field2' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field5' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field29' ),
'field' => 'cat_compras_proveedores_id',
'columnName' => 'field' ),
'cell_field5' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field2' ),
'field' => 'cat_compras_proveedores_id',
'columnName' => 'field' ),
'footcell_field5' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field6' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field30' ),
'field' => 'concepto',
'columnName' => 'field' ),
'cell_field6' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field10' ),
'field' => 'concepto',
'columnName' => 'field' ),
'footcell_field6' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field7' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field31' ),
'field' => 'importe_abono_compra',
'columnName' => 'field' ),
'cell_field7' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field6' ),
'field' => 'importe_abono_compra',
'columnName' => 'field' ),
'footcell_field7' => array( 'model' => 'footcell_field',
'items' => array( 'simple_grid_field32' ),
'field' => 'importe_abono_compra',
'columnName' => 'field' ),
'headcell_field8' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label2' ),
'field' => 'saldo1',
'columnName' => 'field' ),
'cell_field8' => array( 'model' => 'cell_field',
'items' => array( 'grid_field3' ),
'field' => 'saldo1',
'columnName' => 'field' ),
'footcell_field8' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field9' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field18' ),
'field' => 'tr_compras_proveedores_01_cargos_abonos_id',
'columnName' => 'field' ),
'cell_field9' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field7' ),
'field' => 'tr_compras_proveedores_01_cargos_abonos_id',
'columnName' => 'field' ),
'footcell_field9' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field11' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field34' ),
'field' => 'cat_compras_documentos_mu_id',
'columnName' => 'field' ),
'cell_field11' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field11' ),
'field' => 'cat_compras_documentos_mu_id',
'columnName' => 'field' ),
'footcell_field11' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field12' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label3' ),
'field' => 'uuid_sat',
'columnName' => 'field' ),
'cell_field12' => array( 'model' => 'cell_field',
'items' => array( 'grid_field4' ),
'field' => 'uuid_sat',
'columnName' => 'field' ),
'footcell_field12' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field13' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field21' ),
'field' => 'fecha_de_solicitud',
'columnName' => 'field' ),
'cell_field13' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field16' ),
'field' => 'fecha_de_solicitud',
'columnName' => 'field' ),
'footcell_field13' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field14' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label' ),
'field' => 'fecha_de_requisicion',
'columnName' => 'field' ),
'cell_field14' => array( 'model' => 'cell_field',
'items' => array( 'grid_field' ),
'field' => 'fecha_de_requisicion',
'columnName' => 'field' ),
'footcell_field14' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field15' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field36' ),
'field' => 'fecha_de_vencimiento',
'columnName' => 'field' ),
'cell_field15' => array( 'model' => 'cell_field',
'items' => array( 'grid_field2' ),
'field' => 'fecha_de_vencimiento',
'columnName' => 'field' ),
'footcell_field15' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field16' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field33' ),
'field' => 'orden_de_compra_proveedor',
'columnName' => 'field' ),
'cell_field16' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field15' ),
'field' => 'orden_de_compra_proveedor',
'columnName' => 'field' ),
'footcell_field16' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field18' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field37' ),
'field' => 'observacion_abono_compra',
'columnName' => 'field' ),
'cell_field18' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field1' ),
'field' => 'observacion_abono_compra',
'columnName' => 'field' ),
'footcell_field18' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field19' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field40' ),
'field' => 'total_compras_abonos',
'columnName' => 'field' ),
'cell_field19' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field20' ),
'field' => 'total_compras_abonos',
'columnName' => 'field' ),
'footcell_field19' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field20' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field41' ),
'field' => 'total_pagos_cargos',
'columnName' => 'field' ),
'cell_field20' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field25' ),
'field' => 'total_pagos_cargos',
'columnName' => 'field' ),
'footcell_field20' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field22' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label7' ),
'field' => 'cat_finanzas_cuentas_de_balance_04_llave',
'columnName' => 'field' ),
'cell_field22' => array( 'model' => 'cell_field',
'items' => array( 'grid_field8' ),
'field' => 'cat_finanzas_cuentas_de_balance_04_llave',
'columnName' => 'field' ),
'footcell_field22' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'cell_dpreview' => array( 'model' => 'cell_dpreview',
'items' => array( 'details_preview',
'details_preview4',
'details_preview1',
'details_preview2',
'details_preview3' ) ),
'headcell_checkbox' => array( 'model' => 'headcell_checkbox',
'items' => array( 'grid_checkbox_head' ) ),
'cell_checkbox' => array( 'model' => 'cell_checkbox',
'items' => array( 'grid_checkbox' ) ),
'footcell_checkbox' => array( 'model' => 'footcell_checkbox',
'items' => array(  ) ),
'headcell_icons' => array( 'model' => 'headcell_icons',
'items' => array(  ) ),
'cell_icons' => array( 'model' => 'cell_icons',
'items' => array( 'grid_inline_edit',
'grid_inline_save',
'grid_inline_cancel' ) ),
'footcell_icons' => array( 'model' => 'footcell_icons',
'items' => array(  ) ),
'headcell_details' => array( 'model' => 'headcell_details',
'items' => array(  ) ),
'cell_details' => array( 'model' => 'cell_details',
'items' => array( 'grid_alldetails_link',
'grid_details_link',
'grid_details_link1' ) ),
'footcell_details' => array( 'model' => 'footcell_details',
'items' => array(  ) ),
'cell_icons1' => array( 'model' => 'headcell_icons',
'items' => array(  ) ),
'cell_icons2' => array( 'model' => 'cell_icons',
'items' => array( 'custom_button1' ) ),
'cell_icons3' => array( 'model' => 'cell_dpreview',
'items' => array(  ) ),
'cell_icons4' => array( 'model' => 'footcell_icons',
'items' => array(  ) ),
'headcell_field23' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field27' ),
'field' => 'ano_mes',
'columnName' => 'field' ),
'cell_field23' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field' ),
'field' => 'ano_mes',
'columnName' => 'field' ),
'cell_field24' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'footcell_field23' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field24' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field45' ),
'field' => 'uuid_cargo_abono_compra',
'columnName' => 'field' ),
'headcell_field25' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field23' ),
'field' => 'uuid_cargo_abono_compra',
'columnName' => 'field' ),
'headcell_field26' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'headcell_field27' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field28' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label1' ),
'field' => 'cargo_abono',
'columnName' => 'field' ),
'cell_field26' => array( 'model' => 'cell_field',
'items' => array( 'grid_field1' ),
'field' => 'cargo_abono',
'columnName' => 'field' ),
'cell_field27' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'footcell_field24' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field10' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field43' ),
'field' => 'capturista',
'columnName' => 'field' ),
'cell_field10' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field12' ),
'field' => 'capturista',
'columnName' => 'field' ),
'cell_field17' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'footcell_field10' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field29' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field44' ),
'field' => 'tr_compras_requisiciones_01_uuid',
'columnName' => 'field' ),
'headcell_field30' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field8' ),
'field' => 'tr_compras_requisiciones_01_uuid',
'columnName' => 'field' ),
'headcell_field31' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'headcell_field32' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field3' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label4' ),
'field' => 'vigente',
'columnName' => 'field' ),
'cell_field3' => array( 'model' => 'cell_field',
'items' => array( 'grid_field5' ),
'field' => 'vigente',
'columnName' => 'field' ),
'cell_field4' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'footcell_field3' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field4' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label5' ),
'field' => 'cat_compras_cargo_abono_mu_id',
'columnName' => 'field' ),
'cell_field21' => array( 'model' => 'cell_field',
'items' => array( 'grid_field6' ),
'field' => 'cat_compras_cargo_abono_mu_id',
'columnName' => 'field' ),
'cell_field25' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'footcell_field4' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field17' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label6' ),
'field' => 'llave_unica_cargo_abono_tr_compras_requisiciones_01_uuid_pago',
'columnName' => 'field' ),
'cell_field28' => array( 'model' => 'cell_field',
'items' => array( 'grid_field7' ),
'field' => 'llave_unica_cargo_abono_tr_compras_requisiciones_01_uuid_pago',
'columnName' => 'field' ),
'cell_field29' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'footcell_field17' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field21' => array( 'model' => 'headcell_field',
'items' => array(  ) ),
'cell_field30' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'cell_field31' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'footcell_field21' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'cell_field32' => array( 'model' => 'headcell_field',
'items' => array(  ) ),
'cell_field33' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'cell_field34' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'cell_field35' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'cell_field36' => array( 'model' => 'headcell_icons',
'items' => array(  ) ),
'cell_field37' => array( 'model' => 'headcell_icons',
'items' => array(  ) ),
'cell_field38' => array( 'model' => 'headcell_checkbox',
'items' => array(  ) ),
'cell_field39' => array( 'model' => 'headcell_details',
'items' => array(  ) ),
'cell_field40' => array( 'model' => 'headcell_field',
'items' => array(  ) ),
'cell_field41' => array( 'model' => 'headcell_field',
'items' => array(  ) ),
'cell_field42' => array( 'model' => 'headcell_field',
'items' => array(  ) ),
'cell_field43' => array( 'model' => 'headcell_field',
'items' => array(  ) ),
'cell_field44' => array( 'model' => 'headcell_field',
'items' => array(  ) ),
'cell_field45' => array( 'model' => 'headcell_field',
'items' => array(  ) ),
'cell_field46' => array( 'model' => 'headcell_field',
'items' => array(  ) ),
'cell_field47' => array( 'model' => 'headcell_field',
'items' => array(  ) ),
'cell_field48' => array( 'model' => 'headcell_field',
'items' => array(  ) ),
'cell_field49' => array( 'model' => 'headcell_field',
'items' => array(  ) ),
'cell_field50' => array( 'model' => 'headcell_field',
'items' => array(  ) ),
'cell_field51' => array( 'model' => 'headcell_field',
'items' => array(  ) ),
'cell_field52' => array( 'model' => 'headcell_field',
'items' => array(  ) ),
'cell_field53' => array( 'model' => 'headcell_field',
'items' => array(  ) ),
'cell_field54' => array( 'model' => 'headcell_field',
'items' => array(  ) ),
'cell_field55' => array( 'model' => 'headcell_field',
'items' => array(  ) ),
'cell_field56' => array( 'model' => 'headcell_field',
'items' => array(  ) ),
'cell_field57' => array( 'model' => 'headcell_field',
'items' => array(  ) ),
'cell_field58' => array( 'model' => 'headcell_field',
'items' => array(  ) ),
'cell_field59' => array( 'model' => 'headcell_field',
'items' => array(  ) ),
'cell_field60' => array( 'model' => 'headcell_field',
'items' => array(  ) ),
'cell_field61' => array( 'model' => 'headcell_field',
'items' => array(  ) ),
'cell_field62' => array( 'model' => 'headcell_field',
'items' => array(  ) ),
'cell_field63' => array( 'model' => 'headcell_field',
'items' => array(  ) ),
'cell_field64' => array( 'model' => 'headcell_field',
'items' => array(  ) ),
'cell_field65' => array( 'model' => 'headcell_field',
'items' => array(  ) ),
'cell_field66' => array( 'model' => 'headcell_field',
'items' => array(  ) ),
'cell_field67' => array( 'model' => 'headcell_field',
'items' => array( 'inline_save_all2' ) ),
'headcell_field33' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label8' ),
'field' => 'alias_proveedor',
'columnName' => 'field' ),
'headcell_field34' => array( 'model' => 'headcell_field',
'items' => array(  ) ),
'cell_field68' => array( 'model' => 'cell_field',
'items' => array( 'grid_field9' ),
'field' => 'alias_proveedor',
'columnName' => 'field' ),
'cell_field69' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'footcell_field25' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field35' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label9' ),
'field' => 'referencia',
'columnName' => 'field' ),
'headcell_field36' => array( 'model' => 'headcell_field',
'items' => array(  ) ),
'cell_field70' => array( 'model' => 'cell_field',
'items' => array( 'grid_field10' ),
'field' => 'referencia',
'columnName' => 'field' ),
'cell_field71' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'footcell_field26' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field37' => array( 'model' => 'headcell_field',
'items' => array(  ) ),
'headcell_field38' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field42' ),
'field' => 'saldo',
'columnName' => 'field' ),
'headcell_field39' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field26' ),
'field' => 'saldo',
'columnName' => 'field' ),
'headcell_field40' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'headcell_field41' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field42' => array( 'model' => 'headcell_field',
'items' => array(  ) ),
'headcell_field43' => array( 'model' => 'headcell_field',
'items' => array(  ) ),
'headcell_field44' => array( 'model' => 'cell_field',
'items' => array( 'custom_button2' ) ),
'headcell_field45' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'headcell_field46' => array( 'model' => 'footcell_field',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'list-sidebar-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c2' => array( 'model' => 'c2',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'page_size' => array( 'type' => 'page_size' ),
'details_found' => array( 'type' => 'details_found' ),
'breadcrumb' => array( 'type' => 'breadcrumb' ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'simple_search' => array( 'type' => 'simple_search' ),
'pagination' => array( 'type' => 'pagination' ),
'grid_checkbox' => array( 'type' => 'grid_checkbox' ),
'grid_checkbox_head' => array( 'type' => 'grid_checkbox_head' ),
'search_panel' => array( 'type' => 'search_panel',
'items' => array( 'search_panel_field15',
'search_panel_field9',
'search_panel_field8',
'search_panel_field7',
'search_panel_field6',
'search_panel_field5',
'search_panel_field4',
'search_panel_field2',
'search_panel_field1',
'search_panel_field',
'search_panel_field3' ),
'_flexiblePanel' => true ),
'list_options' => array( 'type' => 'list_options',
'items' => array( 'edit_selected',
'-3',
'advsearch_link',
'show_search_panel',
'hide_search_panel',
'-4',
'import' ) ),
'show_search_panel' => array( 'type' => 'show_search_panel' ),
'hide_search_panel' => array( 'type' => 'hide_search_panel' ),
'simple_grid_field17' => array( 'field' => 'id_prov',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'search_panel_field' => array( 'field' => 'id_prov',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field3' => array( 'field' => 'cat_compras_proveedores_id',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'simple_grid_field25' => array( 'field' => 'total_pagos_cargos',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'adminarea_link',
'changepassword_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => false ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'logout_link' => array( 'type' => 'logout_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'changepassword_link' => array( 'type' => 'changepassword_link' ),
'expand_menu_button' => array( 'type' => 'expand_menu_button' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'grid_details_link' => array( 'type' => 'grid_details_link',
'table' => 'tr_compras_proveedores_01_cargos_abonos_pagos',
'badge' => true,
'hideIfNone' => false,
'showCount' => true ),
'grid_alldetails_link' => array( 'type' => 'grid_alldetails_link' ),
'details_preview' => array( 'type' => 'details_preview',
'table' => 'tr_compras_proveedores_01_cargos_abonos_pagos',
'items' => array(  ),
'popup' => false,
'hideEmptyPreview' => false,
'proceedLink' => true,
'pageId' => 'list',
'caption' => array( 'page' => 'list',
'table' => 'tr_compras_proveedores_01_cargos_abonos_pagos',
'type' => 7 ) ),
'-' => array( 'type' => '-' ),
'-1' => array( 'type' => '-' ),
'import' => array( 'type' => 'import' ),
'-2' => array( 'type' => '-' ),
'print_details' => array( 'type' => 'print_details',
'tables' => array( 'tr_compras_proveedores_01_cargos_abonos_pagos' => true,
'tr_compras_proveedores_02_cargos_abonos_centros_de_costos' => true,
'tr_compras_proveedores_02_cargos_abonos_movimientos' => true,
'tr_compras_requisiciones_02_productos' => true,
'tr_compras_requisiciones_02_productos_compras' => true,
'tr_compras_facturas_sat_02' => true ) ),
'print_panel' => array( 'type' => 'print_panel',
'items' => array( 'print_details' ) ),
'advsearch_link' => array( 'type' => 'advsearch_link' ),
'-3' => array( 'type' => '-' ),
'simple_grid_field2' => array( 'field' => 'cat_compras_proveedores_id',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true,
'clickSort' => true ),
'simple_grid_field4' => array( 'field' => 'fecha_de_compra',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true,
'clickSort' => true ),
'simple_grid_field6' => array( 'field' => 'importe_abono_compra',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true,
'clickSort' => true ),
'simple_grid_field9' => array( 'field' => 'fecha_de_vencimiento',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true,
'clickSort' => true ),
'simple_grid_field10' => array( 'field' => 'concepto',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true,
'clickSort' => true ),
'simple_grid_field11' => array( 'field' => 'cat_compras_documentos_mu_id',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true,
'clickSort' => true ),
'simple_grid_field12' => array( 'field' => 'capturista',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true,
'clickSort' => true ),
'simple_grid_field23' => array( 'field' => 'uuid_cargo_abono_compra',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true,
'clickSort' => true,
'label' => array( 'field' => 'uuid_cargo_abono_compra',
'table' => 'tr_compras_proveedores_01_cargos_abonos',
'type' => 3 ) ),
'simple_grid_field26' => array( 'field' => 'saldo',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'inline_add' => array( 'type' => 'inline_add',
'label' => array( 'type' => 0,
'text' => 'Añadir In Line' ) ),
'grid_inline_cancel' => array( 'type' => 'grid_inline_cancel' ),
'grid_inline_save' => array( 'type' => 'grid_inline_save' ),
'inline_save_all' => array( 'type' => 'inline_save_all' ),
'inline_cancel_all' => array( 'type' => 'inline_cancel_all' ),
'edit_selected' => array( 'type' => 'edit_selected' ),
'grid_inline_edit' => array( 'type' => 'grid_inline_edit' ),
'search_panel_field1' => array( 'field' => 'ano_mes',
'type' => 'search_panel_field' ),
'simple_grid_field20' => array( 'field' => 'total_compras_abonos',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field' => array( 'field' => 'ano_mes',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'search_panel_field2' => array( 'field' => 'concepto',
'type' => 'search_panel_field' ),
'simple_grid_field7' => array( 'field' => 'tr_compras_proveedores_01_cargos_abonos_id',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true,
'label' => array( 'field' => 'tr_compras_proveedores_01_cargos_abonos_id',
'table' => 'tr_compras_proveedores_01_cargos_abonos',
'type' => 3 ) ),
'details_preview1' => array( 'type' => 'details_preview',
'table' => 'tr_compras_proveedores_02_cargos_abonos_centros_de_costos',
'items' => array(  ),
'popup' => false,
'hideEmptyPreview' => false,
'proceedLink' => true,
'pageId' => 'list' ),
'grid_details_link1' => array( 'type' => 'grid_details_link',
'table' => 'tr_compras_proveedores_02_cargos_abonos_centros_de_costos',
'badge' => true,
'showCount' => false,
'hideIfNone' => false ),
'details_preview2' => array( 'type' => 'details_preview',
'table' => 'tr_compras_proveedores_02_cargos_abonos_movimientos',
'items' => array(  ),
'popup' => false,
'hideEmptyPreview' => false,
'proceedLink' => true,
'pageId' => 'list' ),
'simple_grid_field8' => array( 'field' => 'tr_compras_requisiciones_01_uuid',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'custom_button' => array( 'type' => 'custom_button',
'eventId' => 'link_requi_orden_de_compra',
'label' => array( 'text' => 'Orden de compra',
'type' => 0 ),
'icon' => array( 'glyph' => 'backward' ) ),
'grid_details_link2' => array( 'type' => 'grid_details_link',
'table' => 'tr_compras_requisiciones_02_productos',
'badge' => true,
'showCount' => false,
'hideIfNone' => false ),
'simple_grid_field15' => array( 'field' => 'orden_de_compra_proveedor',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true,
'clickSort' => true ),
'details_preview4' => array( 'type' => 'details_preview',
'table' => 'tr_compras_requisiciones_02_productos_compras',
'items' => array(  ),
'popup' => false,
'hideEmptyPreview' => false,
'proceedLink' => true,
'pageId' => 'list',
'caption' => array( 'page' => 'list',
'table' => 'tr_compras_requisiciones_02_productos_compras',
'type' => 7 ) ),
'simple_grid_field1' => array( 'field' => 'observacion_abono_compra',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true,
'label' => array( 'field' => 'observacion_abono_compra',
'table' => 'tr_compras_proveedores_01_cargos_abonos',
'type' => 3 ) ),
'text' => array( 'type' => 'text',
'label' => array( 'text' => 'Registro de la compra con el proveedor',
'type' => 0 ),
'editedByRte' => false ),
'simple_grid_field3' => array( 'field' => 'cat_compras_estatus_mu_id',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'search_panel_field15' => array( 'field' => 'cat_compras_estatus_mu_id',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'simple_grid_field16' => array( 'field' => 'fecha_de_solicitud',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field18' => array( 'type' => 'grid_field_label',
'field' => 'tr_compras_proveedores_01_cargos_abonos_id',
'clickSort' => true ),
'simple_grid_field21' => array( 'type' => 'grid_field_label',
'field' => 'fecha_de_solicitud',
'clickSort' => true ),
'simple_grid_field22' => array( 'type' => 'grid_field_label',
'field' => 'cat_compras_estatus_mu_id',
'clickSort' => true ),
'simple_grid_field24' => array( 'type' => 'grid_field_label',
'field' => 'fecha_de_compra',
'clickSort' => true,
'label' => array( 'field' => 'fecha_de_compra',
'table' => 'tr_compras_proveedores_01_cargos_abonos',
'type' => 3 ) ),
'simple_grid_field27' => array( 'type' => 'grid_field_label',
'field' => 'ano_mes',
'clickSort' => true ),
'simple_grid_field28' => array( 'type' => 'grid_field_label',
'field' => 'id_prov',
'clickSort' => true ),
'simple_grid_field29' => array( 'type' => 'grid_field_label',
'field' => 'cat_compras_proveedores_id',
'clickSort' => true ),
'simple_grid_field30' => array( 'type' => 'grid_field_label',
'field' => 'concepto',
'clickSort' => true ),
'simple_grid_field31' => array( 'type' => 'grid_field_label',
'field' => 'importe_abono_compra',
'clickSort' => true ),
'simple_grid_field32' => array( 'type' => 'grid_field_totals',
'field' => 'importe_abono_compra',
'totals' => 'TOTAL' ),
'simple_grid_field33' => array( 'type' => 'grid_field_label',
'field' => 'orden_de_compra_proveedor',
'clickSort' => true ),
'simple_grid_field34' => array( 'type' => 'grid_field_label',
'field' => 'cat_compras_documentos_mu_id',
'clickSort' => true,
'label' => array( 'field' => 'cat_compras_documentos_mu_id',
'table' => 'tr_compras_proveedores_01_cargos_abonos',
'type' => 3 ) ),
'simple_grid_field36' => array( 'type' => 'grid_field_label',
'field' => 'fecha_de_vencimiento',
'clickSort' => true ),
'simple_grid_field37' => array( 'type' => 'grid_field_label',
'field' => 'observacion_abono_compra',
'clickSort' => true ),
'simple_grid_field40' => array( 'type' => 'grid_field_label',
'field' => 'total_compras_abonos',
'clickSort' => true ),
'simple_grid_field41' => array( 'type' => 'grid_field_label',
'field' => 'total_pagos_cargos',
'clickSort' => true ),
'simple_grid_field42' => array( 'type' => 'grid_field_label',
'field' => 'saldo',
'clickSort' => true ),
'simple_grid_field43' => array( 'type' => 'grid_field_label',
'field' => 'capturista',
'clickSort' => true ),
'simple_grid_field44' => array( 'type' => 'grid_field_label',
'field' => 'tr_compras_requisiciones_01_uuid',
'clickSort' => true ),
'simple_grid_field45' => array( 'type' => 'grid_field_label',
'field' => 'uuid_cargo_abono_compra',
'clickSort' => true ),
'custom_button1' => array( 'eventId' => 'pdf_orden_de_compra',
'label' => array( 'type' => 0,
'text' => 'Ver Pedido Pdf' ),
'type' => 'custom_button',
'buttonStyle' => 'warning' ),
'grid_field' => array( 'field' => 'fecha_de_requisicion',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'grid_field_label' => array( 'type' => 'grid_field_label',
'field' => 'fecha_de_requisicion',
'label' => array( 'field' => 'fecha_de_requisicion',
'table' => 'tr_compras_proveedores_01_cargos_abonos',
'type' => 3 ),
'clickSort' => true ),
'grid_field1' => array( 'field' => 'cargo_abono',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label1' => array( 'type' => 'grid_field_label',
'field' => 'cargo_abono',
'clickSort' => true ),
'grid_field2' => array( 'field' => 'fecha_de_vencimiento',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'grid_field3' => array( 'field' => 'saldo1',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label2' => array( 'type' => 'grid_field_label',
'field' => 'saldo1',
'label' => array( 'field' => 'saldo1',
'table' => 'tr_compras_proveedores_01_cargos_abonos',
'type' => 3 ),
'clickSort' => true ),
'grid_field4' => array( 'field' => 'uuid_sat',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label3' => array( 'type' => 'grid_field_label',
'field' => 'uuid_sat',
'clickSort' => true ),
'search_panel_field4' => array( 'field' => 'uuid_sat',
'type' => 'search_panel_field' ),
'details_preview3' => array( 'type' => 'details_preview',
'table' => 'tr_compras_facturas_sat_02',
'items' => array(  ),
'popup' => false,
'hideEmptyPreview' => false,
'proceedLink' => true,
'pageId' => 'list' ),
'grid_field5' => array( 'field' => 'vigente',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'grid_field_label4' => array( 'type' => 'grid_field_label',
'field' => 'vigente',
'clickSort' => true ),
'grid_field6' => array( 'field' => 'cat_compras_cargo_abono_mu_id',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => false ),
'grid_field_label5' => array( 'type' => 'grid_field_label',
'field' => 'cat_compras_cargo_abono_mu_id',
'clickSort' => true ),
'grid_field7' => array( 'field' => 'llave_unica_cargo_abono_tr_compras_requisiciones_01_uuid_pago',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => false ),
'grid_field_label6' => array( 'type' => 'grid_field_label',
'field' => 'llave_unica_cargo_abono_tr_compras_requisiciones_01_uuid_pago',
'clickSort' => true ),
'search_panel_field5' => array( 'field' => 'fecha_de_compra',
'type' => 'search_panel_field' ),
'search_panel_field6' => array( 'field' => 'importe_abono_compra',
'type' => 'search_panel_field' ),
'search_panel_field7' => array( 'field' => 'uuid_cargo_abono_compra',
'type' => 'search_panel_field' ),
'grid_field8' => array( 'field' => 'cat_finanzas_cuentas_de_balance_04_llave',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'grid_field_label7' => array( 'type' => 'grid_field_label',
'field' => 'cat_finanzas_cuentas_de_balance_04_llave',
'clickSort' => true ),
'search_panel_field8' => array( 'field' => 'cat_finanzas_cuentas_de_balance_04_llave',
'type' => 'search_panel_field',
'alwaysOnPanel' => false,
'required' => false ),
'custom_button2' => array( 'eventId' => 'insert_pagos_tr_compras_proveedores_01_cargos_abonos',
'label' => array( 'type' => 0,
'text' => 'Afectar pago directo' ),
'type' => 'custom_button',
'buttonStyle' => 'warning' ),
'inline_save_all1' => array( 'type' => 'inline_save_all' ),
'inline_save_all2' => array( 'type' => 'inline_save_all' ),
'expand_button' => array( 'type' => 'expand_button' ),
'search_panel_field9' => array( 'field' => 'orden_de_compra_proveedor',
'type' => 'search_panel_field' ),
'-4' => array( 'type' => '-' ),
'grid_field9' => array( 'field' => 'alias_proveedor',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label8' => array( 'type' => 'grid_field_label',
'field' => 'alias_proveedor',
'clickSort' => true ),
'grid_field10' => array( 'field' => 'referencia',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label9' => array( 'type' => 'grid_field_label',
'field' => 'referencia',
'clickSort' => true ),
'simple_search_field' => array( 'type' => 'simple_search_field' ),
'simple_search_option' => array( 'type' => 'simple_search_option' ) ),
'dbProps' => array(  ),
'spreadsheetGrid' => false,
'version' => 14,
'reorderRows' => false,
'reorderRowsField' => '',
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>