<?php
			$optionsArray = array( 'list' => array( 'inlineAdd' => false,
'detailsAdd' => true,
'inlineEdit' => false,
'spreadsheetMode' => false,
'addToBottom' => false,
'delete' => false,
'updateSelected' => false,
'addInPopup' => null,
'editInPopup' => null,
'viewInPopup' => null,
'clickSort' => true,
'sortDropdown' => false,
'showHideFields' => false,
'reorderFields' => false,
'fieldFilter' => false,
'hideNumberOfRecords' => false ),
'master' => array( 'tr_compras_facturas_sat_01' => array( 'preview' => true ),
'tr_compras_facturas_sat_01_estatus' => array( 'preview' => true ),
'tr_compras_proveedores_01_cargos_abonos' => array( 'preview' => true ),
'tr_compras_proveedores_01_cargos_abonos_pagos_edit' => array( 'preview' => true ) ),
'listSearch' => array( 'alwaysOnPanelFields' => array(  ),
'searchPanel' => true,
'fixedSearchPanel' => false,
'simpleSearchOptions' => true,
'searchSaving' => false ),
'totals' => array( 'fecha_de_carga' => array( 'totalsType' => '' ),
'tr_compras_facturas_sat_02_carga_masiva_id' => array( 'totalsType' => '' ),
'consecutivo_uuid' => array( 'totalsType' => '' ),
'llave_consecutivo_uudi' => array( 'totalsType' => '' ),
'capturista' => array( 'totalsType' => '' ),
'UUID' => array( 'totalsType' => '' ),
'UUIDs_relacionados' => array( 'totalsType' => '' ),
'Tipo_relacion' => array( 'totalsType' => '' ),
'CP_Expedicion' => array( 'totalsType' => '' ),
'Serie' => array( 'totalsType' => '' ),
'Folio' => array( 'totalsType' => '' ),
'Fecha_emision' => array( 'totalsType' => '' ),
'Fecha_certificacion' => array( 'totalsType' => '' ),
'Nombre_emisor' => array( 'totalsType' => '' ),
'RFC_emisor' => array( 'totalsType' => '' ),
'Nombre_receptor' => array( 'totalsType' => '' ),
'RFC_receptor' => array( 'totalsType' => '' ),
'Uso_CFDI' => array( 'totalsType' => '' ),
'Efecto' => array( 'totalsType' => '' ),
'Tipo' => array( 'totalsType' => '' ),
'Estado_factura' => array( 'totalsType' => '' ),
'Fecha_proceso_cancelacion' => array( 'totalsType' => '' ),
'Estado_cancelacion' => array( 'totalsType' => '' ),
'Estado_proceso_cancelacion' => array( 'totalsType' => '' ),
'Motivo_cancelacion' => array( 'totalsType' => '' ),
'Folio_sustitucion_cancelacion' => array( 'totalsType' => '' ),
'ClaveProdServ' => array( 'totalsType' => '' ),
'No_Identificacion' => array( 'totalsType' => '' ),
'Metodo_pago' => array( 'totalsType' => '' ),
'Forma_pago' => array( 'totalsType' => '' ),
'Descripcion' => array( 'totalsType' => '' ),
'Unidad' => array( 'totalsType' => '' ),
'Clave_unidad' => array( 'totalsType' => '' ),
'Cantidad' => array( 'totalsType' => '' ),
'Valor_unitario' => array( 'totalsType' => '' ),
'Importe' => array( 'totalsType' => '' ),
'IVA_Trasladado' => array( 'totalsType' => '' ),
'IVA_Retenido' => array( 'totalsType' => '' ),
'ISR_Retenido' => array( 'totalsType' => '' ),
'IEPS_Trasladado' => array( 'totalsType' => '' ),
'Local_retenido' => array( 'totalsType' => '' ),
'Local_trasladado' => array( 'totalsType' => '' ),
'Descuento' => array( 'totalsType' => '' ),
'Tipo_cambio' => array( 'totalsType' => '' ),
'Moneda' => array( 'totalsType' => '' ),
'Version' => array( 'totalsType' => '' ),
'cat_compras_productos_id' => array( 'totalsType' => '' ),
'cat_compras_productos_unidad_de_medida_mu_id_entrada' => array( 'totalsType' => '' ),
'cat_compras_productos_unidad_de_medida_mu_id_salida' => array( 'totalsType' => '' ),
'cat_finanzas_cuentas_de_balance_04_id_cargo' => array( 'totalsType' => '' ),
'cat_finanzas_cuentas_de_balance_04_id_abono' => array( 'totalsType' => '' ),
'check_pseudofactura' => array( 'totalsType' => '' ),
'rfc_licencia' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'cat_compras_productos_id',
'Descripcion',
'ClaveProdServ',
'No_Identificacion',
'Unidad',
'Clave_unidad',
'Cantidad',
'Valor_unitario',
'Importe',
'IVA_Trasladado',
'IVA_Retenido',
'ISR_Retenido',
'IEPS_Trasladado',
'Local_retenido',
'Local_trasladado',
'Descuento',
'Tipo_cambio',
'Moneda',
'fecha_de_carga',
'capturista',
'UUID' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array( 'fecha_de_carga',
'rfc_licencia',
'check_pseudofactura',
'cat_finanzas_cuentas_de_balance_04_id_abono',
'cat_finanzas_cuentas_de_balance_04_id_cargo',
'cat_compras_productos_unidad_de_medida_mu_id_salida',
'cat_compras_productos_unidad_de_medida_mu_id_entrada',
'cat_compras_productos_id',
'Version',
'Moneda',
'Tipo_cambio',
'Descuento',
'Local_trasladado',
'Local_retenido',
'IEPS_Trasladado',
'ISR_Retenido',
'IVA_Retenido',
'IVA_Trasladado',
'Importe',
'Valor_unitario',
'Cantidad',
'Clave_unidad',
'Unidad',
'Descripcion',
'Forma_pago',
'Metodo_pago',
'No_Identificacion',
'ClaveProdServ',
'Folio_sustitucion_cancelacion',
'Motivo_cancelacion',
'Estado_proceso_cancelacion',
'Estado_cancelacion',
'Fecha_proceso_cancelacion',
'Estado_factura',
'Tipo',
'Efecto',
'Uso_CFDI',
'RFC_receptor',
'Nombre_receptor',
'RFC_emisor',
'Nombre_emisor',
'Fecha_certificacion',
'Fecha_emision',
'Folio',
'Serie',
'CP_Expedicion',
'Tipo_relacion',
'UUIDs_relacionados',
'UUID',
'capturista',
'llave_consecutivo_uudi',
'consecutivo_uuid',
'tr_compras_facturas_sat_02_carga_masiva_id' ),
'filterFields' => array(  ),
'inlineAddFields' => array(  ),
'inlineEditFields' => array(  ),
'fieldItems' => array( 'cat_compras_productos_id' => array( 'simple_grid_field46',
'simple_grid_field47' ),
'Descripcion' => array( 'simple_grid_field30',
'simple_grid_field45' ),
'ClaveProdServ' => array( 'simple_grid_field26',
'simple_grid_field28' ),
'No_Identificacion' => array( 'simple_grid_field27',
'simple_grid_field29' ),
'Unidad' => array( 'simple_grid_field31',
'simple_grid_field48' ),
'Clave_unidad' => array( 'simple_grid_field32',
'simple_grid_field49' ),
'Cantidad' => array( 'simple_grid_field33',
'simple_grid_field50' ),
'Valor_unitario' => array( 'simple_grid_field34',
'simple_grid_field51' ),
'Importe' => array( 'simple_grid_field35',
'simple_grid_field52' ),
'IVA_Trasladado' => array( 'simple_grid_field36',
'simple_grid_field53' ),
'IVA_Retenido' => array( 'simple_grid_field37',
'simple_grid_field54' ),
'ISR_Retenido' => array( 'simple_grid_field38',
'simple_grid_field55' ),
'IEPS_Trasladado' => array( 'simple_grid_field39',
'simple_grid_field56' ),
'Local_retenido' => array( 'simple_grid_field40',
'simple_grid_field57' ),
'Local_trasladado' => array( 'simple_grid_field41',
'simple_grid_field58' ),
'Descuento' => array( 'simple_grid_field42',
'simple_grid_field59' ),
'Tipo_cambio' => array( 'simple_grid_field43',
'simple_grid_field60' ),
'Moneda' => array( 'simple_grid_field44',
'simple_grid_field61' ),
'fecha_de_carga' => array( 'simple_grid_field',
'simple_grid_field1' ),
'capturista' => array( 'simple_grid_field4',
'simple_grid_field6' ),
'UUID' => array( 'simple_grid_field5',
'simple_grid_field7' ) ),
'hideEmptyFields' => array(  ),
'fieldFilterFields' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'inline_add',
'details_found',
'page_size' ),
'below-grid' => array( 'pagination' ),
'left' => array( 'logo',
'expand_button',
'menu',
'search_panel' ),
'supertop' => array( 'expand_menu_button',
'collapse_button',
'breadcrumb',
'simple_search_field',
'simple_search_option',
'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'top' => array( 'master_info' ),
'grid' => array( 'simple_grid_field47',
'simple_grid_field46',
'simple_grid_field45',
'simple_grid_field30',
'simple_grid_field28',
'simple_grid_field26',
'simple_grid_field29',
'simple_grid_field27',
'simple_grid_field48',
'simple_grid_field31',
'simple_grid_field49',
'simple_grid_field32',
'simple_grid_field50',
'simple_grid_field33',
'simple_grid_field51',
'simple_grid_field34',
'simple_grid_field52',
'simple_grid_field35',
'simple_grid_field53',
'simple_grid_field36',
'simple_grid_field54',
'simple_grid_field37',
'simple_grid_field55',
'simple_grid_field38',
'simple_grid_field56',
'simple_grid_field39',
'simple_grid_field57',
'simple_grid_field40',
'simple_grid_field58',
'simple_grid_field41',
'simple_grid_field59',
'simple_grid_field42',
'simple_grid_field60',
'simple_grid_field43',
'simple_grid_field61',
'simple_grid_field44',
'simple_grid_field1',
'simple_grid_field',
'simple_grid_field6',
'simple_grid_field4',
'simple_grid_field7',
'simple_grid_field5',
'grid_checkbox_head',
'grid_checkbox',
'grid_inline_cancel' ) ),
'formXtTags' => array( 'above-grid' => array( 'inlineadd_link',
'details_found',
'recsPerPage' ),
'below-grid' => array( 'pagination' ),
'top' => array( 'mastertable_block' ) ),
'itemForms' => array( 'inline_add' => 'above-grid',
'details_found' => 'above-grid',
'page_size' => 'above-grid',
'pagination' => 'below-grid',
'logo' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'search_panel' => 'left',
'expand_menu_button' => 'supertop',
'collapse_button' => 'supertop',
'breadcrumb' => 'supertop',
'simple_search_field' => 'supertop',
'simple_search_option' => 'supertop',
'simple_search' => 'supertop',
'list_options' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'master_info' => 'top',
'simple_grid_field47' => 'grid',
'simple_grid_field46' => 'grid',
'simple_grid_field45' => 'grid',
'simple_grid_field30' => 'grid',
'simple_grid_field28' => 'grid',
'simple_grid_field26' => 'grid',
'simple_grid_field29' => 'grid',
'simple_grid_field27' => 'grid',
'simple_grid_field48' => 'grid',
'simple_grid_field31' => 'grid',
'simple_grid_field49' => 'grid',
'simple_grid_field32' => 'grid',
'simple_grid_field50' => 'grid',
'simple_grid_field33' => 'grid',
'simple_grid_field51' => 'grid',
'simple_grid_field34' => 'grid',
'simple_grid_field52' => 'grid',
'simple_grid_field35' => 'grid',
'simple_grid_field53' => 'grid',
'simple_grid_field36' => 'grid',
'simple_grid_field54' => 'grid',
'simple_grid_field37' => 'grid',
'simple_grid_field55' => 'grid',
'simple_grid_field38' => 'grid',
'simple_grid_field56' => 'grid',
'simple_grid_field39' => 'grid',
'simple_grid_field57' => 'grid',
'simple_grid_field40' => 'grid',
'simple_grid_field58' => 'grid',
'simple_grid_field41' => 'grid',
'simple_grid_field59' => 'grid',
'simple_grid_field42' => 'grid',
'simple_grid_field60' => 'grid',
'simple_grid_field43' => 'grid',
'simple_grid_field61' => 'grid',
'simple_grid_field44' => 'grid',
'simple_grid_field1' => 'grid',
'simple_grid_field' => 'grid',
'simple_grid_field6' => 'grid',
'simple_grid_field4' => 'grid',
'simple_grid_field7' => 'grid',
'simple_grid_field5' => 'grid',
'grid_checkbox_head' => 'grid',
'grid_checkbox' => 'grid',
'grid_inline_cancel' => 'grid' ),
'itemLocations' => array( 'simple_grid_field47' => array( 'location' => 'grid',
'cellId' => 'headcell_field' ),
'simple_grid_field46' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'simple_grid_field45' => array( 'location' => 'grid',
'cellId' => 'headcell_field1' ),
'simple_grid_field30' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'simple_grid_field28' => array( 'location' => 'grid',
'cellId' => 'headcell_field2' ),
'simple_grid_field26' => array( 'location' => 'grid',
'cellId' => 'cell_field2' ),
'simple_grid_field29' => array( 'location' => 'grid',
'cellId' => 'headcell_field3' ),
'simple_grid_field27' => array( 'location' => 'grid',
'cellId' => 'cell_field3' ),
'simple_grid_field48' => array( 'location' => 'grid',
'cellId' => 'headcell_field4' ),
'simple_grid_field31' => array( 'location' => 'grid',
'cellId' => 'cell_field4' ),
'simple_grid_field49' => array( 'location' => 'grid',
'cellId' => 'headcell_field5' ),
'simple_grid_field32' => array( 'location' => 'grid',
'cellId' => 'cell_field5' ),
'simple_grid_field50' => array( 'location' => 'grid',
'cellId' => 'headcell_field6' ),
'simple_grid_field33' => array( 'location' => 'grid',
'cellId' => 'cell_field6' ),
'simple_grid_field51' => array( 'location' => 'grid',
'cellId' => 'headcell_field7' ),
'simple_grid_field34' => array( 'location' => 'grid',
'cellId' => 'cell_field7' ),
'simple_grid_field52' => array( 'location' => 'grid',
'cellId' => 'headcell_field8' ),
'simple_grid_field35' => array( 'location' => 'grid',
'cellId' => 'cell_field8' ),
'simple_grid_field53' => array( 'location' => 'grid',
'cellId' => 'headcell_field9' ),
'simple_grid_field36' => array( 'location' => 'grid',
'cellId' => 'cell_field9' ),
'simple_grid_field54' => array( 'location' => 'grid',
'cellId' => 'headcell_field10' ),
'simple_grid_field37' => array( 'location' => 'grid',
'cellId' => 'cell_field10' ),
'simple_grid_field55' => array( 'location' => 'grid',
'cellId' => 'headcell_field11' ),
'simple_grid_field38' => array( 'location' => 'grid',
'cellId' => 'cell_field11' ),
'simple_grid_field56' => array( 'location' => 'grid',
'cellId' => 'headcell_field12' ),
'simple_grid_field39' => array( 'location' => 'grid',
'cellId' => 'cell_field12' ),
'simple_grid_field57' => array( 'location' => 'grid',
'cellId' => 'headcell_field13' ),
'simple_grid_field40' => array( 'location' => 'grid',
'cellId' => 'cell_field13' ),
'simple_grid_field58' => array( 'location' => 'grid',
'cellId' => 'headcell_field14' ),
'simple_grid_field41' => array( 'location' => 'grid',
'cellId' => 'cell_field14' ),
'simple_grid_field59' => array( 'location' => 'grid',
'cellId' => 'headcell_field15' ),
'simple_grid_field42' => array( 'location' => 'grid',
'cellId' => 'cell_field15' ),
'simple_grid_field60' => array( 'location' => 'grid',
'cellId' => 'headcell_field16' ),
'simple_grid_field43' => array( 'location' => 'grid',
'cellId' => 'cell_field16' ),
'simple_grid_field61' => array( 'location' => 'grid',
'cellId' => 'headcell_field17' ),
'simple_grid_field44' => array( 'location' => 'grid',
'cellId' => 'cell_field17' ),
'simple_grid_field1' => array( 'location' => 'grid',
'cellId' => 'headcell_field18' ),
'simple_grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field18' ),
'simple_grid_field6' => array( 'location' => 'grid',
'cellId' => 'headcell_field19' ),
'simple_grid_field4' => array( 'location' => 'grid',
'cellId' => 'cell_field19' ),
'simple_grid_field7' => array( 'location' => 'grid',
'cellId' => 'headcell_field20' ),
'simple_grid_field5' => array( 'location' => 'grid',
'cellId' => 'cell_field20' ),
'grid_checkbox_head' => array( 'location' => 'grid',
'cellId' => 'headcell_checkbox' ),
'grid_checkbox' => array( 'location' => 'grid',
'cellId' => 'cell_checkbox' ),
'grid_inline_cancel' => array( 'location' => 'grid',
'cellId' => 'cell_icons' ) ),
'itemVisiblity' => array( 'breadcrumb' => 5,
'expand_menu_button' => 2,
'expand_button' => 5 ) ),
'itemsByType' => array( 'page_size' => array( 'page_size' ),
'details_found' => array( 'details_found' ),
'breadcrumb' => array( 'breadcrumb' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'simple_search' => array( 'simple_search' ),
'pagination' => array( 'pagination' ),
'list_options' => array( 'list_options' ),
'-' => array( '-3',
'-',
'-1',
'-2' ),
'advsearch_link' => array( 'advsearch_link' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'userinfo_link' => array( 'userinfo_link' ),
'logout_link' => array( 'logout_link' ),
'adminarea_link' => array( 'adminarea_link' ),
'changepassword_link' => array( 'changepassword_link' ),
'expand_menu_button' => array( 'expand_menu_button' ),
'collapse_button' => array( 'collapse_button' ),
'master_info' => array( 'master_info' ),
'search_panel' => array( 'search_panel' ),
'show_search_panel' => array( 'show_search_panel' ),
'hide_search_panel' => array( 'hide_search_panel' ),
'search_panel_field' => array( 'search_panel_field',
'search_panel_field1',
'search_panel_field2',
'search_panel_field3',
'search_panel_field4',
'search_panel_field5',
'search_panel_field6',
'search_panel_field7',
'search_panel_field8',
'search_panel_field9',
'search_panel_field10',
'search_panel_field11',
'search_panel_field12',
'search_panel_field13',
'search_panel_field14',
'search_panel_field15',
'search_panel_field16',
'search_panel_field17',
'search_panel_field18',
'search_panel_field19',
'search_panel_field20',
'search_panel_field21',
'search_panel_field22',
'search_panel_field23',
'search_panel_field24',
'search_panel_field25',
'search_panel_field26',
'search_panel_field27',
'search_panel_field28',
'search_panel_field29',
'search_panel_field30',
'search_panel_field31',
'search_panel_field32',
'search_panel_field33',
'search_panel_field34',
'search_panel_field35',
'search_panel_field36',
'search_panel_field37',
'search_panel_field38',
'search_panel_field39',
'search_panel_field40',
'search_panel_field41',
'search_panel_field42',
'search_panel_field43',
'search_panel_field44',
'search_panel_field45',
'search_panel_field46',
'search_panel_field47',
'search_panel_field48',
'search_panel_field49',
'search_panel_field50',
'search_panel_field51',
'search_panel_field52' ),
'simple_search_field' => array( 'simple_search_field' ),
'simple_search_option' => array( 'simple_search_option' ),
'grid_field' => array( 'simple_grid_field46',
'simple_grid_field30',
'simple_grid_field26',
'simple_grid_field27',
'simple_grid_field31',
'simple_grid_field32',
'simple_grid_field33',
'simple_grid_field34',
'simple_grid_field35',
'simple_grid_field36',
'simple_grid_field37',
'simple_grid_field38',
'simple_grid_field39',
'simple_grid_field40',
'simple_grid_field41',
'simple_grid_field42',
'simple_grid_field43',
'simple_grid_field44',
'simple_grid_field',
'simple_grid_field4',
'simple_grid_field5' ),
'grid_field_label' => array( 'simple_grid_field47',
'simple_grid_field45',
'simple_grid_field28',
'simple_grid_field29',
'simple_grid_field48',
'simple_grid_field49',
'simple_grid_field50',
'simple_grid_field51',
'simple_grid_field52',
'simple_grid_field53',
'simple_grid_field54',
'simple_grid_field55',
'simple_grid_field56',
'simple_grid_field57',
'simple_grid_field58',
'simple_grid_field59',
'simple_grid_field60',
'simple_grid_field61',
'simple_grid_field1',
'simple_grid_field6',
'simple_grid_field7' ),
'grid_checkbox' => array( 'grid_checkbox' ),
'grid_checkbox_head' => array( 'grid_checkbox_head' ),
'expand_button' => array( 'expand_button' ),
'inline_add' => array( 'inline_add' ),
'grid_inline_cancel' => array( 'grid_inline_cancel' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'headcell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_checkbox' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array( 'checkbox_column' ),
'items' => array( 'grid_checkbox_head' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array( 'cat_compras_productos_id_fieldheadercolumn' ),
'items' => array( 'simple_grid_field47' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field1' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array( 'Descripcion_fieldheadercolumn' ),
'items' => array( 'simple_grid_field45' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field2' => array( 'cols' => array( 4 ),
'rows' => array( 0 ),
'tags' => array( 'ClaveProdServ_fieldheadercolumn' ),
'items' => array( 'simple_grid_field28' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field3' => array( 'cols' => array( 5 ),
'rows' => array( 0 ),
'tags' => array( 'No_Identificacion_fieldheadercolumn' ),
'items' => array( 'simple_grid_field29' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field4' => array( 'cols' => array( 6 ),
'rows' => array( 0 ),
'tags' => array( 'Unidad_fieldheadercolumn' ),
'items' => array( 'simple_grid_field48' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field5' => array( 'cols' => array( 7 ),
'rows' => array( 0 ),
'tags' => array( 'Clave_unidad_fieldheadercolumn' ),
'items' => array( 'simple_grid_field49' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field6' => array( 'cols' => array( 8 ),
'rows' => array( 0 ),
'tags' => array( 'Cantidad_fieldheadercolumn' ),
'items' => array( 'simple_grid_field50' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field7' => array( 'cols' => array( 9 ),
'rows' => array( 0 ),
'tags' => array( 'Valor_unitario_fieldheadercolumn' ),
'items' => array( 'simple_grid_field51' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field8' => array( 'cols' => array( 10 ),
'rows' => array( 0 ),
'tags' => array( 'Importe_fieldheadercolumn' ),
'items' => array( 'simple_grid_field52' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field9' => array( 'cols' => array( 11 ),
'rows' => array( 0 ),
'tags' => array( 'IVA_Trasladado_fieldheadercolumn' ),
'items' => array( 'simple_grid_field53' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field10' => array( 'cols' => array( 12 ),
'rows' => array( 0 ),
'tags' => array( 'IVA_Retenido_fieldheadercolumn' ),
'items' => array( 'simple_grid_field54' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field11' => array( 'cols' => array( 13 ),
'rows' => array( 0 ),
'tags' => array( 'ISR_Retenido_fieldheadercolumn' ),
'items' => array( 'simple_grid_field55' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field12' => array( 'cols' => array( 14 ),
'rows' => array( 0 ),
'tags' => array( 'IEPS_Trasladado_fieldheadercolumn' ),
'items' => array( 'simple_grid_field56' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field13' => array( 'cols' => array( 15 ),
'rows' => array( 0 ),
'tags' => array( 'Local_retenido_fieldheadercolumn' ),
'items' => array( 'simple_grid_field57' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field14' => array( 'cols' => array( 16 ),
'rows' => array( 0 ),
'tags' => array( 'Local_trasladado_fieldheadercolumn' ),
'items' => array( 'simple_grid_field58' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field15' => array( 'cols' => array( 17 ),
'rows' => array( 0 ),
'tags' => array( 'Descuento_fieldheadercolumn' ),
'items' => array( 'simple_grid_field59' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field16' => array( 'cols' => array( 18 ),
'rows' => array( 0 ),
'tags' => array( 'Tipo_cambio_fieldheadercolumn' ),
'items' => array( 'simple_grid_field60' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field17' => array( 'cols' => array( 19 ),
'rows' => array( 0 ),
'tags' => array( 'Moneda_fieldheadercolumn' ),
'items' => array( 'simple_grid_field61' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field18' => array( 'cols' => array( 20 ),
'rows' => array( 0 ),
'tags' => array( 'fecha_de_carga_fieldheadercolumn' ),
'items' => array( 'simple_grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field19' => array( 'cols' => array( 21 ),
'rows' => array( 0 ),
'tags' => array( 'capturista_fieldheadercolumn' ),
'items' => array( 'simple_grid_field6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field20' => array( 'cols' => array( 22 ),
'rows' => array( 0 ),
'tags' => array( 'UUID_fieldheadercolumn' ),
'items' => array( 'simple_grid_field7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'inline_cancel' ),
'items' => array( 'grid_inline_cancel' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_checkbox' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array( 'checkbox_column' ),
'items' => array( 'grid_checkbox' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array( 'cat_compras_productos_id_fieldcolumn' ),
'items' => array( 'simple_grid_field46' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array( 'Descripcion_fieldcolumn' ),
'items' => array( 'simple_grid_field30' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 4 ),
'rows' => array( 1 ),
'tags' => array( 'ClaveProdServ_fieldcolumn' ),
'items' => array( 'simple_grid_field26' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field3' => array( 'cols' => array( 5 ),
'rows' => array( 1 ),
'tags' => array( 'No_Identificacion_fieldcolumn' ),
'items' => array( 'simple_grid_field27' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field4' => array( 'cols' => array( 6 ),
'rows' => array( 1 ),
'tags' => array( 'Unidad_fieldcolumn' ),
'items' => array( 'simple_grid_field31' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field5' => array( 'cols' => array( 7 ),
'rows' => array( 1 ),
'tags' => array( 'Clave_unidad_fieldcolumn' ),
'items' => array( 'simple_grid_field32' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field6' => array( 'cols' => array( 8 ),
'rows' => array( 1 ),
'tags' => array( 'Cantidad_fieldcolumn' ),
'items' => array( 'simple_grid_field33' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field7' => array( 'cols' => array( 9 ),
'rows' => array( 1 ),
'tags' => array( 'Valor_unitario_fieldcolumn' ),
'items' => array( 'simple_grid_field34' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field8' => array( 'cols' => array( 10 ),
'rows' => array( 1 ),
'tags' => array( 'Importe_fieldcolumn' ),
'items' => array( 'simple_grid_field35' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field9' => array( 'cols' => array( 11 ),
'rows' => array( 1 ),
'tags' => array( 'IVA_Trasladado_fieldcolumn' ),
'items' => array( 'simple_grid_field36' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field10' => array( 'cols' => array( 12 ),
'rows' => array( 1 ),
'tags' => array( 'IVA_Retenido_fieldcolumn' ),
'items' => array( 'simple_grid_field37' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field11' => array( 'cols' => array( 13 ),
'rows' => array( 1 ),
'tags' => array( 'ISR_Retenido_fieldcolumn' ),
'items' => array( 'simple_grid_field38' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field12' => array( 'cols' => array( 14 ),
'rows' => array( 1 ),
'tags' => array( 'IEPS_Trasladado_fieldcolumn' ),
'items' => array( 'simple_grid_field39' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field13' => array( 'cols' => array( 15 ),
'rows' => array( 1 ),
'tags' => array( 'Local_retenido_fieldcolumn' ),
'items' => array( 'simple_grid_field40' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field14' => array( 'cols' => array( 16 ),
'rows' => array( 1 ),
'tags' => array( 'Local_trasladado_fieldcolumn' ),
'items' => array( 'simple_grid_field41' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field15' => array( 'cols' => array( 17 ),
'rows' => array( 1 ),
'tags' => array( 'Descuento_fieldcolumn' ),
'items' => array( 'simple_grid_field42' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field16' => array( 'cols' => array( 18 ),
'rows' => array( 1 ),
'tags' => array( 'Tipo_cambio_fieldcolumn' ),
'items' => array( 'simple_grid_field43' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field17' => array( 'cols' => array( 19 ),
'rows' => array( 1 ),
'tags' => array( 'Moneda_fieldcolumn' ),
'items' => array( 'simple_grid_field44' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field18' => array( 'cols' => array( 20 ),
'rows' => array( 1 ),
'tags' => array( 'fecha_de_carga_fieldcolumn' ),
'items' => array( 'simple_grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field19' => array( 'cols' => array( 21 ),
'rows' => array( 1 ),
'tags' => array( 'capturista_fieldcolumn' ),
'items' => array( 'simple_grid_field4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field20' => array( 'cols' => array( 22 ),
'rows' => array( 1 ),
'tags' => array( 'UUID_fieldcolumn' ),
'items' => array( 'simple_grid_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_checkbox' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field1' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field2' => array( 'cols' => array( 4 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field3' => array( 'cols' => array( 5 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field4' => array( 'cols' => array( 6 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field5' => array( 'cols' => array( 7 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field6' => array( 'cols' => array( 8 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field7' => array( 'cols' => array( 9 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field8' => array( 'cols' => array( 10 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field9' => array( 'cols' => array( 11 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field10' => array( 'cols' => array( 12 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field11' => array( 'cols' => array( 13 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field12' => array( 'cols' => array( 14 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field13' => array( 'cols' => array( 15 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field14' => array( 'cols' => array( 16 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field15' => array( 'cols' => array( 17 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field16' => array( 'cols' => array( 18 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field17' => array( 'cols' => array( 19 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field18' => array( 'cols' => array( 20 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field19' => array( 'cols' => array( 21 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field20' => array( 'cols' => array( 22 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 23,
'height' => 3 ) ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array( 'details_found' => array( 'tag' => 'DISPLAYING',
'type' => 2 ) ) ),
'gridType' => 0,
'recsPerRow' => 1,
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array( array( 'id' => 'main',
'horizontal' => false ) ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'list',
'breadcrumb' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'list',
'type' => 'list',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'list-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'inline_add' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'details_found',
'page_size' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'list-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'pagination' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo',
'expand_button' ) ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu',
'search_panel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'expand_menu_button',
'collapse_button',
'breadcrumb' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'simple_search_field',
'simple_search_option',
'simple_search',
'list_options',
'loginform_login',
'username_button' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'list-sidebar-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c2' => array( 'model' => 'c2',
'items' => array( 'master_info' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'horizontal-grid',
'grid' => array( array( 'section' => 'head',
'cells' => array( array( 'cell' => 'headcell_icons' ),
array( 'cell' => 'headcell_checkbox' ),
array( 'cell' => 'headcell_field' ),
array( 'cell' => 'headcell_field1' ),
array( 'cell' => 'headcell_field2' ),
array( 'cell' => 'headcell_field3' ),
array( 'cell' => 'headcell_field4' ),
array( 'cell' => 'headcell_field5' ),
array( 'cell' => 'headcell_field6' ),
array( 'cell' => 'headcell_field7' ),
array( 'cell' => 'headcell_field8' ),
array( 'cell' => 'headcell_field9' ),
array( 'cell' => 'headcell_field10' ),
array( 'cell' => 'headcell_field11' ),
array( 'cell' => 'headcell_field12' ),
array( 'cell' => 'headcell_field13' ),
array( 'cell' => 'headcell_field14' ),
array( 'cell' => 'headcell_field15' ),
array( 'cell' => 'headcell_field16' ),
array( 'cell' => 'headcell_field17' ),
array( 'cell' => 'headcell_field18' ),
array( 'cell' => 'headcell_field19' ),
array( 'cell' => 'headcell_field20' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_icons' ),
array( 'cell' => 'cell_checkbox' ),
array( 'cell' => 'cell_field' ),
array( 'cell' => 'cell_field1' ),
array( 'cell' => 'cell_field2' ),
array( 'cell' => 'cell_field3' ),
array( 'cell' => 'cell_field4' ),
array( 'cell' => 'cell_field5' ),
array( 'cell' => 'cell_field6' ),
array( 'cell' => 'cell_field7' ),
array( 'cell' => 'cell_field8' ),
array( 'cell' => 'cell_field9' ),
array( 'cell' => 'cell_field10' ),
array( 'cell' => 'cell_field11' ),
array( 'cell' => 'cell_field12' ),
array( 'cell' => 'cell_field13' ),
array( 'cell' => 'cell_field14' ),
array( 'cell' => 'cell_field15' ),
array( 'cell' => 'cell_field16' ),
array( 'cell' => 'cell_field17' ),
array( 'cell' => 'cell_field18' ),
array( 'cell' => 'cell_field19' ),
array( 'cell' => 'cell_field20' ) ) ),
array( 'section' => 'foot',
'cells' => array( array( 'cell' => 'footcell_icons' ),
array( 'cell' => 'footcell_checkbox' ),
array( 'cell' => 'footcell_field' ),
array( 'cell' => 'footcell_field1' ),
array( 'cell' => 'footcell_field2' ),
array( 'cell' => 'footcell_field3' ),
array( 'cell' => 'footcell_field4' ),
array( 'cell' => 'footcell_field5' ),
array( 'cell' => 'footcell_field6' ),
array( 'cell' => 'footcell_field7' ),
array( 'cell' => 'footcell_field8' ),
array( 'cell' => 'footcell_field9' ),
array( 'cell' => 'footcell_field10' ),
array( 'cell' => 'footcell_field11' ),
array( 'cell' => 'footcell_field12' ),
array( 'cell' => 'footcell_field13' ),
array( 'cell' => 'footcell_field14' ),
array( 'cell' => 'footcell_field15' ),
array( 'cell' => 'footcell_field16' ),
array( 'cell' => 'footcell_field17' ),
array( 'cell' => 'footcell_field18' ),
array( 'cell' => 'footcell_field19' ),
array( 'cell' => 'footcell_field20' ) ) ) ),
'cells' => array( 'headcell_field' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field47' ),
'field' => 'cat_compras_productos_id',
'columnName' => 'field' ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field46' ),
'field' => 'cat_compras_productos_id',
'columnName' => 'field' ),
'footcell_field' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field1' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field45' ),
'field' => 'Descripcion',
'columnName' => 'field' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field30' ),
'field' => 'Descripcion',
'columnName' => 'field' ),
'footcell_field1' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field2' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field28' ),
'field' => 'ClaveProdServ',
'columnName' => 'field' ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field26' ),
'field' => 'ClaveProdServ',
'columnName' => 'field' ),
'footcell_field2' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field3' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field29' ),
'field' => 'No_Identificacion',
'columnName' => 'field' ),
'cell_field3' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field27' ),
'field' => 'No_Identificacion',
'columnName' => 'field' ),
'footcell_field3' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field4' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field48' ),
'field' => 'Unidad',
'columnName' => 'field' ),
'cell_field4' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field31' ),
'field' => 'Unidad',
'columnName' => 'field' ),
'footcell_field4' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field5' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field49' ),
'field' => 'Clave_unidad',
'columnName' => 'field' ),
'cell_field5' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field32' ),
'field' => 'Clave_unidad',
'columnName' => 'field' ),
'footcell_field5' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field6' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field50' ),
'field' => 'Cantidad',
'columnName' => 'field' ),
'cell_field6' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field33' ),
'field' => 'Cantidad',
'columnName' => 'field' ),
'footcell_field6' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field7' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field51' ),
'field' => 'Valor_unitario',
'columnName' => 'field' ),
'cell_field7' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field34' ),
'field' => 'Valor_unitario',
'columnName' => 'field' ),
'footcell_field7' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field8' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field52' ),
'field' => 'Importe',
'columnName' => 'field' ),
'cell_field8' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field35' ),
'field' => 'Importe',
'columnName' => 'field' ),
'footcell_field8' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field9' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field53' ),
'field' => 'IVA_Trasladado',
'columnName' => 'field' ),
'cell_field9' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field36' ),
'field' => 'IVA_Trasladado',
'columnName' => 'field' ),
'footcell_field9' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field10' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field54' ),
'field' => 'IVA_Retenido',
'columnName' => 'field' ),
'cell_field10' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field37' ),
'field' => 'IVA_Retenido',
'columnName' => 'field' ),
'footcell_field10' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field11' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field55' ),
'field' => 'ISR_Retenido',
'columnName' => 'field' ),
'cell_field11' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field38' ),
'field' => 'ISR_Retenido',
'columnName' => 'field' ),
'footcell_field11' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field12' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field56' ),
'field' => 'IEPS_Trasladado',
'columnName' => 'field' ),
'cell_field12' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field39' ),
'field' => 'IEPS_Trasladado',
'columnName' => 'field' ),
'footcell_field12' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field13' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field57' ),
'field' => 'Local_retenido',
'columnName' => 'field' ),
'cell_field13' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field40' ),
'field' => 'Local_retenido',
'columnName' => 'field' ),
'footcell_field13' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field14' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field58' ),
'field' => 'Local_trasladado',
'columnName' => 'field' ),
'cell_field14' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field41' ),
'field' => 'Local_trasladado',
'columnName' => 'field' ),
'footcell_field14' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field15' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field59' ),
'field' => 'Descuento',
'columnName' => 'field' ),
'cell_field15' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field42' ),
'field' => 'Descuento',
'columnName' => 'field' ),
'footcell_field15' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field16' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field60' ),
'field' => 'Tipo_cambio',
'columnName' => 'field' ),
'cell_field16' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field43' ),
'field' => 'Tipo_cambio',
'columnName' => 'field' ),
'footcell_field16' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field17' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field61' ),
'field' => 'Moneda',
'columnName' => 'field' ),
'cell_field17' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field44' ),
'field' => 'Moneda',
'columnName' => 'field' ),
'footcell_field17' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field18' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field1' ),
'field' => 'fecha_de_carga',
'columnName' => 'field' ),
'cell_field18' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field' ),
'field' => 'fecha_de_carga',
'columnName' => 'field' ),
'footcell_field18' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field19' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field6' ),
'field' => 'capturista',
'columnName' => 'field' ),
'cell_field19' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field4' ),
'field' => 'capturista',
'columnName' => 'field' ),
'footcell_field19' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field20' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field7' ),
'field' => 'UUID',
'columnName' => 'field' ),
'cell_field20' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field5' ),
'field' => 'UUID',
'columnName' => 'field' ),
'footcell_field20' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_checkbox' => array( 'model' => 'headcell_checkbox',
'items' => array( 'grid_checkbox_head' ) ),
'cell_checkbox' => array( 'model' => 'cell_checkbox',
'items' => array( 'grid_checkbox' ) ),
'footcell_checkbox' => array( 'model' => 'footcell_checkbox',
'items' => array(  ) ),
'headcell_icons' => array( 'model' => 'headcell_icons',
'items' => array(  ) ),
'cell_icons' => array( 'model' => 'cell_icons',
'items' => array( 'grid_inline_cancel' ) ),
'footcell_icons' => array( 'model' => 'footcell_icons',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'page_size' => array( 'type' => 'page_size' ),
'details_found' => array( 'type' => 'details_found' ),
'breadcrumb' => array( 'type' => 'breadcrumb' ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'simple_search' => array( 'type' => 'simple_search' ),
'pagination' => array( 'type' => 'pagination' ),
'list_options' => array( 'type' => 'list_options',
'items' => array( 'advsearch_link',
'show_search_panel',
'hide_search_panel' ) ),
'-3' => array( 'type' => '-' ),
'advsearch_link' => array( 'type' => 'advsearch_link' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'adminarea_link',
'changepassword_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => false ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'logout_link' => array( 'type' => 'logout_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'changepassword_link' => array( 'type' => 'changepassword_link' ),
'expand_menu_button' => array( 'type' => 'expand_menu_button' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'-' => array( 'type' => '-' ),
'-1' => array( 'type' => '-' ),
'-2' => array( 'type' => '-' ),
'master_info' => array( 'type' => 'master_info',
'tables' => array( 'tr_compras_facturas_sat_01' => 'true',
'tr_compras_facturas_sat_01_estatus' => 'true',
'tr_compras_proveedores_01_cargos_abonos' => 'true',
'tr_compras_proveedores_01_cargos_abonos_pagos_edit' => 'true' ) ),
'search_panel' => array( 'type' => 'search_panel',
'items' => array( 'search_panel_field',
'search_panel_field52',
'search_panel_field51',
'search_panel_field50',
'search_panel_field49',
'search_panel_field48',
'search_panel_field47',
'search_panel_field46',
'search_panel_field45',
'search_panel_field44',
'search_panel_field43',
'search_panel_field42',
'search_panel_field41',
'search_panel_field40',
'search_panel_field39',
'search_panel_field38',
'search_panel_field37',
'search_panel_field36',
'search_panel_field35',
'search_panel_field34',
'search_panel_field33',
'search_panel_field32',
'search_panel_field31',
'search_panel_field30',
'search_panel_field29',
'search_panel_field28',
'search_panel_field27',
'search_panel_field26',
'search_panel_field25',
'search_panel_field24',
'search_panel_field23',
'search_panel_field22',
'search_panel_field21',
'search_panel_field20',
'search_panel_field19',
'search_panel_field18',
'search_panel_field17',
'search_panel_field16',
'search_panel_field15',
'search_panel_field14',
'search_panel_field13',
'search_panel_field12',
'search_panel_field11',
'search_panel_field10',
'search_panel_field9',
'search_panel_field8',
'search_panel_field7',
'search_panel_field6',
'search_panel_field5',
'search_panel_field4',
'search_panel_field3',
'search_panel_field2',
'search_panel_field1' ) ),
'show_search_panel' => array( 'type' => 'show_search_panel' ),
'hide_search_panel' => array( 'type' => 'hide_search_panel' ),
'search_panel_field' => array( 'field' => 'fecha_de_carga',
'type' => 'search_panel_field' ),
'search_panel_field1' => array( 'field' => 'tr_compras_facturas_sat_02_carga_masiva_id',
'type' => 'search_panel_field' ),
'search_panel_field2' => array( 'field' => 'consecutivo_uuid',
'type' => 'search_panel_field' ),
'search_panel_field3' => array( 'field' => 'llave_consecutivo_uudi',
'type' => 'search_panel_field' ),
'search_panel_field4' => array( 'field' => 'capturista',
'type' => 'search_panel_field' ),
'search_panel_field5' => array( 'field' => 'UUID',
'type' => 'search_panel_field' ),
'search_panel_field6' => array( 'field' => 'UUIDs_relacionados',
'type' => 'search_panel_field' ),
'search_panel_field7' => array( 'field' => 'Tipo_relacion',
'type' => 'search_panel_field' ),
'search_panel_field8' => array( 'field' => 'CP_Expedicion',
'type' => 'search_panel_field' ),
'search_panel_field9' => array( 'field' => 'Serie',
'type' => 'search_panel_field' ),
'search_panel_field10' => array( 'field' => 'Folio',
'type' => 'search_panel_field' ),
'search_panel_field11' => array( 'field' => 'Fecha_emision',
'type' => 'search_panel_field' ),
'search_panel_field12' => array( 'field' => 'Fecha_certificacion',
'type' => 'search_panel_field' ),
'search_panel_field13' => array( 'field' => 'Nombre_emisor',
'type' => 'search_panel_field' ),
'search_panel_field14' => array( 'field' => 'RFC_emisor',
'type' => 'search_panel_field' ),
'search_panel_field15' => array( 'field' => 'Nombre_receptor',
'type' => 'search_panel_field' ),
'search_panel_field16' => array( 'field' => 'RFC_receptor',
'type' => 'search_panel_field' ),
'search_panel_field17' => array( 'field' => 'Uso_CFDI',
'type' => 'search_panel_field' ),
'search_panel_field18' => array( 'field' => 'Efecto',
'type' => 'search_panel_field' ),
'search_panel_field19' => array( 'field' => 'Tipo',
'type' => 'search_panel_field' ),
'search_panel_field20' => array( 'field' => 'Estado_factura',
'type' => 'search_panel_field' ),
'search_panel_field21' => array( 'field' => 'Fecha_proceso_cancelacion',
'type' => 'search_panel_field' ),
'search_panel_field22' => array( 'field' => 'Estado_cancelacion',
'type' => 'search_panel_field' ),
'search_panel_field23' => array( 'field' => 'Estado_proceso_cancelacion',
'type' => 'search_panel_field' ),
'search_panel_field24' => array( 'field' => 'Motivo_cancelacion',
'type' => 'search_panel_field' ),
'search_panel_field25' => array( 'field' => 'Folio_sustitucion_cancelacion',
'type' => 'search_panel_field' ),
'search_panel_field26' => array( 'field' => 'ClaveProdServ',
'type' => 'search_panel_field' ),
'search_panel_field27' => array( 'field' => 'No_Identificacion',
'type' => 'search_panel_field' ),
'search_panel_field28' => array( 'field' => 'Metodo_pago',
'type' => 'search_panel_field' ),
'search_panel_field29' => array( 'field' => 'Forma_pago',
'type' => 'search_panel_field' ),
'search_panel_field30' => array( 'field' => 'Descripcion',
'type' => 'search_panel_field' ),
'search_panel_field31' => array( 'field' => 'Unidad',
'type' => 'search_panel_field' ),
'search_panel_field32' => array( 'field' => 'Clave_unidad',
'type' => 'search_panel_field' ),
'search_panel_field33' => array( 'field' => 'Cantidad',
'type' => 'search_panel_field' ),
'search_panel_field34' => array( 'field' => 'Valor_unitario',
'type' => 'search_panel_field' ),
'search_panel_field35' => array( 'field' => 'Importe',
'type' => 'search_panel_field' ),
'search_panel_field36' => array( 'field' => 'IVA_Trasladado',
'type' => 'search_panel_field' ),
'search_panel_field37' => array( 'field' => 'IVA_Retenido',
'type' => 'search_panel_field' ),
'search_panel_field38' => array( 'field' => 'ISR_Retenido',
'type' => 'search_panel_field' ),
'search_panel_field39' => array( 'field' => 'IEPS_Trasladado',
'type' => 'search_panel_field' ),
'search_panel_field40' => array( 'field' => 'Local_retenido',
'type' => 'search_panel_field' ),
'search_panel_field41' => array( 'field' => 'Local_trasladado',
'type' => 'search_panel_field' ),
'search_panel_field42' => array( 'field' => 'Descuento',
'type' => 'search_panel_field' ),
'search_panel_field43' => array( 'field' => 'Tipo_cambio',
'type' => 'search_panel_field' ),
'search_panel_field44' => array( 'field' => 'Moneda',
'type' => 'search_panel_field' ),
'search_panel_field45' => array( 'field' => 'Version',
'type' => 'search_panel_field' ),
'search_panel_field46' => array( 'field' => 'cat_compras_productos_id',
'type' => 'search_panel_field' ),
'search_panel_field47' => array( 'field' => 'cat_compras_productos_unidad_de_medida_mu_id_entrada',
'type' => 'search_panel_field' ),
'search_panel_field48' => array( 'field' => 'cat_compras_productos_unidad_de_medida_mu_id_salida',
'type' => 'search_panel_field' ),
'search_panel_field49' => array( 'field' => 'cat_finanzas_cuentas_de_balance_04_id_cargo',
'type' => 'search_panel_field' ),
'search_panel_field50' => array( 'field' => 'cat_finanzas_cuentas_de_balance_04_id_abono',
'type' => 'search_panel_field' ),
'search_panel_field51' => array( 'field' => 'check_pseudofactura',
'type' => 'search_panel_field' ),
'search_panel_field52' => array( 'field' => 'rfc_licencia',
'type' => 'search_panel_field' ),
'simple_search_field' => array( 'type' => 'simple_search_field' ),
'simple_search_option' => array( 'type' => 'simple_search_option' ),
'simple_grid_field46' => array( 'field' => 'cat_compras_productos_id',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field47' => array( 'type' => 'grid_field_label',
'field' => 'cat_compras_productos_id',
'clickSort' => true ),
'simple_grid_field30' => array( 'field' => 'Descripcion',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field45' => array( 'type' => 'grid_field_label',
'field' => 'Descripcion',
'clickSort' => true ),
'simple_grid_field26' => array( 'field' => 'ClaveProdServ',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field28' => array( 'type' => 'grid_field_label',
'field' => 'ClaveProdServ',
'clickSort' => true ),
'simple_grid_field27' => array( 'field' => 'No_Identificacion',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field29' => array( 'type' => 'grid_field_label',
'field' => 'No_Identificacion',
'clickSort' => true ),
'simple_grid_field31' => array( 'field' => 'Unidad',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field48' => array( 'type' => 'grid_field_label',
'field' => 'Unidad',
'clickSort' => true ),
'simple_grid_field32' => array( 'field' => 'Clave_unidad',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field49' => array( 'type' => 'grid_field_label',
'field' => 'Clave_unidad',
'clickSort' => true ),
'simple_grid_field33' => array( 'field' => 'Cantidad',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field50' => array( 'type' => 'grid_field_label',
'field' => 'Cantidad',
'clickSort' => true ),
'simple_grid_field34' => array( 'field' => 'Valor_unitario',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field51' => array( 'type' => 'grid_field_label',
'field' => 'Valor_unitario',
'clickSort' => true ),
'simple_grid_field35' => array( 'field' => 'Importe',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field52' => array( 'type' => 'grid_field_label',
'field' => 'Importe',
'clickSort' => true ),
'simple_grid_field36' => array( 'field' => 'IVA_Trasladado',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field53' => array( 'type' => 'grid_field_label',
'field' => 'IVA_Trasladado',
'clickSort' => true ),
'simple_grid_field37' => array( 'field' => 'IVA_Retenido',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field54' => array( 'type' => 'grid_field_label',
'field' => 'IVA_Retenido',
'clickSort' => true ),
'simple_grid_field38' => array( 'field' => 'ISR_Retenido',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field55' => array( 'type' => 'grid_field_label',
'field' => 'ISR_Retenido',
'clickSort' => true ),
'simple_grid_field39' => array( 'field' => 'IEPS_Trasladado',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field56' => array( 'type' => 'grid_field_label',
'field' => 'IEPS_Trasladado',
'clickSort' => true ),
'simple_grid_field40' => array( 'field' => 'Local_retenido',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field57' => array( 'type' => 'grid_field_label',
'field' => 'Local_retenido',
'clickSort' => true ),
'simple_grid_field41' => array( 'field' => 'Local_trasladado',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field58' => array( 'type' => 'grid_field_label',
'field' => 'Local_trasladado',
'clickSort' => true ),
'simple_grid_field42' => array( 'field' => 'Descuento',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field59' => array( 'type' => 'grid_field_label',
'field' => 'Descuento',
'clickSort' => true ),
'simple_grid_field43' => array( 'field' => 'Tipo_cambio',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field60' => array( 'type' => 'grid_field_label',
'field' => 'Tipo_cambio',
'clickSort' => true ),
'simple_grid_field44' => array( 'field' => 'Moneda',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field61' => array( 'type' => 'grid_field_label',
'field' => 'Moneda',
'clickSort' => true ),
'simple_grid_field' => array( 'field' => 'fecha_de_carga',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field1' => array( 'type' => 'grid_field_label',
'field' => 'fecha_de_carga',
'clickSort' => true ),
'simple_grid_field4' => array( 'field' => 'capturista',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field6' => array( 'type' => 'grid_field_label',
'field' => 'capturista',
'clickSort' => true ),
'simple_grid_field5' => array( 'field' => 'UUID',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field7' => array( 'type' => 'grid_field_label',
'field' => 'UUID',
'clickSort' => true ),
'grid_checkbox' => array( 'type' => 'grid_checkbox' ),
'grid_checkbox_head' => array( 'type' => 'grid_checkbox_head' ),
'expand_button' => array( 'type' => 'expand_button' ),
'inline_add' => array( 'type' => 'inline_add',
'detailsOnly' => true ),
'grid_inline_cancel' => array( 'type' => 'grid_inline_cancel' ) ),
'dbProps' => array(  ),
'spreadsheetGrid' => false,
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>