<?php
			$optionsArray = array( 'list' => array( 'inlineAdd' => false,
'detailsAdd' => false,
'inlineEdit' => false,
'spreadsheetMode' => false,
'reorderRows' => false,
'addToBottom' => false,
'delete' => false,
'updateSelected' => false,
'addInPopup' => null,
'editInPopup' => null,
'viewInPopup' => null,
'clickSort' => true,
'sortDropdown' => false,
'showHideFields' => false,
'reorderFields' => false,
'fieldFilter' => false,
'hideNumberOfRecords' => false ),
'allDetails' => array( 'linkType' => 0 ),
'details' => array( 'tr_compras_requisiciones_02_productos' => array( 'displayPreview' => 1,
'previewPageId' => 'list',
'showCount' => true,
'hideEmptyChild' => false,
'hideEmptyPreview' => false,
'showProceedLink' => true,
'printDetails' => true ) ),
'listSearch' => array( 'alwaysOnPanelFields' => array(  ),
'searchPanel' => true,
'fixedSearchPanel' => false,
'simpleSearchOptions' => true,
'searchSaving' => false ),
'totals' => array( 'tr_compras_requisiciones_01_id' => array( 'totalsType' => '' ),
'time_stamp' => array( 'totalsType' => '' ),
'vigente' => array( 'totalsType' => '' ),
'capturista' => array( 'totalsType' => '' ),
'fecha_de_captura' => array( 'totalsType' => '' ),
'id_estatus' => array( 'totalsType' => '' ),
'cat_compras_estatus_mu_id' => array( 'totalsType' => '' ),
'fecha_de_orden_de_compra' => array( 'totalsType' => '' ),
'cat_usuarios_licencias_id' => array( 'totalsType' => '' ),
'observaciones' => array( 'totalsType' => '' ),
'capturista_que_autoriza' => array( 'totalsType' => '' ),
'cat_trabajadores_altas_id_solicitante' => array( 'totalsType' => '' ),
'tr_compras_requisiciones_01_uuid' => array( 'totalsType' => '' ),
'descripcion_compras_estatus_mu' => array( 'totalsType' => '' ),
'cat_holding_03_empresas_unidades_productivas_id' => array( 'totalsType' => '' ),
'total_productos' => array( 'totalsType' => '' ),
'check_compra_directa' => array( 'totalsType' => '' ),
'fecha_de_compra' => array( 'totalsType' => '' ),
'cat_compras_proveedores_id' => array( 'totalsType' => '' ),
'importe_abono_compra' => array( 'totalsType' => '' ),
'fecha_de_pago' => array( 'totalsType' => '' ),
'cat_finanzas_cuentas_de_balance_04_llave' => array( 'totalsType' => '' ),
'uuid_sat' => array( 'totalsType' => '' ),
'cat_finanzas_bancos_cuentas_id' => array( 'totalsType' => '' ),
'cat_finanzas_cajas_chicas_id' => array( 'totalsType' => '' ),
'filtro_pagada' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'fecha_de_orden_de_compra',
'descripcion_compras_estatus_mu',
'id_estatus',
'capturista_que_autoriza',
'observaciones',
'cat_trabajadores_altas_id_solicitante',
'fecha_de_captura',
'capturista',
'cat_holding_03_empresas_unidades_productivas_id',
'total_productos',
'vigente',
'tr_compras_requisiciones_01_uuid',
'filtro_pagada' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array( 'fecha_de_orden_de_compra',
'filtro_pagada',
'capturista_que_autoriza',
'total_productos',
'cat_holding_03_empresas_unidades_productivas_id',
'descripcion_compras_estatus_mu',
'cat_trabajadores_altas_id_solicitante',
'tr_compras_requisiciones_01_uuid',
'cat_compras_estatus_mu_id' ),
'filterFields' => array(  ),
'inlineAddFields' => array(  ),
'inlineEditFields' => array(  ),
'fieldItems' => array( 'fecha_de_captura' => array( 'simple_grid_field1',
'simple_grid_field9' ),
'vigente' => array( 'simple_grid_field2',
'simple_grid_field11' ),
'capturista' => array( 'simple_grid_field3',
'simple_grid_field4' ),
'observaciones' => array( 'simple_grid_field13',
'simple_grid_field14' ),
'capturista_que_autoriza' => array( 'simple_grid_field6',
'simple_grid_field8' ),
'fecha_de_orden_de_compra' => array( 'simple_grid_field10',
'simple_grid_field' ),
'cat_compras_estatus_mu_id' => array( 'simple_grid_field7' ),
'tr_compras_requisiciones_01_uuid' => array( 'grid_field',
'grid_field_label' ),
'cat_trabajadores_altas_id_solicitante' => array( 'grid_field1',
'grid_field_label1' ),
'descripcion_compras_estatus_mu' => array( 'grid_field2' ),
'cat_holding_03_empresas_unidades_productivas_id' => array( 'grid_field3',
'grid_field_label3' ),
'total_productos' => array( 'grid_field4',
'grid_field_label4' ),
'id_estatus' => array( 'grid_field5' ),
'filtro_pagada' => array( 'grid_field6',
'grid_field_label2' ) ),
'hideEmptyFields' => array(  ),
'fieldFilterFields' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => true ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'details_found',
'page_size',
'print_panel',
'text',
'custom_button1',
'custom_button2',
'custom_button3' ),
'below-grid' => array( 'pagination' ),
'left' => array( 'logo',
'expand_button',
'menu',
'search_panel' ),
'supertop' => array( 'expand_menu_button',
'collapse_button',
'breadcrumb',
'simple_search_field',
'simple_search_option',
'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'grid' => array( 'simple_grid_field',
'simple_grid_field10',
'simple_grid_field7',
'grid_field2',
'grid_field5',
'simple_grid_field8',
'simple_grid_field6',
'simple_grid_field14',
'simple_grid_field13',
'grid_field_label1',
'grid_field1',
'simple_grid_field9',
'simple_grid_field1',
'details_preview',
'grid_checkbox_head',
'grid_checkbox',
'grid_alldetails_link',
'grid_details_link',
'custom_button',
'simple_grid_field11',
'simple_grid_field2',
'grid_field_label',
'grid_field',
'grid_field4',
'grid_field_label4',
'grid_field3',
'grid_field_label3',
'simple_grid_field3',
'simple_grid_field4',
'grid_field_label2',
'grid_field6' ),
'top' => array(  ) ),
'formXtTags' => array( 'below-grid' => array( 'pagination' ),
'top' => array(  ) ),
'itemForms' => array( 'details_found' => 'above-grid',
'page_size' => 'above-grid',
'print_panel' => 'above-grid',
'text' => 'above-grid',
'custom_button1' => 'above-grid',
'custom_button2' => 'above-grid',
'custom_button3' => 'above-grid',
'pagination' => 'below-grid',
'logo' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'search_panel' => 'left',
'expand_menu_button' => 'supertop',
'collapse_button' => 'supertop',
'breadcrumb' => 'supertop',
'simple_search_field' => 'supertop',
'simple_search_option' => 'supertop',
'simple_search' => 'supertop',
'list_options' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'simple_grid_field' => 'grid',
'simple_grid_field10' => 'grid',
'simple_grid_field7' => 'grid',
'grid_field2' => 'grid',
'grid_field5' => 'grid',
'simple_grid_field8' => 'grid',
'simple_grid_field6' => 'grid',
'simple_grid_field14' => 'grid',
'simple_grid_field13' => 'grid',
'grid_field_label1' => 'grid',
'grid_field1' => 'grid',
'simple_grid_field9' => 'grid',
'simple_grid_field1' => 'grid',
'details_preview' => 'grid',
'grid_checkbox_head' => 'grid',
'grid_checkbox' => 'grid',
'grid_alldetails_link' => 'grid',
'grid_details_link' => 'grid',
'custom_button' => 'grid',
'simple_grid_field11' => 'grid',
'simple_grid_field2' => 'grid',
'grid_field_label' => 'grid',
'grid_field' => 'grid',
'grid_field4' => 'grid',
'grid_field_label4' => 'grid',
'grid_field3' => 'grid',
'grid_field_label3' => 'grid',
'simple_grid_field3' => 'grid',
'simple_grid_field4' => 'grid',
'grid_field_label2' => 'grid',
'grid_field6' => 'grid' ),
'itemLocations' => array( 'simple_grid_field' => array( 'location' => 'grid',
'cellId' => 'headcell_field' ),
'simple_grid_field10' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'simple_grid_field7' => array( 'location' => 'grid',
'cellId' => 'headcell_field1' ),
'grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'grid_field5' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'simple_grid_field8' => array( 'location' => 'grid',
'cellId' => 'headcell_field2' ),
'simple_grid_field6' => array( 'location' => 'grid',
'cellId' => 'cell_field2' ),
'simple_grid_field14' => array( 'location' => 'grid',
'cellId' => 'headcell_field3' ),
'simple_grid_field13' => array( 'location' => 'grid',
'cellId' => 'cell_field3' ),
'grid_field_label1' => array( 'location' => 'grid',
'cellId' => 'headcell_field6' ),
'grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field6' ),
'simple_grid_field9' => array( 'location' => 'grid',
'cellId' => 'headcell_field7' ),
'simple_grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field7' ),
'details_preview' => array( 'location' => 'grid',
'cellId' => 'cell_dpreview' ),
'grid_checkbox_head' => array( 'location' => 'grid',
'cellId' => 'headcell_checkbox' ),
'grid_checkbox' => array( 'location' => 'grid',
'cellId' => 'cell_checkbox' ),
'grid_alldetails_link' => array( 'location' => 'grid',
'cellId' => 'cell_details' ),
'grid_details_link' => array( 'location' => 'grid',
'cellId' => 'cell_details' ),
'custom_button' => array( 'location' => 'grid',
'cellId' => 'footcell_icons2' ),
'simple_grid_field11' => array( 'location' => 'grid',
'cellId' => 'headcell_field4' ),
'simple_grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field4' ),
'grid_field_label' => array( 'location' => 'grid',
'cellId' => 'headcell_field8' ),
'grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field9' ),
'grid_field4' => array( 'location' => 'grid',
'cellId' => 'cell_field47' ),
'grid_field_label4' => array( 'location' => 'grid',
'cellId' => 'cell_field46' ),
'grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_field43' ),
'grid_field_label3' => array( 'location' => 'grid',
'cellId' => 'cell_field42' ),
'simple_grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_field39' ),
'simple_grid_field4' => array( 'location' => 'grid',
'cellId' => 'cell_field38' ),
'grid_field_label2' => array( 'location' => 'grid',
'cellId' => 'headcell_field5' ),
'grid_field6' => array( 'location' => 'grid',
'cellId' => 'cell_field5' ) ),
'itemVisiblity' => array( 'breadcrumb' => 5,
'expand_menu_button' => 2,
'print_panel' => 5,
'expand_button' => 5 ) ),
'itemsByType' => array( 'page_size' => array( 'page_size' ),
'details_found' => array( 'details_found' ),
'breadcrumb' => array( 'breadcrumb' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'simple_search' => array( 'simple_search' ),
'pagination' => array( 'pagination' ),
'grid_checkbox' => array( 'grid_checkbox' ),
'grid_checkbox_head' => array( 'grid_checkbox_head' ),
'list_options' => array( 'list_options' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'userinfo_link' => array( 'userinfo_link' ),
'logout_link' => array( 'logout_link' ),
'adminarea_link' => array( 'adminarea_link' ),
'changepassword_link' => array( 'changepassword_link' ),
'expand_menu_button' => array( 'expand_menu_button' ),
'collapse_button' => array( 'collapse_button' ),
'-' => array( '-',
'-1',
'-2',
'-3',
'-4',
'-5' ),
'advsearch_link' => array( 'advsearch_link' ),
'grid_field' => array( 'simple_grid_field1',
'simple_grid_field2',
'simple_grid_field3',
'simple_grid_field13',
'simple_grid_field6',
'simple_grid_field10',
'grid_field',
'grid_field1',
'grid_field2',
'grid_field3',
'grid_field4',
'grid_field5',
'grid_field6' ),
'print_panel' => array( 'print_panel' ),
'print_details' => array( 'print_details' ),
'search_panel' => array( 'search_panel' ),
'show_search_panel' => array( 'show_search_panel' ),
'hide_search_panel' => array( 'hide_search_panel' ),
'search_panel_field' => array( 'search_panel_field5',
'search_panel_field6',
'search_panel_field',
'search_panel_field1',
'search_panel_field2',
'search_panel_field3',
'search_panel_field4',
'search_panel_field15',
'search_panel_field7' ),
'details_preview' => array( 'details_preview' ),
'grid_alldetails_link' => array( 'grid_alldetails_link' ),
'grid_details_link' => array( 'grid_details_link' ),
'text' => array( 'text' ),
'grid_field_label' => array( 'simple_grid_field',
'simple_grid_field7',
'simple_grid_field8',
'simple_grid_field14',
'simple_grid_field4',
'simple_grid_field9',
'simple_grid_field11',
'grid_field_label',
'grid_field_label1',
'grid_field_label3',
'grid_field_label4',
'grid_field_label2' ),
'custom_button' => array( 'custom_button',
'custom_button1',
'custom_button2',
'custom_button3' ),
'print_scope' => array( 'print_scope' ),
'print_button' => array( 'print_button' ),
'print_records' => array( 'print_records' ),
'simple_search_field' => array( 'simple_search_field' ),
'simple_search_option' => array( 'simple_search_option' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'footcell_icons1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_icons' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_checkbox' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array( 'checkbox_column' ),
'items' => array( 'grid_checkbox_head' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_details' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field' => array( 'cols' => array( 4 ),
'rows' => array( 0 ),
'tags' => array( 'fecha_de_orden_de_compra_fieldheadercolumn' ),
'items' => array( 'simple_grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field1' => array( 'cols' => array( 5 ),
'rows' => array( 0 ),
'tags' => array( 'cat_compras_estatus_mu_id_fieldheadercolumn' ),
'items' => array( 'simple_grid_field7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field2' => array( 'cols' => array( 6 ),
'rows' => array( 0 ),
'tags' => array( 'capturista_que_autoriza_fieldheadercolumn' ),
'items' => array( 'simple_grid_field8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field3' => array( 'cols' => array( 7 ),
'rows' => array( 0 ),
'tags' => array( 'observaciones_fieldheadercolumn' ),
'items' => array( 'simple_grid_field14' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field6' => array( 'cols' => array( 8 ),
'rows' => array( 0 ),
'tags' => array( 'cat_trabajadores_altas_id_solicitante_fieldheadercolumn' ),
'items' => array( 'grid_field_label1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field7' => array( 'cols' => array( 9 ),
'rows' => array( 0 ),
'tags' => array( 'fecha_de_captura_fieldheadercolumn' ),
'items' => array( 'simple_grid_field9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field38' => array( 'cols' => array( 10 ),
'rows' => array( 0 ),
'tags' => array( 'capturista_fieldheadercolumn' ),
'items' => array( 'simple_grid_field4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field42' => array( 'cols' => array( 11 ),
'rows' => array( 0 ),
'tags' => array( 'cat_holding_03_empresas_unidades_productivas_id_fieldheadercolumn' ),
'items' => array( 'grid_field_label3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field46' => array( 'cols' => array( 12 ),
'rows' => array( 0 ),
'tags' => array( 'total_productos_fieldheadercolumn' ),
'items' => array( 'grid_field_label4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field4' => array( 'cols' => array( 13 ),
'rows' => array( 0 ),
'tags' => array( 'vigente_fieldheadercolumn' ),
'items' => array( 'simple_grid_field11' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field8' => array( 'cols' => array( 14 ),
'rows' => array( 0 ),
'tags' => array( 'tr_compras_requisiciones_01_uuid_fieldheadercolumn' ),
'items' => array( 'grid_field_label' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field5' => array( 'cols' => array( 15 ),
'rows' => array( 0 ),
'tags' => array( 'filtro_pagada_fieldheadercolumn' ),
'items' => array( 'grid_field_label2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_icons2' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'cell_icons' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_checkbox' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array( 'checkbox_column' ),
'items' => array( 'grid_checkbox' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_details' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'grid_alldetails_link',
'grid_details_link' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 4 ),
'rows' => array( 1 ),
'tags' => array( 'fecha_de_orden_de_compra_fieldcolumn' ),
'items' => array( 'simple_grid_field10' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 5 ),
'rows' => array( 1 ),
'tags' => array( 'descripcion_compras_estatus_mu_fieldcolumn',
'id_estatus_fieldcolumn' ),
'items' => array( 'grid_field2',
'grid_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 6 ),
'rows' => array( 1 ),
'tags' => array( 'capturista_que_autoriza_fieldcolumn' ),
'items' => array( 'simple_grid_field6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field3' => array( 'cols' => array( 7 ),
'rows' => array( 1 ),
'tags' => array( 'observaciones_fieldcolumn' ),
'items' => array( 'simple_grid_field13' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field6' => array( 'cols' => array( 8 ),
'rows' => array( 1 ),
'tags' => array( 'cat_trabajadores_altas_id_solicitante_fieldcolumn' ),
'items' => array( 'grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field7' => array( 'cols' => array( 9 ),
'rows' => array( 1 ),
'tags' => array( 'fecha_de_captura_fieldcolumn' ),
'items' => array( 'simple_grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field39' => array( 'cols' => array( 10 ),
'rows' => array( 1 ),
'tags' => array( 'capturista_fieldcolumn' ),
'items' => array( 'simple_grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field43' => array( 'cols' => array( 11 ),
'rows' => array( 1 ),
'tags' => array( 'cat_holding_03_empresas_unidades_productivas_id_fieldcolumn' ),
'items' => array( 'grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field47' => array( 'cols' => array( 12 ),
'rows' => array( 1 ),
'tags' => array( 'total_productos_fieldcolumn' ),
'items' => array( 'grid_field4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field4' => array( 'cols' => array( 13 ),
'rows' => array( 1 ),
'tags' => array( 'vigente_fieldcolumn' ),
'items' => array( 'simple_grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field9' => array( 'cols' => array( 14 ),
'rows' => array( 1 ),
'tags' => array( 'tr_compras_requisiciones_01_uuid_fieldcolumn' ),
'items' => array( 'grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field5' => array( 'cols' => array( 15 ),
'rows' => array( 1 ),
'tags' => array( 'filtro_pagada_fieldcolumn' ),
'items' => array( 'grid_field6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_icons3' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_dpreview' => array( 'cols' => array( 1,
2,
3,
4,
5,
6,
7,
8,
9 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'details_preview' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'cell_field40' => array( 'cols' => array( 10 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field44' => array( 'cols' => array( 11 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field48' => array( 'cols' => array( 12 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field8' => array( 'cols' => array( 13 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field10' => array( 'cols' => array( 14 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field11' => array( 'cols' => array( 15 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_icons4' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_icons' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_checkbox' => array( 'cols' => array( 2 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_details' => array( 'cols' => array( 3 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field' => array( 'cols' => array( 4 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field1' => array( 'cols' => array( 5 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field2' => array( 'cols' => array( 6 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field3' => array( 'cols' => array( 7 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field6' => array( 'cols' => array( 8 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field7' => array( 'cols' => array( 9 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field41' => array( 'cols' => array( 10 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field45' => array( 'cols' => array( 11 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field49' => array( 'cols' => array( 12 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field4' => array( 'cols' => array( 13 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field8' => array( 'cols' => array( 14 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field5' => array( 'cols' => array( 15 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 16,
'height' => 4 ) ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array( 'details_found' => array( 'tag' => 'DISPLAYING',
'type' => 2 ) ) ),
'gridType' => 0,
'recsPerRow' => 1,
'hasCustomButtons' => true,
'customButtons' => array( 'tr_compras_requisiciones_01_orden_de_compra_GENERA_FOLIO_DE_PAGO',
'link_utoriza',
'link_requi_pagar',
'link_requisiciones_estatus' ),
'hasNotifications' => false,
'menus' => array( array( 'id' => 'main',
'horizontal' => false ) ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'list',
'breadcrumb' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array( 'tr_compras_requisiciones_01_orden_de_compra_GENERA_FOLIO_DE_PAGO',
'link_utoriza',
'link_requi_pagar',
'link_requisiciones_estatus' ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'list',
'type' => 'list',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'list-above-grid',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c4' ),
array( 'cell' => 'c5' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ),
array( 'cell' => 'c3' ) ) ),
array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'details_found',
'page_size',
'print_panel' ) ),
'c' => array( 'model' => 'c1',
'items' => array( 'text' ) ),
'c3' => array( 'model' => 'c2',
'items' => array(  ) ),
'c4' => array( 'model' => 'c1',
'items' => array( 'custom_button1',
'custom_button2',
'custom_button3' ) ),
'c5' => array( 'model' => 'c2',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'list-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'pagination' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo',
'expand_button' ) ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu',
'search_panel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'expand_menu_button',
'collapse_button',
'breadcrumb' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'simple_search_field',
'simple_search_option',
'simple_search',
'list_options',
'loginform_login',
'username_button' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'horizontal-grid',
'grid' => array( array( 'section' => 'head',
'cells' => array( array( 'cell' => 'footcell_icons1' ),
array( 'cell' => 'headcell_icons' ),
array( 'cell' => 'headcell_checkbox' ),
array( 'cell' => 'headcell_details' ),
array( 'cell' => 'headcell_field' ),
array( 'cell' => 'headcell_field1' ),
array( 'cell' => 'headcell_field2' ),
array( 'cell' => 'headcell_field3' ),
array( 'cell' => 'headcell_field6' ),
array( 'cell' => 'headcell_field7' ),
array( 'cell' => 'cell_field38' ),
array( 'cell' => 'cell_field42' ),
array( 'cell' => 'cell_field46' ),
array( 'cell' => 'headcell_field4' ),
array( 'cell' => 'headcell_field8' ),
array( 'cell' => 'headcell_field5' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'footcell_icons2' ),
array( 'cell' => 'cell_icons' ),
array( 'cell' => 'cell_checkbox' ),
array( 'cell' => 'cell_details' ),
array( 'cell' => 'cell_field' ),
array( 'cell' => 'cell_field1' ),
array( 'cell' => 'cell_field2' ),
array( 'cell' => 'cell_field3' ),
array( 'cell' => 'cell_field6' ),
array( 'cell' => 'cell_field7' ),
array( 'cell' => 'cell_field39' ),
array( 'cell' => 'cell_field43' ),
array( 'cell' => 'cell_field47' ),
array( 'cell' => 'cell_field4' ),
array( 'cell' => 'cell_field9' ),
array( 'cell' => 'cell_field5' ) ) ),
array( 'cells' => array( array( 'cell' => 'footcell_icons3' ),
array( 'cell' => 'cell_dpreview',
'colspan' => 9 ),
array( 'cell' => 'cell_field40' ),
array( 'cell' => 'cell_field44' ),
array( 'cell' => 'cell_field48' ),
array( 'cell' => 'cell_field8' ),
array( 'cell' => 'cell_field10' ),
array( 'cell' => 'cell_field11' ) ),
'section' => 'body' ),
array( 'section' => 'foot',
'cells' => array( array( 'cell' => 'footcell_icons4' ),
array( 'cell' => 'footcell_icons' ),
array( 'cell' => 'footcell_checkbox' ),
array( 'cell' => 'footcell_details' ),
array( 'cell' => 'footcell_field' ),
array( 'cell' => 'footcell_field1' ),
array( 'cell' => 'footcell_field2' ),
array( 'cell' => 'footcell_field3' ),
array( 'cell' => 'footcell_field6' ),
array( 'cell' => 'footcell_field7' ),
array( 'cell' => 'cell_field41' ),
array( 'cell' => 'cell_field45' ),
array( 'cell' => 'cell_field49' ),
array( 'cell' => 'footcell_field4' ),
array( 'cell' => 'footcell_field8' ),
array( 'cell' => 'footcell_field5' ) ) ) ),
'cells' => array( 'headcell_field' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field' ),
'field' => 'fecha_de_orden_de_compra',
'columnName' => 'field' ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field10' ),
'field' => 'fecha_de_orden_de_compra',
'columnName' => 'field' ),
'footcell_field' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field1' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field7' ),
'field' => 'cat_compras_estatus_mu_id',
'columnName' => 'field' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'grid_field2',
'grid_field5' ),
'field' => 'descripcion_compras_estatus_mu',
'columnName' => 'field' ),
'footcell_field1' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field2' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field8' ),
'field' => 'capturista_que_autoriza',
'columnName' => 'field' ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field6' ),
'field' => 'capturista_que_autoriza',
'columnName' => 'field' ),
'footcell_field2' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field3' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field14' ),
'field' => 'observaciones',
'columnName' => 'field' ),
'cell_field3' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field13' ),
'field' => 'observaciones',
'columnName' => 'field' ),
'footcell_field3' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field6' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label1' ),
'field' => 'cat_trabajadores_altas_id_solicitante',
'columnName' => 'field' ),
'cell_field6' => array( 'model' => 'cell_field',
'items' => array( 'grid_field1' ),
'field' => 'cat_trabajadores_altas_id_solicitante',
'columnName' => 'field' ),
'footcell_field6' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field7' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field9' ),
'field' => 'fecha_de_captura',
'columnName' => 'field' ),
'cell_field7' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field1' ),
'field' => 'fecha_de_captura',
'columnName' => 'field' ),
'footcell_field7' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'cell_dpreview' => array( 'model' => 'cell_dpreview',
'items' => array( 'details_preview' ) ),
'headcell_checkbox' => array( 'model' => 'headcell_checkbox',
'items' => array( 'grid_checkbox_head' ) ),
'cell_checkbox' => array( 'model' => 'cell_checkbox',
'items' => array( 'grid_checkbox' ) ),
'footcell_checkbox' => array( 'model' => 'footcell_checkbox',
'items' => array(  ) ),
'headcell_icons' => array( 'model' => 'headcell_icons',
'items' => array(  ) ),
'cell_icons' => array( 'model' => 'cell_icons',
'items' => array(  ) ),
'footcell_icons' => array( 'model' => 'footcell_icons',
'items' => array(  ) ),
'headcell_details' => array( 'model' => 'headcell_details',
'items' => array(  ) ),
'cell_details' => array( 'model' => 'cell_details',
'items' => array( 'grid_alldetails_link',
'grid_details_link' ) ),
'footcell_details' => array( 'model' => 'footcell_details',
'items' => array(  ) ),
'footcell_icons1' => array( 'model' => 'headcell_icons',
'items' => array(  ) ),
'footcell_icons2' => array( 'model' => 'cell_icons',
'items' => array( 'custom_button' ) ),
'footcell_icons3' => array( 'model' => 'cell_dpreview',
'items' => array(  ) ),
'footcell_icons4' => array( 'model' => 'footcell_icons',
'items' => array(  ) ),
'headcell_field4' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field11' ),
'field' => 'vigente',
'columnName' => 'field' ),
'cell_field4' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field2' ),
'field' => 'vigente',
'columnName' => 'field' ),
'cell_field8' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'footcell_field4' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field8' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label' ),
'field' => 'tr_compras_requisiciones_01_uuid',
'columnName' => 'field' ),
'cell_field9' => array( 'model' => 'cell_field',
'items' => array( 'grid_field' ),
'field' => 'tr_compras_requisiciones_01_uuid',
'columnName' => 'field' ),
'cell_field10' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'footcell_field8' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'cell_field49' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'cell_field48' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'cell_field47' => array( 'model' => 'cell_field',
'items' => array( 'grid_field4' ),
'field' => 'total_productos',
'columnName' => 'field' ),
'cell_field46' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label4' ),
'field' => 'total_productos',
'columnName' => 'field' ),
'cell_field45' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'cell_field44' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'cell_field43' => array( 'model' => 'cell_field',
'items' => array( 'grid_field3' ),
'field' => 'cat_holding_03_empresas_unidades_productivas_id',
'columnName' => 'field' ),
'cell_field42' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label3' ),
'field' => 'cat_holding_03_empresas_unidades_productivas_id',
'columnName' => 'field' ),
'cell_field41' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'cell_field40' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'cell_field39' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field3' ),
'field' => 'capturista',
'columnName' => 'field' ),
'cell_field38' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field4' ),
'field' => 'capturista',
'columnName' => 'field' ),
'headcell_field5' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label2' ),
'field' => 'filtro_pagada',
'columnName' => 'field' ),
'cell_field5' => array( 'model' => 'cell_field',
'items' => array( 'grid_field6' ),
'field' => 'filtro_pagada',
'columnName' => 'field' ),
'cell_field11' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'footcell_field5' => array( 'model' => 'footcell_field',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'list-sidebar-top',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'page_size' => array( 'type' => 'page_size' ),
'details_found' => array( 'type' => 'details_found' ),
'breadcrumb' => array( 'type' => 'breadcrumb' ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'simple_search' => array( 'type' => 'simple_search' ),
'pagination' => array( 'type' => 'pagination' ),
'grid_checkbox' => array( 'type' => 'grid_checkbox' ),
'grid_checkbox_head' => array( 'type' => 'grid_checkbox_head' ),
'list_options' => array( 'type' => 'list_options',
'items' => array( 'advsearch_link',
'show_search_panel',
'hide_search_panel' ) ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'adminarea_link',
'changepassword_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => false ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'logout_link' => array( 'type' => 'logout_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'changepassword_link' => array( 'type' => 'changepassword_link' ),
'expand_menu_button' => array( 'type' => 'expand_menu_button' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'-' => array( 'type' => '-' ),
'-1' => array( 'type' => '-' ),
'-2' => array( 'type' => '-' ),
'advsearch_link' => array( 'type' => 'advsearch_link' ),
'-3' => array( 'type' => '-' ),
'simple_grid_field1' => array( 'field' => 'fecha_de_captura',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field2' => array( 'field' => 'vigente',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field3' => array( 'field' => 'capturista',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field13' => array( 'field' => 'observaciones',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'-4' => array( 'type' => '-' ),
'print_panel' => array( 'type' => 'print_panel',
'items' => array( 'print_scope',
'print_details',
'print_records',
'print_button' ) ),
'print_details' => array( 'type' => 'print_details',
'tables' => array( 'tr_compras_requisiciones_02_productos' => true,
'tr_compras_requisiciones_02_productos_orden_de_compra' => true ) ),
'simple_grid_field6' => array( 'field' => 'capturista_que_autoriza',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'label' => array( 'field' => 'capturista_que_autoriza',
'table' => 'tr_compras_requisiciones_01',
'type' => 3 ),
'clickSort' => true ),
'search_panel' => array( 'type' => 'search_panel',
'items' => array( 'search_panel_field6',
'search_panel_field7',
'search_panel_field15',
'search_panel_field4',
'search_panel_field3',
'search_panel_field2',
'search_panel_field1',
'search_panel_field',
'search_panel_field5' ) ),
'show_search_panel' => array( 'type' => 'show_search_panel' ),
'hide_search_panel' => array( 'type' => 'hide_search_panel' ),
'simple_grid_field10' => array( 'field' => 'fecha_de_orden_de_compra',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'search_panel_field5' => array( 'field' => 'cat_compras_estatus_mu_id',
'type' => 'search_panel_field',
'alwaysOnPanel' => false,
'required' => false ),
'search_panel_field6' => array( 'field' => 'fecha_de_orden_de_compra',
'type' => 'search_panel_field',
'alwaysOnPanel' => false,
'required' => false ),
'-5' => array( 'type' => '-' ),
'details_preview' => array( 'type' => 'details_preview',
'table' => 'tr_compras_requisiciones_02_productos',
'items' => array(  ),
'popup' => false,
'hideEmptyPreview' => false,
'proceedLink' => true,
'pageId' => 'list' ),
'grid_alldetails_link' => array( 'type' => 'grid_alldetails_link' ),
'grid_details_link' => array( 'type' => 'grid_details_link',
'table' => 'tr_compras_requisiciones_02_productos',
'badge' => true,
'hideIfNone' => false,
'showCount' => true ),
'text' => array( 'type' => 'text',
'label' => array( 'type' => 0,
'text' => 'ORDEN DE COMPRA. Generar folio de pago' ),
'editedByRte' => false,
'bold' => true ),
'simple_grid_field' => array( 'type' => 'grid_field_label',
'field' => 'fecha_de_orden_de_compra',
'clickSort' => true ),
'simple_grid_field7' => array( 'type' => 'grid_field_label',
'field' => 'cat_compras_estatus_mu_id',
'clickSort' => true ),
'simple_grid_field8' => array( 'type' => 'grid_field_label',
'field' => 'capturista_que_autoriza',
'clickSort' => true ),
'simple_grid_field14' => array( 'type' => 'grid_field_label',
'field' => 'observaciones',
'clickSort' => true ),
'simple_grid_field4' => array( 'type' => 'grid_field_label',
'field' => 'capturista',
'clickSort' => true ),
'simple_grid_field9' => array( 'type' => 'grid_field_label',
'field' => 'fecha_de_captura',
'clickSort' => true ),
'simple_grid_field11' => array( 'type' => 'grid_field_label',
'field' => 'vigente',
'clickSort' => true ),
'custom_button' => array( 'eventId' => 'tr_compras_requisiciones_01_orden_de_compra_GENERA_FOLIO_DE_PAGO',
'label' => array( 'text' => 'Crear Folio de Pago',
'type' => 0 ),
'type' => 'custom_button',
'buttonStyle' => 'info',
'buttonSize' => 'small',
'icon' => array( 'glyph' => 'usd' ) ),
'grid_field' => array( 'field' => 'tr_compras_requisiciones_01_uuid',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label' => array( 'type' => 'grid_field_label',
'field' => 'tr_compras_requisiciones_01_uuid',
'clickSort' => true ),
'search_panel_field' => array( 'field' => 'tr_compras_requisiciones_01_uuid',
'type' => 'search_panel_field',
'required' => false ),
'custom_button1' => array( 'eventId' => 'link_utoriza',
'label' => array( 'text' => 'Autorizar',
'type' => 0 ),
'type' => 'custom_button',
'icon' => array( 'glyph' => 'backward' ) ),
'custom_button2' => array( 'eventId' => 'link_requi_pagar',
'label' => array( 'text' => 'Pagar',
'type' => 0 ),
'type' => 'custom_button',
'icon' => array( 'glyph' => 'forward' ) ),
'grid_field1' => array( 'field' => 'cat_trabajadores_altas_id_solicitante',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label1' => array( 'type' => 'grid_field_label',
'field' => 'cat_trabajadores_altas_id_solicitante',
'clickSort' => true ),
'search_panel_field1' => array( 'field' => 'cat_trabajadores_altas_id_solicitante',
'type' => 'search_panel_field',
'required' => false ),
'grid_field2' => array( 'field' => 'descripcion_compras_estatus_mu',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'search_panel_field2' => array( 'field' => 'descripcion_compras_estatus_mu',
'type' => 'search_panel_field',
'required' => false ),
'grid_field3' => array( 'field' => 'cat_holding_03_empresas_unidades_productivas_id',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label3' => array( 'type' => 'grid_field_label',
'field' => 'cat_holding_03_empresas_unidades_productivas_id',
'clickSort' => true ),
'search_panel_field3' => array( 'field' => 'cat_holding_03_empresas_unidades_productivas_id',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'grid_field4' => array( 'field' => 'total_productos',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label4' => array( 'type' => 'grid_field_label',
'field' => 'total_productos',
'clickSort' => true ),
'search_panel_field4' => array( 'field' => 'total_productos',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field15' => array( 'field' => 'capturista_que_autoriza',
'type' => 'search_panel_field' ),
'grid_field5' => array( 'field' => 'id_estatus',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field6' => array( 'field' => 'filtro_pagada',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label2' => array( 'type' => 'grid_field_label',
'field' => 'filtro_pagada',
'clickSort' => true ),
'search_panel_field7' => array( 'field' => 'filtro_pagada',
'type' => 'search_panel_field',
'required' => false ),
'custom_button3' => array( 'eventId' => 'link_requisiciones_estatus',
'label' => array( 'type' => 0,
'text' => 'Estatus Requis' ),
'type' => 'custom_button',
'icon' => array( 'glyph' => 'info-sign' ) ),
'print_scope' => array( 'type' => 'print_scope' ),
'print_button' => array( 'type' => 'print_button' ),
'print_records' => array( 'type' => 'print_records' ),
'simple_search_field' => array( 'type' => 'simple_search_field' ),
'simple_search_option' => array( 'type' => 'simple_search_option' ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'spreadsheetGrid' => false,
'version' => 14,
'pageWidth' => 'full',
'reorderRows' => false,
'reorderRowsField' => '',
'addToBottom' => false,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>