<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'tr_compras_proveedores_01_cargos_abonos_id',
'descripcion_proveedores',
'alias_proveedor',
'fecha_de_compra',
'referencia',
'importe_abono_compra',
'importe_cargo_pago',
'fecha_de_pago',
'fecha_de_vencimiento',
'concepto',
'cat_compras_documentos_mu_id',
'capturista',
'vigente',
'cat_finanzas_cuentas_de_balance_03_mu_id',
'alias_cuenta_de_balance',
'imei',
'uuid_sat',
'time_stamp',
'consecutivo_id',
'cat_finanzas_bancos_cuentas_id',
'cat_finanzas_cajas_chicas_id',
'uuid_cargo_abono_compra',
'uuid_cargo_abono_pago',
'cat_usuarios_licencias_id',
'cat_compras_cargo_abono_mu_id',
'id_prov',
'total_compras_abonos',
'total_pagos_cargos',
'saldo',
'alias_cuenta_de_abono_compra',
'alias_cuenta_de_cargo_pago',
'cat_finanzas_cuentas_de_balance_04_llave',
'tr_compras_requisiciones_01_uuid_pago',
'tr_compras_requisiciones_01_uuid',
'referencia_bancaria',
'observacion_cargo_pago',
'llave_unica_cargo_abono_tr_compras_requisiciones_01_uuid_pago',
'fecha_de_recibo',
'tr_compras_almacenes_01_recibo_lpn_uuid',
'orden_de_compra_proveedor',
'cat_compras_estatus_mu_id',
'tr_finanzas_bancos_01_id' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'tr_compras_proveedores_01_cargos_abonos_id' => array( 'integrated_search_field' ),
'descripcion_proveedores' => array( 'integrated_search_field2' ),
'alias_proveedor' => array( 'integrated_search_field3' ),
'fecha_de_compra' => array( 'integrated_search_field4' ),
'referencia' => array( 'integrated_search_field5' ),
'importe_abono_compra' => array( 'integrated_search_field6' ),
'importe_cargo_pago' => array( 'integrated_search_field7' ),
'fecha_de_pago' => array( 'integrated_search_field8' ),
'fecha_de_vencimiento' => array( 'integrated_search_field9' ),
'concepto' => array( 'integrated_search_field10' ),
'cat_compras_documentos_mu_id' => array( 'integrated_search_field11' ),
'capturista' => array( 'integrated_search_field12' ),
'vigente' => array( 'integrated_search_field13' ),
'cat_finanzas_cuentas_de_balance_03_mu_id' => array( 'integrated_search_field14' ),
'alias_cuenta_de_balance' => array( 'integrated_search_field16' ),
'imei' => array( 'integrated_search_field17' ),
'uuid_sat' => array( 'integrated_search_field18' ),
'time_stamp' => array( 'integrated_search_field19' ),
'consecutivo_id' => array( 'integrated_search_field20' ),
'cat_finanzas_bancos_cuentas_id' => array( 'integrated_search_field21' ),
'cat_finanzas_cajas_chicas_id' => array( 'integrated_search_field22' ),
'uuid_cargo_abono_compra' => array( 'integrated_search_field23' ),
'uuid_cargo_abono_pago' => array( 'integrated_search_field24' ),
'cat_usuarios_licencias_id' => array( 'integrated_search_field25' ),
'cat_compras_cargo_abono_mu_id' => array( 'integrated_search_field26' ),
'id_prov' => array( 'integrated_search_field27' ),
'total_compras_abonos' => array( 'integrated_search_field28' ),
'total_pagos_cargos' => array( 'integrated_search_field29' ),
'saldo' => array( 'integrated_search_field30' ),
'alias_cuenta_de_abono_compra' => array( 'integrated_search_field31' ),
'alias_cuenta_de_cargo_pago' => array( 'integrated_search_field32' ),
'cat_finanzas_cuentas_de_balance_04_llave' => array( 'integrated_search_field1' ),
'tr_compras_requisiciones_01_uuid_pago' => array( 'integrated_search_field15' ),
'tr_compras_requisiciones_01_uuid' => array( 'integrated_search_field33' ),
'referencia_bancaria' => array( 'integrated_search_field34' ),
'observacion_cargo_pago' => array( 'integrated_search_field35' ),
'llave_unica_cargo_abono_tr_compras_requisiciones_01_uuid_pago' => array( 'integrated_search_field36' ),
'fecha_de_recibo' => array( 'integrated_search_field37' ),
'tr_compras_almacenes_01_recibo_lpn_uuid' => array( 'integrated_search_field38' ),
'orden_de_compra_proveedor' => array( 'integrated_search_field39' ),
'cat_compras_estatus_mu_id' => array( 'integrated_search_field40' ),
'tr_finanzas_bancos_01_id' => array( 'integrated_search_field41' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array(  ),
'below-grid' => array( 'search_search',
'search_reset',
'search_back_list',
'search_cancel' ),
'top' => array( 'search_header' ),
'grid' => array( 'integrated_search_field',
'integrated_search_field4',
'integrated_search_field5',
'integrated_search_field8',
'integrated_search_field9',
'integrated_search_field10',
'integrated_search_field11',
'integrated_search_field12',
'integrated_search_field13',
'integrated_search_field14',
'integrated_search_field16',
'integrated_search_field17',
'integrated_search_field18',
'integrated_search_field19',
'integrated_search_field20',
'integrated_search_field21',
'integrated_search_field22',
'integrated_search_field25',
'integrated_search_field26',
'integrated_search_field27',
'integrated_search_field28',
'integrated_search_field29',
'integrated_search_field30',
'integrated_search_field6',
'integrated_search_field7',
'integrated_search_field23',
'integrated_search_field24',
'integrated_search_field2',
'integrated_search_field31',
'integrated_search_field32',
'integrated_search_field1',
'integrated_search_field15',
'integrated_search_field33',
'integrated_search_field34',
'integrated_search_field3',
'integrated_search_field35',
'integrated_search_field36',
'integrated_search_field37',
'integrated_search_field38',
'integrated_search_field39',
'integrated_search_field40',
'integrated_search_field41' ) ),
'formXtTags' => array( 'above-grid' => array(  ) ),
'itemForms' => array( 'search_search' => 'below-grid',
'search_reset' => 'below-grid',
'search_back_list' => 'below-grid',
'search_cancel' => 'below-grid',
'search_header' => 'top',
'integrated_search_field' => 'grid',
'integrated_search_field4' => 'grid',
'integrated_search_field5' => 'grid',
'integrated_search_field8' => 'grid',
'integrated_search_field9' => 'grid',
'integrated_search_field10' => 'grid',
'integrated_search_field11' => 'grid',
'integrated_search_field12' => 'grid',
'integrated_search_field13' => 'grid',
'integrated_search_field14' => 'grid',
'integrated_search_field16' => 'grid',
'integrated_search_field17' => 'grid',
'integrated_search_field18' => 'grid',
'integrated_search_field19' => 'grid',
'integrated_search_field20' => 'grid',
'integrated_search_field21' => 'grid',
'integrated_search_field22' => 'grid',
'integrated_search_field25' => 'grid',
'integrated_search_field26' => 'grid',
'integrated_search_field27' => 'grid',
'integrated_search_field28' => 'grid',
'integrated_search_field29' => 'grid',
'integrated_search_field30' => 'grid',
'integrated_search_field6' => 'grid',
'integrated_search_field7' => 'grid',
'integrated_search_field23' => 'grid',
'integrated_search_field24' => 'grid',
'integrated_search_field2' => 'grid',
'integrated_search_field31' => 'grid',
'integrated_search_field32' => 'grid',
'integrated_search_field1' => 'grid',
'integrated_search_field15' => 'grid',
'integrated_search_field33' => 'grid',
'integrated_search_field34' => 'grid',
'integrated_search_field3' => 'grid',
'integrated_search_field35' => 'grid',
'integrated_search_field36' => 'grid',
'integrated_search_field37' => 'grid',
'integrated_search_field38' => 'grid',
'integrated_search_field39' => 'grid',
'integrated_search_field40' => 'grid',
'integrated_search_field41' => 'grid' ),
'itemLocations' => array( 'integrated_search_field' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field4' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field5' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field8' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field9' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field10' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field11' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field12' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field13' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field14' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field16' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field17' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field18' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field19' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field20' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field21' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field22' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field25' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field26' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field27' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field28' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field29' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field30' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field6' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field7' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field23' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field24' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field2' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field31' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field32' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field1' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field15' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field33' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field34' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field3' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field35' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field36' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field37' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field38' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field39' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field40' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field41' => array( 'location' => 'grid',
'cellId' => 'c3' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'search_header' => array( 'search_header' ),
'search_reset' => array( 'search_reset' ),
'search_back_list' => array( 'search_back_list' ),
'search_search' => array( 'search_search' ),
'search_cancel' => array( 'search_cancel' ),
'integrated_search_field' => array( 'integrated_search_field',
'integrated_search_field2',
'integrated_search_field3',
'integrated_search_field4',
'integrated_search_field5',
'integrated_search_field6',
'integrated_search_field7',
'integrated_search_field8',
'integrated_search_field9',
'integrated_search_field10',
'integrated_search_field11',
'integrated_search_field12',
'integrated_search_field13',
'integrated_search_field14',
'integrated_search_field16',
'integrated_search_field17',
'integrated_search_field18',
'integrated_search_field19',
'integrated_search_field20',
'integrated_search_field21',
'integrated_search_field22',
'integrated_search_field23',
'integrated_search_field24',
'integrated_search_field25',
'integrated_search_field26',
'integrated_search_field27',
'integrated_search_field28',
'integrated_search_field29',
'integrated_search_field30',
'integrated_search_field31',
'integrated_search_field32',
'integrated_search_field1',
'integrated_search_field15',
'integrated_search_field33',
'integrated_search_field34',
'integrated_search_field35',
'integrated_search_field36',
'integrated_search_field37',
'integrated_search_field38',
'integrated_search_field39',
'integrated_search_field40',
'integrated_search_field41' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field',
'integrated_search_field4',
'integrated_search_field5',
'integrated_search_field8',
'integrated_search_field9',
'integrated_search_field10',
'integrated_search_field11',
'integrated_search_field12',
'integrated_search_field13',
'integrated_search_field14',
'integrated_search_field16',
'integrated_search_field17',
'integrated_search_field18',
'integrated_search_field19',
'integrated_search_field20',
'integrated_search_field21',
'integrated_search_field22',
'integrated_search_field25',
'integrated_search_field26',
'integrated_search_field27',
'integrated_search_field28',
'integrated_search_field29',
'integrated_search_field30',
'integrated_search_field6',
'integrated_search_field7',
'integrated_search_field23',
'integrated_search_field24',
'integrated_search_field2',
'integrated_search_field31',
'integrated_search_field32',
'integrated_search_field1',
'integrated_search_field15',
'integrated_search_field33',
'integrated_search_field34',
'integrated_search_field3',
'integrated_search_field35',
'integrated_search_field36',
'integrated_search_field37',
'integrated_search_field38',
'integrated_search_field39',
'integrated_search_field40',
'integrated_search_field41' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'search',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'search',
'type' => 'search',
'layoutId' => 'nomenu',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'search-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1',
'colspan' => 2 ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'search-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'search_search',
'search_reset',
'search_back_list',
'search_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'search-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'search_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-search',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3' ) ),
'section' => '' ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'integrated_search_field',
'integrated_search_field4',
'integrated_search_field5',
'integrated_search_field8',
'integrated_search_field9',
'integrated_search_field10',
'integrated_search_field11',
'integrated_search_field12',
'integrated_search_field13',
'integrated_search_field14',
'integrated_search_field16',
'integrated_search_field17',
'integrated_search_field18',
'integrated_search_field19',
'integrated_search_field20',
'integrated_search_field21',
'integrated_search_field22',
'integrated_search_field25',
'integrated_search_field26',
'integrated_search_field27',
'integrated_search_field28',
'integrated_search_field29',
'integrated_search_field30',
'integrated_search_field6',
'integrated_search_field7',
'integrated_search_field23',
'integrated_search_field24',
'integrated_search_field2',
'integrated_search_field31',
'integrated_search_field32',
'integrated_search_field1',
'integrated_search_field15',
'integrated_search_field33',
'integrated_search_field34',
'integrated_search_field3',
'integrated_search_field35',
'integrated_search_field36',
'integrated_search_field37',
'integrated_search_field38',
'integrated_search_field39',
'integrated_search_field40',
'integrated_search_field41' ) ) ),
'deferredItems' => array(  ),
'separateLabels' => false ) ),
'items' => array( 'search_header' => array( 'type' => 'search_header' ),
'search_reset' => array( 'type' => 'search_reset' ),
'search_back_list' => array( 'type' => 'search_back_list' ),
'search_search' => array( 'type' => 'search_search' ),
'search_cancel' => array( 'type' => 'search_cancel' ),
'integrated_search_field' => array( 'field' => 'tr_compras_proveedores_01_cargos_abonos_id',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field2' => array( 'field' => 'descripcion_proveedores',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field3' => array( 'field' => 'alias_proveedor',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field4' => array( 'field' => 'fecha_de_compra',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field5' => array( 'field' => 'referencia',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field6' => array( 'field' => 'importe_abono_compra',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field7' => array( 'field' => 'importe_cargo_pago',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field8' => array( 'field' => 'fecha_de_pago',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field9' => array( 'field' => 'fecha_de_vencimiento',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field10' => array( 'field' => 'concepto',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field11' => array( 'field' => 'cat_compras_documentos_mu_id',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field12' => array( 'field' => 'capturista',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field13' => array( 'field' => 'vigente',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field14' => array( 'field' => 'cat_finanzas_cuentas_de_balance_03_mu_id',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field16' => array( 'field' => 'alias_cuenta_de_balance',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field17' => array( 'field' => 'imei',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field18' => array( 'field' => 'uuid_sat',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field19' => array( 'field' => 'time_stamp',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field20' => array( 'field' => 'consecutivo_id',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field21' => array( 'field' => 'cat_finanzas_bancos_cuentas_id',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field22' => array( 'field' => 'cat_finanzas_cajas_chicas_id',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field23' => array( 'field' => 'uuid_cargo_abono_compra',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field24' => array( 'field' => 'uuid_cargo_abono_pago',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field25' => array( 'field' => 'cat_usuarios_licencias_id',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field26' => array( 'field' => 'cat_compras_cargo_abono_mu_id',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field27' => array( 'field' => 'id_prov',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field28' => array( 'field' => 'total_compras_abonos',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field29' => array( 'field' => 'total_pagos_cargos',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field30' => array( 'field' => 'saldo',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field31' => array( 'field' => 'alias_cuenta_de_abono_compra',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field32' => array( 'field' => 'alias_cuenta_de_cargo_pago',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field1' => array( 'field' => 'cat_finanzas_cuentas_de_balance_04_llave',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field15' => array( 'field' => 'tr_compras_requisiciones_01_uuid_pago',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field33' => array( 'field' => 'tr_compras_requisiciones_01_uuid',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field34' => array( 'field' => 'referencia_bancaria',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field35' => array( 'field' => 'observacion_cargo_pago',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field36' => array( 'field' => 'llave_unica_cargo_abono_tr_compras_requisiciones_01_uuid_pago',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field37' => array( 'field' => 'fecha_de_recibo',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field38' => array( 'field' => 'tr_compras_almacenes_01_recibo_lpn_uuid',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field39' => array( 'field' => 'orden_de_compra_proveedor',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field40' => array( 'field' => 'cat_compras_estatus_mu_id',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field41' => array( 'field' => 'tr_finanzas_bancos_01_id',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>