<?php
			$optionsArray = array( 'list' => array( 'inlineAdd' => true,
'detailsAdd' => true,
'inlineEdit' => true,
'spreadsheetMode' => false,
'reorderRows' => false,
'addToBottom' => false,
'delete' => false,
'updateSelected' => false,
'addInPopup' => null,
'editInPopup' => null,
'viewInPopup' => null,
'clickSort' => true,
'sortDropdown' => false,
'showHideFields' => false,
'reorderFields' => false,
'fieldFilter' => false,
'hideNumberOfRecords' => false ),
'master' => array( 'tr_compras_proveedores_01_cargos_abonos' => array( 'preview' => true ) ),
'listSearch' => array( 'alwaysOnPanelFields' => array(  ),
'searchPanel' => true,
'fixedSearchPanel' => false,
'simpleSearchOptions' => true,
'searchSaving' => false ),
'totals' => array( 'tr_compras_proveedores_01_cargos_abonos_id' => array( 'totalsType' => '' ),
'id_prov' => array( 'totalsType' => '' ),
'descripcion_proveedores' => array( 'totalsType' => '' ),
'alias_proveedor' => array( 'totalsType' => '' ),
'fecha_de_compra' => array( 'totalsType' => '' ),
'referencia' => array( 'totalsType' => '' ),
'importe_abono_compra' => array( 'totalsType' => '' ),
'importe_cargo_pago' => array( 'totalsType' => 'TOTAL' ),
'fecha_de_pago' => array( 'totalsType' => '' ),
'fecha_de_vencimiento' => array( 'totalsType' => '' ),
'concepto' => array( 'totalsType' => '' ),
'cat_compras_documentos_mu_id' => array( 'totalsType' => '' ),
'capturista' => array( 'totalsType' => '' ),
'vigente' => array( 'totalsType' => '' ),
'cat_finanzas_cuentas_de_balance_03_mu_id' => array( 'totalsType' => '' ),
'cat_finanzas_cuentas_de_balance_04_llave' => array( 'totalsType' => '' ),
'alias_cuenta_de_balance' => array( 'totalsType' => '' ),
'imei' => array( 'totalsType' => '' ),
'uuid_sat' => array( 'totalsType' => '' ),
'time_stamp' => array( 'totalsType' => '' ),
'consecutivo_id' => array( 'totalsType' => '' ),
'cat_finanzas_bancos_cuentas_id' => array( 'totalsType' => '' ),
'cat_finanzas_cajas_chicas_id' => array( 'totalsType' => '' ),
'uuid_cargo_abono_compra' => array( 'totalsType' => '' ),
'uuid_cargo_abono_pago' => array( 'totalsType' => '' ),
'cat_usuarios_licencias_id' => array( 'totalsType' => '' ),
'cat_compras_cargo_abono_mu_id' => array( 'totalsType' => '' ),
'total_compras_abonos' => array( 'totalsType' => '' ),
'total_pagos_cargos' => array( 'totalsType' => '' ),
'saldo' => array( 'totalsType' => '' ),
'alias_cuenta_de_abono_compra' => array( 'totalsType' => '' ),
'alias_cuenta_de_cargo_pago' => array( 'totalsType' => '' ),
'tr_compras_requisiciones_01_uuid_pago' => array( 'totalsType' => '' ),
'tr_compras_requisiciones_01_uuid' => array( 'totalsType' => '' ),
'referencia_bancaria' => array( 'totalsType' => '' ),
'observacion_cargo_pago' => array( 'totalsType' => '' ),
'llave_unica_cargo_abono_tr_compras_requisiciones_01_uuid_pago' => array( 'totalsType' => '' ),
'fecha_de_recibo' => array( 'totalsType' => '' ),
'tr_compras_almacenes_01_recibo_lpn_uuid' => array( 'totalsType' => '' ),
'orden_de_compra_proveedor' => array( 'totalsType' => '' ),
'cat_compras_estatus_mu_id' => array( 'totalsType' => '' ),
'tr_finanzas_bancos_01_id' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'fecha_de_pago',
'id_prov',
'descripcion_proveedores',
'importe_cargo_pago',
'cat_compras_estatus_mu_id',
'uuid_sat',
'orden_de_compra_proveedor',
'referencia_bancaria',
'tr_finanzas_bancos_01_id',
'cat_finanzas_cuentas_de_balance_04_llave',
'observacion_cargo_pago',
'fecha_de_recibo',
'tr_compras_almacenes_01_recibo_lpn_uuid',
'vigente',
'uuid_cargo_abono_pago',
'tr_compras_requisiciones_01_uuid',
'tr_compras_proveedores_01_cargos_abonos_id',
'cat_compras_cargo_abono_mu_id',
'capturista',
'llave_unica_cargo_abono_tr_compras_requisiciones_01_uuid_pago',
'fecha_de_compra' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array( 'alias_cuenta_de_cargo_pago',
'tr_finanzas_bancos_01_id',
'cat_compras_estatus_mu_id',
'orden_de_compra_proveedor',
'fecha_de_pago',
'fecha_de_compra',
'tr_compras_almacenes_01_recibo_lpn_uuid',
'fecha_de_recibo',
'llave_unica_cargo_abono_tr_compras_requisiciones_01_uuid_pago',
'uuid_sat',
'observacion_cargo_pago',
'alias_proveedor',
'referencia_bancaria',
'tr_compras_requisiciones_01_uuid_pago',
'tr_compras_requisiciones_01_uuid',
'cat_finanzas_cuentas_de_balance_04_llave',
'tr_compras_proveedores_01_cargos_abonos_id',
'descripcion_proveedores',
'uuid_cargo_abono_pago',
'uuid_cargo_abono_compra',
'importe_cargo_pago',
'importe_abono_compra',
'id_prov' ),
'filterFields' => array(  ),
'inlineAddFields' => array( 'fecha_de_pago',
'id_prov',
'importe_cargo_pago',
'uuid_sat',
'orden_de_compra_proveedor',
'referencia_bancaria',
'tr_finanzas_bancos_01_id',
'cat_finanzas_cuentas_de_balance_04_llave',
'observacion_cargo_pago',
'fecha_de_recibo',
'tr_compras_almacenes_01_recibo_lpn_uuid',
'vigente',
'uuid_cargo_abono_pago',
'tr_compras_requisiciones_01_uuid',
'cat_compras_cargo_abono_mu_id',
'capturista',
'llave_unica_cargo_abono_tr_compras_requisiciones_01_uuid_pago' ),
'inlineEditFields' => array( 'fecha_de_pago',
'id_prov',
'importe_cargo_pago',
'uuid_sat',
'orden_de_compra_proveedor',
'referencia_bancaria',
'tr_finanzas_bancos_01_id',
'cat_finanzas_cuentas_de_balance_04_llave',
'observacion_cargo_pago',
'fecha_de_recibo',
'tr_compras_almacenes_01_recibo_lpn_uuid',
'vigente',
'cat_compras_cargo_abono_mu_id',
'capturista',
'llave_unica_cargo_abono_tr_compras_requisiciones_01_uuid_pago' ),
'fieldItems' => array( 'fecha_de_pago' => array( 'simple_grid_field8',
'simple_grid_field20' ),
'id_prov' => array( 'simple_grid_field17',
'simple_grid_field21' ),
'descripcion_proveedores' => array( 'simple_grid_field',
'simple_grid_field22' ),
'importe_cargo_pago' => array( 'simple_grid_field7',
'simple_grid_field23',
'simple_grid_field25' ),
'cat_compras_estatus_mu_id' => array( 'simple_grid_field15',
'simple_grid_field26' ),
'uuid_sat' => array( 'simple_grid_field18',
'simple_grid_field27' ),
'orden_de_compra_proveedor' => array( 'simple_grid_field14',
'simple_grid_field28' ),
'referencia_bancaria' => array( 'simple_grid_field6',
'simple_grid_field29' ),
'tr_finanzas_bancos_01_id' => array( 'simple_grid_field16',
'simple_grid_field30' ),
'cat_finanzas_cuentas_de_balance_04_llave' => array( 'simple_grid_field1',
'simple_grid_field31' ),
'observacion_cargo_pago' => array( 'simple_grid_field10',
'simple_grid_field32' ),
'fecha_de_recibo' => array( 'simple_grid_field5',
'simple_grid_field33' ),
'tr_compras_almacenes_01_recibo_lpn_uuid' => array( 'simple_grid_field9',
'simple_grid_field34' ),
'vigente' => array( 'simple_grid_field13',
'simple_grid_field35' ),
'uuid_cargo_abono_pago' => array( 'simple_grid_field24',
'simple_grid_field36' ),
'tr_compras_requisiciones_01_uuid' => array( 'simple_grid_field4',
'simple_grid_field37' ),
'tr_compras_proveedores_01_cargos_abonos_id' => array( 'simple_grid_field3',
'simple_grid_field38' ),
'cat_compras_cargo_abono_mu_id' => array( 'simple_grid_field19',
'simple_grid_field39' ),
'capturista' => array( 'simple_grid_field12',
'simple_grid_field40' ),
'llave_unica_cargo_abono_tr_compras_requisiciones_01_uuid_pago' => array( 'simple_grid_field2',
'simple_grid_field41' ),
'fecha_de_compra' => array( 'simple_grid_field11',
'simple_grid_field42' ) ),
'hideEmptyFields' => array(  ),
'fieldFilterFields' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'inline_add',
'inline_save_all',
'inline_cancel_all',
'details_found',
'page_size' ),
'below-grid' => array( 'pagination' ),
'left' => array( 'logo',
'expand_button',
'menu',
'search_panel' ),
'supertop' => array( 'expand_menu_button',
'collapse_button',
'breadcrumb',
'simple_search_field',
'simple_search_option',
'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'top' => array( 'master_info' ),
'grid' => array( 'simple_grid_field20',
'simple_grid_field8',
'simple_grid_field21',
'simple_grid_field17',
'simple_grid_field22',
'simple_grid_field',
'simple_grid_field23',
'simple_grid_field7',
'simple_grid_field25',
'simple_grid_field26',
'simple_grid_field15',
'simple_grid_field27',
'simple_grid_field18',
'simple_grid_field28',
'simple_grid_field14',
'simple_grid_field29',
'simple_grid_field6',
'simple_grid_field30',
'simple_grid_field16',
'simple_grid_field31',
'simple_grid_field1',
'simple_grid_field32',
'simple_grid_field10',
'simple_grid_field33',
'simple_grid_field5',
'simple_grid_field34',
'simple_grid_field9',
'simple_grid_field35',
'simple_grid_field13',
'simple_grid_field36',
'simple_grid_field24',
'simple_grid_field37',
'simple_grid_field4',
'simple_grid_field38',
'simple_grid_field3',
'simple_grid_field39',
'simple_grid_field19',
'simple_grid_field40',
'simple_grid_field12',
'simple_grid_field41',
'simple_grid_field2',
'simple_grid_field42',
'simple_grid_field11',
'grid_checkbox_head',
'grid_checkbox',
'grid_inline_edit',
'grid_inline_save',
'grid_inline_cancel' ) ),
'formXtTags' => array( 'above-grid' => array( 'inlineadd_link',
'saveall_link',
'cancelall_link',
'details_found',
'recsPerPage' ),
'below-grid' => array( 'pagination' ),
'top' => array( 'mastertable_block' ) ),
'itemForms' => array( 'inline_add' => 'above-grid',
'inline_save_all' => 'above-grid',
'inline_cancel_all' => 'above-grid',
'details_found' => 'above-grid',
'page_size' => 'above-grid',
'pagination' => 'below-grid',
'logo' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'search_panel' => 'left',
'expand_menu_button' => 'supertop',
'collapse_button' => 'supertop',
'breadcrumb' => 'supertop',
'simple_search_field' => 'supertop',
'simple_search_option' => 'supertop',
'simple_search' => 'supertop',
'list_options' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'master_info' => 'top',
'simple_grid_field20' => 'grid',
'simple_grid_field8' => 'grid',
'simple_grid_field21' => 'grid',
'simple_grid_field17' => 'grid',
'simple_grid_field22' => 'grid',
'simple_grid_field' => 'grid',
'simple_grid_field23' => 'grid',
'simple_grid_field7' => 'grid',
'simple_grid_field25' => 'grid',
'simple_grid_field26' => 'grid',
'simple_grid_field15' => 'grid',
'simple_grid_field27' => 'grid',
'simple_grid_field18' => 'grid',
'simple_grid_field28' => 'grid',
'simple_grid_field14' => 'grid',
'simple_grid_field29' => 'grid',
'simple_grid_field6' => 'grid',
'simple_grid_field30' => 'grid',
'simple_grid_field16' => 'grid',
'simple_grid_field31' => 'grid',
'simple_grid_field1' => 'grid',
'simple_grid_field32' => 'grid',
'simple_grid_field10' => 'grid',
'simple_grid_field33' => 'grid',
'simple_grid_field5' => 'grid',
'simple_grid_field34' => 'grid',
'simple_grid_field9' => 'grid',
'simple_grid_field35' => 'grid',
'simple_grid_field13' => 'grid',
'simple_grid_field36' => 'grid',
'simple_grid_field24' => 'grid',
'simple_grid_field37' => 'grid',
'simple_grid_field4' => 'grid',
'simple_grid_field38' => 'grid',
'simple_grid_field3' => 'grid',
'simple_grid_field39' => 'grid',
'simple_grid_field19' => 'grid',
'simple_grid_field40' => 'grid',
'simple_grid_field12' => 'grid',
'simple_grid_field41' => 'grid',
'simple_grid_field2' => 'grid',
'simple_grid_field42' => 'grid',
'simple_grid_field11' => 'grid',
'grid_checkbox_head' => 'grid',
'grid_checkbox' => 'grid',
'grid_inline_edit' => 'grid',
'grid_inline_save' => 'grid',
'grid_inline_cancel' => 'grid' ),
'itemLocations' => array( 'simple_grid_field20' => array( 'location' => 'grid',
'cellId' => 'headcell_field' ),
'simple_grid_field8' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'simple_grid_field21' => array( 'location' => 'grid',
'cellId' => 'headcell_field1' ),
'simple_grid_field17' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'simple_grid_field22' => array( 'location' => 'grid',
'cellId' => 'headcell_field2' ),
'simple_grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field2' ),
'simple_grid_field23' => array( 'location' => 'grid',
'cellId' => 'headcell_field3' ),
'simple_grid_field7' => array( 'location' => 'grid',
'cellId' => 'cell_field3' ),
'simple_grid_field25' => array( 'location' => 'grid',
'cellId' => 'footcell_field3' ),
'simple_grid_field26' => array( 'location' => 'grid',
'cellId' => 'headcell_field4' ),
'simple_grid_field15' => array( 'location' => 'grid',
'cellId' => 'cell_field4' ),
'simple_grid_field27' => array( 'location' => 'grid',
'cellId' => 'headcell_field5' ),
'simple_grid_field18' => array( 'location' => 'grid',
'cellId' => 'cell_field5' ),
'simple_grid_field28' => array( 'location' => 'grid',
'cellId' => 'headcell_field6' ),
'simple_grid_field14' => array( 'location' => 'grid',
'cellId' => 'cell_field6' ),
'simple_grid_field29' => array( 'location' => 'grid',
'cellId' => 'headcell_field7' ),
'simple_grid_field6' => array( 'location' => 'grid',
'cellId' => 'cell_field7' ),
'simple_grid_field30' => array( 'location' => 'grid',
'cellId' => 'headcell_field8' ),
'simple_grid_field16' => array( 'location' => 'grid',
'cellId' => 'cell_field8' ),
'simple_grid_field31' => array( 'location' => 'grid',
'cellId' => 'headcell_field9' ),
'simple_grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field9' ),
'simple_grid_field32' => array( 'location' => 'grid',
'cellId' => 'headcell_field10' ),
'simple_grid_field10' => array( 'location' => 'grid',
'cellId' => 'cell_field10' ),
'simple_grid_field33' => array( 'location' => 'grid',
'cellId' => 'headcell_field11' ),
'simple_grid_field5' => array( 'location' => 'grid',
'cellId' => 'cell_field11' ),
'simple_grid_field34' => array( 'location' => 'grid',
'cellId' => 'headcell_field12' ),
'simple_grid_field9' => array( 'location' => 'grid',
'cellId' => 'cell_field12' ),
'simple_grid_field35' => array( 'location' => 'grid',
'cellId' => 'headcell_field13' ),
'simple_grid_field13' => array( 'location' => 'grid',
'cellId' => 'cell_field13' ),
'simple_grid_field36' => array( 'location' => 'grid',
'cellId' => 'headcell_field14' ),
'simple_grid_field24' => array( 'location' => 'grid',
'cellId' => 'cell_field14' ),
'simple_grid_field37' => array( 'location' => 'grid',
'cellId' => 'headcell_field15' ),
'simple_grid_field4' => array( 'location' => 'grid',
'cellId' => 'cell_field15' ),
'simple_grid_field38' => array( 'location' => 'grid',
'cellId' => 'headcell_field16' ),
'simple_grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_field16' ),
'simple_grid_field39' => array( 'location' => 'grid',
'cellId' => 'headcell_field17' ),
'simple_grid_field19' => array( 'location' => 'grid',
'cellId' => 'cell_field17' ),
'simple_grid_field40' => array( 'location' => 'grid',
'cellId' => 'headcell_field18' ),
'simple_grid_field12' => array( 'location' => 'grid',
'cellId' => 'cell_field18' ),
'simple_grid_field41' => array( 'location' => 'grid',
'cellId' => 'headcell_field19' ),
'simple_grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field19' ),
'simple_grid_field42' => array( 'location' => 'grid',
'cellId' => 'headcell_field20' ),
'simple_grid_field11' => array( 'location' => 'grid',
'cellId' => 'cell_field20' ),
'grid_checkbox_head' => array( 'location' => 'grid',
'cellId' => 'headcell_checkbox' ),
'grid_checkbox' => array( 'location' => 'grid',
'cellId' => 'cell_checkbox' ),
'grid_inline_edit' => array( 'location' => 'grid',
'cellId' => 'cell_icons' ),
'grid_inline_save' => array( 'location' => 'grid',
'cellId' => 'cell_icons' ),
'grid_inline_cancel' => array( 'location' => 'grid',
'cellId' => 'cell_icons' ) ),
'itemVisiblity' => array( 'breadcrumb' => 5,
'expand_menu_button' => 2,
'expand_button' => 5 ) ),
'itemsByType' => array( 'page_size' => array( 'page_size' ),
'details_found' => array( 'details_found' ),
'breadcrumb' => array( 'breadcrumb' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'simple_search' => array( 'simple_search' ),
'pagination' => array( 'pagination' ),
'search_panel' => array( 'search_panel' ),
'list_options' => array( 'list_options' ),
'show_search_panel' => array( 'show_search_panel' ),
'hide_search_panel' => array( 'hide_search_panel' ),
'search_panel_field' => array( 'search_panel_field',
'search_panel_field3',
'search_panel_field5',
'search_panel_field6',
'search_panel_field7',
'search_panel_field8',
'search_panel_field11',
'search_panel_field1',
'search_panel_field2',
'search_panel_field4',
'search_panel_field9',
'search_panel_field12',
'search_panel_field13',
'search_panel_field10',
'search_panel_field14',
'search_panel_field15',
'search_panel_field16',
'search_panel_field17',
'search_panel_field18',
'search_panel_field19',
'search_panel_field20',
'search_panel_field21',
'search_panel_field22' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'userinfo_link' => array( 'userinfo_link' ),
'logout_link' => array( 'logout_link' ),
'adminarea_link' => array( 'adminarea_link' ),
'changepassword_link' => array( 'changepassword_link' ),
'expand_menu_button' => array( 'expand_menu_button' ),
'collapse_button' => array( 'collapse_button' ),
'-' => array( '-',
'-1',
'-2',
'-3' ),
'import' => array( 'import' ),
'advsearch_link' => array( 'advsearch_link' ),
'inline_add' => array( 'inline_add' ),
'inline_save_all' => array( 'inline_save_all' ),
'inline_cancel_all' => array( 'inline_cancel_all' ),
'edit_selected' => array( 'edit_selected' ),
'master_info' => array( 'master_info' ),
'simple_search_field' => array( 'simple_search_field' ),
'simple_search_option' => array( 'simple_search_option' ),
'grid_field' => array( 'simple_grid_field8',
'simple_grid_field17',
'simple_grid_field',
'simple_grid_field7',
'simple_grid_field15',
'simple_grid_field18',
'simple_grid_field14',
'simple_grid_field6',
'simple_grid_field16',
'simple_grid_field1',
'simple_grid_field10',
'simple_grid_field5',
'simple_grid_field9',
'simple_grid_field13',
'simple_grid_field24',
'simple_grid_field4',
'simple_grid_field3',
'simple_grid_field19',
'simple_grid_field12',
'simple_grid_field2',
'simple_grid_field11' ),
'grid_field_label' => array( 'simple_grid_field20',
'simple_grid_field21',
'simple_grid_field22',
'simple_grid_field23',
'simple_grid_field26',
'simple_grid_field27',
'simple_grid_field28',
'simple_grid_field29',
'simple_grid_field30',
'simple_grid_field31',
'simple_grid_field32',
'simple_grid_field33',
'simple_grid_field34',
'simple_grid_field35',
'simple_grid_field36',
'simple_grid_field37',
'simple_grid_field38',
'simple_grid_field39',
'simple_grid_field40',
'simple_grid_field41',
'simple_grid_field42' ),
'grid_field_totals' => array( 'simple_grid_field25' ),
'grid_checkbox' => array( 'grid_checkbox' ),
'grid_checkbox_head' => array( 'grid_checkbox_head' ),
'grid_inline_cancel' => array( 'grid_inline_cancel' ),
'grid_inline_save' => array( 'grid_inline_save' ),
'grid_inline_edit' => array( 'grid_inline_edit' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'headcell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_checkbox' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array( 'checkbox_column' ),
'items' => array( 'grid_checkbox_head' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array( 'fecha_de_pago_fieldheadercolumn' ),
'items' => array( 'simple_grid_field20' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field1' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array( 'id_prov_fieldheadercolumn' ),
'items' => array( 'simple_grid_field21' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field2' => array( 'cols' => array( 4 ),
'rows' => array( 0 ),
'tags' => array( 'descripcion_proveedores_fieldheadercolumn' ),
'items' => array( 'simple_grid_field22' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field3' => array( 'cols' => array( 5 ),
'rows' => array( 0 ),
'tags' => array( 'importe_cargo_pago_fieldheadercolumn' ),
'items' => array( 'simple_grid_field23' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field4' => array( 'cols' => array( 6 ),
'rows' => array( 0 ),
'tags' => array( 'cat_compras_estatus_mu_id_fieldheadercolumn' ),
'items' => array( 'simple_grid_field26' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field5' => array( 'cols' => array( 7 ),
'rows' => array( 0 ),
'tags' => array( 'uuid_sat_fieldheadercolumn' ),
'items' => array( 'simple_grid_field27' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field6' => array( 'cols' => array( 8 ),
'rows' => array( 0 ),
'tags' => array( 'orden_de_compra_proveedor_fieldheadercolumn' ),
'items' => array( 'simple_grid_field28' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field7' => array( 'cols' => array( 9 ),
'rows' => array( 0 ),
'tags' => array( 'referencia_bancaria_fieldheadercolumn' ),
'items' => array( 'simple_grid_field29' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field8' => array( 'cols' => array( 10 ),
'rows' => array( 0 ),
'tags' => array( 'tr_finanzas_bancos_01_id_fieldheadercolumn' ),
'items' => array( 'simple_grid_field30' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field9' => array( 'cols' => array( 11 ),
'rows' => array( 0 ),
'tags' => array( 'cat_finanzas_cuentas_de_balance_04_llave_fieldheadercolumn' ),
'items' => array( 'simple_grid_field31' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field10' => array( 'cols' => array( 12 ),
'rows' => array( 0 ),
'tags' => array( 'observacion_cargo_pago_fieldheadercolumn' ),
'items' => array( 'simple_grid_field32' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field11' => array( 'cols' => array( 13 ),
'rows' => array( 0 ),
'tags' => array( 'fecha_de_recibo_fieldheadercolumn' ),
'items' => array( 'simple_grid_field33' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field12' => array( 'cols' => array( 14 ),
'rows' => array( 0 ),
'tags' => array( 'tr_compras_almacenes_01_recibo_lpn_uuid_fieldheadercolumn' ),
'items' => array( 'simple_grid_field34' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field13' => array( 'cols' => array( 15 ),
'rows' => array( 0 ),
'tags' => array( 'vigente_fieldheadercolumn' ),
'items' => array( 'simple_grid_field35' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field14' => array( 'cols' => array( 16 ),
'rows' => array( 0 ),
'tags' => array( 'uuid_cargo_abono_pago_fieldheadercolumn' ),
'items' => array( 'simple_grid_field36' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field15' => array( 'cols' => array( 17 ),
'rows' => array( 0 ),
'tags' => array( 'tr_compras_requisiciones_01_uuid_fieldheadercolumn' ),
'items' => array( 'simple_grid_field37' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field16' => array( 'cols' => array( 18 ),
'rows' => array( 0 ),
'tags' => array( 'tr_compras_proveedores_01_cargos_abonos_id_fieldheadercolumn' ),
'items' => array( 'simple_grid_field38' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field17' => array( 'cols' => array( 19 ),
'rows' => array( 0 ),
'tags' => array( 'cat_compras_cargo_abono_mu_id_fieldheadercolumn' ),
'items' => array( 'simple_grid_field39' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field18' => array( 'cols' => array( 20 ),
'rows' => array( 0 ),
'tags' => array( 'capturista_fieldheadercolumn' ),
'items' => array( 'simple_grid_field40' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field19' => array( 'cols' => array( 21 ),
'rows' => array( 0 ),
'tags' => array( 'llave_unica_cargo_abono_tr_compras_requisiciones_01_uuid_pago_fieldheadercolumn' ),
'items' => array( 'simple_grid_field41' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field20' => array( 'cols' => array( 22 ),
'rows' => array( 0 ),
'tags' => array( 'fecha_de_compra_fieldheadercolumn' ),
'items' => array( 'simple_grid_field42' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'inlineedit_column',
'inline_save',
'inline_cancel' ),
'items' => array( 'grid_inline_edit',
'grid_inline_save',
'grid_inline_cancel' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_checkbox' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array( 'checkbox_column' ),
'items' => array( 'grid_checkbox' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array( 'fecha_de_pago_fieldcolumn' ),
'items' => array( 'simple_grid_field8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array( 'id_prov_fieldcolumn' ),
'items' => array( 'simple_grid_field17' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 4 ),
'rows' => array( 1 ),
'tags' => array( 'descripcion_proveedores_fieldcolumn' ),
'items' => array( 'simple_grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field3' => array( 'cols' => array( 5 ),
'rows' => array( 1 ),
'tags' => array( 'importe_cargo_pago_fieldcolumn' ),
'items' => array( 'simple_grid_field7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field4' => array( 'cols' => array( 6 ),
'rows' => array( 1 ),
'tags' => array( 'cat_compras_estatus_mu_id_fieldcolumn' ),
'items' => array( 'simple_grid_field15' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field5' => array( 'cols' => array( 7 ),
'rows' => array( 1 ),
'tags' => array( 'uuid_sat_fieldcolumn' ),
'items' => array( 'simple_grid_field18' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field6' => array( 'cols' => array( 8 ),
'rows' => array( 1 ),
'tags' => array( 'orden_de_compra_proveedor_fieldcolumn' ),
'items' => array( 'simple_grid_field14' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field7' => array( 'cols' => array( 9 ),
'rows' => array( 1 ),
'tags' => array( 'referencia_bancaria_fieldcolumn' ),
'items' => array( 'simple_grid_field6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field8' => array( 'cols' => array( 10 ),
'rows' => array( 1 ),
'tags' => array( 'tr_finanzas_bancos_01_id_fieldcolumn' ),
'items' => array( 'simple_grid_field16' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field9' => array( 'cols' => array( 11 ),
'rows' => array( 1 ),
'tags' => array( 'cat_finanzas_cuentas_de_balance_04_llave_fieldcolumn' ),
'items' => array( 'simple_grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field10' => array( 'cols' => array( 12 ),
'rows' => array( 1 ),
'tags' => array( 'observacion_cargo_pago_fieldcolumn' ),
'items' => array( 'simple_grid_field10' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field11' => array( 'cols' => array( 13 ),
'rows' => array( 1 ),
'tags' => array( 'fecha_de_recibo_fieldcolumn' ),
'items' => array( 'simple_grid_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field12' => array( 'cols' => array( 14 ),
'rows' => array( 1 ),
'tags' => array( 'tr_compras_almacenes_01_recibo_lpn_uuid_fieldcolumn' ),
'items' => array( 'simple_grid_field9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field13' => array( 'cols' => array( 15 ),
'rows' => array( 1 ),
'tags' => array( 'vigente_fieldcolumn' ),
'items' => array( 'simple_grid_field13' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field14' => array( 'cols' => array( 16 ),
'rows' => array( 1 ),
'tags' => array( 'uuid_cargo_abono_pago_fieldcolumn' ),
'items' => array( 'simple_grid_field24' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field15' => array( 'cols' => array( 17 ),
'rows' => array( 1 ),
'tags' => array( 'tr_compras_requisiciones_01_uuid_fieldcolumn' ),
'items' => array( 'simple_grid_field4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field16' => array( 'cols' => array( 18 ),
'rows' => array( 1 ),
'tags' => array( 'tr_compras_proveedores_01_cargos_abonos_id_fieldcolumn' ),
'items' => array( 'simple_grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field17' => array( 'cols' => array( 19 ),
'rows' => array( 1 ),
'tags' => array( 'cat_compras_cargo_abono_mu_id_fieldcolumn' ),
'items' => array( 'simple_grid_field19' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field18' => array( 'cols' => array( 20 ),
'rows' => array( 1 ),
'tags' => array( 'capturista_fieldcolumn' ),
'items' => array( 'simple_grid_field12' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field19' => array( 'cols' => array( 21 ),
'rows' => array( 1 ),
'tags' => array( 'llave_unica_cargo_abono_tr_compras_requisiciones_01_uuid_pago_fieldcolumn' ),
'items' => array( 'simple_grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field20' => array( 'cols' => array( 22 ),
'rows' => array( 1 ),
'tags' => array( 'fecha_de_compra_fieldcolumn' ),
'items' => array( 'simple_grid_field11' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_checkbox' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field1' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field2' => array( 'cols' => array( 4 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field3' => array( 'cols' => array( 5 ),
'rows' => array( 2 ),
'tags' => array( 'importe_cargo_pago_fieldfootercolumn' ),
'items' => array( 'simple_grid_field25' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field4' => array( 'cols' => array( 6 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field5' => array( 'cols' => array( 7 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field6' => array( 'cols' => array( 8 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field7' => array( 'cols' => array( 9 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field8' => array( 'cols' => array( 10 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field9' => array( 'cols' => array( 11 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field10' => array( 'cols' => array( 12 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field11' => array( 'cols' => array( 13 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field12' => array( 'cols' => array( 14 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field13' => array( 'cols' => array( 15 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field14' => array( 'cols' => array( 16 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field15' => array( 'cols' => array( 17 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field16' => array( 'cols' => array( 18 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field17' => array( 'cols' => array( 19 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field18' => array( 'cols' => array( 20 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field19' => array( 'cols' => array( 21 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field20' => array( 'cols' => array( 22 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 23,
'height' => 3 ) ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array( 'details_found' => array( 'tag' => 'DISPLAYING',
'type' => 2 ) ) ),
'gridType' => 0,
'recsPerRow' => 1,
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array( array( 'id' => 'main',
'horizontal' => false ) ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'list',
'breadcrumb' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'list',
'type' => 'list',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'list-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'inline_add',
'inline_save_all',
'inline_cancel_all' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'details_found',
'page_size' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'list-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'pagination' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo',
'expand_button' ) ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu',
'search_panel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'expand_menu_button',
'collapse_button',
'breadcrumb' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'simple_search_field',
'simple_search_option',
'simple_search',
'list_options',
'loginform_login',
'username_button' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'list-sidebar-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c2' => array( 'model' => 'c2',
'items' => array( 'master_info' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'horizontal-grid',
'grid' => array( array( 'section' => 'head',
'cells' => array( array( 'cell' => 'headcell_icons' ),
array( 'cell' => 'headcell_checkbox' ),
array( 'cell' => 'headcell_field' ),
array( 'cell' => 'headcell_field1' ),
array( 'cell' => 'headcell_field2' ),
array( 'cell' => 'headcell_field3' ),
array( 'cell' => 'headcell_field4' ),
array( 'cell' => 'headcell_field5' ),
array( 'cell' => 'headcell_field6' ),
array( 'cell' => 'headcell_field7' ),
array( 'cell' => 'headcell_field8' ),
array( 'cell' => 'headcell_field9' ),
array( 'cell' => 'headcell_field10' ),
array( 'cell' => 'headcell_field11' ),
array( 'cell' => 'headcell_field12' ),
array( 'cell' => 'headcell_field13' ),
array( 'cell' => 'headcell_field14' ),
array( 'cell' => 'headcell_field15' ),
array( 'cell' => 'headcell_field16' ),
array( 'cell' => 'headcell_field17' ),
array( 'cell' => 'headcell_field18' ),
array( 'cell' => 'headcell_field19' ),
array( 'cell' => 'headcell_field20' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_icons' ),
array( 'cell' => 'cell_checkbox' ),
array( 'cell' => 'cell_field' ),
array( 'cell' => 'cell_field1' ),
array( 'cell' => 'cell_field2' ),
array( 'cell' => 'cell_field3' ),
array( 'cell' => 'cell_field4' ),
array( 'cell' => 'cell_field5' ),
array( 'cell' => 'cell_field6' ),
array( 'cell' => 'cell_field7' ),
array( 'cell' => 'cell_field8' ),
array( 'cell' => 'cell_field9' ),
array( 'cell' => 'cell_field10' ),
array( 'cell' => 'cell_field11' ),
array( 'cell' => 'cell_field12' ),
array( 'cell' => 'cell_field13' ),
array( 'cell' => 'cell_field14' ),
array( 'cell' => 'cell_field15' ),
array( 'cell' => 'cell_field16' ),
array( 'cell' => 'cell_field17' ),
array( 'cell' => 'cell_field18' ),
array( 'cell' => 'cell_field19' ),
array( 'cell' => 'cell_field20' ) ) ),
array( 'section' => 'foot',
'cells' => array( array( 'cell' => 'footcell_icons' ),
array( 'cell' => 'footcell_checkbox' ),
array( 'cell' => 'footcell_field' ),
array( 'cell' => 'footcell_field1' ),
array( 'cell' => 'footcell_field2' ),
array( 'cell' => 'footcell_field3' ),
array( 'cell' => 'footcell_field4' ),
array( 'cell' => 'footcell_field5' ),
array( 'cell' => 'footcell_field6' ),
array( 'cell' => 'footcell_field7' ),
array( 'cell' => 'footcell_field8' ),
array( 'cell' => 'footcell_field9' ),
array( 'cell' => 'footcell_field10' ),
array( 'cell' => 'footcell_field11' ),
array( 'cell' => 'footcell_field12' ),
array( 'cell' => 'footcell_field13' ),
array( 'cell' => 'footcell_field14' ),
array( 'cell' => 'footcell_field15' ),
array( 'cell' => 'footcell_field16' ),
array( 'cell' => 'footcell_field17' ),
array( 'cell' => 'footcell_field18' ),
array( 'cell' => 'footcell_field19' ),
array( 'cell' => 'footcell_field20' ) ) ) ),
'cells' => array( 'headcell_field' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field20' ),
'field' => 'fecha_de_pago',
'columnName' => 'field' ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field8' ),
'field' => 'fecha_de_pago',
'columnName' => 'field' ),
'footcell_field' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field1' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field21' ),
'field' => 'id_prov',
'columnName' => 'field' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field17' ),
'field' => 'id_prov',
'columnName' => 'field' ),
'footcell_field1' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field2' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field22' ),
'field' => 'descripcion_proveedores',
'columnName' => 'field' ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field' ),
'field' => 'descripcion_proveedores',
'columnName' => 'field' ),
'footcell_field2' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field3' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field23' ),
'field' => 'importe_cargo_pago',
'columnName' => 'field' ),
'cell_field3' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field7' ),
'field' => 'importe_cargo_pago',
'columnName' => 'field' ),
'footcell_field3' => array( 'model' => 'footcell_field',
'items' => array( 'simple_grid_field25' ),
'field' => 'importe_cargo_pago',
'columnName' => 'field' ),
'headcell_field4' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field26' ),
'field' => 'cat_compras_estatus_mu_id',
'columnName' => 'field' ),
'cell_field4' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field15' ),
'field' => 'cat_compras_estatus_mu_id',
'columnName' => 'field' ),
'footcell_field4' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field5' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field27' ),
'field' => 'uuid_sat',
'columnName' => 'field' ),
'cell_field5' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field18' ),
'field' => 'uuid_sat',
'columnName' => 'field' ),
'footcell_field5' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field6' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field28' ),
'field' => 'orden_de_compra_proveedor',
'columnName' => 'field' ),
'cell_field6' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field14' ),
'field' => 'orden_de_compra_proveedor',
'columnName' => 'field' ),
'footcell_field6' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field7' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field29' ),
'field' => 'referencia_bancaria',
'columnName' => 'field' ),
'cell_field7' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field6' ),
'field' => 'referencia_bancaria',
'columnName' => 'field' ),
'footcell_field7' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field8' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field30' ),
'field' => 'tr_finanzas_bancos_01_id',
'columnName' => 'field' ),
'cell_field8' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field16' ),
'field' => 'tr_finanzas_bancos_01_id',
'columnName' => 'field' ),
'footcell_field8' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field9' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field31' ),
'field' => 'cat_finanzas_cuentas_de_balance_04_llave',
'columnName' => 'field' ),
'cell_field9' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field1' ),
'field' => 'cat_finanzas_cuentas_de_balance_04_llave',
'columnName' => 'field' ),
'footcell_field9' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field10' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field32' ),
'field' => 'observacion_cargo_pago',
'columnName' => 'field' ),
'cell_field10' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field10' ),
'field' => 'observacion_cargo_pago',
'columnName' => 'field' ),
'footcell_field10' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field11' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field33' ),
'field' => 'fecha_de_recibo',
'columnName' => 'field' ),
'cell_field11' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field5' ),
'field' => 'fecha_de_recibo',
'columnName' => 'field' ),
'footcell_field11' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field12' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field34' ),
'field' => 'tr_compras_almacenes_01_recibo_lpn_uuid',
'columnName' => 'field' ),
'cell_field12' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field9' ),
'field' => 'tr_compras_almacenes_01_recibo_lpn_uuid',
'columnName' => 'field' ),
'footcell_field12' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field13' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field35' ),
'field' => 'vigente',
'columnName' => 'field' ),
'cell_field13' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field13' ),
'field' => 'vigente',
'columnName' => 'field' ),
'footcell_field13' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field14' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field36' ),
'field' => 'uuid_cargo_abono_pago',
'columnName' => 'field' ),
'cell_field14' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field24' ),
'field' => 'uuid_cargo_abono_pago',
'columnName' => 'field' ),
'footcell_field14' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field15' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field37' ),
'field' => 'tr_compras_requisiciones_01_uuid',
'columnName' => 'field' ),
'cell_field15' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field4' ),
'field' => 'tr_compras_requisiciones_01_uuid',
'columnName' => 'field' ),
'footcell_field15' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field16' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field38' ),
'field' => 'tr_compras_proveedores_01_cargos_abonos_id',
'columnName' => 'field' ),
'cell_field16' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field3' ),
'field' => 'tr_compras_proveedores_01_cargos_abonos_id',
'columnName' => 'field' ),
'footcell_field16' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field17' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field39' ),
'field' => 'cat_compras_cargo_abono_mu_id',
'columnName' => 'field' ),
'cell_field17' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field19' ),
'field' => 'cat_compras_cargo_abono_mu_id',
'columnName' => 'field' ),
'footcell_field17' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field18' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field40' ),
'field' => 'capturista',
'columnName' => 'field' ),
'cell_field18' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field12' ),
'field' => 'capturista',
'columnName' => 'field' ),
'footcell_field18' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field19' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field41' ),
'field' => 'llave_unica_cargo_abono_tr_compras_requisiciones_01_uuid_pago',
'columnName' => 'field' ),
'cell_field19' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field2' ),
'field' => 'llave_unica_cargo_abono_tr_compras_requisiciones_01_uuid_pago',
'columnName' => 'field' ),
'footcell_field19' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field20' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field42' ),
'field' => 'fecha_de_compra',
'columnName' => 'field' ),
'cell_field20' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field11' ),
'field' => 'fecha_de_compra',
'columnName' => 'field' ),
'footcell_field20' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_checkbox' => array( 'model' => 'headcell_checkbox',
'items' => array( 'grid_checkbox_head' ) ),
'cell_checkbox' => array( 'model' => 'cell_checkbox',
'items' => array( 'grid_checkbox' ) ),
'footcell_checkbox' => array( 'model' => 'footcell_checkbox',
'items' => array(  ) ),
'headcell_icons' => array( 'model' => 'headcell_icons',
'items' => array(  ) ),
'cell_icons' => array( 'model' => 'cell_icons',
'items' => array( 'grid_inline_edit',
'grid_inline_save',
'grid_inline_cancel' ) ),
'footcell_icons' => array( 'model' => 'footcell_icons',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'page_size' => array( 'type' => 'page_size' ),
'details_found' => array( 'type' => 'details_found' ),
'breadcrumb' => array( 'type' => 'breadcrumb' ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'simple_search' => array( 'type' => 'simple_search' ),
'pagination' => array( 'type' => 'pagination' ),
'search_panel' => array( 'type' => 'search_panel',
'items' => array( 'search_panel_field11',
'search_panel_field22',
'search_panel_field21',
'search_panel_field20',
'search_panel_field19',
'search_panel_field18',
'search_panel_field17',
'search_panel_field16',
'search_panel_field15',
'search_panel_field14',
'search_panel_field10',
'search_panel_field13',
'search_panel_field12',
'search_panel_field9',
'search_panel_field4',
'search_panel_field2',
'search_panel_field1',
'search_panel_field3',
'search_panel_field8',
'search_panel_field7',
'search_panel_field6',
'search_panel_field5',
'search_panel_field' ),
'_flexiblePanel' => true ),
'list_options' => array( 'type' => 'list_options',
'items' => array( 'edit_selected',
'-3',
'advsearch_link',
'show_search_panel',
'hide_search_panel',
'-1',
'import' ) ),
'show_search_panel' => array( 'type' => 'show_search_panel' ),
'hide_search_panel' => array( 'type' => 'hide_search_panel' ),
'search_panel_field' => array( 'field' => 'id_prov',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field3' => array( 'field' => 'descripcion_proveedores',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'adminarea_link',
'changepassword_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => false ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'logout_link' => array( 'type' => 'logout_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'changepassword_link' => array( 'type' => 'changepassword_link' ),
'expand_menu_button' => array( 'type' => 'expand_menu_button' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'-' => array( 'type' => '-' ),
'-1' => array( 'type' => '-' ),
'import' => array( 'type' => 'import' ),
'-2' => array( 'type' => '-' ),
'advsearch_link' => array( 'type' => 'advsearch_link' ),
'-3' => array( 'type' => '-' ),
'search_panel_field5' => array( 'field' => 'importe_abono_compra',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field6' => array( 'field' => 'importe_cargo_pago',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'inline_add' => array( 'type' => 'inline_add' ),
'inline_save_all' => array( 'type' => 'inline_save_all' ),
'inline_cancel_all' => array( 'type' => 'inline_cancel_all' ),
'edit_selected' => array( 'type' => 'edit_selected' ),
'master_info' => array( 'type' => 'master_info',
'tables' => array( 'tr_compras_proveedores_01_cargos_abonos' => 'true' ) ),
'search_panel_field7' => array( 'field' => 'uuid_cargo_abono_compra',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field8' => array( 'field' => 'uuid_cargo_abono_pago',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field11' => array( 'field' => 'alias_cuenta_de_cargo_pago',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field1' => array( 'field' => 'tr_compras_proveedores_01_cargos_abonos_id',
'type' => 'search_panel_field' ),
'search_panel_field2' => array( 'field' => 'cat_finanzas_cuentas_de_balance_04_llave',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field4' => array( 'field' => 'tr_compras_requisiciones_01_uuid',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field9' => array( 'field' => 'tr_compras_requisiciones_01_uuid_pago',
'type' => 'search_panel_field' ),
'search_panel_field12' => array( 'field' => 'referencia_bancaria',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field13' => array( 'field' => 'alias_proveedor',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field10' => array( 'field' => 'observacion_cargo_pago',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field14' => array( 'field' => 'uuid_sat',
'type' => 'search_panel_field',
'alwaysOnPanel' => false,
'required' => false ),
'search_panel_field15' => array( 'field' => 'llave_unica_cargo_abono_tr_compras_requisiciones_01_uuid_pago',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field16' => array( 'field' => 'fecha_de_recibo',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field17' => array( 'field' => 'tr_compras_almacenes_01_recibo_lpn_uuid',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field18' => array( 'field' => 'fecha_de_compra',
'type' => 'search_panel_field' ),
'search_panel_field19' => array( 'field' => 'fecha_de_pago',
'type' => 'search_panel_field' ),
'search_panel_field20' => array( 'field' => 'orden_de_compra_proveedor',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field21' => array( 'field' => 'cat_compras_estatus_mu_id',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field22' => array( 'field' => 'tr_finanzas_bancos_01_id',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'simple_search_field' => array( 'type' => 'simple_search_field' ),
'simple_search_option' => array( 'type' => 'simple_search_option' ),
'simple_grid_field8' => array( 'field' => 'fecha_de_pago',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true,
'clickSort' => true ),
'simple_grid_field20' => array( 'type' => 'grid_field_label',
'field' => 'fecha_de_pago',
'clickSort' => true ),
'simple_grid_field17' => array( 'field' => 'id_prov',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true,
'clickSort' => true ),
'simple_grid_field21' => array( 'type' => 'grid_field_label',
'field' => 'id_prov',
'clickSort' => true ),
'simple_grid_field' => array( 'field' => 'descripcion_proveedores',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field22' => array( 'type' => 'grid_field_label',
'field' => 'descripcion_proveedores',
'clickSort' => true ),
'simple_grid_field7' => array( 'field' => 'importe_cargo_pago',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true,
'clickSort' => true ),
'simple_grid_field23' => array( 'type' => 'grid_field_label',
'field' => 'importe_cargo_pago',
'clickSort' => true ),
'simple_grid_field25' => array( 'type' => 'grid_field_totals',
'field' => 'importe_cargo_pago',
'totals' => 'TOTAL' ),
'simple_grid_field15' => array( 'field' => 'cat_compras_estatus_mu_id',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field26' => array( 'type' => 'grid_field_label',
'field' => 'cat_compras_estatus_mu_id',
'clickSort' => true ),
'simple_grid_field18' => array( 'field' => 'uuid_sat',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true,
'clickSort' => true ),
'simple_grid_field27' => array( 'type' => 'grid_field_label',
'field' => 'uuid_sat',
'clickSort' => true ),
'simple_grid_field14' => array( 'field' => 'orden_de_compra_proveedor',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true,
'clickSort' => true ),
'simple_grid_field28' => array( 'type' => 'grid_field_label',
'field' => 'orden_de_compra_proveedor',
'clickSort' => true ),
'simple_grid_field6' => array( 'field' => 'referencia_bancaria',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true,
'clickSort' => true ),
'simple_grid_field29' => array( 'type' => 'grid_field_label',
'field' => 'referencia_bancaria',
'clickSort' => true ),
'simple_grid_field16' => array( 'field' => 'tr_finanzas_bancos_01_id',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true,
'clickSort' => true ),
'simple_grid_field30' => array( 'type' => 'grid_field_label',
'field' => 'tr_finanzas_bancos_01_id',
'clickSort' => true ),
'simple_grid_field1' => array( 'field' => 'cat_finanzas_cuentas_de_balance_04_llave',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true,
'clickSort' => true ),
'simple_grid_field31' => array( 'type' => 'grid_field_label',
'field' => 'cat_finanzas_cuentas_de_balance_04_llave',
'clickSort' => true ),
'simple_grid_field10' => array( 'field' => 'observacion_cargo_pago',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true,
'clickSort' => true ),
'simple_grid_field32' => array( 'type' => 'grid_field_label',
'field' => 'observacion_cargo_pago',
'clickSort' => true ),
'simple_grid_field5' => array( 'field' => 'fecha_de_recibo',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true,
'clickSort' => true ),
'simple_grid_field33' => array( 'type' => 'grid_field_label',
'field' => 'fecha_de_recibo',
'clickSort' => true ),
'simple_grid_field9' => array( 'field' => 'tr_compras_almacenes_01_recibo_lpn_uuid',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true,
'clickSort' => true ),
'simple_grid_field34' => array( 'type' => 'grid_field_label',
'field' => 'tr_compras_almacenes_01_recibo_lpn_uuid',
'clickSort' => true ),
'simple_grid_field13' => array( 'field' => 'vigente',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true,
'clickSort' => true ),
'simple_grid_field35' => array( 'type' => 'grid_field_label',
'field' => 'vigente',
'clickSort' => true ),
'simple_grid_field24' => array( 'field' => 'uuid_cargo_abono_pago',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field36' => array( 'type' => 'grid_field_label',
'field' => 'uuid_cargo_abono_pago',
'clickSort' => true ),
'simple_grid_field4' => array( 'field' => 'tr_compras_requisiciones_01_uuid',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field37' => array( 'type' => 'grid_field_label',
'field' => 'tr_compras_requisiciones_01_uuid',
'clickSort' => true ),
'simple_grid_field3' => array( 'field' => 'tr_compras_proveedores_01_cargos_abonos_id',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field38' => array( 'type' => 'grid_field_label',
'field' => 'tr_compras_proveedores_01_cargos_abonos_id',
'clickSort' => true ),
'simple_grid_field19' => array( 'field' => 'cat_compras_cargo_abono_mu_id',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true,
'clickSort' => true ),
'simple_grid_field39' => array( 'type' => 'grid_field_label',
'field' => 'cat_compras_cargo_abono_mu_id',
'clickSort' => true ),
'simple_grid_field12' => array( 'field' => 'capturista',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true,
'clickSort' => true ),
'simple_grid_field40' => array( 'type' => 'grid_field_label',
'field' => 'capturista',
'clickSort' => true ),
'simple_grid_field2' => array( 'field' => 'llave_unica_cargo_abono_tr_compras_requisiciones_01_uuid_pago',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true,
'clickSort' => true ),
'simple_grid_field41' => array( 'type' => 'grid_field_label',
'field' => 'llave_unica_cargo_abono_tr_compras_requisiciones_01_uuid_pago',
'clickSort' => true ),
'simple_grid_field11' => array( 'field' => 'fecha_de_compra',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field42' => array( 'type' => 'grid_field_label',
'field' => 'fecha_de_compra',
'clickSort' => true ),
'grid_checkbox' => array( 'type' => 'grid_checkbox' ),
'grid_checkbox_head' => array( 'type' => 'grid_checkbox_head' ),
'grid_inline_cancel' => array( 'type' => 'grid_inline_cancel' ),
'grid_inline_save' => array( 'type' => 'grid_inline_save' ),
'grid_inline_edit' => array( 'type' => 'grid_inline_edit' ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'spreadsheetGrid' => false,
'version' => 14,
'reorderRows' => false,
'reorderRowsField' => '',
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>