<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'importe_neto_orden_de_compra',
'referencia_proveedor',
'numero_de_productos',
'observaciones',
'fecha_de_orden_de_compra',
'descripcion_proveedores',
'descripcion_intermediario' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'importe_neto_orden_de_compra' => array( 'import_field9' ),
'referencia_proveedor' => array( 'import_field10' ),
'numero_de_productos' => array( 'import_field12' ),
'observaciones' => array( 'import_field15' ),
'descripcion_intermediario' => array( 'import_field1' ),
'descripcion_proveedores' => array( 'import_field' ),
'fecha_de_orden_de_compra' => array( 'import_field16' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field9',
'import_field10',
'import_field12',
'import_field15',
'import_field16',
'import_field',
'import_field1' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field12' => 'grid',
'import_field15' => 'grid',
'import_field16' => 'grid',
'import_field' => 'grid',
'import_field1' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field9',
'import_field10',
'import_field12',
'import_field15',
'import_field1',
'import_field',
'import_field16' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field9',
'import_field10',
'import_field12',
'import_field15',
'import_field16',
'import_field',
'import_field1' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field9' => array( 'field' => 'importe_neto_orden_de_compra',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'referencia_proveedor',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'numero_de_productos',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'observaciones',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'descripcion_intermediario',
'type' => 'import_field' ),
'import_field' => array( 'field' => 'descripcion_proveedores',
'type' => 'import_field' ),
'import_field16' => array( 'field' => 'fecha_de_orden_de_compra',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>