<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'cat_finanzas_bancos_cuentas_id',
'vigente',
'fecha_bancos',
'concepto_general',
'ingreso',
'egreso',
'centro_de_costos',
'cat_ventas_clientes_id',
'cat_compras_proveedores_id',
'poliza',
'referencia_general',
'fecha_registro',
'capturista',
'referencia_documento',
'poliza_contpaq',
'llave_contpaq',
'cuenta_contable',
'poliza_ok',
'cuenta_contable_ok',
'cat_finanzas_movimientos_id',
'tr_finanzas_bancos_01_id',
'numero_de_cuenta',
'descripcion_bancos',
'valor',
'fecha',
'ingreso_pesos',
'egresos_pesos',
'descripcion_movimientos',
'descripcion_cliente',
'descripcion_proveedores' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'centro_de_costos' => array( 'import_field' ),
'cat_finanzas_bancos_cuentas_id' => array( 'import_field1' ),
'vigente' => array( 'import_field2' ),
'fecha_bancos' => array( 'import_field6' ),
'concepto_general' => array( 'import_field7' ),
'ingreso' => array( 'import_field8' ),
'egreso' => array( 'import_field9' ),
'cat_finanzas_movimientos_id' => array( 'import_field5' ),
'cat_ventas_clientes_id' => array( 'import_field11' ),
'cat_compras_proveedores_id' => array( 'import_field13' ),
'poliza' => array( 'import_field15' ),
'referencia_general' => array( 'import_field16' ),
'fecha_registro' => array( 'import_field17' ),
'capturista' => array( 'import_field18' ),
'referencia_documento' => array( 'import_field19' ),
'poliza_contpaq' => array( 'import_field21' ),
'llave_contpaq' => array( 'import_field22' ),
'cuenta_contable' => array( 'import_field23' ),
'poliza_ok' => array( 'import_field24' ),
'cuenta_contable_ok' => array( 'import_field25' ),
'tr_finanzas_bancos_01_id' => array( 'import_field3' ),
'numero_de_cuenta' => array( 'import_field4' ),
'descripcion_bancos' => array( 'import_field10' ),
'valor' => array( 'import_field12' ),
'fecha' => array( 'import_field14' ),
'ingreso_pesos' => array( 'import_field20' ),
'egresos_pesos' => array( 'import_field26' ),
'descripcion_movimientos' => array( 'import_field27' ),
'descripcion_cliente' => array( 'import_field28' ),
'descripcion_proveedores' => array( 'import_field29' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field1',
'import_field2',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field',
'import_field11',
'import_field13',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field5',
'import_field3',
'import_field4',
'import_field10',
'import_field12',
'import_field14',
'import_field20',
'import_field26',
'import_field27',
'import_field28',
'import_field29' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field' => 'grid',
'import_field11' => 'grid',
'import_field13' => 'grid',
'import_field15' => 'grid',
'import_field16' => 'grid',
'import_field17' => 'grid',
'import_field18' => 'grid',
'import_field19' => 'grid',
'import_field21' => 'grid',
'import_field22' => 'grid',
'import_field23' => 'grid',
'import_field24' => 'grid',
'import_field25' => 'grid',
'import_field5' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field10' => 'grid',
'import_field12' => 'grid',
'import_field14' => 'grid',
'import_field20' => 'grid',
'import_field26' => 'grid',
'import_field27' => 'grid',
'import_field28' => 'grid',
'import_field29' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field5',
'import_field11',
'import_field13',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field3',
'import_field4',
'import_field10',
'import_field12',
'import_field14',
'import_field20',
'import_field26',
'import_field27',
'import_field28',
'import_field29' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field1',
'import_field2',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field',
'import_field11',
'import_field13',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field5',
'import_field3',
'import_field4',
'import_field10',
'import_field12',
'import_field14',
'import_field20',
'import_field26',
'import_field27',
'import_field28',
'import_field29' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'centro_de_costos',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'cat_finanzas_bancos_cuentas_id',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'vigente',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'fecha_bancos',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'concepto_general',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'ingreso',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'egreso',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'cat_finanzas_movimientos_id',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'cat_ventas_clientes_id',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'cat_compras_proveedores_id',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'poliza',
'type' => 'import_field' ),
'import_field16' => array( 'field' => 'referencia_general',
'type' => 'import_field' ),
'import_field17' => array( 'field' => 'fecha_registro',
'type' => 'import_field' ),
'import_field18' => array( 'field' => 'capturista',
'type' => 'import_field' ),
'import_field19' => array( 'field' => 'referencia_documento',
'type' => 'import_field' ),
'import_field21' => array( 'field' => 'poliza_contpaq',
'type' => 'import_field' ),
'import_field22' => array( 'field' => 'llave_contpaq',
'type' => 'import_field' ),
'import_field23' => array( 'field' => 'cuenta_contable',
'type' => 'import_field' ),
'import_field24' => array( 'field' => 'poliza_ok',
'type' => 'import_field' ),
'import_field25' => array( 'field' => 'cuenta_contable_ok',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'tr_finanzas_bancos_01_id',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'numero_de_cuenta',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'descripcion_bancos',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'valor',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'fecha',
'type' => 'import_field' ),
'import_field20' => array( 'field' => 'ingreso_pesos',
'type' => 'import_field' ),
'import_field26' => array( 'field' => 'egresos_pesos',
'type' => 'import_field' ),
'import_field27' => array( 'field' => 'descripcion_movimientos',
'type' => 'import_field' ),
'import_field28' => array( 'field' => 'descripcion_cliente',
'type' => 'import_field' ),
'import_field29' => array( 'field' => 'descripcion_proveedores',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>