<?php
$dalTabletr_compras_facturas_sat_02_carga_masiva = array();
$dalTabletr_compras_facturas_sat_02_carga_masiva["fecha_de_carga"] = array("type"=>135,"varname"=>"fecha_de_carga", "name" => "fecha_de_carga", "autoInc" => "0");
$dalTabletr_compras_facturas_sat_02_carga_masiva["tr_compras_facturas_sat_02_carga_masiva_id"] = array("type"=>3,"varname"=>"tr_compras_facturas_sat_02_carga_masiva_id", "name" => "tr_compras_facturas_sat_02_carga_masiva_id", "autoInc" => "1");
$dalTabletr_compras_facturas_sat_02_carga_masiva["consecutivo_uuid"] = array("type"=>3,"varname"=>"consecutivo_uuid", "name" => "consecutivo_uuid", "autoInc" => "0");
$dalTabletr_compras_facturas_sat_02_carga_masiva["llave_consecutivo_uudi"] = array("type"=>200,"varname"=>"llave_consecutivo_uudi", "name" => "llave_consecutivo_uudi", "autoInc" => "0");
$dalTabletr_compras_facturas_sat_02_carga_masiva["capturista"] = array("type"=>200,"varname"=>"capturista", "name" => "capturista", "autoInc" => "0");
$dalTabletr_compras_facturas_sat_02_carga_masiva["UUID"] = array("type"=>200,"varname"=>"UUID", "name" => "UUID", "autoInc" => "0");
$dalTabletr_compras_facturas_sat_02_carga_masiva["UUIDs_relacionados"] = array("type"=>200,"varname"=>"UUIDs_relacionados", "name" => "UUIDs_relacionados", "autoInc" => "0");
$dalTabletr_compras_facturas_sat_02_carga_masiva["Tipo_relacion"] = array("type"=>200,"varname"=>"Tipo_relacion", "name" => "Tipo_relacion", "autoInc" => "0");
$dalTabletr_compras_facturas_sat_02_carga_masiva["CP_Expedicion"] = array("type"=>200,"varname"=>"CP_Expedicion", "name" => "CP_Expedicion", "autoInc" => "0");
$dalTabletr_compras_facturas_sat_02_carga_masiva["Serie"] = array("type"=>200,"varname"=>"Serie", "name" => "Serie", "autoInc" => "0");
$dalTabletr_compras_facturas_sat_02_carga_masiva["Folio"] = array("type"=>200,"varname"=>"Folio", "name" => "Folio", "autoInc" => "0");
$dalTabletr_compras_facturas_sat_02_carga_masiva["Fecha_emision"] = array("type"=>135,"varname"=>"Fecha_emision", "name" => "Fecha_emision", "autoInc" => "0");
$dalTabletr_compras_facturas_sat_02_carga_masiva["Fecha_certificacion"] = array("type"=>135,"varname"=>"Fecha_certificacion", "name" => "Fecha_certificacion", "autoInc" => "0");
$dalTabletr_compras_facturas_sat_02_carga_masiva["Nombre_emisor"] = array("type"=>200,"varname"=>"Nombre_emisor", "name" => "Nombre_emisor", "autoInc" => "0");
$dalTabletr_compras_facturas_sat_02_carga_masiva["RFC_emisor"] = array("type"=>200,"varname"=>"RFC_emisor", "name" => "RFC_emisor", "autoInc" => "0");
$dalTabletr_compras_facturas_sat_02_carga_masiva["Nombre_receptor"] = array("type"=>200,"varname"=>"Nombre_receptor", "name" => "Nombre_receptor", "autoInc" => "0");
$dalTabletr_compras_facturas_sat_02_carga_masiva["RFC_receptor"] = array("type"=>200,"varname"=>"RFC_receptor", "name" => "RFC_receptor", "autoInc" => "0");
$dalTabletr_compras_facturas_sat_02_carga_masiva["Uso_CFDI"] = array("type"=>200,"varname"=>"Uso_CFDI", "name" => "Uso_CFDI", "autoInc" => "0");
$dalTabletr_compras_facturas_sat_02_carga_masiva["Efecto"] = array("type"=>200,"varname"=>"Efecto", "name" => "Efecto", "autoInc" => "0");
$dalTabletr_compras_facturas_sat_02_carga_masiva["Tipo"] = array("type"=>200,"varname"=>"Tipo", "name" => "Tipo", "autoInc" => "0");
$dalTabletr_compras_facturas_sat_02_carga_masiva["Estado_factura"] = array("type"=>200,"varname"=>"Estado_factura", "name" => "Estado_factura", "autoInc" => "0");
$dalTabletr_compras_facturas_sat_02_carga_masiva["Fecha_proceso_cancelacion"] = array("type"=>200,"varname"=>"Fecha_proceso_cancelacion", "name" => "Fecha_proceso_cancelacion", "autoInc" => "0");
$dalTabletr_compras_facturas_sat_02_carga_masiva["Estado_cancelacion"] = array("type"=>200,"varname"=>"Estado_cancelacion", "name" => "Estado_cancelacion", "autoInc" => "0");
$dalTabletr_compras_facturas_sat_02_carga_masiva["Estado_proceso_cancelacion"] = array("type"=>200,"varname"=>"Estado_proceso_cancelacion", "name" => "Estado_proceso_cancelacion", "autoInc" => "0");
$dalTabletr_compras_facturas_sat_02_carga_masiva["Motivo_cancelacion"] = array("type"=>200,"varname"=>"Motivo_cancelacion", "name" => "Motivo_cancelacion", "autoInc" => "0");
$dalTabletr_compras_facturas_sat_02_carga_masiva["Folio_sustitucion_cancelacion"] = array("type"=>200,"varname"=>"Folio_sustitucion_cancelacion", "name" => "Folio_sustitucion_cancelacion", "autoInc" => "0");
$dalTabletr_compras_facturas_sat_02_carga_masiva["ClaveProdServ"] = array("type"=>200,"varname"=>"ClaveProdServ", "name" => "ClaveProdServ", "autoInc" => "0");
$dalTabletr_compras_facturas_sat_02_carga_masiva["No_Identificacion"] = array("type"=>200,"varname"=>"No_Identificacion", "name" => "No_Identificacion", "autoInc" => "0");
$dalTabletr_compras_facturas_sat_02_carga_masiva["Metodo_pago"] = array("type"=>200,"varname"=>"Metodo_pago", "name" => "Metodo_pago", "autoInc" => "0");
$dalTabletr_compras_facturas_sat_02_carga_masiva["Forma_pago"] = array("type"=>200,"varname"=>"Forma_pago", "name" => "Forma_pago", "autoInc" => "0");
$dalTabletr_compras_facturas_sat_02_carga_masiva["Descripcion"] = array("type"=>200,"varname"=>"Descripcion", "name" => "Descripcion", "autoInc" => "0");
$dalTabletr_compras_facturas_sat_02_carga_masiva["Unidad"] = array("type"=>200,"varname"=>"Unidad", "name" => "Unidad", "autoInc" => "0");
$dalTabletr_compras_facturas_sat_02_carga_masiva["Clave_unidad"] = array("type"=>200,"varname"=>"Clave_unidad", "name" => "Clave_unidad", "autoInc" => "0");
$dalTabletr_compras_facturas_sat_02_carga_masiva["Cantidad"] = array("type"=>14,"varname"=>"Cantidad", "name" => "Cantidad", "autoInc" => "0");
$dalTabletr_compras_facturas_sat_02_carga_masiva["Valor_unitario"] = array("type"=>14,"varname"=>"Valor_unitario", "name" => "Valor_unitario", "autoInc" => "0");
$dalTabletr_compras_facturas_sat_02_carga_masiva["Importe"] = array("type"=>14,"varname"=>"Importe", "name" => "Importe", "autoInc" => "0");
$dalTabletr_compras_facturas_sat_02_carga_masiva["IVA_Trasladado"] = array("type"=>14,"varname"=>"IVA_Trasladado", "name" => "IVA_Trasladado", "autoInc" => "0");
$dalTabletr_compras_facturas_sat_02_carga_masiva["IVA_Retenido"] = array("type"=>14,"varname"=>"IVA_Retenido", "name" => "IVA_Retenido", "autoInc" => "0");
$dalTabletr_compras_facturas_sat_02_carga_masiva["ISR_Retenido"] = array("type"=>14,"varname"=>"ISR_Retenido", "name" => "ISR_Retenido", "autoInc" => "0");
$dalTabletr_compras_facturas_sat_02_carga_masiva["IEPS_Trasladado"] = array("type"=>14,"varname"=>"IEPS_Trasladado", "name" => "IEPS_Trasladado", "autoInc" => "0");
$dalTabletr_compras_facturas_sat_02_carga_masiva["Local_retenido"] = array("type"=>14,"varname"=>"Local_retenido", "name" => "Local_retenido", "autoInc" => "0");
$dalTabletr_compras_facturas_sat_02_carga_masiva["Local_trasladado"] = array("type"=>14,"varname"=>"Local_trasladado", "name" => "Local_trasladado", "autoInc" => "0");
$dalTabletr_compras_facturas_sat_02_carga_masiva["Descuento"] = array("type"=>14,"varname"=>"Descuento", "name" => "Descuento", "autoInc" => "0");
$dalTabletr_compras_facturas_sat_02_carga_masiva["Tipo_cambio"] = array("type"=>14,"varname"=>"Tipo_cambio", "name" => "Tipo_cambio", "autoInc" => "0");
$dalTabletr_compras_facturas_sat_02_carga_masiva["Moneda"] = array("type"=>200,"varname"=>"Moneda", "name" => "Moneda", "autoInc" => "0");
$dalTabletr_compras_facturas_sat_02_carga_masiva["Version"] = array("type"=>200,"varname"=>"Version", "name" => "Version", "autoInc" => "0");
$dalTabletr_compras_facturas_sat_02_carga_masiva["cat_compras_productos_id"] = array("type"=>3,"varname"=>"cat_compras_productos_id", "name" => "cat_compras_productos_id", "autoInc" => "0");
$dalTabletr_compras_facturas_sat_02_carga_masiva["cat_compras_productos_unidad_de_medida_mu_id_entrada"] = array("type"=>3,"varname"=>"cat_compras_productos_unidad_de_medida_mu_id_entrada", "name" => "cat_compras_productos_unidad_de_medida_mu_id_entrada", "autoInc" => "0");
$dalTabletr_compras_facturas_sat_02_carga_masiva["cat_compras_productos_unidad_de_medida_mu_id_salida"] = array("type"=>3,"varname"=>"cat_compras_productos_unidad_de_medida_mu_id_salida", "name" => "cat_compras_productos_unidad_de_medida_mu_id_salida", "autoInc" => "0");
$dalTabletr_compras_facturas_sat_02_carga_masiva["cat_finanzas_cuentas_de_balance_04_id_cargo"] = array("type"=>3,"varname"=>"cat_finanzas_cuentas_de_balance_04_id_cargo", "name" => "cat_finanzas_cuentas_de_balance_04_id_cargo", "autoInc" => "0");
$dalTabletr_compras_facturas_sat_02_carga_masiva["cat_finanzas_cuentas_de_balance_04_id_abono"] = array("type"=>3,"varname"=>"cat_finanzas_cuentas_de_balance_04_id_abono", "name" => "cat_finanzas_cuentas_de_balance_04_id_abono", "autoInc" => "0");
$dalTabletr_compras_facturas_sat_02_carga_masiva["check_pseudofactura"] = array("type"=>3,"varname"=>"check_pseudofactura", "name" => "check_pseudofactura", "autoInc" => "0");
$dalTabletr_compras_facturas_sat_02_carga_masiva["rfc_licencia"] = array("type"=>200,"varname"=>"rfc_licencia", "name" => "rfc_licencia", "autoInc" => "0");
$dalTabletr_compras_facturas_sat_02_carga_masiva["tr_compras_facturas_sat_02_carga_masiva_id"]["key"]=true;

$dal_info["wwinte_app_at_intelagro_mx__tr_compras_facturas_sat_02_carga_masiva"] = &$dalTabletr_compras_facturas_sat_02_carga_masiva;
?>