<?php
$securitySettings_var = array( 'providers' => array( array( 'type' => '%db',
'activationField' => '',
'active' => true,
'code' => '00',
'emailField' => 'correo',
'extUserIdField' => null,
'fullnameField' => 'nombre',
'label' => array( 'text' => 'Database',
'type' => 0 ),
'name' => 'db',
'passwordField' => 'pass',
'resetDateField' => '',
'resetTokenField' => '',
'table' => array( 'connId' => 'wwinte_app_at_intelagro_mx',
'table' => 'cat_usuarios' ),
'userGroupField' => 'user',
'usernameField' => 'usuario',
'userpicField' => '' ) ),
'sessionControl' => array( 'lifeTime' => 120,
'sessionName' => '55HS8qlkRuJf4lgL4W22',
'JWTSecret' => 'g91AFlltkotirEuxKPtZ',
'forceExpire' => true,
'keepAlive' => false,
'warnExpire' => true ),
'registration' => array( 'passwordValidation' => array( 'strong' => false,
'minimumLength' => 8,
'uniqueCharacters' => 4,
'digitsAndSymbols' => 2,
'upperAndLowerCase' => false ),
'remindMethod' => 0,
'hashAlgorithm' => 0,
'changePasswordPage' => true,
'changePwdPage' => false,
'notifyAdmin' => true,
'notifyUser' => true,
'registerPage' => false,
'remindPage' => false,
'remindPasswordPage' => true ),
'captchaSettings' => array( 'captchaType' => 1,
'siteKey' => '6LenSj8iAAAAAOysgqPlyhwTfkBj1qzm7DlrVUMJ',
'secretKey' => '6LenSj8iAAAAADUn2BdiHe_dRLk7uU3q-_RiiaKU',
'passesCount' => 5 ),
'emailSettings' => array( 'fromEmail' => '',
'usePHPDefinedSMTP' => false,
'useBuiltInMailer' => false,
'SMTPServer' => 'localhost',
'SMTPPort' => 25,
'SMTPUser' => '',
'SMTPPassword' => '',
'securityProtocol' => 0 ),
'advancedSecurity' => array( 'allowGuestLogin' => false,
'tables' => array( 'admin_members' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'admin_rights' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'admin_users' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'app_cat_actividades' => array( 'mainOwnerIDField' => 'cat_usuarios_licencias_id',
'securityOption' => 0,
'userOwnerIDField' => 'cat_usuarios_licencias_id' ),
'app_cat_actividades_alcance' => array( 'mainOwnerIDField' => 'cat_usuarios_licencias_id',
'securityOption' => 0,
'userOwnerIDField' => 'cat_usuarios_licencias_id' ),
'app_cat_actividades_metodo_de_costeo' => array( 'mainOwnerIDField' => 'cat_usuarios_licencias_id',
'securityOption' => 0,
'userOwnerIDField' => 'cat_usuarios_licencias_id' ),
'app_cat_actividades_query' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'app_cat_actividades_unidades_de_costo' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'app_cat_holding_03_unidades_productivas' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'app_cat_trabajadores_altas' => array( 'mainOwnerIDField' => 'cat_usuarios_licencias_id',
'securityOption' => 0,
'userOwnerIDField' => 'cat_usuarios_licencias_id' ),
'app_cat_trabajadores_query' => array( 'mainOwnerIDField' => 'cat_usuarios_licencias_id',
'securityOption' => 0,
'userOwnerIDField' => 'cat_usuarios_id' ),
'box_actividades_costo_asignado_01' => array( 'mainOwnerIDField' => 'cat_usuarios_licencias_id',
'securityOption' => 0,
'userOwnerIDField' => 'cat_usuarios_licencias_id' ),
'box_cat_trabajadores' => array( 'mainOwnerIDField' => 'cat_usuarios_licencias_id',
'securityOption' => 0,
'userOwnerIDField' => 'cat_usuarios_licencias_id' ),
'box_lotes' => array( 'mainOwnerIDField' => 'cat_usuarios_licencias_id',
'securityOption' => 0,
'userOwnerIDField' => 'cat_usuarios_licencias_id' ),
'box_proyectos_productivos_02' => array( 'mainOwnerIDField' => 'tr_proyectos_productivos_02_sku_id',
'securityOption' => 0,
'userOwnerIDField' => 'cat_usuarios_licencias_id' ),
'box_usuarios_licencias_sku' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'cat_actividades' => array( 'mainOwnerIDField' => 'cat_usuarios_licencias_id',
'securityOption' => 0,
'userOwnerIDField' => 'cat_usuarios_licencias_id' ),
'cat_actividades_alcance' => array( 'mainOwnerIDField' => 'cat_usuarios_licencias_id',
'securityOption' => 0,
'userOwnerIDField' => 'cat_usuarios_licencias_id' ),
'cat_actividades_categoria' => array( 'mainOwnerIDField' => 'cat_usuarios_licencias_id',
'securityOption' => 0,
'userOwnerIDField' => 'cat_usuarios_licencias_id' ),
'cat_actividades_metodo_de_costeo' => array( 'mainOwnerIDField' => 'cat_usuarios_licencias_id',
'securityOption' => 0,
'userOwnerIDField' => 'cat_usuarios_licencias_id' ),
'cat_actividades_metodo_de_costeo_categoria' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'cat_actividades_unidades_de_costo' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'cat_actividades_unidades_de_medida' => array( 'mainOwnerIDField' => 'cat_usuarios_licencias_id',
'securityOption' => 0,
'userOwnerIDField' => 'cat_usuarios_licencias_id' ),
'cat_actividades_unidades_productivas' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'cat_actividades_variabilidad_de_costo' => array( 'mainOwnerIDField' => 'cat_usuarios_licencias_id',
'securityOption' => 0,
'userOwnerIDField' => 'cat_usuarios_licencias_id' ),
'cat_compras_documentos_mu' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'cat_compras_estatus_mu' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'cat_compras_estatus_mu_box' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'cat_compras_intermediarios' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'cat_compras_productos' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'cat_compras_productos_box' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'cat_compras_productos_box_app' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'cat_compras_productos_categorias' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'cat_compras_productos_presentacion_mu' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'cat_compras_productos_unidad_de_medida_mu' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'cat_compras_proveedores' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'cat_compras_proveedores_asignacion_mu' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'cat_compras_proveedores_categorias' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'cat_finanzas_centros_de_costos_alcance_mu' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'cat_holding_01' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'cat_holding_02_departamentos' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'cat_holding_02_empresas' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'cat_holding_03_empresas_registros_patronales' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'cat_holding_03_unidades_productivas' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'cat_holding_03_unidades_productivas_box' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'cat_holding_03_unidades_productivas_categoria' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'cat_holding_03_unidades_productivas_query_app' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'cat_productos_sku_box' => array( 'mainOwnerIDField' => 'cat_usuarios_id',
'securityOption' => 0,
'userOwnerIDField' => 'cat_usuarios_id' ),
'cat_soporte_estatus_mu' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'cat_soporte_prioridad_mu' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'cat_trabajadores_altas' => array( 'mainOwnerIDField' => 'cat_usuarios_licencias_id',
'securityOption' => 0,
'userOwnerIDField' => 'cat_usuarios_licencias_id' ),
'cat_trabajadores_documentos' => array( 'mainOwnerIDField' => 'cat_usuarios_licencias_id',
'securityOption' => 0,
'userOwnerIDField' => 'cat_usuarios_licencias_id' ),
'cat_trabajadores_documentos_link' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'cat_trabajadores_imprimir_gafete' => array( 'mainOwnerIDField' => 'cat_usuarios_licencias_id',
'securityOption' => 0,
'userOwnerIDField' => 'cat_usuarios_licencias_id' ),
'cat_trabajadores_puestos' => array( 'mainOwnerIDField' => 'cat_usuarios_licencias_id',
'securityOption' => 0,
'userOwnerIDField' => 'cat_usuarios_licencias_id' ),
'cat_trabajadores_puestos_areas' => array( 'mainOwnerIDField' => 'cat_usuarios_licencias_id',
'securityOption' => 0,
'userOwnerIDField' => 'cat_usuarios_licencias_id' ),
'cat_trabajadores_puestos_categorias' => array( 'mainOwnerIDField' => 'cat_usuarios_licencias_id',
'securityOption' => 0,
'userOwnerIDField' => 'cat_usuarios_licencias_id' ),
'cat_trabajadores_puestos_tabulador' => array( 'mainOwnerIDField' => 'cat_usuarios_licencias_id',
'securityOption' => 0,
'userOwnerIDField' => 'cat_usuarios_licencias_id' ),
'cat_usuarios' => array( 'mainOwnerIDField' => 'cat_usuarios_id',
'securityOption' => 0,
'userOwnerIDField' => 'cat_usuarios_id' ),
'cat_usuarios_apps_01' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'cat_usuarios_apps_02_licencias' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'cat_usuarios_apps_descarga' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'cat_usuarios_box' => array( 'mainOwnerIDField' => 'cat_usuarios_id',
'securityOption' => 0,
'userOwnerIDField' => 'cat_usuarios_id' ),
'cat_usuarios_licencias' => array( 'mainOwnerIDField' => 'cat_usuarios_licencias_id',
'securityOption' => 0,
'userOwnerIDField' => 'cat_usuarios_id' ),
'cat_usuarios_licencias_sku' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'cat_ventas_productos' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'con_licencias_filtro' => array( 'mainOwnerIDField' => 'capturista',
'securityOption' => 0,
'userOwnerIDField' => 'cat_usuarios_id' ),
'ext_monitoreo_de_plagas_jot_query_inf_sector' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tr_actividades' => array( 'mainOwnerIDField' => 'cat_usuarios_licencias_id',
'securityOption' => 0,
'userOwnerIDField' => 'cat_usuarios_licencias_id' ),
'tr_actividades_01_culturales' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tr_actividades_01_edit' => array( 'mainOwnerIDField' => 'cat_usuarios_licencias_id',
'securityOption' => 0,
'userOwnerIDField' => 'cat_usuarios_licencias_id' ),
'tr_actividades_01_fecha' => array( 'mainOwnerIDField' => 'cat_usuarios_licencias_id',
'securityOption' => 0,
'userOwnerIDField' => 'cat_usuarios_licencias_id' ),
'tr_actividades_01_query_glori' => array( 'mainOwnerIDField' => 'cat_usuarios_licencias_id',
'securityOption' => 0,
'userOwnerIDField' => 'cat_usuarios_licencias_id' ),
'tr_actividades_01_query_glori_total_dia_sector' => array( 'mainOwnerIDField' => 'cat_usuarios_licencias_id',
'securityOption' => 0,
'userOwnerIDField' => 'cat_usuarios_licencias_id' ),
'tr_actividades_01_query_glori_total_dia_semana' => array( 'mainOwnerIDField' => 'cat_usuarios_licencias_id',
'securityOption' => 0,
'userOwnerIDField' => 'cat_usuarios_licencias_id' ),
'tr_actividades_01_query_glori_total_dia_trabajador' => array( 'mainOwnerIDField' => 'cat_usuarios_licencias_id',
'securityOption' => 0,
'userOwnerIDField' => 'cat_usuarios_licencias_id' ),
'tr_actividades_01_query_glori_total_mes' => array( 'mainOwnerIDField' => 'cat_usuarios_licencias_id',
'securityOption' => 0,
'userOwnerIDField' => 'cat_usuarios_licencias_id' ),
'tr_actividades_01_query_glori_total_semana' => array( 'mainOwnerIDField' => 'cat_usuarios_licencias_id',
'securityOption' => 0,
'userOwnerIDField' => 'cat_usuarios_licencias_id' ),
'tr_actividades_01_trabajadores_inf' => array( 'mainOwnerIDField' => 'cat_usuarios_licencias_id',
'securityOption' => 0,
'userOwnerIDField' => 'cat_usuarios_licencias_id' ),
'tr_actividades_02_actividad' => array( 'mainOwnerIDField' => 'cat_usuarios_licencias_id',
'securityOption' => 0,
'userOwnerIDField' => 'cat_usuarios_licencias_id' ),
'tr_actividades_02_edit' => array( 'mainOwnerIDField' => 'cat_usuarios_licencias_id',
'securityOption' => 0,
'userOwnerIDField' => 'cat_usuarios_licencias_id' ),
'tr_actividades_03_sectores' => array( 'mainOwnerIDField' => 'cat_usuarios_licencias_id',
'securityOption' => 0,
'userOwnerIDField' => 'cat_usuarios_licencias_id' ),
'tr_actividades_03_trabajadores' => array( 'mainOwnerIDField' => 'cat_usuarios_licencias_id',
'securityOption' => 0,
'userOwnerIDField' => 'cat_usuarios_licencias_id' ),
'tr_actividades_04_cajas_sector' => array( 'mainOwnerIDField' => 'cat_usuarios_licencias_id',
'securityOption' => 0,
'userOwnerIDField' => 'cat_usuarios_licencias_id' ),
'tr_actividades_04_cajas_trabajador' => array( 'mainOwnerIDField' => 'cat_usuarios_licencias_id',
'securityOption' => 0,
'userOwnerIDField' => 'cat_usuarios_licencias_id' ),
'tr_actividades_costo_asignado_01' => array( 'mainOwnerIDField' => 'cat_usuarios_licencias_id',
'securityOption' => 0,
'userOwnerIDField' => 'cat_usuarios_licencias_id' ),
'tr_actividades_costo_asignado_01_box_nb' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tr_actividades_costo_asignado_02_lotes' => array( 'mainOwnerIDField' => 'cat_usuarios_licencias_id',
'securityOption' => 0,
'userOwnerIDField' => 'cat_usuarios_licencias_id' ),
'tr_actividades_costo_asignado_02_proyectos' => array( 'mainOwnerIDField' => 'cat_usuarios_licencias_id',
'securityOption' => 0,
'userOwnerIDField' => 'cat_usuarios_licencias_id' ),
'tr_actividades_costo_asignado_02_sku' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tr_actividades_edit' => array( 'mainOwnerIDField' => 'cat_usuarios_licencias_id',
'securityOption' => 0,
'userOwnerIDField' => 'cat_usuarios_licencias_id' ),
'tr_actividades_edit_root' => array( 'mainOwnerIDField' => 'cat_usuarios_licencias_id',
'securityOption' => 0,
'userOwnerIDField' => 'cat_usuarios_licencias_id' ),
'tr_actividades_script_insert_a_tr_actividades_costeo' => array( 'mainOwnerIDField' => 'cat_usuarios_licencias_id',
'securityOption' => 0,
'userOwnerIDField' => 'cat_usuarios_licencias_id' ),
'tr_compras_facturas_carga_masiva_sat_02' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tr_compras_facturas_carga_masiva_sat_02_script_insert_tr_01' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tr_compras_facturas_carga_masiva_sat_02_script_insert_tr_02' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tr_compras_facturas_sat_01' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tr_compras_facturas_sat_02' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tr_compras_requisiciones_01' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tr_compras_requisiciones_01_autorizacion' => array( 'mainOwnerIDField' => 'capturista_que_autoriza',
'securityOption' => 0,
'userOwnerIDField' => 'usuario' ),
'tr_compras_requisiciones_01_orden_de_compra' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tr_compras_requisiciones_02_cotizaciones' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tr_compras_requisiciones_02_productos' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tr_compras_requisiciones_02_productos_app' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tr_compras_requisiciones_02_productos_app_script_insert_tr_compras_requisiciones_01' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tr_compras_requisiciones_02_productos_app_script_insert_tr_compras_requisiciones_02' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tr_compras_requisiciones_02_productos_autorizacion' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tr_compras_requisiciones_02_productos_orden_de_compra' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tr_finanzas_centros_de_costos_01_holding' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tr_finanzas_centros_de_costos_01_holding_box' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tr_finanzas_centros_de_costos_02_departamentos' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tr_finanzas_centros_de_costos_02_departamentos_box' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tr_finanzas_centros_de_costos_02_empresas' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tr_finanzas_centros_de_costos_02_empresas_box' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tr_finanzas_centros_de_costos_03_almacenes_mat_prima' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tr_finanzas_centros_de_costos_03_unidades_productivas' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tr_finanzas_centros_de_costos_04_unid_prod_clientes' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tr_finanzas_centros_de_costos_04_unid_prod_productos' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tr_finanzas_centros_de_costos_05_almacenes_prod_term' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tr_finanzas_centros_de_costos_05_unid_prod_productos_lotes' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tr_proyectos_productivos_01_unidad_productiva' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tr_proyectos_productivos_02_clientes' => array( 'mainOwnerIDField' => 'cat_usuarios_licencias_id',
'securityOption' => 0,
'userOwnerIDField' => 'cat_usuarios_licencias_id' ),
'tr_proyectos_productivos_02_lotes' => array( 'mainOwnerIDField' => 'cat_usuarios_licencias_id',
'securityOption' => 0,
'userOwnerIDField' => 'cat_usuarios_licencias_id' ),
'tr_proyectos_productivos_clientes_03_sku' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tr_root_audit_editing_locking' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tr_root_audit_log_audit' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tr_soporte_tickets_01' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tr_soporte_tickets_01_root' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tr_soporte_tickets_02' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tr_soporte_tickets_02_root' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ) ) ),
'auditAndLocking' => array( 'loggingTable' => array( 'connId' => 'wwinte_app_at_intelagro_mx',
'table' => 'tr_root_audit_log_audit' ),
'lockingTable' => array( 'connId' => 'wwinte_app_at_intelagro_mx',
'table' => 'tr_root_audit_editing_locking' ),
'tables' => array( 'admin_members' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'admin_rights' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'admin_users' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'app_box_cat_holding_03_empresas_unidades_productivas' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'app_box_cat_ventas_productos_almacenes' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'app_box_cat_ventas_productos_sku' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'app_cat_actividades' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'app_cat_actividades_metodo_de_costeo' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'app_cat_actividades_query_modulo_cosecha' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'app_cat_actividades_unidades_de_costo' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'app_cat_alta_trabajadores_query' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'app_cat_usuarios_licencias_query' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'app_form_cat_holding_04_unidades_productivas_lotes' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'app_inf_cosecha_dia' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'app_inf_tr_actividades_asistencias' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'app_inf_tr_control_de_plagas' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'app_inf_tr_control_de_plagas_avg_diario' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'app_inf_tr_control_de_plagas_box_up' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'app_inf_tr_control_de_suelo_phcena' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'app_query_cat_usuarios_modulos' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'app_query_cosecha_informe_diario' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'app_query_tr_actividades_01_total_dia_trabajador' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'app_query_tr_actividades_corte_diario' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'app_query_tr_actividades_general' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'app_query_tr_actividades_planeacion_02_tareas_app' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'app_query_tr_actividades_sector_rancho_dia' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'app_query_tr_actividades_sector_rancho_diax' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'app_tr_actividades_query_dia_trabajador' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'app_tr_actividades_query_general' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'app_tr_compras_requisiciones_02_productos_app_script_insert_tr_compras_requisiciones_01' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'app_tr_compras_requisiciones_02_productos_app_script_insert_tr_compras_requisiciones_02' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'app_tr_control_de_suelo_phcena_ano_semana_sector_inf' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'app_tr_control_de_suelo_phcena_box_up' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'app_tr_control_de_suelo_phcet_drenaje_inf_drenaje_agua_dia' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'box_cat_actividades' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'box_cat_actividades_metodo_de_costeo' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'box_cat_actividades_unidades_de_costo' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'box_cat_compras_almacenes' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'box_cat_compras_documentos_mu' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'box_cat_compras_productos' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'box_cat_compras_proveedores' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'box_cat_finanzas_cuentas_de_balance_04' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'box_cat_holding_03_empresas_unidades_productivas' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'box_cat_holding_04_unidades_productivas_lotes' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'box_cat_trabajadores' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'box_cat_ventas_clientes' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'box_cat_ventas_productos_sku' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'box_root_cat_holding_03_empresas_unidades_productivas' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'box_tr_compras_requisiciones_tr_compras_almacenes_01' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'box_tr_finanzas_centros_de_costos_03_unidades_productivas' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'box_usuarios_licencias_sku' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_actividades' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_actividades_asignacion_de_costos' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_actividades_box_root' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_actividades_categorias' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_actividades_categorias_mu' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_actividades_metodo_de_costeo' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_actividades_turnos_mu' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_actividades_unidades_de_costo' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_compras_almacenes' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_compras_documentos_mu' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_compras_estatus_mu' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_compras_estatus_mu_box' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_compras_intermediarios' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_compras_productos' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_compras_productos_categorias' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_compras_productos_presentacion_mu' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_compras_productos_unidad_de_medida_mu' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_compras_proveedores' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_compras_proveedores_asignacion_mu' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_compras_proveedores_categorias' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_control_aplicaciones_campo_boquillas' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_control_aplicaciones_campo_metodo_de_aplicacion' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_control_aplicaciones_campo_tipo_de_control' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_finanzas_bancos' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_finanzas_bancos_cuentas' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_finanzas_bancos_cuentas_box' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_finanzas_centros_de_costos' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_finanzas_centros_de_costos_categorias_mu' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_finanzas_cuentas_contables' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_finanzas_cuentas_contables_categorias' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_finanzas_cuentas_de_balance_01_mu' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_finanzas_cuentas_de_balance_02_mu' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_finanzas_cuentas_de_balance_03_mu' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_finanzas_cuentas_de_balance_04' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_finanzas_socios' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_finanzas_transacciones' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_finanzas_transacciones_box' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_holding_01' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_holding_02_empresas' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_holding_03_empresas_almacenes' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_holding_03_empresas_departamentos' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_holding_03_empresas_mu_unidades_productivas_categorias' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_holding_03_empresas_registros_patronales' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_holding_03_empresas_unidades_productivas' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_holding_03_empresas_unidades_productivas_box' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_holding_03_empresas_unidades_productivas_categorias' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_holding_04_unidades_productivas_lotes' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_holding_04_unidades_productivas_lotes_box' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_holding_04_unidades_productivas_lotes_categorias' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_holding_04_unidades_productivas_lotes_llave_ubicacion_nb' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_holding_04_unidades_productivas_mu_lotes_categorias' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_multiusuarios_dias_de_la_semana' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_produccion_nutricion_01_programas_nombre' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_produccion_nutricion_02_programas_productos' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_root_dispositivos' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_root_dispositivos_categorias' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_root_usuarios_inicio_de_semana' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_soporte_estatus_mu' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_soporte_prioridad_mu' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_trabajadores_altas' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_trabajadores_box_root' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_trabajadores_documentos' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_trabajadores_documentos_link' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_trabajadores_imprimir_gafete' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_trabajadores_puestos' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_trabajadores_puestos_areas' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_trabajadores_puestos_categorias' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_trabajadores_puestos_tabulador' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_usuarios' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_usuarios_02_modulos' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_usuarios_box' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_usuarios_box_2' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_usuarios_licencias' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_usuarios_modulos' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_ventas_clientes' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_ventas_productos' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_ventas_productos_almacenes' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_ventas_productos_almacenes_box' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_ventas_productos_almacenes_categorias' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_ventas_productos_categorias' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_ventas_productos_lotes' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_ventas_productos_manejo' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_ventas_productos_marcas' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_ventas_productos_presentaciones' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_ventas_productos_sku' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_ventas_productos_sku_box' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_ventas_productos_unidades_de_medida' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_ventas_productos_unidades_de_produccion' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cat_ventas_productos_unidades_de_venta' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'con_licencias_filtro' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_activiades_sector_dia_nb_nb' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_activiades_sector_dia_nb_nb_mapa' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_actividades' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_actividades_01_edit' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_actividades_01_query_glori' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_actividades_01_query_glori_total_dia_sector' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_actividades_01_query_glori_total_dia_semana' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_actividades_01_query_glori_total_mes' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_actividades_01_query_glori_total_semana' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_actividades_02_edit' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_actividades_04_cajas_sector' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_actividades_app_inf_cosecha_dia' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_actividades_asistencias' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_actividades_edit' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_actividades_edit_root' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_actividades_inf_cosecha_01_semana' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_actividades_inf_cosecha_02_dia' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_actividades_inf_cosecha_03_sectores' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_actividades_inf_cosecha_03_trabajadores' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_actividades_inf_sector_dia_nb' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_actividades_planeacion_02_tareas_app' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_actividades_planeacion_02_tareas_app1' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_actividades_planeacion_03_personas_app' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_actividades_planeacion_03_personas_app_seguimiento' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_actividades_script_cat_actividades_configuraciones' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_actividades_script_costo' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_actividades_script_insert_a_tr_actividades_costeo' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_actividades_script_insert_tr_trabajadores_nomina_03_costos_por_actividad_dia' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_actividades_sectores_01_inf' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_actividades_sectores_02_inf' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_compras_almacenes_01_lpn' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_compras_almacenes_02_productos' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_compras_almacenes_02_productos_root_carga_masiva' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_compras_facturas_sat_01' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_compras_facturas_sat_02' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_compras_facturas_sat_02_update' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_compras_requisiciones_01' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_compras_requisiciones_01_autorizacion' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_compras_requisiciones_01_autorizacion_user' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_compras_requisiciones_01_informe_intelagro' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_compras_requisiciones_01_orden_de_compra' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_compras_requisiciones_01_orden_de_compra_enviada' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_compras_requisiciones_01_orden_de_compra_pagada' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_compras_requisiciones_01_script_balance' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_compras_requisiciones_02_productos' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_compras_requisiciones_02_productos_app' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_compras_requisiciones_02_productos_autorizacion' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_compras_requisiciones_02_productos_orden_de_compra' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_compras_requisiciones_02_productos_script_insert_tr_compras_orden_de_compra_01' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_control_aplicaciones_campo_01_up_productos_app' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_control_aplicaciones_campo_02_lotes_app' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_control_aplicaciones_campo_02_lotes_app_query_costos' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_control_aplicaciones_campo_query_costos' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_control_de_plagas' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_control_de_suelo_phcena' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_control_de_suelo_phcet_drenaje' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_control_de_suelo_phcet_drenaje_box_up' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_control_suelo_5pin_rs485_thcph_app' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_control_suelo_hum_temp_app' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_control_suelo_hum_temp_app_mapa_minutos' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_control_suelo_hum_temp_app_minutos' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_control_suelo_hum_temp_app_query' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_control_suelo_hum_temp_inf' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_finanzas_bancos_01' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_finanzas_bancos_02' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_finanzas_centros_de_costos_01_holding' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_finanzas_centros_de_costos_01_holding_box' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_finanzas_centros_de_costos_01_holding_nb_catalogo' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_finanzas_centros_de_costos_01_holding_script__cat_finanzas_centro_de_costos' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_finanzas_centros_de_costos_02_departamentos_box' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_finanzas_centros_de_costos_02_empresas' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_finanzas_centros_de_costos_02_empresas_box' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_finanzas_centros_de_costos_03_04_form_UP_prod_recetas' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_finanzas_centros_de_costos_03_almacenes' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_finanzas_centros_de_costos_03_unidades_productivas' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_finanzas_centros_de_costos_04_almacenes_prod_term' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_finanzas_centros_de_costos_04_unid_prod_clientes' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_finanzas_centros_de_costos_04_unid_prod_productos' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_finanzas_centros_de_costos_05_lotes_recetas' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_finanzas_centros_de_costos_05_unid_prod_productos_lotes' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_finanzas_centros_de_costos_06_lotes_actividades' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_finanzas_centros_de_costos_06_lotes_prog_recetas' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_finanzas_centros_de_costos_06_lotes_programa_nutricion' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_finanzas_centros_de_costos_06_lotes_programa_plantas' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_finanzas_centros_de_costos_06_total_plantas_sector_nb' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_finanzas_centros_de_costos_06_unid_prod_produc_lotes_sku' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_finanzas_centros_de_costos_07_lotes_actividades_costeo' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_finanzas_centros_de_costos_07_lotes_programa_nutri_receta' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_finanzas_centros_de_costos_07_lotes_programa_periodicidad' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_finanzas_centros_de_costos_07_programa_recetas' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_finanzas_socios_aportaciones' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_root_audit_editing_locking' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'tr_root_audit_log_audit' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'tr_soporte_tickets_01' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_soporte_tickets_01_root' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_soporte_tickets_02' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_soporte_tickets_02_root' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_ventas_almacenes_01' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tr_ventas_almacenes_02' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'validaciones' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ) ),
'loggingMode' => 1,
'loggingFile' => 'audit.log',
'logSecurityActions' => true,
'lockAfterUnsuccessfulLogin' => true,
'enableLocking' => true ),
'twoFactorSettings' => array( 'available' => false,
'required' => false,
'enable' => true,
'remember' => true,
'types' => array(  ),
'twoFactorField' => '',
'emailField' => '',
'phoneField' => '',
'codeField' => '',
'projectName' => '' ),
'projectName' => 'Intelagro_clouster_250609Digital',
'loginDataSource' => 'cat_usuarios',
'loginForm' => 0,
'dynamicPermissions' => true,
'dpTablePrefix' => 'aaa_permisos_',
'dpTableConnId' => 'wwinte_app_at_intelagro_mx',
'hardcodedLogin' => false,
'enabled' => true,
'advancedSecurityAvailable' => true,
'userGroupsAvailable' => true,
'defaultProviderCode' => '00',
'adOnlyLogin' => false,
'dbProvider' => array( 'type' => '%db',
'activationField' => '',
'active' => true,
'code' => '00',
'emailField' => 'correo',
'extUserIdField' => null,
'fullnameField' => 'nombre',
'label' => array( 'text' => 'Database',
'type' => 0 ),
'name' => 'db',
'passwordField' => 'pass',
'resetDateField' => '',
'resetTokenField' => '',
'table' => array( 'connId' => 'wwinte_app_at_intelagro_mx',
'table' => 'cat_usuarios' ),
'userGroupField' => 'user',
'usernameField' => 'usuario',
'userpicField' => '' ),
'adAdminGroups' => array(  ),
'showUserSource' => false,
'dbProviderCodes' => array( '00' ),
'notifications' => array( 'enabled' => false,
'table' => array( 'connId' => 'wwinte_app_at_intelagro_mx',
'table' => 'tr_root_notificaciones_noti' ) ) );
?>