<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_tr_compras_almacenes_01_salida_lpn  extends eventsBase
{
	function __construct()
	{
	// fill list of events

		$this->events["AfterAdd"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record added
function AfterAdd(&$values, &$keys, $inline, $pageObject)
{

		$sql = "INSERT IGNORE INTO tr_compras_almacenes_01_recibo_lpn (
            tr_compras_almacenes_01_recibo_lpn_uuid,
            cat_compras_documentos_mu_id,
            referencia_documentos,
            vigente,
            cat_compras_almacenes_id,
            cat_compras_almacenes_estatus_mu_id,
            fecha_de_captura,
            cat_compras_almacenes_id_origen
        )
        SELECT
            sal.tr_compras_almacenes_01_salida_lpn_uuid,
            7,
            sal.tr_compras_almacenes_01_salida_lpn_uuid,
            1,
            sal.cat_compras_almacenes_id_destino,
            8,
            CURRENT_TIMESTAMP(),
            sal.cat_compras_almacenes_id_destino
        FROM tr_compras_almacenes_01_salida_lpn sal
        WHERE sal.cat_compras_almacenes_estatus_mu_id = 3"; // Aquí agregas la condición WHERE

// Ejecuta la consulta con la conexión de base de datos de PHP Runner
DB::Query($sql);


// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function AfterAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
