<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_tr_compras_requisiciones_01  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeShowEdit"]=true;

		$this->events["BeforeShowAdd"]=true;




		$this->events["AfterEdit"]=true;

		$this->events["BeforeShowList"]=true;

		$this->events["AfterAdd"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowEdit(&$xt, &$templatefile, $values, $pageObject)
{

		$pageObject->hideItem("grid_edit");
$pageObject->hideItem("grid_checkbox");




if ($values["check_compra_directa"]!="on") {
$pageObject->hideField("fecha_de_compra");
$pageObject->hideField("cat_compras_proveedores_id");
$pageObject->hideField("importe_abono_compra");
$pageObject->hideField("fecha_de_pago");
$pageObject->hideField("cat_finanzas_cuentas_de_balance_04_llave");
$pageObject->hideField("uuid_sat");
$pageObject->hideField("cat_finanzas_bancos_cuentas_id");
$pageObject->hideField("cat_finanzas_cajas_chicas_id");
$pageObject->hideField("orden_de_compra_proveedor");
$pageObject->hideField("referencia_bancaria");
$pageObject->hideField("observacion_abono_compra");
$pageObject->hideField("observacion_cargo_pago");
$pageObject->hideField("referencia"); 
$pageObject->hideField("cat_compras_documentos_mu_id"); 
$pageObject->hideItem("boton_afectar_compra");
}

// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function BeforeShowEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowAdd(&$xt, &$templatefile, $pageObject)
{

		$pageObject->hideItem("grid_edit");
$pageObject->hideField("capturista_que_autoriza");
// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function BeforeShowAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record updated
function AfterEdit(&$values, $where, &$oldvalues, &$keys, $inline, $pageObject)
{

		

$sql = DB::PrepareSQL("
update tr_compras_requisiciones_02_productos
set llave_cat_compras_proveedores_id = ':cat_compras_proveedores_id'
where tr_compras_requisiciones_01_uuid = ':tr_compras_requisiciones_01_uuid'
");
DB::Exec( $sql );


// Place event code here.
// Use "Add Action" button to add code snippets.


;		
} // function AfterEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowList(&$xt, &$templatefile, $pageObject)
{

		include 'admin/scripts/tr_compras_requisiciones_01_update_estatus_compra.php';

// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function BeforeShowList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record added
function AfterAdd(&$values, &$keys, $inline, $pageObject)
{

		//header("Location: tr_compras_requisiciones_02_productos_list.php?mastertable=orders&masterkey1=".$values["tr_compras_requisiciones_01_uuid"]);
//exit();


//header("Location: tr_compras_requisiciones_02_productos_list.php?masterkey1=".$values["tr_compras_requisiciones_01_uuid"]."&page=list&mastertable=tr_compras_requisiciones_01");
//exit();


// Place event code here.
// Use "Add Action" button to add code snippets.


;		
} // function AfterAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
