
Runner.pages.PageSettings.addPageEvent('tr_compras_requisiciones_01_estatus',Runner.pages.constants.PAGE_ADD,"afterPageReady",function(pageObj,proxy,pageid,inlineRow,inlineObject,row){var ctrUUID=Runner.getControl(pageid,'tr_compras_requisiciones_01_uuid');var ctrMovimiento=Runner.getControl(pageid,'cat_trabajadores_altas_id_solicitante');function generateUUID(){var d=new Date().getTime();var d2=(typeof performance!=="undefined"&&performance.now&&performance.now()*1000)||0;return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(c){var r=Math.random()*16;if(d>0){r=(d+r)%16|0;d=Math.floor(d/16);}else{r=(d2+r)%16|0;d2=Math.floor(d2/16);}
return(c==="x"?r:(r&0x3)|0x8).toString(16);});}
function uuid(){ctrUUID.setValue(generateUUID());}
ctrMovimiento.on('change',uuid);console.log(this.getValue());var ctrl_check_compra_directa=Runner.getControl(pageid,'check_compra_directa');if(ctrl_check_compra_directa.getValue()==0)
{pageObj.hideField("fecha_de_compra");pageObj.hideField("cat_compras_proveedores_id");pageObj.hideField("importe_abono_compra");pageObj.hideField("fecha_de_pago");pageObj.hideField("cat_finanzas_cuentas_de_balance_04_llave");pageObj.hideField("uuid_sat");pageObj.hideField("cat_finanzas_bancos_cuentas_id");pageObj.hideField("cat_finanzas_cajas_chicas_id");pageObj.hideField("orden_de_compra_proveedor");pageObj.hideField("referencia_bancaria");pageObj.hideField("observacion_abono_compra");pageObj.hideField("observacion_cargo_pago");}
else if(ctrl_check_compra_directa.getValue()==1){pageObj.showField("fecha_de_compra");pageObj.showField("cat_compras_proveedores_id");pageObj.showField("importe_abono_compra");pageObj.showField("fecha_de_pago");pageObj.showField("cat_finanzas_cuentas_de_balance_04_llave");pageObj.showField("uuid_sat");pageObj.showField("cat_finanzas_bancos_cuentas_id");pageObj.showField("cat_finanzas_cajas_chicas_id");pageObj.showField("orden_de_compra_proveedor");pageObj.showField("referencia_bancaria");pageObj.showField("observacion_abono_compra");pageObj.showField("observacion_cargo_pago");}
if(!pageObj.myAfterInline){this.on('afterInlineAdd',function(fieldsData){pageObj.reload({});});pageObj.myAfterInline=true;}});Runner.pages.PageSettings.addPageEvent('tr_compras_requisiciones_01_estatus',Runner.pages.constants.PAGE_EDIT,"afterPageReady",function(pageObj,proxy,pageid,inlineRow,inlineObject,row){});Runner.pages.fieldsEvents["check_compra_directa_event"]=function(pageObj,pageid,row){if(row){row=new Runner.AjaxRow(pageObj,row);}
var ret,reqParams,ctrl=this,fieldsData={},params={},ajax=new Runner.form.Button({id:'check_compra_directa_event',btnName:'check_compra_directa_event'}),before=function(){console.log(this.getValue());if(this.getValue()=="on")
{pageObj.showField("cat_compras_proveedores_id");pageObj.showField("fecha_de_compra");pageObj.showField("importe_abono_compra");pageObj.showField("fecha_de_pago");pageObj.showField("cat_finanzas_cuentas_de_balance_04_llave");pageObj.showField("uuid_sat");pageObj.showField("cat_finanzas_bancos_cuentas_id");pageObj.showField("cat_finanzas_cajas_chicas_id");pageObj.showField("orden_de_compra_proveedor");pageObj.showField("referencia_bancaria");pageObj.showField("observacion_cargo_pago");pageObj.showField("observacion_abono_compra");pageObj.showField("referencia");pageObj.showField("cat_compras_documentos_mu_id");pageObj.toggleItem("boton_afectar_compra",true);}
else{pageObj.hideField("fecha_de_compra");pageObj.hideField("cat_compras_proveedores_id");pageObj.hideField("importe_abono_compra");pageObj.hideField("fecha_de_pago");pageObj.hideField("cat_finanzas_cuentas_de_balance_04_llave");pageObj.hideField("uuid_sat");pageObj.hideField("cat_finanzas_bancos_cuentas_id");pageObj.hideField("cat_finanzas_cajas_chicas_id");pageObj.hideField("orden_de_compra_proveedor");pageObj.hideField("referencia_bancaria");pageObj.hideField("observacion_cargo_pago");pageObj.hideField("observacion_abono_compra");pageObj.hideField("referencia");pageObj.hideField("cat_compras_documentos_mu_id");pageObj.toggleItem("boton_afectar_compra",false);}},after=function(result){},submit=function(){params["table"]="tr_compras_requisiciones_01_estatus";params["field"]=ctrl.fieldName;params.page=pageObj.pageName;(Runner.controls.ControlStorage.byId(pageid)||[]).forEach(function(ctrl){if(!(ctrl instanceof Runner.controls.MultiUploadField)&&!(ctrl instanceof Runner.controls.FileControl)){fieldsData[ctrl.fieldName]=ctrl.getStringValue();}});reqParams={params:JSON.stringify(params),event:"check_compra_directa_event",pageType:pageObj.pageType,keys:JSON.stringify(pageObj.keys?pageObj.keys:(row&&row.getKeys())),fieldsData:JSON.stringify(fieldsData)};if(pageObj.masterTable){reqParams.masterTable=pageObj.masterTable;reqParams=Runner.apply(reqParams,pageObj.masterKeys);}
$.post(Runner.getPageUrl("buttonhandler"),reqParams,function(result){var _result;try{_result=JSON.parse(result);}catch(e){Runner.displayGenericAjaxError(result);}
after.call(ctrl,_result);}).fail(function(jqXHR,textStatus,errorThrown){Runner.displayGenericAjaxError(jqXHR.responseText||textStatus+' '+errorThrown);});submit=function(){};};ajax.submitHandler=submit;ajax.submit=submit;ret=before.call(this);if(ret===false){return;}
submit();};